<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="FacepageModel" nsURI="http://facepage/model" nsPrefix="facepage">

    <!-- User class -->
    <ecore:EClass name="User">
      <eStructuralFeatures xmi:id="id" name="id" type="ecore:EString"/>
      <eStructuralFeatures xmi:id="name" name="name" type="ecore:EString"/>
      <eStructuralFeatures xmi:id="email" name="email" type="ecore:EString"/>
      <eStructuralFeatures xmi:id="dateOfBirth" name="dateOfBirth" type="ecore:EDate"/>
    </ecore:EClass>

    <!-- Account class -->
    <ecore:EClass name="Account">
      <eStructuralFeatures xmi:id="accountNumber" name="accountNumber" type="ecore:EInt"/>
      <eStructuralFeatures xmi:id="userRef" name="user" eType="#//User"/>
      <eOperations xmi:id="getPagesOp" name="getPages"/>
    </ecore:EClass>

    <!-- BusinessAccount class -->
    <ecore:EClass name="BusinessAccount">
      <eSuperTypes href="#//Account"/>
      <eStructuralFeatures xmi:id="companyName" name="companyName" type="ecore:EString"/>
      <eStructuralFeatures xmi:id="monthlyFee" name="monthlyFee" type="ecore:EDouble"/>
    </ecore:EClass>

    <!-- PersonalAccount class -->
    <ecore:EClass name="PersonalAccount">
      <eSuperTypes href="#//Account"/>
      <eOperations xmi:id="sendFriendRequestOp" name="sendFriendRequest"/>
      <eOperations xmi:id="receiveFriendRequestOp" name="receiveFriendRequest"/>
    </ecore:EClass>

    <!-- Page class -->
    <ecore:EClass name="Page">
      <eStructuralFeatures xmi:id="pageName" name="pageName" type="ecore:EString"/>
      <eStructuralFeatures xmi:id="numberOfVisits" name="numberOfVisits" type="ecore:EInt"/>
      <eStructuralFeatures xmi:id="adminAccountRef" name="adminAccount" eType="#//Account"/>
    </ecore:EClass>

    <!-- AdvertisementPage class -->
    <ecore:EClass name="AdvertisementPage">
      <eSuperTypes href="#//Page"/>
      <eStructuralFeatures xmi:id="bounceRate" name="bounceRate" type="ecore:EDouble"/>
      <eStructuralFeatures xmi:id="clickThroughRate" name="clickThroughRate" type="ecore:EDouble"/>
      <eStructuralFeatures xmi:id="conversionRate" name="conversionRate" type="ecore:EDouble"/>
    </ecore:EClass>

    <!-- FacepageSystem root container -->
    <ecore:EClass name="FacepageSystem">
      <eStructuralFeatures xmi:id="usersRef" name="users" eType="#//User" upperBound="-1"/>
      <eStructuralFeatures xmi:id="accountsRef" name="accounts" eType="#//Account" upperBound="-1"/>
      <eStructuralFeatures xmi:id="pagesRef" name="pages" eType="#//Page" upperBound="-1"/>
    </ecore:EClass>

  </ecore:EPackage>
</xmi:XMI>
