<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="OTS" nsURI="ots.metamodel" nsPrefix="ots" xmi:version="2.0">

    <!-- Root container class -->
    <ecore:EClass name="SystemContainer">
      <ecore:EReference name="tutors" eType="#//Tutor" upperBound="-1" containment="true"/>
      <ecore:EReference name="students" eType="#//Student" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Person class -->
    <ecore:EClass name="Person">
      <ecore:EAttribute name="name" eType="ecore:EString"/>
      <ecore:EAttribute name="emailAddress" eType="ecore:EString"/>
    </ecore:EClass>

    <!-- Tutor class -->
    <ecore:EClass name="Tutor">
      <ecore:EReference name="person" eType="#//Person" containment="true"/>
      <ecore:EAttribute name="bankAccount" eType="ecore:EString"/>
      <ecore:EReference name="offeredSubjects" eType="#//OfferedSubject" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Student class -->
    <ecore:EClass name="Student">
      <ecore:EReference name="person" eType="#//Person" containment="true"/>
      <ecore:EReference name="tutoringRequests" eType="#//TutoringRequest" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Offered Subject class -->
    <ecore:EClass name="OfferedSubject">
      <ecore:EAttribute name="subjectName" eType="ecore:EString"/>
      <ecore:EAttribute name="expertiseLevel" eType="ecore:EString"/>
      <ecore:EAttribute name="hourlyPrice" eType="ecore:EDouble"/>
    </ecore:EClass>

    <!-- Availability class -->
    <ecore:EClass name="Availability">
      <ecore:EReference name="tutor" eType="#//Tutor"/>
      <ecore:EAttribute name="dayOfWeek" eType="ecore:EString"/>
      <ecore:EAttribute name="startTime" eType="#//Time"/>
      <ecore:EAttribute name="endTime" eType="#//Time"/>
    </ecore:EClass>

    <!-- Tutoring Request class -->
    <ecore:EClass name="TutoringRequest">
      <ecore:EReference name="student" eType="#//Student"/>
      <ecore:EReference name="tutor" eType="#//Tutor"/>
      <ecore:EAttribute name="subjectName" eType="ecore:EString"/>
      <ecore:EAttribute name="expertiseLevel" eType="ecore:EString"/>
      <ecore:EAttribute name="requestedDateTime" eType="#//Timestamp"/>
    </ecore:EClass>

    <!-- Tutoring Session class -->
    <ecore:EClass name="TutoringSession">
      <ecore:EReference name="tutor" eType="#//Tutor"/>
      <ecore:EReference name="student" eType="#//Student"/>
      <ecore:EAttribute name="sessionDateTime" eType="#//Timestamp"/>
      <ecore:EAttribute name="price" eType="ecore:EDouble"/>
    </ecore:EClass>

    <!-- Custom Data Types -->
    <ecore:EDataType name="Time">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="serialization" value="java.time.LocalTime"/>
      </eAnnotations>
    </ecore:EDataType>

    <ecore:EDataType name="Timestamp">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="serialization" value="java.time.Instant"/>
      </eAnnotations>
    </ecore:EDataType>

  </ecore:EPackage>
</xmi:XMI>
