<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="inventoryManagement" nsURI="http://inventoryManagement" nsPrefix="inventoryManagement">

    <!-- Root container class -->
    <ecore:EClass name="SystemContainer">
      <ecore:EReference name="customers" eType="#//Customer" upperBound="-1" containment="true"/>
      <ecore:EReference name="products" eType="#//Product" upperBound="-1" containment="true"/>
      <ecore:EReference name="orders" eType="#//Order" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Customer class -->
    <ecore:EClass name="Customer">
      <ecore:EAttribute name="address" eType="ecore:EString" />
      <ecore:EAttribute name="vatNumber" eType="ecore:EString" />
      <ecore:EReference name="headOfficeAddress" eType="#//Address" containment="true"/>
      <ecore:EReference name="deliveryAddresses" eType="#//Address" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Address class -->
    <ecore:EClass name="Address">
      <ecore:EAttribute name="street" eType="ecore:EString" />
      <ecore:EAttribute name="city" eType="ecore:EString" />
      <ecore:EAttribute name="postalCode" eType="ecore:EString" />
    </ecore:EClass>

    <!-- Product class -->
    <ecore:EClass name="Product">
      <ecore:EAttribute name="name" eType="ecore:EString" />
      <ecore:EReference name="stockLevel" eType="#//StockLevel" containment="true"/>
    </ecore:EClass>

    <!-- Stock Level class -->
    <ecore:EClass name="StockLevel">
      <ecore:EAttribute name="quantity" eType="ecore:EInt"/>
    </ecore:EClass>

    <!-- Order class -->
    <ecore:EClass name="Order">
      <ecore:EReference name="customer" eType="#//Customer"/>
      <ecore:EReference name="orderLines" eType="#//OrderLine" upperBound="-1" containment="true"/>
      <ecore:EAttribute name="paidDate" eType="#//TimeWithoutDate"/>
      <ecore:EAttribute name="shippedDate" eType="#//TimeWithoutDate"/>
    </ecore:EClass>

    <!-- Order Line class -->
    <ecore:EClass name="OrderLine">
      <ecore:EReference name="product" eType="#//Product"/>
      <ecore:EAttribute name="quantity" eType="ecore:EInt"/>
      <ecore:EAttribute name="shippedQuantity" eType="ecore:EInt"/>
    </ecore:EClass>

    <!-- TimeWithoutDate Data Type -->
    <ecore:EDataType name="TimeWithoutDate">
      <ecore:EAnnotation source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="instanceClassName" value="java.time.LocalTime"/>
      </ecore:EAnnotation>
    </ecore:EDataType>

  </ecore:EPackage>
</xmi:XMI>
