<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
    <ecore:EPackage name="transportCompanyModel" nsURI="transportCompanyModel" nsPrefix="transportCompanyModel">

        <!-- Data Types -->
        <ecore:EDataType xmi:id="_Time" name="Time" instanceClassName="java.time.LocalTime"/>

        <!-- Classes -->
        <ecore:EClass xmi:id="_RootContainer" name="RootContainer">
            <ecore:EReference xmi:id="_RootContainer_employees" name="employees" eType="#//Employee" upperBound="-1"/>
            <ecore:EReference xmi:id="_RootContainer_customers" name="customers" eType="#//Customer" upperBound="-1"/>
            <ecore:EReference xmi:id="_RootContainer_vehicles" name="vehicles" eType="#//Vehicle" upperBound="-1"/>
            <ecore:EReference xmi:id="_RootContainer_orders" name="orders" eType="#//Order" upperBound="-1"/>
        </ecore:EClass>

        <!-- Employee Hierarchy -->
        <ecore:EClass xmi:id="_Employee" name="Employee">
            <ecore:EAttribute xmi:id="_Employee_name" name="name" eType="ecore:EString"/>
            <ecore:EAttribute xmi:id="_Employee_socialSecurityNumber" name="socialSecurityNumber" eType="ecore:EString"/>
        </ecore:EClass>

        <ecore:EClass xmi:id="_Driver" name="Driver" superTypes="#_Employee">
            <!-- Operations for Driver class can be added here -->
        </ecore:EClass>

        <ecore:EClass xmi:id="_Planner" name="Planner" superTypes="#_Employee"/>
        <ecore:EClass xmi:id="_AdministrativeStaff" name="AdministrativeStaff" superTypes="#_Employee">
            <ecore:EAttribute xmi:id="_AdministrativeStaff_fieldOfActivity" name="fieldOfActivity" eType="ecore:EString"/>
        </ecore:EClass>

        <!-- Customer Class -->
        <ecore:EClass xmi:id="_Customer" name="Customer">
            <ecore:EAttribute xmi:id="_Customer_name" name="name" eType="ecore:EString"/>
            <ecore:EAttribute xmi:id="_Customer_billingAddress" name="billingAddress" eType="ecore:EString"/>
        </ecore:EClass>

        <!-- Vehicle Hierarchy -->
        <ecore:EClass xmi:id="_Vehicle" name="Vehicle">
            <ecore:EAttribute xmi:id="_Vehicle_licensePlateNumber" name="licensePlateNumber" eType="ecore:EString"/>
            <ecore:EAttribute xmi:id="_Vehicle_mileage" name="mileage" eType="ecore:EDouble"/>
        </ecore:EClass>

        <ecore:EClass xmi:id="_RefrigeratedTruck" name="RefrigeratedTruck" superTypes="#_Vehicle"/>
        <ecore:EClass xmi:id="_SmallVan" name="SmallVan" superTypes="#_Vehicle"/>
        <ecore:EClass xmi:id="_LoadingPlatform" name="LoadingPlatform" superTypes="#_Vehicle"/>
        <ecore:EClass xmi:id="_BoxTruck" name="BoxTruck" superTypes="#_Vehicle"/>

        <!-- Repair Shop Class -->
        <ecore:EClass xmi:id="_RepairShop" name="RepairShop">
            <ecore:EAttribute xmi:id="_RepairShop_name" name="name" eType="ecore:EString"/>
            <ecore:EAttribute xmi:id="_RepairShop_address" name="address" eType="ecore:EString"/>
        </ecore:EClass>

        <!-- Order and Association Classes -->
        <ecore:EClass xmi:id="_Order" name="Order">
            <ecore:EReference xmi:id="_Order_planner" name="planner" eType="#_Planner"/>
            <ecore:EAttribute xmi:id="_Order_comment" name="comment" eType="ecore:EString"/>
            <ecore:EReference xmi:id="_Order_driver" name="driver" eType="#_Driver"/>
            <ecore:EAttribute xmi:id="_Order_startTime" name="startTime" eType="#_Time"/>
            <ecore:EAttribute xmi:id="_Order_endTime" name="endTime" eType="#_Time"/>
            <ecore:EReference xmi:id="_Order_customer" name="customer" eType="#_Customer"/>
            <ecore:EAttribute xmi:id="_Order_pickUpAddress" name="pickUpAddress" eType="ecore:EString"/>
            <ecore:EAttribute xmi:id="_Order_deliveryAddress" name="deliveryAddress" eType="ecore:EString"/>
        </ecore:EClass>

        <!-- Association Classes -->
        <ecore:EClass xmi:id="_OrderAssignment" name="OrderAssignment">
            <ecore:EReference xmi:id="_OrderAssignment_order" name="order" eType="#_Order" containment="true"/>
            <ecore:EReference xmi:id="_OrderAssignment_planner" name="planner" eType="#_Planner"/>
            <ecore:EReference xmi:id="_OrderAssignment_vehicle" name="vehicle" eType="#_Vehicle"/>
        </ecore:EClass>

        <!-- Partner Company Class -->
        <ecore:EClass xmi:id="_PartnerCompany" name="PartnerCompany">
            <ecore:EAttribute xmi:id="_PartnerCompany_name" name="name" eType="ecore:EString"/>
            <ecore:EAttribute xmi:id="_PartnerCompany_address" name="address" eType="ecore:EString"/>
        </ecore:EClass>

    </ecore:EPackage>
</xmi:XMI>
