<xmi:XMI xmlns:xmi="http://schema.omg.org/spec/XMI/2.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns.ecore="http://www.eclipse.org/emf/2002/Ecore"
         xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore http://www.eclipse.org/emf/2002/Ecore.ecore"
         version="2.0">
  <ecore:EPackage xmi:id="_rootPackage" name="ClothingManagement" nsURI="clothingmanagement" nslPrefix="ClothingManagement">

    <!-- Root container class -->
    <ecore:EClass xmi:id="_Model" name="Model">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="Root container for the entire model."/>
      </eAnnotations>
    </ecore:EClass>

    <!-- Product class -->
    <ecore:EClass xmi:id="_Product" name="Product">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="Represents a clothing product."/>
      </eAnnotations>
      <eStructuralFeatures>
        <!-- Using EString for name, description and manufacturer -->
        <ecore:EAttribute xmi:id="_Product_name" name="name"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Product_description" name="description"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Product_netPrice" name="netPrice"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EDouble"/>  <!-- price can be fractional -->
        <ecore:EAttribute xmi:id="_Product_manufacturer" name="manufacturer"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Country class (VAT, currency, conversion) -->
    <ecore:EClass xmi:id="_Country" name="Country">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="Represents a country with VAT and currency information."/>
      </eAnnotations>
      <eStructuralFeatures>
        <ecore:EAttribute xmi:id="_Country_name" name="name"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Country_vatRate" name="vatRate"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EDouble"/> <!-- percentage as a decimal -->
        <ecore:EAttribute xmi:id="_Country_currency" name="currency"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Country_euroConversionRate" name="euroConversionRate"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EDouble"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Representative class -->
    <ecore:EClass xmi:id="_Representative" name="Representative">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="Represents a sales representative responsible for one country."/>
      </eAnnotations>
      <eStructuralFeatures>
        <ecore:EAttribute xmi:id="_Representative_firstName" name="firstName"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Representative_lastName" name="lastName"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Representative_ssn" name="ssn"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Representative_telephone" name="telephone"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Representative_email" name="email"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <!-- reference to the country they cover -->
        <ecore:EReference xmi:id="_Representative_country" name="country"
                          eType="#/_Country" containment="false"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Customer class -->
    <ecore:EClass xmi:id="_Customer" name="Customer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="Represents a customer who places orders."/>
      </eAnnotations>
      <eStructuralFeatures>
        <ecore:EAttribute xmi:id="_Customer_name" name="name"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Customer_address" name="address"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Customer_telephone" name="telephone"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Customer_email" name="email"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <!-- many‑to‑many (via association class) -->
        <ecore:EReference xmi:id="_Customer_countries" name="countries"
                          eType="#/_Country" upper="-1" containment="false"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Order class -->
    <ecore:EClass xmi:id="_Order" name="Order">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation" value="Represents an order placed by a customer through a representative."/>
      </eAnnotations>
      <eStructuralFeatures>
        <ecore:EAttribute xmi:id="_Order_id" name="id"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EString"/>
        <ecore:EAttribute xmi:id="_Order_quantity" name="quantity"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EInt"/>
        <ecore:EReference xmi:id="_Order_product" name="product"
                          eType="#/_Product" containment="false"/>
        <ecore:EReference xmi:id="_Order_customer" name="customer"
                          eType="#/_Customer" containment="false"/>
        <ecore:EReference xmi:id="_Order_representative" name="representative"
                          eType="#/_Representative" containment="false"/>
        <!-- dates are modelled with EDate -->
        <ecore:EAttribute xmi:id="_Order_orderDate" name="orderDate"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EDate"/>
        <ecore:EAttribute xmi:id="_Order_deliveryDate" name="deliveryDate"
                           eType="<http://www.eclipse.org/emf/2002/Ecore>!EDate"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Association class for the many‑to‑many relationship between Product and Country -->
    <ecore:EClass xmi:id="_ProductCountry" name="ProductCountry">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="documentation"
                 value="Links a product to the countries where it is available."/>
      </eAnnotations>
      <eStructuralFeatures>
        <!-- containment from Product -->
        <ecore:EReference xmi:id="_ProductCountry_product" name="product"
                          eType="#/_Product" containment="true"/>
        <!-- non‑containment reference to Country -->
        <ecore:EReference xmi:id="_ProductCountry_country" name="country"
                          eType="#/_Country"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Package contents (all classes) -->
    <eClassifiers>
      <eClasses href="#_Model"/>
      <eClasses href="#_Product"/>
      <eClasses href="#_Country"/>
      <eClasses href="#_Representative"/>
      <eClasses href="#_Customer"/>
      <eClasses href="#_Order"/>
      <eClasses href="#_ProductCountry"/>
    </eClassifiers>

    <!-- Root container content -->
    <eContents>
      <eFeature refEObject="#/_Model"/>
    </eContents>

  </ecore:EPackage>
</xmi:XMI>
