<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="cinema"
    nsURI="http://www.example.org/cinema"
    nsPrefix="cinema">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="CinemaSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cinemas"
        eType="#//Cinema" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="movies"
        eType="#//Movie" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers"
        eType="#//Customer" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- Cinema -->
  <eClassifiers xsi:type="ecore:EClass" name="Cinema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theatres"
        eType="#//Theatre" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copyLocations"
        eType="#//CopyLocation" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- Theatre -->
  <eClassifiers xsi:type="ecore:EClass" name="Theatre">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seats"
        eType="#//Seat" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shows"
        eType="#//Show" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- Movie -->
  <eClassifiers xsi:type="ecore:EClass" name="Movie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationMinutes"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="movieCopies"
        eType="#//MovieCopy" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- MovieCopy -->
  <eClassifiers xsi:type="ecore:EClass" name="MovieCopy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copyLocations"
        eType="#//CopyLocation" upperBound="-1"/>
  </eClassifiers>

  <!-- CopyLocation -->
  <eClassifiers xsi:type="ecore:EClass" name="CopyLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shows"
        eType="#//Show" upperBound="-1"/>
  </eClassifiers>

  <!-- Seat -->
  <eClassifiers xsi:type="ecore:EClass" name="Seat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets"
        eType="#//Ticket" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineTickets"
        eType="#//OnlineTicket" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeOffers"
        eType="#//AlternativeOffer" upperBound="-1"/>
  </eClassifiers>

  <!-- Show -->
  <eClassifiers xsi:type="ecore:EClass" name="Show">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets"
        eType="#//Ticket" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineTickets"
        eType="#//OnlineTicket" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeOffers"
        eType="#//AlternativeOffer" upperBound="-1"/>
    <eOperations name="publish"/>
    <eOperations name="cancelShow"/>
  </eClassifiers>

  <!-- Ticket -->
  <eClassifiers xsi:type="ecore:EClass" name="Ticket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ticketId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="show"
        eType="#//Show" lowerBound="1"/>
  </eClassifiers>

  <!-- Customer -->
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineTickets"
        eType="#//OnlineTicket" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- OnlineTicket -->
  <eClassifiers xsi:type="ecore:EClass" name="OnlineTicket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlineTicketId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seat"
        eType="#//Seat" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="show"
        eType="#//Show" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeOffer"
        eType="#//AlternativeOffer" containment="true"/>
    <eOperations name="cancelReservationCustomer"/>
    <eOperations name="cancelReservationKinepolis"/>
  </eClassifiers>

  <!-- AlternativeOffer -->
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeOffer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternativeOfferId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seat"
        eType="#//Seat" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="show"
        eType="#//Show" lowerBound="1"/>
    <eOperations name="accept"/>
    <eOperations name="decline"/>
    <eOperations name="expire"/>
    <eOperations name="refund"/>
  </eClassifiers>

</ecore:EPackage>
