<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cinema" nsURI="http://www.example.org/cinema" nsPrefix="cinema">
  <eClassifiers xsi:type="ecore:EClass" name="CinemaSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cinemas" upperBound="-1"
        eType="#//Cinema" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="movies" upperBound="-1"
        eType="#//Movie" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" upperBound="-1"
        eType="#//Customer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cinema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="theatres" upperBound="-1"
        eType="#//Theatre" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copyLocations" upperBound="-1"
        eType="#//CopyLocation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Theatre">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seats" upperBound="-1"
        eType="#//Seat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shows" upperBound="-1"
        eType="#//Show" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Movie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationMinutes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="movieCopies" upperBound="-1"
        eType="#//MovieCopy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MovieCopy">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copyLocations" upperBound="-1"
        eType="#//CopyLocation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CopyLocation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shows" upperBound="-1"
        eType="#//Show"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets" upperBound="-1"
        eType="#//Ticket" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineTickets" upperBound="-1"
        eType="#//OnlineTicket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeOffers" upperBound="-1"
        eType="#//AlternativeOffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Show">
    <eOperations name="publish"/>
    <eOperations name="cancelShow"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets" upperBound="-1"
        eType="#//Ticket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineTickets" upperBound="-1"
        eType="#//OnlineTicket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeOffers" upperBound="-1"
        eType="#//AlternativeOffer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ticket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ticketId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="show" lowerBound="1" eType="#//Show"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="customerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineTickets" upperBound="-1"
        eType="#//OnlineTicket" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OnlineTicket">
    <eOperations name="cancelReservationCustomer"/>
    <eOperations name="cancelReservationKinepolis"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onlineTicketId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seat" lowerBound="1" eType="#//Seat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="show" lowerBound="1" eType="#//Show"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alternativeOffer" eType="#//AlternativeOffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlternativeOffer">
    <eOperations name="accept"/>
    <eOperations name="decline"/>
    <eOperations name="expire"/>
    <eOperations name="refund"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternativeOfferId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seat" lowerBound="1" eType="#//Seat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="show" lowerBound="1" eType="#//Show"/>
  </eClassifiers>
</ecore:EPackage>
