<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/Ecore/">
  <ePackage name="hmbs" nsUri="http://www.example.org/hmbs" xmi:id="hmbs_package">

    <!-- Root Container -->
    <eClass name="HMBS" xmi:id="hmbs_root">
      <eStructuralFeatures>
        <eReference xmi:id="ref_travellers" name="travellers" eClassifier="#traveller_class"/>
        <eReference xmi:id="ref_hotels" name="hotels" eClassifier="#hotel_class"/>
        <eReference xmi:id="ref_chains" name="hotelChains" eClassifier="#chain_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Traveller" xmi:id="traveller_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_t_name" name="name" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_t_company" name="companyName" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_t_address" name="billingAddress" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_t_rating" name="reliabilityRating" eType="ecore:EFloat"/>
        <eReference xmi:id="ref_t_prefs" name="preferences" eClassifier="#pref_class"/>
        <eReference xmi:id="ref_t_bookings" name="bookings" eClassifier="#booking_abstract"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="TravelPreference" xmi:id="pref_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_p_desc" name="description" eType="ecore:EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="HotelChain" xmi:id="chain_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_c_name" name="chainName" eType="ecore:EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Hotel" xmi:id="hotel_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_h_name" name="name" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_h_city" name="city" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_h_address" name="address" eType="ecore:EString"/>
        <eReference xmi:id="ref_h_chain" name="chain" eClassifier="#chain_class"/>
        <eReference xmi:id="ref_h_rooms" name="offeredRoomTypes" eClassifier="#roomtype_class"/>
      </eStructuralFeatures>
      <eOperations>
        <eOperation xmi:id="op_confirm" name="confirmBooking">
          <eParameters>
            <eParameter xmi:id="param_conf_b" name="booking" eClassifier="#finalized_booking_class"/>
          </eParameters>
        </eOperation>
        <eOperation xmi:id="op_cancel" name="cancelConfirmedBooking">
          <eParameters>
            <eParameter xmi:id="param_can_b" name="booking" eClassifier="#finalized_booking_class"/>
          </eParameters>
        </eOperation>
      </eOperations>
    </eClass>

    <eClass name="RoomType" xmi:id="roomtype_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_rt_name" name="typeName" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_rt_booked" name="isFullyBooked" eType="ecore:EBoolean"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Booking" abstract="true" xmi:id="booking_abstract">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_b_id" name="bookingId" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_b_arrival" name="arrivalDate" eType="ecore:EDate"/>
        <eAttribute xmi:id="attr_b_departure" name="departureDate" eType="ecore:EDate"/>
        <eAttribute xmi:id="attr_b_numrooms" name="numRooms" eType="ecore:EInt"/>
        <eReference xmi:id="ref_b_traveller" name="traveller" eClassifier="#traveller_class"/>
        <eReference xmi:id="ref_b_hotel" name="hotel" eClassifier="#hotel_class"/>
        <eReference xmi:id="ref_b_roomtype" name="roomType" eClassifier="#roomtype_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="PreliminaryBooking" xmi:id="prelim_booking_class">
      <eExtends xmi:id="ext_prelim" eClass="#booking_abstract"/>
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_pb_price" name="price" eType="ecore:EDouble"/>
        <eAttribute xmi:id="attr_pb_area" name="cityArea" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_pb_rating" name="hotelRating" eType="ecore:EInt"/>
        <eReference xmi:id="ref_pb_offers" name="triggeredOffers" eClassifier="#specialoffer_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="FinalizedBooking" xmi:id="finalized_booking_class">
      <eExtends xmi:id="ext_final" eClass="#booking_abstract"/>
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_fb_card" name="creditCardInfo" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_fb_method" name="paymentMethod" eType="#paymethod_enum"/>
        <eAttribute xmi:id="attr_fb_confirmed" name="isConfirmed" eType="ecore:EBoolean"/>
        <eAttribute xmi:id="attr_fb_deadline" name="cancellationDeadline" eType="ecore:EDate"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="SpecialOffer" xmi:id="specialoffer_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_so_price" name="offerPrice" eType="ecore:EDouble"/>
        <eAttribute xmi:id="attr_so_expiry" name="expiryDate" eType="ecore:EDate"/>
        <eReference xmi:id="ref_so_prelim" name="preliminaryBooking" eClassifier="#prelim_booking_class"/>
        <eReference xmi:id="ref_so_hotel" name="offeringHotel" eClassifier="#hotel_class"/>
      </eStructuralFeatures>
    </eClass>

    <eEnum name="PaymentMethod" xmi:id="paymethod_enum">
      <eLiterals>
        <eLiteral name="PREPAID" xmi:id="lit_prepaid"/>
        <eLiteral name="PAID_AT_HOTEL" xmi:id="lit_at_hotel"/>
      </eLiterals>
    </eEnum>

    <eClass name="SearchRequest" xmi:id="searchreq_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_sr_city" name="city" eType="ecore:EString"/>
        <eAttribute xmi:id="attr_sr_arrival" name="arrivalDate" eType="ecore:EDate"/>
        <eAttribute xmi:id="attr_sr_departure" name="departureDate" eType="ecore:EDate"/>
        <eAttribute xmi:id="attr_sr_numrooms" name="numRooms" eType="ecore:EInt"/>
        <eAttribute xmi:id="attr_sr_minrating" name="minRating" eType="ecore:EInt"/>
        <eAttribute xmi:id="attr_sr_budget" name="maxBudgetPerNight" eType="ecore:EDouble"/>
        <eReference xmi:id="ref_sr_prefs" name="filterPreferences" eClassifier="#pref_class"/>
      </eStructuralFeatures>
    </eClass>

  </ePackage>
</xmi:XMI>
