<model xmlns:xmi="http://schema.omg.org/spec/XMI/2.0" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
       xmi:type="ecore:EObject" xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore EclipseEMF.ecore"
       xmi:id="model">
  <modelPackage xmi:type="ecore:EPackage" xmi:id="ModelPackage"
                name="HotelBookingManagementSystem"
                nsURI="http://hostname/yourproject"
                eClassifiers>
    <!-- Classes -->
    <eClassifiers xmi:type="ecore:EClass" xmi:id="Traveller">
      <eStructuralFeatures>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="name"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="companyName"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="companyAddress"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="preferences"
                            upperBound="-1" eType="http://hostname/yourproject#TravelPreference"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="bookings"
                            upperBound="-1" eOpposite="Booking#traveller" containment="true"
                            eType="http://hostname/yourproject#Booking"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="reliabilityRating"
                            eType="http://www.eclipse.org/emf/2003/xsd#EInt"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="Hotel">
      <eStructuralFeatures>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="name"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="address"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="chain"
                            eType="http://hostname/yourproject#HotelChain"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="offers"
                            upperBound="-1" eOpposite="Offer#hotel" containment="true"
                            eType="http://hostname/yourproject#Offer"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="roomTypes"
                            upperBound="-1" eType="http://hostname/yourproject#RoomType"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="HotelChain">
      <eStructuralFeatures>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="name"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="TravelPreference">
      <eStructuralFeatures>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="type"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="Offer">
      <eStructuralFeatures>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="pricePerNight"
                            eType="http://www.eclipse.org/emf/2003/xsd#EDouble"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="cityArea"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="hotelRating"
                            eType="http://www.eclipse.org/emf/2003/xsd#EInt"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="preferences"
                            upperBound="-1" eOpposite="TravelPreference#offer"
                            eType="http://hostname/yourproject#TravelPreference"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="hotel"
                            lowerBound="1" eOpposite="Hotel#offers"
                            eType="http://hostname/yourproject#Hotel"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="RoomType">
      <eStructuralFeatures>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="type"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="Booking">
      <eStructuralFeatures>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="identifier"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="city"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="arrivalDate"
                            eType="EDate"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="departureDate"
                            eType="EDate"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="numberOfRooms"
                            eType="http://www.eclipse.org/emf/2003/xsd#EInt"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="roomType"
                            eOpposite="RoomType#bookings" eType="http://hostname/yourproject#RoomType"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="minRating"
                            eType="http://www.eclipse.org/emf/2003/xsd#EInt"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="budgetPerNight"
                            eType="http://www.eclipse.org/emf/2003/xsd#EDouble"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="preferences"
                            upperBound="-1" eOpposite="TravelPreference#bookings"
                            eType="http://hostname/yourproject#TravelPreference"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="isPreliminary"
                            eType="http://www.eclipse.org/emf/2003/xsd#EBoolean"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="paymentMethod"
                            eType="http://www.eclipse.org/emf/2003/xsd#EString"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="confirmationDeadline"
                            eType="EDateTime"/>
        <eStructuralFeature xmi:type="ecore:EAttribute" name="cancellationDeadline"
                            eType="EDateTime"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="traveller"
                            lowerBound="1" eOpposite="Traveller#bookings"
                            eType="http://hostname/yourproject#Traveller"/>
        <eStructuralFeature xmi:type="ecore:EReference" name="offer"
                            upperBound="1" eOpposite="Offer#booking"
                            eType="http://hostname/yourproject#Offer"/>
      </eStructuralFeatures>

      <!-- Operations -->
      <eOperations>
        <eOperation xmi:id="Booking_finalizeOperation" name="finalize">
          <eTypeParameters>
            <eClassifiers xmi:type="ecore:EDataType"
                          href="http://www.eclipse.org/emf/2003/xsd#EBooleanObject"/>
          </eTypeParameters>
        </eOperation>
        <eOperation xmi:id="Booking_cancelOperation" name="cancel">
          <eTypeParameters>
            <eClassifiers xmi:type="ecore:EDataType"
                          href="http://www.eclipse.org/emf/2003/xsd#EBooleanObject"/>
          </eTypeParameters>
        </eOperation>
      </eOperations>
    </eClassifiers>

    <!-- Data types -->
    <eClassifiers xmi:type="ecore:EDataType" xmi:id="EDate"
                  instanceClassName="java.time.LocalDate">
      <eAnnotations source="http://www.eclipse.org/emf/2003/XML"/>
    </eClassifiers>
    <eClassifiers xmi:type="ecore:EDataType" xmi:id="EDateTime"
                  instanceClassName="java.time.LocalDateTime">
      <eAnnotations source="http://www.eclipse.org/emf/2003/XML"/>
    </eClassifiers>

  </modelPackage>
</model>
