<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="breakout"
    nsURI="http://www.example.org/breakout"
    nsPrefix="breakout">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="BreakoutSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users"
        eType="#//User" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="games"
        eType="#//Game" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="players"
        eType="#//Player" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="admins"
        eType="#//Admin" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hallOfFameEntries"
        eType="#//HallOfFameEntry" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedGames"
        eType="#//PlayedGame" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- User -->
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Player -->
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="player"
        eType="#//User" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedGames"
        eType="#//PlayedGame" upperBound="-1" eOpposite="#//PlayedGame/player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hallOfFameEntries"
        eType="#//HallOfFameEntry" upperBound="-1" eOpposite="#//HallOfFameEntry/player"/>
  </eClassifiers>

  <!-- Admin -->
  <eClassifiers xsi:type="ecore:EClass" name="Admin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="admin"
        eType="#//User" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="games"
        eType="#//Game" upperBound="-1" eOpposite="#//Game/admin"/>
  </eClassifiers>

  <!-- Game -->
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrBlocksPerLevel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="published"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks"
        eType="#//Block" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paddle"
        eType="#//Paddle" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ball"
        eType="#//Ball" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels"
        eType="#//Level" containment="true" lowerBound="1" upperBound="99"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockAssignments"
        eType="#//BlockAssignment" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mostRecentEntry"
        eType="#//HallOfFameEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedGames"
        eType="#//PlayedGame" upperBound="-1" eOpposite="#//PlayedGame/game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="admin"
        eType="#//Admin" eOpposite="#//Admin/games"/>
  </eClassifiers>

  <!-- Block -->
  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedBlockAssignments"
        eType="#//PlayedBlockAssignment" upperBound="-1" eOpposite="#//PlayedBlockAssignment/block"/>
  </eClassifiers>

  <!-- Paddle -->
  <eClassifiers xsi:type="ecore:EClass" name="Paddle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPaddleLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minPaddleLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- Ball -->
  <eClassifiers xsi:type="ecore:EClass" name="Ball">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBallSpeedX"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBallSpeedY"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballSpeedIncreaseFactor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- Level -->
  <eClassifiers xsi:type="ecore:EClass" name="Level">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRandom"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockAssignments"
        eType="#//BlockAssignment" upperBound="-1" eOpposite="#//BlockAssignment/level"/>
  </eClassifiers>

  <!-- BlockAssignment -->
  <eClassifiers xsi:type="ecore:EClass" name="BlockAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridHorizontalPosition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridVerticalPosition"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block"
        eType="#//Block" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level"
        eType="#//Level" eOpposite="#//Level/blockAssignments"/>
  </eClassifiers>

  <!-- HallOfFameEntry -->
  <eClassifiers xsi:type="ecore:EClass" name="HallOfFameEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="game"
        eType="#//Game" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player"
        eType="#//Player" eOpposite="#//Player/hallOfFameEntries"/>
  </eClassifiers>

  <!-- PlayedGame -->
  <eClassifiers xsi:type="ecore:EClass" name="PlayedGame">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lives"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentLevel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks"
        eType="#//PlayedBlockAssignment" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedPaddle"
        eType="#//PlayedPaddle" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedBall"
        eType="#//PlayedBall" containment="true" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="game"
        eType="#//Game" lowerBound="1" eOpposite="#//Game/playedGames"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player"
        eType="#//Player" eOpposite="#//Player/playedGames"/>
  </eClassifiers>

  <!-- PlayedBall -->
  <eClassifiers xsi:type="ecore:EClass" name="PlayedBall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballDirectionX"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballDirectionY"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentBallX"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentBallY"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- PlayedPaddle -->
  <eClassifiers xsi:type="ecore:EClass" name="PlayedPaddle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPaddleLength"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPaddleX"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPaddleY"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- PlayedBlockAssignment -->
  <eClassifiers xsi:type="ecore:EClass" name="PlayedBlockAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block"
        eType="#//Block" lowerBound="1" eOpposite="#//Block/playedBlockAssignments"/>
  </eClassifiers>

</ecore:EPackage>
