<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="breakout"
    nsURI="http://www.example.org/breakout"
    nsPrefix="breakout">

  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="BlockAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridHorizontalPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gridVerticalPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1"
        eType="#//Block"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" eType="#//Level"
        eOpposite="#//Level/blockAssignments"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Level">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRandom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockAssignments" upperBound="-1"
        eType="#//BlockAssignment" eOpposite="#//BlockAssignment/level"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nrBlocksPerLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="published" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//Block" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paddle" lowerBound="1"
        eType="#//Paddle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ball" lowerBound="1"
        eType="#//Ball" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="levels" lowerBound="1"
        upperBound="99" eType="#//Level" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockAssignments" upperBound="-1"
        eType="#//BlockAssignment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mostRecentEntry" upperBound="1"
        eType="#//HallOfFameEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedGames" upperBound="-1"
        eType="#//PlayedGame" eOpposite="#//PlayedGame/game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="admin" lowerBound="1"
        eType="#//Admin" eOpposite="#//Admin/games"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="red" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="green" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="points" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedBlockAssignments"
        upperBound="-1" eType="#//PlayedBlockAssignment" eOpposite="#//PlayedBlockAssignment/block"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Paddle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxPaddleLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minPaddleLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Ball">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBallSpeedX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minBallSpeedY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballSpeedIncreaseFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="HallOfFameEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" lowerBound="1"
        eType="#//Game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player" eOpposite="#//Player/hallOfFameEntries"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PlayedGame">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lives" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blocks" upperBound="-1"
        eType="#//PlayedBlockAssignment" containment="true" eOpposite="#//PlayedBlockAssignment/playedGame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedPaddle" lowerBound="1"
        eType="#//PlayedPaddle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedBall" lowerBound="1"
        eType="#//PlayedBall" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="game" lowerBound="1"
        eType="#//Game" eOpposite="#//Game/playedGames"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="player" lowerBound="1"
        eType="#//Player" eOpposite="#//Player/playedGames"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PlayedBall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballDirectionX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ballDirectionY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentBallX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentBallY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PlayedPaddle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPaddleLength" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPaddleX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentPaddleY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PlayedBlockAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBuiltinTypes#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="block" lowerBound="1"
        eType="#//Block" eOpposite="#//Block/playedBlockAssignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedGame" lowerBound="1"
        eType="#//PlayedGame" eOpposite="#//PlayedGame/blocks"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1"
        upperBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="playedGames" upperBound="-1"
        eType="#//PlayedGame" eOpposite="#//PlayedGame/player"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hallOfFameEntries" upperBound="-1"
        eType="#//HallOfFameEntry" eOpposite="#//HallOfFameEntry/player"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Admin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1"
        upperBound="1" eType="#//User"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="games" upperBound="-1"
        eType="#//Game" eOpposite="#//Game/admin"/>
  </eClassifiers>

</ecore:EPackage>
