<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/Ecore/">
  <ePackage name="conan.fitness" nsURI="http://www.conan.fitness/ns" nsPrefix="conan">
    
    <!-- Custom Datatype for Time -->
    <eDataType name="LocalTime" uri="java.time.LocalTime"/>

    <!-- Root Container -->
    <eClass name="FitnessSystem">
      <eStructuralFeatures>
        <eReference name="centers" EClassifier="conan.fitness.Center" containment="true"/>
        <eReference name="people" EClassifier="conan.fitness.Person" containment="true"/>
        <eReference name="sessions" EClassifier="conan.fitness.Session" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Infrastructure -->
    <eClass name="Center">
      <eStructuralFeatures>
        <eAttribute name="name" eType="eString"/>
        <eAttribute name="address" eType="eString"/>
        <eReference name="rooms" EClassifier="conan.fitness.Room" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Room">
      <eStructuralFeatures>
        <eAttribute name="roomNumber" eType="eInt"/>
        <eAttribute name="maxCapacity" eType="eInt"/>
        <eReference name="center" EClassifier="conan.fitness.Center"/>
      </eStructuralFeatures>
    </eClass>

    <!-- People -->
    <eClass name="Person">
      <eStructuralFeatures>
        <eAttribute name="firstName" eType="eString"/>
        <eAttribute name="lastName" eType="eString"/>
        <eAttribute name="birthDate" eType="eDate"/>
        <!-- Association Class End: Containment reference to Participation -->
        <eReference name="participations" EClassifier="conan.fitness.Participation" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Trainer" eSuperClass="conan.fitness.Person">
      <eStructuralFeatures>
        <eAttribute name="diploma" eType="eString"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Sessions -->
    <eClass name="Session" eAbstract="true">
      <eStructuralFeatures>
        <eAttribute name="date" eType="eDate"/>
        <eAttribute name="startTime" eType="conan.fitness.LocalTime"/>
        <eReference name="room" EClassifier="conan.fitness.Room"/>
        <!-- Association Class End: Non-containment reference to Participation -->
        <eReference name="participations" EClassifier="conan.fitness.Participation"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="IndividualSession" eSuperClass="conan.fitness.Session">
    </eClass>

    <eClass name="GroupSession" eSuperClass="conan.fitness.Session">
      <eStructuralFeatures>
        <eAttribute name="type" eType="eString"/>
        <eReference name="trainer" EClassifier="conan.fitness.Trainer"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Association Class for Person <-> Session -->
    <eClass name="Participation">
      <eStructuralFeatures>
        <eReference name="person" EClassifier="conan.fitness.Person"/>
        <eReference name="session" EClassifier="conan.fitness.Session"/>
      </eStructuralFeatures>
    </eClass>

  </ePackage>
</xmi:XMI>
