<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="university"
    nsURI="http://www.example.org/university"
    nsPrefix="university">

  <!-- Abstract class Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Employee leads 0..1 Faculty -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="leads" eType="#//Faculty"
        upperBound="1" lowerBound="0"/>
  </eClassifiers>

  <!-- Class Faculty -->
  <eClassifiers xsi:type="ecore:EClass" name="Faculty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Faculty composed of 1..* Institute -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="institutes" eType="#//Institute"
        upperBound="-1" lowerBound="1" containment="true"/>
  </eClassifiers>

  <!-- Class AdministrativeEmployee, extends Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="AdministrativeEmployee" eSuperTypes="#//Employee"/>

  <!-- Class ResearchAssociate, extends Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="ResearchAssociate" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfStudy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- ResearchAssociate aggregated in 1..* Institute (opposite side) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="institutes" eType="#//Institute"
        upperBound="-1" lowerBound="1" eOpposite="#//Institute/researchAssociates"/>
    <!-- ResearchAssociate participates in Projects via Participation -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="participations" eType="#//Participation"
        upperBound="-1" lowerBound="0" containment="true"/>
  </eClassifiers>

  <!-- Class Institute -->
  <eClassifiers xsi:type="ecore:EClass" name="Institute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Institute aggregates 1..* ResearchAssociate -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchAssociates" eType="#//ResearchAssociate"
        upperBound="-1" lowerBound="1" eOpposite="#//ResearchAssociate/institutes"/>
  </eClassifiers>

  <!-- Class Lecturer, extends ResearchAssociate -->
  <eClassifiers xsi:type="ecore:EClass" name="Lecturer" eSuperTypes="#//ResearchAssociate">
    <!-- Lecturer teaches 1..* Course -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="teaches" eType="#//Course"
        upperBound="-1" lowerBound="1" eOpposite="#//Course/lecturers"/>
  </eClassifiers>

  <!-- Class Course -->
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <!-- Course taught by 1..* Lecturer -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturers" eType="#//Lecturer"
        upperBound="-1" lowerBound="1" eOpposite="#//Lecturer/teaches"/>
  </eClassifiers>

  <!-- Class Project -->
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Project linked to ResearchAssociates via Participation -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="participations" eType="#//Participation"
        upperBound="-1" lowerBound="0" eOpposite="#//Participation/project"/>
  </eClassifiers>

  <!-- Association class Participation (between ResearchAssociate and Project) -->
  <eClassifiers xsi:type="ecore:EClass" name="Participation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Participation references Project -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"
        lowerBound="1" eOpposite="#//Project/participations"/>
  </eClassifiers>

</ecore:EPackage>
