<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
  xmi:version="2.0"
  xmlns:xmi="http://www.omg.org/XMI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
  name="university"
  nsURI="http://www.example.org/university"
  nsPrefix="university">

  <!-- Abstract class Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Employee leads 0..1 Faculty -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="leads" eType="#//Faculty" upperBound="1"/>
  </eClassifiers>

  <!-- Class Faculty -->
  <eClassifiers xsi:type="ecore:EClass" name="Faculty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Faculty contains 1..* Institutes (composition) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="institutes" lowerBound="1" upperBound="-1" eType="#//Institute" containment="true"/>
  </eClassifiers>

  <!-- Class AdministrativeEmployee -->
  <eClassifiers xsi:type="ecore:EClass" name="AdministrativeEmployee" eSuperTypes="#//Employee"/>

  <!-- Class ResearchAssociate -->
  <eClassifiers xsi:type="ecore:EClass" name="ResearchAssociate" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfStudy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- ResearchAssociate aggregated by 1..* Institutes -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="institutes" lowerBound="1" upperBound="-1" eType="#//Institute" eOpposite="#//Institute/researchAssociates"/>
    <!-- ResearchAssociate participates in 0..* Projects -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1" eType="#//Project" eOpposite="#//Project/researchAssociates"/>
    <!-- ResearchAssociate has Participations (association class) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="participations" upperBound="-1" eType="#//Participation" containment="true"/>
  </eClassifiers>

  <!-- Class Institute -->
  <eClassifiers xsi:type="ecore:EClass" name="Institute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Institute aggregates 1..* ResearchAssociates -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchAssociates" lowerBound="1" upperBound="-1" eType="#//ResearchAssociate" eOpposite="#//ResearchAssociate/institutes"/>
  </eClassifiers>

  <!-- Class Course -->
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <!-- Course is taught by 1..* Lecturers -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturers" lowerBound="1" upperBound="-1" eType="#//Lecturer" eOpposite="#//Lecturer/courses"/>
  </eClassifiers>

  <!-- Class Lecturer -->
  <eClassifiers xsi:type="ecore:EClass" name="Lecturer" eSuperTypes="#//ResearchAssociate">
    <!-- Lecturer teaches 1..* Courses -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses" lowerBound="1" upperBound="-1" eType="#//Course" eOpposite="#//Course/lecturers"/>
  </eClassifiers>

  <!-- Class Project -->
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Project involves 1..* ResearchAssociates -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchAssociates" lowerBound="1" upperBound="-1" eType="#//ResearchAssociate" eOpposite="#//ResearchAssociate/projects"/>
    <!-- Project has Participations (association class) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="participations" upperBound="-1" eType="#//Participation"/>
  </eClassifiers>

  <!-- Class Participation (association class between ResearchAssociate and Project) -->
  <eClassifiers xsi:type="ecore:EClass" name="Participation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchAssociate" lowerBound="1" eType="#//ResearchAssociate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" lowerBound="1" eType="#//Project"/>
  </eClassifiers>

</ecore:EPackage>
