<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
  xmi:version="2.0"
  xmlns:xmi="http://www.omg.org/XMI"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
  name="university"
  nsURI="http://www.example.org/university"
  nsPrefix="university">

  <!-- Root container class -->
  <eClassifiers xsi:type="ecore:EClass" name="UniversitySystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees"
      eType="#//Employee" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="faculties"
      eType="#//Faculty" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="courses"
      eType="#//Course" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects"
      eType="#//Project" upperBound="-1" containment="true"/>
  </eClassifiers>

  <!-- Abstract Employee class -->
  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssNo"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Employee "1" - "0..1" Faculty : leads -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="leads"
      eType="#//Faculty" upperBound="1" eOpposite="#//Faculty/leadBy"/>
  </eClassifiers>

  <!-- Faculty class -->
  <eClassifiers xsi:type="ecore:EClass" name="Faculty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Opposite of Employee.leads -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadBy"
      eType="#//Employee" lowerBound="1" eOpposite="#//Employee/leads"/>
    <!-- Faculty "1" composed of "1..*" Institute -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="institutes"
      eType="#//Institute" lowerBound="1" upperBound="-1"
      containment="true" eOpposite="#//Institute/faculty"/>
  </eClassifiers>

  <!-- AdministrativeEmployee class -->
  <eClassifiers xsi:type="ecore:EClass" name="AdministrativeEmployee"
    eSuperTypes="#//Employee"/>

  <!-- ResearchAssociate class -->
  <eClassifiers xsi:type="ecore:EClass" name="ResearchAssociate"
    eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfStudy"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Institute aggregates ResearchAssociate -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="institutes"
      eType="#//Institute" lowerBound="1" upperBound="-1"
      eOpposite="#//Institute/researchAssociates"/>
    <!-- ResearchAssociate contains Participation association class -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="participations"
      eType="#//Participation" upperBound="-1"
      containment="true" eOpposite="#//Participation/researchAssociate"/>
  </eClassifiers>

  <!-- Institute class -->
  <eClassifiers xsi:type="ecore:EClass" name="Institute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Opposite of Faculty.institutes -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="faculty"
      eType="#//Faculty" lowerBound="1" eOpposite="#//Faculty/institutes"/>
    <!-- Institute aggregates ResearchAssociates -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchAssociates"
      eType="#//ResearchAssociate" lowerBound="1" upperBound="-1"
      eOpposite="#//ResearchAssociate/institutes"/>
  </eClassifiers>

  <!-- Lecturer class -->
  <eClassifiers xsi:type="ecore:EClass" name="Lecturer"
    eSuperTypes="#//ResearchAssociate">
    <!-- Lecturer teaches Course -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="teaches"
      eType="#//Course" lowerBound="1" upperBound="-1"
      eOpposite="#//Course/taughtBy"/>
  </eClassifiers>

  <!-- Course class -->
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <!-- Opposite of Lecturer.teaches -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="taughtBy"
      eType="#//Lecturer" lowerBound="1" upperBound="-1"
      eOpposite="#//Lecturer/teaches"/>
  </eClassifiers>

  <!-- Project class -->
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Non-containment reference to Participation association class -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="participations"
      eType="#//Participation" upperBound="-1"
      eOpposite="#//Participation/project"/>
  </eClassifiers>

  <!-- Participation association class between ResearchAssociate and Project -->
  <eClassifiers xsi:type="ecore:EClass" name="Participation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours"
      eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Reference back to ResearchAssociate (contained there) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchAssociate"
      eType="#//ResearchAssociate" lowerBound="1"
      eOpposite="#//ResearchAssociate/participations"/>
    <!-- Reference to Project -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="project"
      eType="#//Project" lowerBound="1"
      eOpposite="#//Project/participations"/>
  </eClassifiers>

</ecore:EPackage>
