<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    xsi:type="ecore:EPackage"
    epackageID="BankAccount">

  <eClassifiers>

    <!-- Root Container -->
    <eClass xmi:id="_BankRoot" name="BankRoot">
      <eStructuralFeatures/>
    </eClass>

    <!-- Bank (Package Containing Classes) -->

    <!-- Customer Class -->
    <eClass xmi:id="_Customer" name="Customer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" dataType="_String" name="firstName"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" dataType="_String" name="lastName"/>

      <!-- Association to Accounts Class -->
      <eClassifiers xmi:id="_Accounts" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EReference" eType="_Account" lower="-1"
                             upper="5" containment="true" aggregation="composite"
                             eOpposite="_owner" name="accounts"/>
      </eClassifiers>

      <eStructuralFeatures xsi:type="ecore:EReference" opposite="_customerAccounts"
                           containment="false" name="accounts" eType="_Accounts"/>
    </eClass>
    
    <!-- Association to Account Class -->
    <eClass xmi:id="_CustomerAccountRef" abstract="true">
      <eReferences eType="_Customer" opposite="_accounts"
                   aggregation="composite" containment="false"/>

      <eClassifiers xmi:idref="_Owner"/>
    </eClass>

    <!-- Branch Class -->
    <eClass xmi:id="_Branch" name="Branch">
      <eStructuralFeatures xsi:type="ecore:EReference" opposite="_bank"
                           containment="false" name="bank" eType="_Bank"/>
    </eClass>

    <!-- Bank Class -->
    <eClass xmi:id="_Bank" name="Bank">
      <eStructuralFeatures xsi:type="ecore:EReference" eType="_Customer" upper="-1"
                           eOpposite="_bank" containment="false" name="customers"/>
      <eStructuralFeatures xsi:type="ecore:EReference" eType="_Branch" upper="-1"
                           eOpposite="_bank" containment="false" name="branches"/>
    </eClass>

    <!-- Account Class -->
    <eClass xmi:id="_Account" abstract="true" name="Account">
      <eStructuralFeatures xsi:type="ecore:EAttribute" dataType="_int" name="accountNumber"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" dataType="_double" name="balance"/>

      <!-- Association to Customer Account -->
      <eReferences xmi:id="CustomerAccountRefRef"
                   opposite="_owner" eType="_Customer"
                   containment="false">
        <eClassifiers xmi:idref="_Owner"/>
      </eReferences>
    </eClass>

    <!-- Current Account Class -->
    <eClass xmi:id="_CurrentAccount" name="CurrentAccount"
            eSuperTypes="_Account">
      <eStructuralFeatures xsi:type="ecore:EAttribute" dataType="_double" name="overdraftLimit"/>
    </eClass>

    <!-- Savings Account Class -->
    <eClass xmi:id="_SavingsAccount" name="SavingsAccount"
            eSuperTypes="_Account"/>

  </eClassifiers>

  <eSubPackages/>

  <!-- Data Type Definitions -->
  <eDataType xmi:type="ecore:EJavaDatatype" href="http://www.eclipse.org/emf/2002/Ecore#//String"/>  
</ecore:EPackage>
