<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
                xmlns:xmi="http://www.omg.org/XMI"
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

  <!-- Enumeration for InvitationStatus -->
  <eClassifiers xsi:type="ecore:EEnum" name="InvitationStatus">
    <eLiterals>
      <eEnumLiteral eName="ATTENDING"/>
      <eEnumLiteral eName="MAYBE_ATTENDING"/>
      <eEnumLiteral eName="NOT_ATTENDING"/>
    </eLiterals>
  </eClassifiers>

  <!-- Enumeration for TaskStatus -->
  <eClassifiers xsi:type="ecore:EEnum" name="TaskStatus">
    <eLiterals>
      <eEnumLiteral eName="NEEDS_TO_BE_DONE"/>
      <eEnumLiteral eName="DONE"/>
      <eEnumLiteral eName="NOT_APPLICABLE"/>
    </eLiterals>
  </eClassifiers>

  <!-- Custom DataType for LocalDate -->
  <eClassifiers xsi:type="ecore:EDataType" name="LocalDate">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="primitiveType">java.time.LocalDate</details>
    </eAnnotations>
  </eClassifiers>

  <!-- Custom DataType for LocalTime -->
  <eClassifiers xsi:type="ecore:EDataType" name="LocalTime">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="primitiveType">java.time.LocalTime</details>
    </eAnnotations>
  </eClassifiers>

  <!-- Class for Event -->
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures>
      <eAttribute eType="ecore:EString" name="_description"/>
      <eAttribute eType="ecore:EDate" name="_startDate"/>
      <eAttribute eType="ecore:EDate" name="_endDate"/>
      <eReference eType="#EventHasTasks" name="tasks" upper="-1" lower="0"
                  containment="false" resolveProxies="true"/>
      <eReference eType="#Location" name="location" upper="1" lower="0"
                  containment="false" resolveProxies="true"/>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Class for Location -->
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures>
      <eAttribute eType="ecore:EString" name="_name"/>
      <eAttribute eType="ecore:EString" name="_address"/>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Class for Organizer -->
  <eClassifiers xsi:type="ecore:EClass" name="Organizer">
    <eStructuralFeatures>
      <eAttribute eType="ecore:EString" name="_firstName"/>
      <eAttribute eType="ecore:EString" name="_lastName"/>
      <eAttribute eType="ecore:EString" name="_email"/>
      <eAttribute eType="ecore:EString" name="_postalAddress"/>
      <eAttribute eType="ecore:EString" name="_phone"/>
      <eAttribute eType="ecore:EString" name="_password"/>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Class for Attendee -->
  <eClassifiers xsi:type="ecore:EClass" name="Attendee">
    <eStructuralFeatures>
      <eAttribute eType="ecore:EString" name="_firstName"/>
      <eAttribute eType="ecore:EString" name="_lastName"/>
      <eAttribute eType="ecore:EString" name="_email"/>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Association Class for Event Tasks -->
  <eClassifiers xsi:type="ecore:EClassifier" name="EventHasTasks">
    <eStructuralFeatures>
      <eReference eType="#Event" name="_event" upper="1" lower="1"
                  containment="true"/>
      <eReference eType="#Task" name="_tasks" upper="-2" lower="*"
                  containment="false" resolveProxies="true"/>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Association class for Invitations -->
  <eClassifiers xsi:type="ecore:EClass" name="EventInvitation">
    <eStructuralFeatures>
      <eReference eType="#Organizer" name="_organizer" upper="1"/>
      <eReference eType="#Attendee" name="_attendee" upper="-2" lower="0"
                  containment="false" resolveProxies="true"/>
      <eAttribute eType="InvitationStatus" name="_status"/>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Class for Task -->
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures>
      <eAttribute eType="ecore:EString" name="_name"/>
      <eReference eType="#TaskStatus" name="_taskStatus" upper="1" lower="1"
                  containment="false"/>
    </eStructuralFeatures>
  </eClassifiers> 

  <!-- Root container class -->
  <eClassifiers xsi:type="ecore:EClass" name="CelebrationOrganization">
    <eStructuralFeatures>
      <eReference eType="#Event" name="_events" upper="-2" lower="1"
                  containment="false"/>
      <eReference eType="#Task" name="_checklists" upper="-2" lower="0"
                  containment="false"/>
    </eStructuralFeatures>
  </eClassifiers>

</ecore:EPackage>
