<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="housing"
    nsURI="http://www.example.org/housing"
    nsPrefix="housing">

  <!-- Enumerations -->
  <eClassifiers xsi:type="ecore:EEnum" name="BuildingMaterial">
    <eLiterals name="wood"/>
    <eLiterals name="brick"/>
    <eLiterals name="concrete"/>
  </eClassifiers>

  <!-- Classes -->

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="HousingSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="houses"
        eType="#//House" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="companies"
        eType="#//Company" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- House -->
  <eClassifiers xsi:type="ecore:EClass" name="House">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildingMaterial"
        eType="#//BuildingMaterial"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basement"
        eType="#//Basement" containment="true" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobLogs"
        eType="#//JobLog" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servicedBy"
        eType="#//JobLog" upperBound="-1" eOpposite="#//JobLog/house"/>
  </eClassifiers>

  <!-- SemiDetachedHouse -->
  <eClassifiers xsi:type="ecore:EClass" name="SemiDetachedHouse" eSuperTypes="#//House">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasOwnGarden"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfWindows"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parking"
        eType="#//Parking" containment="true" upperBound="1" lowerBound="1"/>
  </eClassifiers>

  <!-- Basement (abstract) -->
  <eClassifiers xsi:type="ecore:EClass" name="Basement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- EarthBasement -->
  <eClassifiers xsi:type="ecore:EClass" name="EarthBasement" eSuperTypes="#//Basement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="humidityLevel"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- ConcreteBasement -->
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteBasement" eSuperTypes="#//Basement">
  </eClassifiers>

  <!-- Parking (abstract) - either Carport or Garage -->
  <eClassifiers xsi:type="ecore:EClass" name="Parking" abstract="true">
  </eClassifiers>

  <!-- Carport -->
  <eClassifiers xsi:type="ecore:EClass" name="Carport" eSuperTypes="#//Parking">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDoubleCarport"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasFlatRoof"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>

  <!-- Garage -->
  <eClassifiers xsi:type="ecore:EClass" name="Garage" eSuperTypes="#//Parking">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasAutomaticGarageDoor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>

  <!-- Company -->
  <eClassifiers xsi:type="ecore:EClass" name="Company">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobLogs"
        eType="#//JobLog" upperBound="-1" eOpposite="#//JobLog/company"/>
  </eClassifiers>

  <!-- JobLog - association class between House and Company -->
  <eClassifiers xsi:type="ecore:EClass" name="JobLog">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfHours"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agreedPrice"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="house"
        eType="#//House" eOpposite="#//House/servicedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="company"
        eType="#//Company" eOpposite="#//Company/jobLogs"/>
  </eClassifiers>

</ecore:EPackage>
