<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deLijnModel" nsURI="http://deLijn/model" nsPrefix="deLijn">
    <!-- Classes -->
    <ecore:EClass name="RootContainer">
      <eStructuralFeatures>
        <ecore:EReference name="buses" eType="#//Bus" containment="true" upperBound="-1"/>
        <ecore:EReference name="trajectories" eType="#//Trajectory" containment="true" upperBound="-1"/>
        <ecore:EReference name="lines" eType="#//Line" containment="true" upperBound="-1"/>
        <ecore:EReference name="mensos" eType="#//MensoTicket" containment="true" upperBound="-1"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Bus">
      <eStructuralFeatures>
        <ecore:EAttribute name="lineNumber" eType="ecore:EInt"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Trajectory">
      <eStructuralFeatures>
        <ecore:EReference name="approvals" eType="#//Approval" containment="true" upperBound="-1"/>
        <ecore:EAttribute name="destination" eType="ecore:EString"/>
        <ecore:EAttribute name="startDate" eType="ecore:EDate"/>
        <ecore:EAttribute name="endDate" eType="ecore:EDate"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Line">
      <eStructuralFeatures>
        <ecore:EReference name="trajectories" eType="#//Trajectory" upperBound="-1"/>
        <ecore:EAttribute name="category" eType="ecore:EString"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Approval">
      <eStructuralFeatures>
        <ecore:EReference name="trajectory" eType="#//Trajectory"/>
        <ecore:EAttribute name="status" eType="ecore:EString"/>
        <ecore:EAttribute name="requestDate" eType="ecore:EDate"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="MensoTicket">
      <eStructuralFeatures>
        <ecore:EReference name="customer" eType="#//Customer"/>
        <ecore:EAttribute name="issueDate" eType="ecore:EDate"/>
        <ecore:EAttribute name="validityPeriodMonths" eType="ecore:EInt"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Customer">
      <eStructuralFeatures>
        <ecore:EAttribute name="homeAddress" eType="ecore:EString"/>
        <ecore:EAttribute name="officeAddress" eType="ecore:EString"/>
        <ecore:EAttribute name="workingHours" eType="ecore:EString"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Data Types -->
    <ecore:EDataType name="TimeOfDay">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="documentation">A time of day type using java.time.LocalTime</details>
      </eAnnotations>
    </ecore:EDataType>

    <!-- Associations -->
    <ecore:EClass name="TripRecord">
      <eStructuralFeatures>
        <ecore:EReference name="mensoticket" eType="#//MensoTicket"/>
        <ecore:EAttribute name="timeOfDay" eType="#//TimeOfDay"/>
        <ecore:EAttribute name="date" eType="ecore:EDate"/>
      </eStructuralFeatures>
    </ecore:EClass>

  </ecore:EPackage>
</xmi:XMI>
