<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="WebPortalModel" nsURI="http://www.example.org/webportal">
    
    <!-- Enum for Energy Class -->
    <ecore:EEnum name="EnergyClassEnum">
      <ecore:EEnumLiteral name="A"/>
      <ecore:EEnumLiteral name="B"/>
      <ecore:EEnumLiteral name="C"/>
      <ecore:EEnumLiteral name="D"/>
    </ecore:EEnum>

    <!-- Root Container -->
    <ecore:EClass name="SystemRoot">
      <ecore:EStructuralFeatures>
        <ecore:EReference name="webPortals" eClassifier="WebPortal" eContainment="true"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <!-- Web Portal -->
    <ecore:EClass name="WebPortal">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="versionNumber" eType="java.lang.String"/>
        <ecore:EAttribute name="urlAddress" eType="java.lang.String"/>
        <ecore:EReference name="buildings" eClassifier="Building" eContainment="true"/>
        <ecore:EReference name="users" eClassifier="User" eContainment="true"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <!-- User Hierarchy -->
    <ecore:EClass name="User">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="userName" eType="java.lang.String"/>
        <ecore:EAttribute name="email" eType="java.lang.String"/>
        <ecore:EAttribute name="password" eType="java.lang.String"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Administrator">
      <ecore:ESuperTypes>
        <ecore:EClassifier eClassifier="User"/>
      </ecore:ESuperTypes>
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="idCardNumber" eType="java.lang.String"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <!-- Building and related entities -->
    <ecore:EClass name="Building">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="buildingId" eType="java.lang.Long"/>
        <ecore:EAttribute name="name" eType="java.lang.String"/>
        <ecore:EAttribute name="energyClass" eType="EnergyClassEnum"/>
        <ecore:EAttribute name="address" eType="java.lang.String"/>
        <ecore:EAttribute name="yearOfConstruction" eType="java.lang.Integer"/>
        <ecore:EReference name="owner" eClassifier="User"/>
        <ecore:EReference name="additionalEntries" eClassifier="AdditionalEntry" eContainment="true"/>
        <ecore:EReference name="images" eClassifier="Image" eContainment="true"/>
        <ecore:EReference name="comments" eClassifier="Comment" eContainment="true"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <!-- Additional Entry Hierarchy -->
    <ecore:EClass name="AdditionalEntry" abstract="true">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="name" eType="java.lang.String"/>
        <ecore:EAttribute name="isPublic" eType="java.lang.Boolean"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="TextualEntry">
      <ecore:ESuperTypes>
        <ecore:EClassifier eClassifier="AdditionalEntry"/>
      </ecore:ESuperTypes>
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="textContent" eType="java.lang.String"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="NumericEntry">
      <ecore:ESuperTypes>
        <ecore:EClassifier eClassifier="AdditionalEntry"/>
      </ecore:ESuperTypes>
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="value" eType="java.lang.Double"/>
        <ecore:EAttribute name="unit" eType="java.lang.String"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <!-- Image -->
    <ecore:EClass name="Image">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="fileName" eType="java.lang.String"/>
        <ecore:EAttribute name="isProfilePhoto" eType="java.lang.Boolean"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <!-- Comment -->
    <ecore:EClass name="Comment">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="content" eType="java.lang.String"/>
        <ecore:EAttribute name="timestamp" eType="java.util.Date"/>
        <ecore:EReference name="author" eClassifier="User"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

  </ecore:EPackage>
</xmi:XMI>
