<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="sober" nsURI="http://sober.com/metamodel">

    <!-- Custom Datatype for time without date as per requirements -->
    <ecore:EDataType name="SoberLocalTime" instanceClassName="java.time.LocalTime"/>

    <!-- Enum for ride-hailing request types -->
    <ecore:EEnum name="RequestType">
      <ecore:EEnumLiteral name="SOBER_APP"/>
      <ecore:EEnumLiteral name="HAND_WAVING"/>
    </ecore:EEnum>

    <!-- Root container acting as the entry point for the system -->
    <ecore:EClass name="SoberSystem">
      <ecore:EReference name="cabs" EClassifier="Cab" containment="true"/>
      <ecore:EReference name="customers" EClassifier="Customer" containment="true"/>
      <ecore:EReference name="owners" EClassifier="CarOwner" containment="true"/>
      <ecore:EReference name="rides" EClassifier="Ride" containment="true"/>
    </ecore:EClass>

    <!-- Cab hierarchy -->
    <ecore:EClass name="Cab" abstract="true">
      <ecore:EReference name="accidents" EClassifier="Accident" containment="true"/>
    </ecore:EClass>

    <ecore:EClass name="FleetCab">
      <ecore:ESuperClass EClassifier="Cab"/>
    </ecore:EClass>

    <ecore:EClass name="PrivateCab">
      <ecore:ESuperClass EClassifier="Cab"/>
      <ecore:EReference name="owner" EClassifier="CarOwner"/>
    </ecore:EClass>

    <!-- Car Owner information -->
    <ecore:EClass name="CarOwner">
      <ecore:EAttribute name="name" EType="java.lang.String"/>
    </ecore:EClass>

    <!-- Customer information -->
    <ecore:EClass name="Customer">
      <ecore:EAttribute name="name" EType="java.lang.String"/>
    </ecore:EClass>

    <!-- Base Ride class for shared common attributes -->
    <ecore:EClass name="Ride" abstract="true">
      <ecore:EReference name="cab" EClassifier="Cab"/>
      <ecore:EAttribute name="pickUpTime" EType="SoberLocalTime"/>
      <ecore:EAttribute name="dropOffTime" EType="SoberLocalTime"/>
      <ecore:EAttribute name="pickUpLocation" EType="java.lang.String"/>
      <ecore:EAttribute name="dropOffLocation" EType="java.lang.String"/>
      <ecore:EAttribute name="rideDuration" EType="java.lang.Double"/>
      <ecore:EAttribute name="distance" EType="java.lang.Double"/>
    </ecore:EClass>

    <!-- Ride-hailing specific service -->
    <ecore:EClass name="RideHail">
      <ecore:ESuperClass EClassifier="Ride"/>
      <ecore:EAttribute name="fee" EType="java.lang.Double"/>
      <ecore:EAttribute name="requestType" EClassifier="RequestType"/>
      <ecore:EAttribute name="numberOfPassengers" EType="java.lang.Integer"/>
      <ecore:EReference name="leadCustomer" EClassifier="Customer"/>
    </ecore:EClass>

    <!-- Ride-sharing (carpooling) specific service -->
    <ecore:EClass name="RideShare">
      <ecore:ESuperClass EClassifier="Ride"/>
      <ecore:EAttribute name="upfrontNegotiatedFee" EType="java.lang.Double"/>
      <ecore:EReference name="customers" EClassifier="Customer"/>
    </ecore:EClass>

    <!-- Accident information -->
    <ecore:EClass name="Accident">
      <ecore:EAttribute name="date" EType="EDate"/>
      <ecore:EAttribute name="location" EType="java.lang.String"/>
      <ecore:EAttribute name="damageAmount" EType="java.lang.Double"/>
    </ecore:EClass>

  </ecore:EPackage>
</xmi:XMI>
