<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="ResearchProjectManagement" nsURI="http://www.example.org/ResearchProjectManagement" xmi:type="ecore:EPackage">
    <eClass name="ResearchManagementSystem" xmi:type="ecore:EClass">
      <eStructuralFeatures>
        <eReference name="departments" containment="true" eType="Department" xmi:type="ecore:ERefReference"/>
        <eReference name="projects" containment="true" eType="Project" xmi:type="ecore:ERefReference"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Department" xmi:type="ecore:EClass">
      <eStructuralFeatures>
        <eReference name="researchGroups" containment="true" eType="ResearchGroup" xmi:type="ecore:ERefReference"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="ResearchGroup" xmi:type="ecore:EClass">
      <eStructuralFeatures>
        <eReference name="department" eType="Department" xmi:type="ecore:ERefReference"/>
        <eReference name="researchers" containment="true" eType="Researcher" xmi:type="ecore:ERefReference"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Researcher" xmi:type="ecore:EClass">
      <eStructuralFeatures>
        <eReference name="researchGroup" eType="ResearchGroup" xmi:type="ecore:ERefReference"/>
        <!-- Association class containment side -->
        <eReference name="wpAssignments" containment="true" eType="WPAssignment" xmi:type="ecore:ERefReference"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Project" xmi:type="ecore:EClass">
      <eStructuralFeatures>
        <eReference name="workPackages" containment="true" eType="WorkPackage" xmi:type="ecore:ERefReference"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="WorkPackage" xmi:type="ecore:EClass">
      <eStructuralFeatures>
        <eReference name="project" eType="Project" xmi:type="ecore:ERefReference"/>
        <eReference name="leaderRG" eType="ResearchGroup" xmi:type="ecore:ERefReference"/>
        <!-- Association class non-containment side -->
        <eReference name="wpAssignments" eType="WPAssignment" xmi:type="ecore:ERefReference"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="WPAssignment" xmi:type="ecore:EClass">
      <eStructuralFeatures>
        <eReference name="researcher" eType="Researcher" xmi:type="ecore:ERefReference"/>
        <eReference name="workPackage" eType="WorkPackage" xmi:type="ecore:ERefReference"/>
      </eStructuralFeatures>
    </eClass>
  </ePackage>
</xmi:XMI>
