<?xml version="1.0" encoding="UTF-8"?>
<ePackages xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/spec/XMI/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ePackage name="bank" nsUri="http://www.example.org/bank">
    <eClass name="BankSystem">
      <eReferences xsi:type="eReference" name="banks" eType="Bank" containment="true"/>
    </eClass>

    <eClass name="Bank">
      <eReferences xsi:type="eReference" name="branches" eType="Branch" containment="true"/>
      <eReferences xsi:type="eReference" name="customers" eType="Customer" containment="true"/>
    </eClass>

    <eClass name="Branch"/>

    <eClass name="Customer">
      <eAttributes xsi:type="eAttribute" name="firstName" eType="String"/>
      <eAttributes xsi:type="eAttribute" name="lastName" eType="String"/>
      <eReferences xsi:type="eReference" name="accounts" eType="Account" containment="true"/>
    </eClass>

    <eClass name="Account" abstract="true">
      <eAttributes xsi:type="eAttribute" name="accountNumber" eType="int"/>
      <eAttributes xsi:type="eAttribute" name="balance" eType="double"/>
      <eReferences xsi:type="eReference" name="owner" eType="Customer"/>
    </eClass>

    <eClass name="CurrentAccount">
      <eSuperTypes xsi:type="eSuperType" eClass="Account"/>
      <eAttributes xsi:type="eAttribute" name="overdraftLimit" eType="double"/>
    </eClass>

    <eClass name="SavingsAccount">
      <eSuperTypes xsi:type="eSuperType" eClass="Account"/>
    </eClass>
  </ePackage>
</ePackages>
