<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:version="2.0">
  <ecore:EPackage name="louvreMuseum" nsURI="http://www.example.org/louvreMuseum" nsPrefix="louvreMuseum" xmi:id="package">
    <!-- RootContainer class -->
    <eClassifiers xmi:type="ecore:EClass" name="RootContainer">
      <eStructuralFeatures xmi:type="ecore:EReference" name="locations" ordered="false" unique="true" lowerBound="0" upperBound="-1" eType="#//Location"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="employees" ordered="false" unique="true" lowerBound="0" upperBound="-1" eType="#//Employee"/>
    </eClassifiers>

    <!-- Location class -->
    <eClassifiers xmi:type="ecore:EClass" name="Location">
      <eStructuralFeatures xmi:type="ecore:EReference" name="exhibitions" ordered="false" unique="true" lowerBound="0" upperBound="-1" eType="#//Exhibition"/>
    </eClassifiers>

    <!-- Exhibition class -->
    <eClassifiers xmi:type="ecore:EClass" name="Exhibition">
      <eStructuralFeatures xmi:type="ecore:EReference" name="coordinator" ordered="false" unique="true" lowerBound="1" upperBound="1" eType="#//Employee"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="desiredItems" ordered="false" unique="true" lowerBound="0" upperBound="-1" eType="#//ExhibitionItem"/>
    </eClassifiers>

    <!-- ExhibitionItem class -->
    <eClassifiers xmi:type="ecore:EClass" name="ExhibitionItem">
      <eStructuralFeatures xmi:type="ecore:EReference" name="requestedPieces" ordered="false" unique="true" lowerBound="0" upperBound="-1" eType="#//RequestedPiece"/>
    </eClassifiers>

    <!-- RequestedPiece class -->
    <eClassifiers xmi:type="ecore:EClass" name="RequestedPiece">
      <eStructuralFeatures xmi:type="ecore:EReference" name="collector" ordered="false" unique="true" lowerBound="1" upperBound="1" eType="#//Collector"/>
    </eClassifiers>

    <!-- Employee class -->
    <eClassifiers xmi:type="ecore:EClass" name="Employee">
      <eStructuralFeatures xmi:type="ecore:EReference" name="coachedBy" ordered="false" unique="true" lowerBound="0" upperBound="1" eType="#//Employee"/>
    </eClassifiers>

    <!-- Collector class -->
    <eClassifiers xmi:type="ecore:EClass" name="Collector"/>

    <!-- Custom Data Type for TimeWithoutDate -->
    <eClassifiers xmi:type="ecore:EDataType" name="TimeWithoutDate">
      <instanceClassName>java.time.LocalTime</instanceClassName>
    </eClassifiers>

    <!-- Association class ExhibitionCoordinator -->
    <eClassifiers xmi:type="ecore:EClass" name="ExhibitionCoordinator">
      <eStructuralFeatures xmi:type="ecore:EReference" name="exhibition" ordered="false" unique="true" lowerBound="1" upperBound="1" eType="#//Exhibition"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="employee" ordered="false" unique="true" lowerBound="1" upperBound="1" eType="#//Employee" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
