<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.5.1"
           xmlns:xmi="http://www.omg.org/spec/XMI/2.5/20160804"
           xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
           xmlns:uml="path/to/UML/metamodel.xmi">
    
    <packagedElement xmi:type="uml:Class" name="InsuranceCompany">
        <ownedAttribute xmi:id="_zQjL1cMhEeuyb6s7U9rN0w" name="name" type="_String"/>
        
        <!-- Broker class -->
        <ownedElement>
            <packagedElement xmi:type="uml:Class" name="Broker">
                <ownedAttribute xmi:id="broker_id_attribute" name="id" type="_int"/>
                <generalizableElement xmi:idref="_uV5R6cPTEeuxg7vA0Mq4jQ"/>
                <ownedOperation xmi:id="getAssignedTo" name="__toString"/>
            </packagedElement>

            <!-- Customer class -->
            <packagedElement xmi:type="uml:Class" name="Customer">
                <ownedAttribute xmi:id="customer_id_attribute" name="id" type="_int"/>
                <ownedOperation xmi:id="createProfile" name="__toString"/>
                <generalizableElement xmi:endType="_uV5R5cPTEeuxg7vA0Mq4jQ"/>
            </packagedElement>

            <!-- PolicyType class -->
            <packagedElement xmi:type="uml:Class" name="PolicyType"/>

            <!-- Claim class -->
            <ownedElement>
                <packagedElement xmi:type="uml:Class" name="Claim">
                    <ownedAttribute xmi:id="claim_id_attribute" name="id" type="_int"/>
                </packagedElement>
            </ownedElement>

        </ownedElement>
    </packagedElement>

    <!-- Root container class -->
    <packagedElement xmi:type="uml:Class" name="RootContainer">
        <ownedAttribute xmi:id="insuranceCompanies_attribute"
                        name="insuranceCompanies"
                        type="_uml_Collection_Property__InsuranceCompany"/>
    </packagedElement>
</uml:Model>

<!-- Datatypes section correctly separated beyond the root element -->
<ecore:EDataType xsi:type="ucore:SimpleType" xmi:id="_int" name="int">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value"/>
</ecore:EDataType>

<ecore:EDataType xsi:type="ucore:SimpleType" xmi:id="_String" name="String">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value"/>                
</ecore:EDataType>
