<?xml version="1.0" encoding="UTF-8"?>
<uml:Package xmi:version="2.4"
    xmlns:xmi="http://schema.omg.org/spec/XMI/2.4"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

    <eAnnotations source="Custom_Annotation" xmi:id="_1">
        <details value="RootContainer"/>
    </eAnnotations>

    <!-- Enumeration for ProblemType -->
    <ecore:EEnum name="ProblemType">
        <EltStrLit name="CARDIAC_ISSUE"/>
        <!-- Additional problem types can be added here -->
    </ecore:EEnum>

    <!-- Hospital Class -->
    <ecore:EClass name="Hospital">
        <eStructuralFeatures xsi:type="ecore:EReference" name="permissionForExaminations"
                             upper="-1" lower="0" containment="true" eType="#ExaminationPermission"/>
    </ecore:EClass>

    <!-- ExaminationPermission Class -->
    <ecore:EClass name="ExaminationPermission">
        <eStructuralFeatures xsi:type="ecore:EReference" name="examinationType"
                             upper="-1" lower="0" containment="false" eType="#ExaminationType"/>
    </ecore:EClass>

    <!-- ExaminationType Class -->
    <ecore:EClass name="ExaminationType">
        <eStructuralFeatures xsi:type="ecore:EReference" name="hospitalsWithPermission"
                             upper="-1" lower="0" containment="false" eType="#Hospital"/>
    </ecore:EClass>

    <!-- TreatmentPlan Class -->
    <ecore:EClass name="TreatmentPlan">
        <eStructuralFeatures xsi:type="ecore:EReference" name="problemType"
                             upper="-1" lower="0" containment="false" eType="#ProblemType"/>
        <eStructuralFeatures xsi:type="ecore:EReference" name="advisedExaminations"
                             upper="-1" lower="0" containment="false" eType="#ExaminationType"/>
    </ecore:EClass>

    <!-- Patient Class -->
    <ecore:EClass name="Patient">
        <eStructuralFeatures xsi:type="ecore:EReference" name="hospitalVisit"
                             upper="-1" lower="0" containment="false" eType="#HospitalVisit"/>
    </ecore:EClass>

    <!-- HospitalVisit Class -->
    <ecore:EClass name="HospitalVisit">
        <eStructuralFeatures xsi:type="ecore:EReference" name="hospital"
                             upper="-1" lower="0" containment="false" eType="#Hospital"/>
    </ecore:EClass>

</uml:Package>
