<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.5.0"
           xmlns:xmi="http://www.omg.org/spec/XMI/20131024"
           xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
           xmlns:uml="http://example.com/UML_Model">

    <eAnnotations>
        <details key="description">Ecore metamodel of De Lijn BUS SYSTEM</details>
    </eAnnotations>

    <!-- Root container for the model -->
    <packagedElement xmi:id="_RootContainer" xmi:type="uml:Package" name="DeLijnBusSystem">
        
        <!-- Class Definitions -->

        <packagedElement xmi:id="_TrajectoryId" xmi:type="uml:Class" name="Trajectory">
            <ownedAttributes>
                <property xmi:id="_name" type="_string_"/> 
                <reference xmi:id="_approvalStatus_ref" type="ApprovalStatus"/>
            </ownedAttributes>
        </packagedElement>

        <packagedElement xmi:id="_BusLineId" xmi:type="uml:Class" name="BusLine">
            <generalization general="_TrajectoryId" />
            <ownedAttributes>
                <property xmi:id="_categoryType" type="_string_"/>
            </ownedAttributes>
        </packagedElement>

        <packagedElement xmi:id="_BusId" xmi:type="uml:Class" name="Bus">
            <ownedAttributes>
                <reference xmi:id="_line_ref" upper="[1]" type="BusLine"/>
            </ownedAttributes>
        </packagedElement>

        <packagedElement xmi:id="_ApprovalId" xmi:type="uml:Class" name="Approval">
            <ownedAttributes>
                <enumLiteralValue xmi:id="_approved" displayName="Approved" value="" type="ApprovalStatus"/>
            </ownedAttributes>
        </packagedElement>

        <packagedElement xmi:id="_UserId" xmi:type="uml:Class" name="User">
            <ownedAttributes>
                <reference xmi:id="_mensoTicket_ref" upper="[1]" type="MENSO"/>
            </ownedAttributes>
        </packagedElement>

        <packagedElement xmi:id="_MensoId" xmi:type="uml:Class" name="MENSO">
            <ownedAttributes>
                <reference xmi:id="_customerId_ref" type="User"/>
                <associationEnd xmi:id="_transaction_ref" upper="[0..*]" type="MENSOTransaction"/>
            </ownedAttributes>
        </packagedElement>

        <packagedElement xmi:id="_MensoTransactionId" xmi:type="uml:Class" name="MENSOTransaction">
            <ownedAttributes>
                <reference xmi:id="_busLine_ref" type="BusLine" visibility="public"/>
                <property xmi:id="_date" type="EDate"/>
                <property xmi:id="_time" type="ETime"/>
            </ownedAttributes>
        </packagedElement>

        <!-- Enumeration for Statuses -->

        <packagedElement xmi:id="_ApprovalStatusId" xmi:type="uml:Enumeration" name="ApprovalStatus">
             <ownedLiteral>
                 <enumerationLiteral xmi:id="_approved" displayName="Approved"/>
                 <enumerationLiteral xmi:id="_refused" displayName="Refused"/>
                 <enumerationLiteral xmi:id="_pendingChange" displayName="Pending Change"/>
            </ownedLiteral>
        </packagedElement>

        <!-- Datatypes -->
        
        <simpleType xmi:id="_string_" name="String" />
        <simpleType xmi:id="_EDate" name="EDate">
            <remarks> Custom datatype for dates based on Java time API </remarks>
        </simpleType>
        <simpleType xmi:id="_ETime" name="ETime">
            <remarks> Custom datatype for times without dates, built upon Java time API</remarks>
        </simpleType>

    </packagedElement>
    
</uml:Model>
