import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'application'
    id 'com.gradleup.shadow' version '9.4.2'
}

group = 'uk.ac.york.cs.puml2emfatic'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
    }

    // Needed for EMF Compare
    ivy {
        url 'https://download.eclipse.org/releases/2023-12/202312061001/plugins'
        patternLayout {
            artifact '/[artifact]_[revision].[ext]'
        }
        metadataSources { artifact()}
    }
}

application {
    mainClass = 'uk.ac.york.cs.puml2emfatic.cmd.Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'dev.langchain4j:langchain4j-open-ai:1.11.8'
    implementation 'dev.langchain4j:langchain4j:1.11.8'
    implementation 'io.github.cdimascio:dotenv-java:3.2.0'
    implementation 'ch.qos.logback:logback-classic:1.5.35'

    implementation 'info.picocli:picocli:4.7.7'
    annotationProcessor 'info.picocli:picocli-codegen:4.7.7'

    implementation 'org.a2aproject.sdk:a2a-java-sdk-client:1.1.0.Final'
    implementation 'org.a2aproject.sdk:a2a-java-sdk-opentelemetry-client:1.1.0.Final'

    implementation 'org.eclipse.emfatic:org.eclipse.emfatic.core:1.1.0'
    implementation 'org.eclipse.platform:org.eclipse.core.resources:3.24.0'
    implementation 'org.eclipse.emf:org.eclipse.emf.ecore:2.23.0'
    implementation 'org.eclipse.emf:org.eclipse.emf.common:2.23.0'
    implementation 'org.eclipse.emf:org.eclipse.emf.ecore.xmi:2.16.0'
    implementation 'org.eclipse.epsilon:org.eclipse.epsilon.evl.engine:2.9.0-SNAPSHOT'
    implementation 'org.eclipse.epsilon:org.eclipse.epsilon.emc.emf:2.9.0-SNAPSHOT'
    implementation 'org.eclipse.epsilon:org.eclipse.epsilon.flexmi:2.9.0-SNAPSHOT'

    implementation 'org.eclipse.emf.compare:org.eclipse.emf.compare:3.5.3.202311200811'
    implementation 'com.google.guava:guava:27.0-jre'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

shadowJar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    mergeServiceFiles()
    filesMatching('META-INF/services/**') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE // Or WARN.
    }
    filesMatching('plugin.properties') {
        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
    append('plugin.properties')
}

test {
    useJUnitPlatform()
}

compileJava {
    options.compilerArgs += ["-Aproject=${project.group}/${project.name}"]
}