<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="airlineModel" nsURI="airlineModel" nsPrefix="airlineModel">

    <!-- Root container class -->
    <ecore:EClass xmi:id="-1" name="RootContainer">
      <eStructuralFeatures xmi:id="-2" name="aircrafts" eType="#//Aircraft"/>
      <eStructuralFeatures xmi:id="-3" name="flights" eType="#//Flight"/>
      <eStructuralFeatures xmi:id="-4" name="passengers" eType="#//Passenger"/>
      <eStructuralFeatures xmi:id="-5" name="tickets" eType="#//Ticket"/>
      <eStructuralFeatures xmi:id="-6" name="seatCategories" eType="#//SeatCategory"/>
      <eStructuralFeatures xmi:id="-7" name="airlines" eType="#//Airline"/>
      <eStructuralFeatures xmi:id="-8" name="crewMembers" eType="#//CrewMember"/>
      <eStructuralFeatures xmi:id="-9" name="pilots" eType="#//Pilot"/>
      <eStructuralFeatures xmi:id="-10" name="flightAttendants" eType="#//FlightAttendant"/>
      <eStructuralFeatures xmi:id="-11" name="airports" eType="#//Airport"/>
    </ecore:EClass>

    <!-- Aircraft class -->
    <ecore:EClass xmi:id="-12" name="Aircraft">
      <eStructuralFeatures xmi:id="-13" name="name" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-14" name="type" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-15" name="yearOfManufacture" eType="ecore:EInt"/>
      <eStructuralFeatures xmi:id="-16" name="nextInspectionDate" eType="#//DateTime"/>
      <eStructuralFeatures xmi:id="-17" name="flights" eType="#//Flight" lowerBound="0" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Flight class -->
    <ecore:EClass xmi:id="-18" name="Flight">
      <eStructuralFeatures xmi:id="-19" name="flightNumber" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-20" name="date" eType="#//DateTime"/>
      <eStructuralFeatures xmi:id="-21" name="passengers" eType="#//Passenger" lowerBound="0" upperBound="-1"/>
    </ecore:EClass>

    <!-- Passenger class -->
    <ecore:EClass xmi:id="-22" name="Passenger">
      <eStructuralFeatures xmi:id="-23" name="name" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-24" name="passportNumber" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-25" name="flights" eType="#//Flight" lowerBound="0" upperBound="-1"/>
    </ecore:EClass>

    <!-- Ticket class -->
    <ecore:EClass xmi:id="-26" name="Ticket">
      <eStructuralFeatures xmi:id="-27" name="ticketNumber" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-28" name="price" eType="ecore:EDouble"/>
      <eStructuralFeatures xmi:id="-29" name="upgradeDesired" eType="ecore:EBoolean"/>
    </ecore:EClass>

    <!-- SeatCategory class -->
    <ecore:EClass xmi:id="-30" name="SeatCategory">
      <eStructuralFeatures xmi:id="-31" name="designation" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-32" name="offersEntertainment" eType="ecore:EBoolean"/>
      <eStructuralFeatures xmi:id="-33" name="numberOfSeats" eType="ecore:EInt"/>
    </ecore:EClass>

    <!-- Airline class -->
    <ecore:EClass xmi:id="-34" name="Airline">
      <eStructuralFeatures xmi:id="-35" name="name" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-36" name="aircrafts" eType="#//Aircraft" lowerBound="0" upperBound="-1"/>
      <eStructuralFeatures xmi:id="-37" name="crewMembers" eType="#//CrewMember" lowerBound="0" upperBound="-1"/>
    </ecore:EClass>

    <!-- CrewMember class -->
    <ecore:EClass xmi:id="-38" name="CrewMember">
      <eStructuralFeatures xmi:id="-39" name="name" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-40" name="dateOfEmployment" eType="#//Date"/>
    </ecore:EClass>

    <!-- Pilot class, extends CrewMember -->
    <ecore:EClass xmi:id="-41" name="Pilot" superTypes="#//CrewMember">
      <eStructuralFeatures xmi:id="-42" name="license" eType="ecore:EString"/>
    </ecore:EClass>

    <!-- FlightAttendant class, extends CrewMember -->
    <ecore:EClass xmi:id="-43" name="FlightAttendant" superTypes="#//CrewMember">
      <eStructuralFeatures xmi:id="-44" name="isChiefSteward" eType="ecore:EBoolean"/>
    </ecore:EClass>

    <!-- Airport class -->
    <ecore:EClass xmi:id="-45" name="Airport">
      <eStructuralFeatures xmi:id="-46" name="name" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-47" name="address" eType="ecore:EString"/>
      <eStructuralFeatures xmi:id="-48" name="numberOfRunways" eType="ecore:EInt"/>
    </ecore:EClass>

    <!-- Custom Data Types -->
    <ecore:EDataType xmi:id="-49" name="Date">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="instanceClassName" value="java.util.Date"/>
      </eAnnotations>
    </ecore:EDataType>

    <ecore:EDataType xmi:id="-50" name="Time">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="instanceClassName" value="java.time.LocalTime"/>
      </eAnnotations>
    </ecore:EDataType>

    <ecore:EDataType xmi:id="-51" name="DateTime">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="instanceClassName" value="java.time.LocalDateTime"/>
      </eAnnotations>
    </ecore:EDataType>

  </ecore:EPackage>
</xmi:XMI>
