<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="hospital"
    nsURI="http://www.example.org/hospital"
    nsPrefix="hospital">

  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms"
        lowerBound="0" upperBound="-1"
        eType="#//Room"
        eOpposite="#//Room/department"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms"
        lowerBound="0" upperBound="-1"
        eType="#//Room"
        eOpposite="#//Room/category"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="department"
        lowerBound="1" upperBound="1"
        eType="#//Department"
        eOpposite="#//Department/rooms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category"
        lowerBound="1" upperBound="1"
        eType="#//Category"
        eOpposite="#//Category/rooms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beds"
        lowerBound="0" upperBound="-1"
        containment="true"
        eType="#//Bed"
        eOpposite="#//Bed/room"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Bed">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room"
        lowerBound="1" upperBound="1"
        eType="#//Room"
        eOpposite="#//Room/beds"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        lowerBound="0" upperBound="1"
        eType="#//Person"
        eOpposite="#//Person/bed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stays"
        lowerBound="0" upperBound="-1"
        eType="#//Stay"
        eOpposite="#//Stay/bed"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposal"
        lowerBound="0" upperBound="1"
        eType="#//Proposal"
        eOpposite="#//Proposal/bed"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Proposal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validated"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bed"
        lowerBound="0" upperBound="1"
        eType="#//Bed"
        eOpposite="#//Bed/proposal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        lowerBound="0" upperBound="1"
        eType="#//Person"
        eOpposite="#//Person/proposal"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthdate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abilities"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bed"
        lowerBound="0" upperBound="1"
        eType="#//Bed"
        eOpposite="#//Bed/person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stays"
        lowerBound="0" upperBound="-1"
        eType="#//Stay"
        eOpposite="#//Stay/person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoices"
        lowerBound="0" upperBound="-1"
        containment="true"
        eType="#//Invoice"
        eOpposite="#//Invoice/person"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="proposal"
        lowerBound="0" upperBound="1"
        eType="#//Proposal"
        eOpposite="#//Proposal/person"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Stay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="intakeDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        lowerBound="1" upperBound="1"
        eType="#//Person"
        eOpposite="#//Person/stays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bed"
        lowerBound="1" upperBound="1"
        eType="#//Bed"
        eOpposite="#//Bed/stays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceItem"
        lowerBound="0" upperBound="1"
        eType="#//InvoiceItem"
        eOpposite="#//InvoiceItem/stay"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invoiceDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outstandingAmount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        lowerBound="1" upperBound="1"
        eType="#//Person"
        eOpposite="#//Person/invoices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLines"
        lowerBound="0" upperBound="-1"
        containment="true"
        eType="#//InvoiceLine"
        eOpposite="#//InvoiceLine/invoice"/>
    <eOperations name="payment">
      <eParameters name="paymentAmount"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="InvoiceItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLine"
        lowerBound="0" upperBound="1"
        eType="#//InvoiceLine"
        eOpposite="#//InvoiceLine/invoiceItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stay"
        lowerBound="1" upperBound="1"
        eType="#//Stay"
        eOpposite="#//Stay/invoiceItem"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="InvoiceLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice"
        lowerBound="1" upperBound="1"
        eType="#//Invoice"
        eOpposite="#//Invoice/invoiceLines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceItem"
        lowerBound="1" upperBound="1"
        eType="#//InvoiceItem"
        eOpposite="#//InvoiceItem/invoiceLine"/>
  </eClassifiers>

</ecore:EPackage>
