<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/Ecore/">
  <ePackage name="gasstation" nsURI="http://www.example.org/gasstation" xmi:id="package_0">
    
    <eClass name="GasStationChain" xmi:id="class_GasStationChain">
      <eStructuralFeatures>
        <eReference xmi:id="ref_chain_stations" name="gasStations" EClassifier="@class_GasStation" containment="true"/>
        <eReference xmi:id="ref_chain_fuels" name="fuels" EClassifier="@class_Fuel" containment="true"/>
        <eReference xmi:id="ref_chain_purchases" name="fuelPurchases" EClassifier="@class_FuelPurchase" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="GasStation" xmi:id="class_GasStation">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_station_id" name="id" EType="eString"/>
        <eAttribute xmi:id="attr_station_address" name="address" EType="eString"/>
        <eReference xmi:id="ref_station_pumps" name="fuelPumps" EClassifier="@class_FuelPump" containment="true"/>
        <eReference xmi:id="ref_station_prices" name="dailyPrices" EClassifier="@class_DailyPrice" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="FuelPump" xmi:id="class_FuelPump">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_pump_num" name="pumpNumber" EType="eInteger"/>
        <eAttribute xmi:id="attr_pump_self" name="isSelfService" EType="eBoolean"/>
        <eReference xmi:id="ref_pump_fuels" name="offeredFuels" EClassifier="@class_Fuel"/>
        <eReference xmi:id="ref_pump_station" name="gasStation" EClassifier="@class_GasStation"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Fuel" xmi:id="class_Fuel">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_fuel_name" name="name" EType="eString"/>
        <eAttribute xmi:id="attr_fuel_octane" name="octaneRating" EType="eDouble"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="DailyPrice" xmi:id="class_DailyPrice">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_price_date" name="date" EType="eDate"/>
        <eAttribute xmi:id="attr_price_val" name="pricePerLiter" EType="eDouble"/>
        <eReference xmi:id="ref_price_fuel" name="fuel" EClassifier="@class_Fuel"/>
        <eReference xmi:id="ref_price_station" name="gasStation" EClassifier="@class_GasStation"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="FuelPurchase" xmi:id="class_FuelPurchase">
      <eStructuralFeatures>
        <eAttribute xmi:id="attr_purchase_id" name="purchaseId" EType="eString"/>
        <eAttribute xmi:id="attr_purchase_liters" name="litersDispensed" EType="eDouble"/>
        <eReference xmi:id="ref_purchase_pump" name="fuelPump" EClassifier="@class_FuelPump"/>
        <eReference xmi:id="ref_purchase_fuel" name="fuel" EClassifier="@class_Fuel"/>
        <eReference xmi:id="ref_purchase_price" name="dailyPrice" EClassifier="@class_DailyPrice"/>
      </eStructuralFeatures>
    </eClass>

  </ePackage>
</xmi:XMI>
