<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="busSystem"
    nsURI="http://www.example.org/busSystem"
    nsPrefix="busSystem">

  <!-- Custom datatype for DateTime (date + time timestamp) -->
  <eClassifiers xsi:type="ecore:EDataType" name="DateTime"
      instanceClassName="java.util.Date"/>

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="BusSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="busLines"
        eType="#//BusLine" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priceCategories"
        eType="#//PriceCategory" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buses"
        eType="#//Bus" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers"
        eType="#//Customer" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoices"
        eType="#//Invoice" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="BusLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destination"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priceCategory"
        eType="#//PriceCategory" upperBound="1"
        eOpposite="#//PriceCategory/busLines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trajectories"
        eType="#//Trajectory" containment="true" upperBound="-1"
        eOpposite="#//Trajectory/busLine"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PriceCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busLines"
        eType="#//BusLine" upperBound="-1"
        eOpposite="#//BusLine/priceCategory"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Trajectory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busLine"
        eType="#//BusLine"
        eOpposite="#//BusLine/trajectories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectories"
        eType="#//BusOnTrajectory" containment="true" upperBound="-1"
        eOpposite="#//BusOnTrajectory/trajectory"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Bus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectories"
        eType="#//BusOnTrajectory" upperBound="-1"
        eOpposite="#//BusOnTrajectory/bus"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="BusOnTrajectory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trajectory"
        eType="#//Trajectory"
        eOpposite="#//Trajectory/busOnTrajectories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bus"
        eType="#//Bus"
        eOpposite="#//Bus/busOnTrajectories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trips"
        eType="#//Trip" containment="true" upperBound="-1"
        eOpposite="#//Trip/busOnTrajectory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTrips"
        eType="#//MensoTrip" upperBound="-1"
        eOpposite="#//MensoTrip/busOnTrajectory"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Trip">
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectory"
        eType="#//BusOnTrajectory"
        eOpposite="#//BusOnTrajectory/trips"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="MensoTicket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTrips"
        eType="#//MensoTrip" containment="true" upperBound="-1"
        eOpposite="#//MensoTrip/mensoTicket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoices"
        eType="#//Invoice" upperBound="-1"
        eOpposite="#//Invoice/mensoTicket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer"
        eType="#//Customer"
        eOpposite="#//Customer/mensoTickets"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="MensoTrip">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tripDateTime"
        eType="#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTicket"
        eType="#//MensoTicket"
        eOpposite="#//MensoTicket/mensoTrips"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectory"
        eType="#//BusOnTrajectory"
        eOpposite="#//BusOnTrajectory/mensoTrips"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLine"
        eType="#//InvoiceLine" upperBound="1"
        eOpposite="#//InvoiceLine/mensoTrip"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="InvoiceLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTrip"
        eType="#//MensoTrip"
        eOpposite="#//MensoTrip/invoiceLine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice"
        eType="#//Invoice"
        eOpposite="#//Invoice/invoiceLines"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="total"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLines"
        eType="#//InvoiceLine" containment="true" upperBound="-1"
        eOpposite="#//InvoiceLine/invoice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTicket"
        eType="#//MensoTicket"
        eOpposite="#//MensoTicket/invoices"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="homeAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="officeAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingHours"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTickets"
        eType="#//MensoTicket" containment="true" upperBound="-1"
        eOpposite="#//MensoTicket/customer"/>
  </eClassifiers>

</ecore:EPackage>
