<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="busSystem"
    nsURI="http://www.example.org/busSystem"
    nsPrefix="busSystem">

  <eClassifiers xsi:type="ecore:EClass" name="BusLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Destination" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="priceCategory" eType="#//PriceCategory"
        upperBound="1" lowerBound="0" eOpposite="#//PriceCategory/busLines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trajectories" eType="#//Trajectory"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//Trajectory/busLine"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PriceCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busLines" eType="#//BusLine"
        upperBound="-1" lowerBound="0" eOpposite="#//BusLine/priceCategory"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Trajectory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busLine" eType="#//BusLine"
        upperBound="1" lowerBound="1" eOpposite="#//BusLine/trajectories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectories" eType="#//BusOnTrajectory"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//BusOnTrajectory/trajectory"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Bus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectories" eType="#//BusOnTrajectory"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//BusOnTrajectory/bus"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="BusOnTrajectory">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trajectory" eType="#//Trajectory"
        upperBound="1" lowerBound="1" eOpposite="#//Trajectory/busOnTrajectories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bus" eType="#//Bus"
        upperBound="1" lowerBound="1" eOpposite="#//Bus/busOnTrajectories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trips" eType="#//Trip"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//Trip/busOnTrajectory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTrips" eType="#//MensoTrip"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//MensoTrip/busOnTrajectory"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Trip">
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectory" eType="#//BusOnTrajectory"
        upperBound="1" lowerBound="1" eOpposite="#//BusOnTrajectory/trips"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="MensoTicket">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTrips" eType="#//MensoTrip"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//MensoTrip/mensoTicket"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" eType="#//Customer"
        upperBound="1" lowerBound="1" eOpposite="#//Customer/mensoTickets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoices" eType="#//Invoice"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//Invoice/mensoTicket"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="MensoTrip">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TripDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTicket" eType="#//MensoTicket"
        upperBound="1" lowerBound="1" eOpposite="#//MensoTicket/mensoTrips"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busOnTrajectory" eType="#//BusOnTrajectory"
        upperBound="1" lowerBound="1" eOpposite="#//BusOnTrajectory/mensoTrips"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLine" eType="#//InvoiceLine"
        upperBound="1" lowerBound="0" containment="false" eOpposite="#//InvoiceLine/mensoTrip"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="InvoiceLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTrip" eType="#//MensoTrip"
        upperBound="1" lowerBound="1" eOpposite="#//MensoTrip/invoiceLine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" eType="#//Invoice"
        upperBound="1" lowerBound="1" eOpposite="#//Invoice/invoiceLines"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Total" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Discount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLines" eType="#//InvoiceLine"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//InvoiceLine/invoice"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTicket" eType="#//MensoTicket"
        upperBound="1" lowerBound="1" eOpposite="#//MensoTicket/invoices"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HomeAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OfficeAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WorkingHours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mensoTickets" eType="#//MensoTicket"
        upperBound="-1" lowerBound="0" containment="false" eOpposite="#//MensoTicket/customer"/>
  </eClassifiers>

</ecore:EPackage>
