<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
                xmlns:xmi="http://www.omg.org/spec/XMI/20100501"
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
    <eClassifiers>
        <!-- RootContainer Class -->
        <eClass name="RootContainer"/>

        <!-- Game Class -->
        <eClass name="Game">
            <eStructuralFeatures>
                <eReference name="players" upper="-1" elementType="#//Player"/>
                <eReference name="deck" type="#//Deck"/>
                <eReference name="scoringTable" type="#//ScoringTable"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Player Class -->
        <eClass name="Player">
            <eStructuralFeatures>
                <eAttribute name="id" eType="#//ID"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Deck Class -->
        <eClass name="Deck" extends="#/HasCards">
            <eStructuralFeatures>
                <eAttribute name="id" eType="#//ID"/>
                <eReferences upper="-1" containment="true" type="ecore:ECollectionType" name="cards">
                    <eType href="#/Card"/>
                </eReferences>
            </eStructuralFeatures>
        </eClass>

        <!-- HasCards Interface -->
        <eInterface name="HasCards"/>

        <!-- Card Class -->
        <eClass name="Card">
            <eStructuralFeatures>
                <eAttribute name="id" eType="#//ID"/>
                <eAttribute name="suit" eType="#/Suit"/>
            </eStructuralFeatures>
            <eOperations>
                <eOperation name="compareHeight" eType="#/ComparisonResult"/>
            </eOperations>
        </eClass>

        <!-- ComparisonResult Class -->
        <eClass name="ComparisonResult">
            <eStructuralFeatures>
                <eAttribute name="id" eType="#//ID"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Suit EDataType with Enumerations -->
        <eClassifiers xsi:type="ecore:EEnum" id="Suit">
            <eLiterals name="DIAMONDS"/>
            <eLiterals name="HEARTS"/>
            <eLiterals name="SPADES"/>
            <eLiterals name="CLUBS"/>
        </eClassifiers>

        <!-- ScoringTable Class -->
        <eClass name="ScoringTable">
            <eStructuralFeatures>
                <eReference name="rounds" upper="-1" elementType="#//Round"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Round Class -->
        <eClass name="Round">
            <eStructuralFeatures>
                <eAttribute name="id" eType="#//ID"/>
                <eReferences upper="-1" containment="true" type="ecore:ECollectionType" name="winningPlayers" elementType="#//Player"/>
                <eReference name="pointValue" type="#//PointValue"/>
                <eAttribute name="isSoloRound" type="ecore:EBooleanObject"/>
            </eStructuralFeatures>
        </eClass>

        <!-- PointValue Class -->
        <eClass name="PointValue">
            <eStructuralFeatures>
                <eAttribute name="value" eType="#/EInt"/>
            </eStructuralFeatures>
        </eClass>

        <!-- SoloRound Association and Classes -->
        <eClass name="SoloRound">
            <eReferences upper="-1" containment="true" type="#//SoloType" name="soloType"/>
            <eReference upper="1" containment="false" type="#//Player"  name="soloPlayer"/>
            <eStructuralFeatures>
                <eAttribute name="id" eType="#//ID"/>
            </eStructuralFeatures>
        </eClass>

        <!-- SoloType Class -->
        <eClass name="SoloType">
            <eStructuralFeatures>
                <eAttribute name="type" type="ecore:EString"/>
            </eStructuralFeatures>
        </eClass>

        <!-- CustomDatatype for ID -->
        <eClassifiers xsi:type="ecore:EDataType" id="ID">
            <eSuperTypes href="http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eClassifiers>

    </eClassifiers>
    
</ecore:EPackage>
