<?xml version="1.0" encoding="UTF-8"?>
<XMI xmi:xmi="2.5" xmlns:xmi="http://www.omg.org/XMI" 
     xmlns:uml="http://www.eclipse.org/uml2/4.1.0/UML"
     xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

    <XMI.Header xmi:id="Header">
        <Namespace Uuid="_LouvreMuseumEPackage" URI="Package"/>
    </XMI.Header>
    
    <eResource xsi:type="uml:Model" xmi:id="_MuseumManagementSystem" name="MuseumManagementSystem">
        
        <packagedElement xsi:type="uml:Package" xmi:id="_LouvreMuseumPackage"
                         name="LouvreMuseum"/>
        
        <!-- Root Container Class -->
        <packagedElement xsi:type="uml:Class" xmi:id="_RootContainer" 
                         name="RootContainer" isAbstract="false">
            
            <ownedAttribute xmi:id="_rootExhibitionLocations"
                            type="_LocationAssignment"
                            aggregation="composite"/>
        </packagedElement>
        
        <!-- Location Class -->
        <packagedElement xsi:type="uml:Class" xmi:id="_Location" name="Location">
            <ownedAttribute xmi:id="_exhibitionAssignments"
                            type="_ExhibitionAssignment"
                            aggregation="composite"/>
        </packagedElement>

        <!-- Exhibition Class -->
        <packagedElement xsi:type="uml:Class" xmi:id="_Exhibition" name="Exhibition">
            <ownedAttribute xmi:id="_coordinationByEmployee"
                            type="_MuseumEmployee"/>

            <ownedAttribute xmi:id="_exhibitionItemsListed"
                            type="_ExhibitionItemAssignment">
                <lower>0</lower>
                <upper>-1</upper>
            </ownedAttribute>
        </packagedElement>

        <!-- Museum Employee Class -->
        <packagedElement xsi:type="uml:Class" xmi:id="_MuseumEmployee" name="MuseumEmployee">
            <ownedAttribute xmi:id="_coachAssignment"
                            type="_CoachingAssignment">
                <lower>0</lower>
                <upper>-1</upper>
            </ownedAttribute>
        </packagedElement>

        <!-- Collector Class -->
        <packagedElement xsi:type="uml:Class" xmi:id="_Collector" name="Collector"/>

        <!-- Association Classes -->

        <!-- Exhibition Assignment Association Class -->
        <packagedElement xsi:type="uml:Association" xmi:id="_ExhibitionAssignment"
                         name="LocationHasExhibitions">
            
            <ownedEnd xmi:id="_endLocationHasExhibitions1"
                      type="_Location"/>
                    
            <ownedEnd xmi:id="_endLocationHasExhibitions2"
                      type="_Exhibition"
                      aggregation="composite"/>
        </packagedElement>

        <!-- Coaching Assignment Association Class -->
        <packagedElement xsi:type="uml:Association" xmi:id="_CoachingAssignment"
                         name="CoachRelationship">
            
            <ownedEnd xmi:id="_endEmployeeIsTrainedBy1"
                      type="_MuseumEmployee"/>
                    
            <ownedEnd xmi:id="_endEmployeeIsTrainedBy2"
                      type="_MuseumEmployee"/>
        </packagedElement>

        <!-- Exhibition Item Assignment Class -->
        <packagedElement xsi:type="uml:Association" xmi:id="_ExhibitionItemAssignment"
                         name="ExhibitionRequiresItems">
            
            <ownedEnd xmi:id="_endExhibitionsContains1"
                      type="_Exhibition"
                      aggregation="composite"/>
                    
            <ownedEnd xmi:id="_endRequestedByCollector2"
                      type="_Collector"/>
        </packagedElement>
    
    </eResource>

</XMI>
