<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="TransportSystem" nsURI="transport.system" nsPrefix="ts">

    <!-- Root container class -->
    <ecore:EClass xmi:id="_root" name="TransportSystemRoot">
      <ecore:EReference name="locations" containment="true" eType="#//Location" upperBound="-1"/>
      <ecore:EReference name="drivers" containment="true" eType="#//Driver" upperBound="-1"/>
      <ecore:EReference name="vehicles" containment="true" eType="#//Vehicle" upperBound="-1"/>
      <ecore:EReference name="orders" containment="true" eType="#//Order" upperBound="-1"/>
    </ecore:EClass>

    <!-- Location class -->
    <ecore:EClass xmi:id="_location" name="Location">
      <ecore:EAttribute name="address" eType="ecore:EString"/>
      <ecore:EReference name="drivers" containment="true" eType="#//Driver" upperBound="-1"/>
      <ecore:EReference name="vehicles" containment="true" eType="#//Vehicle" upperBound="-1"/>
    </ecore:EClass>

    <!-- Vehicle class hierarchy -->
    <ecore:EClass xmi:id="_vehicle" name="Vehicle">
      <ecore:EAttribute name="vehicleNumber" eType="ecore:EString"/>
      <ecore:EReference name="driver" eType="#//Driver" upperBound="1"/>
    </ecore:EClass>

    <!-- Specific vehicle types -->
    <ecore:EClass xmi:id="_truck" name="Truck">
      <ecore:EGenericType>
        <ecore:EUpperBound value="-1"/>
        <ecore:EClassifier href="#//Vehicle"/>
      </ecore:EGenericType>
      <ecore:EAttribute name="weight" eType="ecore:EDouble"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_car" name="Car">
      <ecore:EGenericType>
        <ecore:EUpperBound value="-1"/>
        <ecore:EClassifier href="#//Vehicle"/>
      </ecore:EGenericType>
      <ecore:EAttribute name="numberOfSeats" eType="ecore:EInt"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_van" name="Van">
      <ecore:EGenericType>
        <ecore:EUpperBound value="-1"/>
        <ecore:EClassifier href="#//Vehicle"/>
      </ecore:EGenericType>
    </ecore:EClass>

    <!-- Driver class -->
    <ecore:EClass xmi:id="_driver" name="Driver">
      <ecore:EAttribute name="firstName" eType="ecore:EString"/>
      <ecore:EAttribute name="lastName" eType="ecore:EString"/>
      <ecore:EReference name="vehicle" eType="#//Vehicle" upperBound="1"/>
    </ecore:EClass>

    <!-- Order class -->
    <ecore:EClass xmi:id="_order" name="Order">
      <ecore:EAttribute name="executionDate" eType="ecore:EDate"/>
      <ecore:EReference name="originLocation" eType="#//Location"/>
      <ecore:EReference name="destinationLocation" eType="#//Location"/>
      <ecore:EReference name="driver" eType="#//Driver" upperBound="1"/>
    </ecore:EClass>

  <!-- Custom datatype for time -->
    <ecore:EDataType xmi:id="_timeWithoutDate" name="TimeWithoutDate">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="pattern">HH:mm:ss</details>
      </eAnnotations>
    </ecore:EDataType>

  </ecore:EPackage>
</xmi:XMI>
