<?xml version="1.0" encoding="UTF-8"?>
<ecore:Ecore xmlns:xmi="http://www.omg.org/XMI"
             xmlns:ecore="http://www.eclipse.org/uml2/ecore"
             xmi:version="2.1">
  
  <packagedElement xmi:id="_bAaRf7eSEem6DdYz2y-9Kw" name="SmartHomeAutomationSystemPackage" nsPrefix="SHAS">
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_aWbR07i8EewxNtYkC3pT4Q" name="SmartHomeAutomationSystem">
      <eStructuralFeatures>
        <eReferences name="smarthomes" eType="#_aXfO27i8EewxNtYkC3pT4Q">
          <upperValue xsi:type="ecore:EReferenceMany"/>
          <lowerValue xsi:type="ecore:EReferenceMany"/>
        </eReferences>
        <eReferences name="automationRules" eType="#_bAaRdLeSEem6DdYz2y-9Kw">
          <upperValue xsi:type="ecore:EReferenceMany"/>
          <lowerValue xsi:type="ecore:EReferenceMany"/>
        </eReferences>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" xmi:id="_aXfO37i8EewxNtYkC3pT4Q" name="SmartHome">
      <eStructuralFeatures>
        <eAttribute name="physicalAddress"/>
        <eReferences name="rooms" eType="#_bAaReLeSEem6DdYz2y-9Kw">
          <upperValue xsi:type="ecore:EReferenceMany"/>
          <lowerValue xsi:type="ecore:EReferenceOne"/>
        </eReferences>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" xmi:id="_bAaRdLeSEem6DdYz2y-9Kw" name="AutomationRule">
      <eStructuralFeatures>
        <eAttribute name="precondition"/>
        <eAttribute name="action"/>
        <eOperations>
          <eOperation name="create" eType="#_bAaRe7eSEem6DdYz2y-9Kw"/>
          <eOperation name="edit" eType="#_bAaRfLeSEem6DdYz2y-9Kw"/>
          <eOperation name="activate"/>
          <eOperation name="deactivate"/>
        </eOperations>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Define additional classes for Device, Room, Sensor, Actuator etc. following the same pattern -->

  </packagedElement>
  
</ecore:Ecore>
