<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="logistics"
    nsURI="http://www.example.org/logistics"
    nsPrefix="logistics">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="LogisticsSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations"
        eType="#//Location" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles"
        eType="#//Vehicle" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drivers"
        eType="#//Driver" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- Location -->
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Driver -->
  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- The order currently assigned to this driver (at most one) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="currentOrder"
        eType="#//Order" upperBound="1"/>
    <!-- The vehicle driven by this driver (derived opposite of Vehicle.driver) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="drivenVehicle"
        eType="#//Vehicle" upperBound="1" eOpposite="#//Vehicle/driver"/>
  </eClassifiers>

  <!-- Vehicle (abstract) -->
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Up to one driver assigned to drive this vehicle -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver"
        eType="#//Driver" upperBound="1" eOpposite="#//Driver/drivenVehicle"/>
  </eClassifiers>

  <!-- Truck -->
  <eClassifiers xsi:type="ecore:EClass" name="Truck" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- Car -->
  <eClassifiers xsi:type="ecore:EClass" name="Car" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSeats"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- Van -->
  <eClassifiers xsi:type="ecore:EClass" name="Van" eSuperTypes="#//Vehicle"/>

  <!-- Order -->
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="origin"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination"
        eType="#//Location"/>
    <!-- At least one driver carries out this order -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="drivers"
        eType="#//Driver" upperBound="-1" lowerBound="1"/>
  </eClassifiers>

</ecore:EPackage>
