<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="pizzaEntertainment"
    nsURI="http://www.example.org/pizzaEntertainment"
    nsPrefix="pizzaEntertainment">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="PizzaEntertainmentSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users"
        eType="#//User" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzaRestaurants"
        eType="#//PizzaRestaurant" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzas"
        eType="#//Pizza" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employments"
        eType="#//Employment" upperBound="-1" containment="true"/>
  </eClassifiers>

  <!-- Custom datatype for DateTime (date + time) -->
  <eClassifiers xsi:type="ecore:EDataType" name="DateTime"
      instanceClassName="java.time.LocalDateTime"/>

  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthdate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Customer" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order" upperBound="-1" containment="true" eOpposite="#//Order/customer"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderPlacement"
        eType="#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="latestDelivery"
        eType="#//DateTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfPeople"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer"
        eType="#//Customer" eOpposite="#//Customer/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzaRestaurant"
        eType="#//PizzaRestaurant" eOpposite="#//PizzaRestaurant/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzas"
        eType="#//Pizza" upperBound="-1" lowerBound="1" eOpposite="#//Pizza/orders"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="EntertainmentOrder" eSuperTypes="#//Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entertainmentType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entertainer"
        eType="#//Entertainer" eOpposite="#//Entertainer/entertainmentOrders"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="BusinessOwner" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="linkedInAccount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzaRestaurants"
        eType="#//PizzaRestaurant" upperBound="-1" eOpposite="#//PizzaRestaurant/businessOwner"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PizzaRestaurant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="zipCode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="website"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="openingHours"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessOwner"
        eType="#//BusinessOwner" eOpposite="#//BusinessOwner/pizzaRestaurants"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzas"
        eType="#//Pizza" upperBound="-1" eOpposite="#//Pizza/pizzaRestaurants"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order" upperBound="-1" eOpposite="#//Order/pizzaRestaurant"/>
    <!-- Association class end: references Employment instead of Entertainer directly -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="employments"
        eType="#//Employment" upperBound="-1" eOpposite="#//Employment/pizzaRestaurant"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Pizza">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crustStructure"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzaRestaurants"
        eType="#//PizzaRestaurant" upperBound="-1" eOpposite="#//PizzaRestaurant/pizzas"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order" upperBound="-1" eOpposite="#//Order/pizzas"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Entertainer" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stageName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bio"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priceThirtyMin"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <!-- Association class end: references Employment instead of PizzaRestaurant directly -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="employments"
        eType="#//Employment" upperBound="-1" eOpposite="#//Employment/entertainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entertainmentOrders"
        eType="#//EntertainmentOrder" upperBound="-1" eOpposite="#//EntertainmentOrder/entertainer"/>
  </eClassifiers>

  <!-- Association class for PizzaRestaurant - Entertainer -->
  <eClassifiers xsi:type="ecore:EClass" name="Employment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availability"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pizzaRestaurant"
        eType="#//PizzaRestaurant" eOpposite="#//PizzaRestaurant/employments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entertainer"
        eType="#//Entertainer" eOpposite="#//Entertainer/employments"/>
  </eClassifiers>

</ecore:EPackage>
