<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
  xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

  <ecore:EPackage name="HouseModel" nsURI="house.model" nsPrefix="house_model">
    <eClassifiers xsi:type="ecore:EClass" name="RootContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="houses" eType="#//House" lowerBound="0" upperBound="-1"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="House">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="buildingMaterial" eType="#//BuildingMaterial"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="basement" eType="#//Basement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="companies" eType="#//Company" lowerBound="0" upperBound="-1"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EEnum" name="BuildingMaterial">
      <eLiterals>
        <xsi:type="ecore:EEnumLiteral" name="WOOD" value="0"/>
        <xsi:type="ecore:EEnumLiteral" name="BRICK" value="1"/>
        <xsi:type="ecore:EEnumLiteral" name="CONCRETE" value="2"/>
      </eLiterals>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Basement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="EarthBasement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="humidityLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="ConcreteBasement">
      <!-- ConcreteBasement has no additional attributes -->
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="SemiDetachedHouse">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasOwnGarden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfWindows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="carports" lowerBound="0" upperBound="2" eType="#//Carport"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="garage" eType="#//Garage"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Carport">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDoubleCarport" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasFlatRoof" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Garage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasAutomaticDoor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Company">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="JobLog">
      <eStructuralFeatures xsi:type="ecore:EReference" name="company" eType="#//Company"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="house" eType="#//House"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="hoursWorked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="agreedPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
