<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="ConanFitness">
    <!-- RootContainer definition -->
    <eClassifiers xsi:type="ecore:EClass" name="RootContainer">
      <eStructuralFeatures xsi:type="ecore:EReference" name="centers" eType="#//Center" upperBound="-1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="people" eType="#//Person" upperBound="-1"/>
    </eClassifiers>

    <!-- Center definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Center">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" eType="#//Room" upperBound="-1" containment="true"/>
    </eClassifiers>

    <!-- Room definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Room">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNumber" eType="ecore:EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCapacity" eType="ecore:EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" eType="#//Session" upperBound="-1" containment="true"/>
    </eClassifiers>

    <!-- Person definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Person">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="familyName" eType="ecore:EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="participatesIn" eType="#//ParticipationAssociation" upperBound="-1"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="supervises" eType="#//SupervisionAssociation" upperBound="-1"/>
    </eClassifiers>

    <!-- Trainer definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Trainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diploma" eType="ecore:EString"/>
      <eSuperTypes href="#//Person"/>
    </eClassifiers>

    <!-- EDate Data Type definition -->
    <eClassifiers xsi:type="ecore:EDataType" name="EDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="instanceClassName" value="java.util.Date"/>
      </eAnnotations>
    </eClassifiers>

    <!-- Session definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Session">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="#//EDate"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingHour" eType="ecore:EInt"/> <!-- Assuming hour of the day -->
      <eStructuralFeatures xsi:type="ecore:EReference" name="room" eType="#//Room" containment="false"/>
    </eClassifiers>

    <!-- GroupSession definition -->
    <eClassifiers xsi:type="ecore:EClass" name="GroupSession">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EString"/>
      <eSuperTypes href="#//Session"/>
    </eClassifiers>

    <!-- IndividualSession definition -->
    <eClassifiers xsi:type="ecore:EClass" name="IndividualSession">
      <!-- No additional attributes needed -->
      <eSuperTypes href="#//Session"/>
    </eClassifiers>

    <!-- ParticipationAssociation definition -->
    <eClassifiers xsi:type="ecore:EClass" name="ParticipationAssociation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="#//Person" containment="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="session" eType="#//Session" containment="false"/>
    </eClassifiers>

    <!-- SupervisionAssociation definition -->
    <eClassifiers xsi:type="ecore:EClass" name="SupervisionAssociation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="trainer" eType="#//Trainer" containment="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="session" eType="#//GroupSession" containment="false"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
