<model xsi:type="ecore:EPackage" name="LouvrePackage" nsURI="http://www.example.com/louvre" nslPrefix="Louvre">
	<eClassifiers xsi:type="ecore:EClass" name="Model">
		<eStructuralFeatures xsi:type="ecore:EReference" name="locations" type="Louvre(Location)" containment="true"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Location">
		<eStructuralFeatures xsi:type="ecore:EReference" name="exhibitions" type="Louvre(Exhibition)" containment="true"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Exhibition">
		<eStructuralFeatures xsi:type="ecore:EReference" name="coordinator" type="Louvre(Employee)"/>
		<eStructuralFeatures xsi:type="ecore:EReference" name="desiredItems" type="Louvre(DesiredItem)" containment="true"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Employee">
		<eStructuralFeatures xsi:type="ecore:EReference" name="coachedEmployees" type="Louvre(Employee)" upper="unlimited" changeable="false" transient="true" volatile="true"/>
		<eStructuralFeatures xsi:type="ecore:EReference" name="coach" type="Louvre(Employee)"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="DesiredItem">
		<eStructuralFeatures xsi:type="ecore:EReference" name="exhibition" type="Louvre(Exhibition)"/>
		<eStructuralFeatures xsi:type="ecore:EReference" name="requestedPieces" type="Louvre(RequestedPiece)" containment="true"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="RequestedPiece">
		<eStructuralFeatures xsi:type="ecore:EReference" name="desiredItem" type="Louvre(DesiredItem)"/>
		<eStructuralFeatures xsi:type="ecore:EReference" name="collector" type="Louvre(Collector)"/>
	</eClassifiers>
	<eClassifiers xsi:type="ecore:EClass" name="Collector"/>
</model>
