<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.5.0"
    xmlns:xmi="http://www.omg.org/spec/XMI/2.5"
    xmlns:uml="http://www.eclipse.org/uml2/3.0.0/UML">

  <packagedElement xmi:type="uml:Package" name="HouseSystem">
    
    <!-- RootContainer class to hold all main classes -->
    <packagedElement xmi:type="uml:Class" name="RootContainer">
      <ownedAttribute xmi:id="_1"
                      type="#House"
                      containment="true"/>
      <ownedAttribute xmi:id="_2"
                      type="#Company"
                      containment="true"/>
    </packagedElement>

    <!-- House class -->
    <packagedElement xmi:type="uml:Class" name="House">
      <ownedAttribute xmi:id="_3" 
                      name="address" 
                      type="_dateType"/>
      
      <ownedAttribute xmi:id="_4"
                      name="buildingMaterial" 
                      type="_String"/>

      <!-- Generalization to SemiDetachedHouse -->
      <generalization client="_SemiDetachedHouse">
        <general xmi:type="uml:Class" href="#_SemiDetachedHouse"/>
      </generalization>

      <ownedAttribute xmi:id="_5"
                      name="basement" 
                      type="_Basement">
        <lowerValue xmi:type="uml:LiteralInteger" value="0"/>
        <upperValue xmi:type="uml:TheUnlimitedNatural"/>
      </ownedAttribute>
      
      <!-- Association with Company for servicing companies -->
      <association xmi:id="_6" name="servicingCompanies">
        <memberEnd xmi:idref="_7"
                   type="#Company"
                   aggregation="composite">
          <lowerValue xmi:type="uml:LiteralInteger" value="0"/>
          <upperValue xmi:type="uml:TheUnlimitedNatural"/>
        </memberEnd>
        
        <ownedEnd xmi:id="_8" name="servicingCompanies">
          <association href="#_7"/>
          <type xsi:type="uml:Class" href="#_Company"/>
        </ownedEnd>

        <navigableOwnedEnd xmi:id="_9" 
                           name="houses"
                           association="_7"/>
      </association>
    </packagedElement>

    <!-- Basements base class -->
    <packagedElement xmi:type="uml:Class" 
                     name="Basement">
      <ownedAttribute xmi:id="_10" 
                      name="size" 
                      type="_Integer"/>

      <ownedAttribute xmi:id="_11"
                      name="name" 
                      type="_String"/>
    </packagedElement>

    <!-- Concrete Basement class -->
    <packagedElement xmi:type="uml:Class"
                     name="ConcreteBasement">
      <generalization client="#_Basement"/>
    </packagedElement>
    
    <!-- Earth Basements class -->
    <packagedElement xmi:type="uml:Class" 
                     name="EarthBasement">
      <ownedAttribute xmi:id="_12" 
                      name="humidityLevel" 
                      type="_Integer"/>

      <generalization client="#_House"
                      general="#_Basement"/>
    </packagedElement>

    <!-- SemiDetachedHouse class -->
    <packagedElement xmi:type="uml:Class" 
                     name="SemiDetachedHouse">
      <extension xmi:idref="_13" client="_House"/>

      <ownedAttribute xmi:id="_14"
                      name="hasGarden" 
                      type="_Boolean"/>
      
      <ownedAttribute xmi:id="_15"
                      name="windowCount" 
                      type="_Integer"/>
      
      <!-- Transportation feature -->
      <ownedAttribute xmi:id="_16" 
                      name="transportFeature">
        <lowerValue xmi:type="uml:LiteralInteger" value="1"/>
        <upperValue xmi:type="uml:LiteralInteger" value="1"/>
        
        <type xsi:type="uml:Class" href="#_TransportationFeature"/>
      </ownedAttribute>
    </packagedElement>

    <!-- Abstract TransportationFeature class -->
    <packagedElement xmi:type="uml:Class" name="TransportationFeature"/>

    <!-- Garage class -->
    <packagedElement xmi:type="uml:Class"
                     name="Garage">
      <generalization client="#_TransportationFeature"/>
      
      <ownedAttribute xmi:id="_17"
                      name="hasAutomaticDoor" 
                      type="_Boolean"/>
    </packagedElement>

    <!-- Carport class -->
    <packagedElement xmi:type="uml:Class"
                     name="Carport">
      <generalization client="#_TransportationFeature"/>
      
      <ownedAttribute xmi:id="_18"
                       name="isDouble" 
                       type="_Boolean"/>

      <ownedAttribute xmi:id="_19"
                      name="hasFlatRoof" 
                      type="_Boolean"/>
    </packagedElement>

    <!-- Company class -->
    <packagedElement xmi:type="uml:Class" name="Company">
      <ownedAttribute xmi:id="_20"
                      name="name" 
                      type="_String"/>

      <ownedAttribute xmi:id="_21"
                      name="address" 
                      type="_dateType"/>
    </packagedElement>

    <!-- JobLog Association Class -->
    <packagedElement xmi:type="uml:Class" name="JobLog">
      <ownedAttribute xmi:id="_22" name="jobHours" type="_Integer"/>

      <ownedAttribute xmi:id="_23" name="jobPrice" type="_Decimal"/>
      
      <!-- Association with House and Company -->
      <association xmi:id="_24" target="_House" navigableOwnedEnd="_25" opposite="#_26"/>
    </packagedElement>

    <!-- Job log association connecting House and Company classes -->
    <packagedElement xmi:type="uml:Association"
                     name="JobLogger">
      <navigableOwnedEnd xmi:idref="_24"/>

      <memberEnd xmi:idref="_25" type="#House"/>
      
      <memberEnd xmi:idref="_26" 
                 type="#Company">
        <association href="#_24"/>
      </memberEnd>
    </packagedElement>

    <!-- Define primitive data types -->
    <packagedElement xmi:type="uml:PrimitiveType" name="_dateType">
      <generalization base="EDate"/>
    </packagedElement>

    <packagedElement xmi:type="uml:PrimitiveType" 
                     name="_String"/>
                     
    <packagedElement xmi:type="uml:PrimitiveType"
                    name="_Integer"/>    
  
    <packagedElement xmi:type="uml:PrimitiveType"
                name="_Decimal"/>

  </packagedElement> <!-- End of Package -->
</uml:Model>
