<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="busmanagement"
    nsURI="http://www.example.org/busmanagement"
    nsPrefix="busmanagement">

  <!-- Enum: Shift -->
  <eClassifiers xsi:type="ecore:EEnum" name="Shift">
    <eLiterals name="Morning" value="0"/>
    <eLiterals name="Afternoon" value="1"/>
    <eLiterals name="Night" value="2"/>
  </eClassifiers>

  <!-- Class: BusVehicle -->
  <eClassifiers xsi:type="ecore:EClass" name="BusVehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LicencePlate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InRepairShop" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeAssignments"
        lowerBound="0" upperBound="-1"
        eType="#//RouteAssignment"
        containment="false"
        eOpposite="#//RouteAssignment/busVehicle"/>
  </eClassifiers>

  <!-- Class: Route -->
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeAssignments"
        lowerBound="0" upperBound="-1"
        eType="#//RouteAssignment"
        containment="false"
        eOpposite="#//RouteAssignment/route"/>
  </eClassifiers>

  <!-- Class: RouteAssignment -->
  <eClassifiers xsi:type="ecore:EClass" name="RouteAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="busVehicle"
        lowerBound="1" upperBound="1"
        eType="#//BusVehicle"
        eOpposite="#//BusVehicle/routeAssignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="route"
        lowerBound="1" upperBound="1"
        eType="#//Route"
        eOpposite="#//Route/routeAssignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driverSchedules"
        lowerBound="0" upperBound="-1"
        eType="#//DriverSchedule"
        containment="false"
        eOpposite="#//DriverSchedule/routeAssignment"/>
  </eClassifiers>

  <!-- Class: Driver -->
  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OnSickLeave" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driverSchedules"
        lowerBound="0" upperBound="-1"
        eType="#//DriverSchedule"
        containment="false"
        eOpposite="#//DriverSchedule/driver"/>
  </eClassifiers>

  <!-- Class: DriverSchedule -->
  <eClassifiers xsi:type="ecore:EClass" name="DriverSchedule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Shift" eType="#//Shift"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver"
        lowerBound="1" upperBound="1"
        eType="#//Driver"
        eOpposite="#//Driver/driverSchedules"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routeAssignment"
        lowerBound="1" upperBound="1"
        eType="#//RouteAssignment"
        eOpposite="#//RouteAssignment/driverSchedules"/>
  </eClassifiers>

</ecore:EPackage>
