<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage 
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

    <eClassifiers>
        <!-- Root Container -->
        <eClass name="CruiseSystem" abstract="false" isRoot="true"/>

        <!-- Classes -->
        
        <!-- Provider Class -->
        <eClass name="Provider">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore:EString"/>
                <eAttribute name="location" eType="ecore:EString"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise Class -->
        <eClass name="Cruise">
            <eStructuralFeatures>
                <eAttribute name="number" eType="ecore:EInt"/>
                <eAttribute name="name" eType="ecore:EString"/>
                <eAttribute name="startDate" eType="ecore:EDate"/>
                <eAttribute name="endDate" eType="ecore:EDate"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Employee Class -->
        <eClass name="Employee">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore:EString"/>
                <eAttribute name="socialSecurityNumber" eType="ecore:EString"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Guest Class -->
        <eClass name="Guest">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore:EString"/>
                <eAttribute name="isVIP" eType="ecore:EBoolean"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Ship Class -->
        <eClass name="Ship">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore:EString"/>
                <eAttribute name="numberOfDecks" eType="ecore:EInt"/>
                <eAttribute name="length" eType="ecore:EDouble"/>
                <eAttribute name="capacityInPassengers" eType="ecore:EInt"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Destination Area Class -->
        <eClass name="DestinationArea">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore:EString"/>
                <eAttribute name="seaName" eType="ecore:EString"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Show Class -->
        <eClass name="Show">
            <eStructuralFeatures>
                <eAttribute name="title" eType="ecore:EString"/>
                <eAttribute name="duration" eType="Duration"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Booking Class -->
        <eClass name="Booking">
            <eStructuralFeatures>
                <eAttribute name="bookingNumber" eType="ecore:EInt"/>
                <eAttribute name="bookingDate" eType="ecore:EDate"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Travel Agency Class -->
        <eClass name="TravelAgency">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore:EString"/>
                <eAttribute name="address" eType="ecore:EString"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Ticket Class -->
        <eClass name="Ticket">
            <eStructuralFeatures>
                <eAttribute name="number" eType="ecore:EInt"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Custom Type for Duration -->
        <eClass name="Duration"/>

        <!-- Associations -->

        <!-- Provider-Cruise Association Class -->
        <eClass name="Provider_Cruise">
            <eStructuralFeatures>
                <eReference source="Provider" target="Cruise"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise-Employee Association Class -->
        <eClass name="Cruise_Employee">
            <eStructuralFeatures>
                <eReference source="Cruise" target="Employee" upper="-1"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise-Guest Association Class -->
        <eClass name="Cruise_Guest">
            <eStructuralFeatures>
                <eReference source="Cruise" target="Guest" upper="-1"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise-Ship Association Class -->
        <eClass name="Cruise_Ship">
            <eStructuralFeatures>
                <eReference source="Cruise" target="Ship"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise-DestinationArea Association Class -->
        <eClass name="Cruise_DestinationArea">
            <eStructuralFeatures>
                <eReference source="Cruise" target="DestinationArea"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise-Show Association Class -->
        <eClass name="Cruise_Show">
            <eStructuralFeatures>
                <eReference source="Cruise" target="Show" upper="-1"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise-Ticket Association Class -->
        <eClass name="Cruise_Ticket">
            <eStructuralFeatures>
                <eReference source="Cruise" target="Ticket" upper="-1" containment="true"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Guest-Ticket Association Class -->
        <eClass name="Guest_Ticket">
            <eStructuralFeatures>
                <eReference source="Guest" target="Ticket" upper="-1"/>
                <eOpposite eOpposite="guest" type="Cruise_Guest"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Travel Agency-Booking Association Class -->
        <eClass name="TravelAgency_Booking">
            <eStructuralFeatures>
                <eReference source="TravelAgency" target="Booking" upper="-1"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Cruise-Travel Agency Association Class -->
        <eClass name="Cruise_TravelAgency">
            <eStructuralFeatures>
                <eReference source="Cruise" target="TravelAgency"/>
                <eOpposite eOpposite="cruises" type="Provider_Cruise"/>
            </eStructuralFeatures>
        </eClass>

    </eClassifiers>

</ecore:EPackage>
