<ecore:EPackage 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore http://www.eclipse.org/emf/2002/Ecore.xsd"
    xmlns:ePackage="http://www.eclipse.org/emf/20131001/ecore/packagedLiterals.ecore#"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
    
    <eClassifiers>
        <!-- Root Container -->
        <eClass name="HmbsSystem"/>

        <!-- Person Superclass -->
        <eClass name="Person">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore::EString"/>
                <eAttribute name="companyName" eType="ecore::EString"/>
                <eAttribute name="address" eType="ecore::EString"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Business Traveller Class -->
        <eClass name="BusinessTraveller" eSuperTypes="#//Person">
            <eStructuralFeatures>
                <eReference name="preferences" upper="-1" lower="0" eType="#//Preference"/>
                <eReference name="creditCardInfo" eType="#//CreditCardInfo"/>
                <eReference name="billingInfo" eType="#//BillingInformation"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Preference Class -->
        <eClass name="Preference"/>

        <!-- Billing Information Class -->
        <eClass name="BillingInformation">
            <eStructuralFeatures>
                <eAttribute name="companyName" eType="ecore::EString"/>
                <eAttribute name="address" eType="ecore::EString"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Credit Card Information Class -->
        <eClass name="CreditCardInfo">
            <eStructuralFeatures>
                <eAttribute name="cardNumber" eType="ecore::EString"/>
                <eAttribute name="expirationDate" eType="#//LocalDate"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Accommodation Booking Class -->
        <eClass name="AccommodationBooking">
            <eStructuralFeatures>
                <eAttribute type="#//LocalDate" name="checkInDate"/>
                <eAttribute type="#//LocalDate" name="checkOutDate"/>
                <eAttribute type="ecore::EInt" name="numberOfRooms"/>
                <eAttribute type="ecore::EString" name="roomType"/>
                <eAttribute type="ecore::EDouble" name="budgetPerNight"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Hotel Class -->
        <eClass name="Hotel">
            <eStructuralFeatures>
                <eAttribute name="name" eType="ecore::EString"/>
                <eReference name="roomAvailabilities" upper="-1" lower="0" eType="#//RoomAvailability"/>
                <eReference type="ecore::EReference" containment="false" name="hotelChain" referencedClass="#//Chain"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Room Availability Class -->
        <eClass name="RoomAvailability">
            <eStructuralFeatures>
                <eAttribute type="#//LocalDateInterval" name="timePeriod"/>
                <eAttribute type="ecore::EBoolean" name="isBooked"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Chain Class -->
        <eClass name="Chain"/>

        <!-- Special Offer Association Between Traveller and Hotel -->
        <eClass name="SpecialOffer">
            <eStructuralFeatures>
                <eAttribute name="offerDetails" eType="ecore::EString"/>
                <eAttribute type="#//CurrencyAmount" name="price"/>
                <eReference containment="true" lower="1" upper="1" name="traveller" referencedClass="#/BusinessTraveller"/>
                <eReference containment="false" lower="1" upper="1" name="hotel" referencedClass="#/Hotel"/>
            </eStructuralFeatures>
        </eClass>

        <!-- Currency Amount Class -->
        <eClass name="CurrencyAmount">
            <eStructuralFeatures>
                <eAttribute type="ecore::EDouble" name="amount"/>
            </eStructuralFeatures>
        </eClass>
        
    </eClassifiers>
</ecore:EPackage>
