<?xml version="1.0" encoding="UTF-8"?>
<umldiagram:Model xmi:version="2.5.0"
                  xmlns:xmi="http://www.omg.org/XMI"
                  xmlns:umldiagram="https://www.eclipse.org/uml2/4.2.0/UML"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <packagedElement xsi:type="umldiagram:Class" name="RootContainer" xmi:id="_Root">
    
        <!-- HospitalHouseMD Class -->
        <packagedElement xsi:type="umldiagram:Class" name="HospitalHouseMD" xmi:id="_HospitalHouseMDClass">
            <ownedAttribute xmi:id="_diagnosisApprovals" name="diagnosisApprovals"/>
            <ownedOperation xmi:id="_approveDiagnosisOprn" name="approveDiagnosis(Diagnosis)"/>
        </packagedElement>
        
        <!-- Patient Class -->
        <packagedElement xsi:type="umldiagram:Class" name="Patient" xmi:id="_PatientClass">
            <ownedAttribute xmi:id="_assignedDoctors" name="assignedDoctors"/>
            <ownedAttribute xmi:id="_consents" name="consentFormSigned"/>
            <ownedOperation xmi:id="_signConsentOprn" name="signConsent()"/>
        </packagedElement>
        
        <!-- Doctor Class -->
        <packagedElement xsi:type="umldiagram:Class" name="Doctor" xmi:id="_DoctorClass">
            <ownedAttribute xmi:id="_approvedDiagnoses" name="approvedDiagnoses"/>
            <ownedOperation xmi:id="_makeDiagnosisOprn" name="makeDiagnosis(Patient)"/>
        </packagedElement>
        
        <!-- Illness Class -->
        <packagedElement xsi:type="umldiagram:Class" name="Illness" xmi:id="_IllnessClass">
            <ownedAttribute xmi:id="_priorityScore" name="priorityScore" type="_PriorityScoreEnum"/>
            <ownedOperation xmi:id="_updatePriorityOprn" name="updatePriority(String)"/>
        </packagedElement>
        
        <!-- Treatment Class -->
        <packagedElement xsi:type="umldiagram:Class" name="Treatment" xmi:id="_TreatmentClass">
            <ownedAttribute xmi:id="_currentStage" name="currentStage" type="_StageEnum"/>
            <ownedOperation xmi:id="_moveToHigherStageOprn" name="moveToHigherStage()"/>
        </packagedElement>
        
        <!-- PriorityScore Enum -->
        <packagedElement xsi:type="umldiagram:Enumeration" name="PriorityScore" xmi:id="_PriorityScoreEnum">
            <literalLiteral name="High" />
            <literalLiteral name="Low" />
        </packagedElement>

        <!-- Stage Enum -->
        <packagedElement xsi:type="umldiagram:Enumeration" name="Stage" xmi:id="_StageEnum">
            <literalLiteral name="Stage1" />
            <literalLiteral name="Stage2" />
            <literalLiteral name="Stage3" />
        </packagedElement>

        <!-- PatientsToDoctors Association -->
        <packagedElement xsi:type="umldiagram:Association" name="PatientsToDoctors" xmi:id="_PatientsToDocsAssoc">
            <ownedEnd xmi:id="_doctorsEnd" type="_DoctorClass">
                <associationEnd xmi:type="umldiagram:StructuralFeature"
                                xmi:idref="_DoctorClass"/>
            </ownedEnd>
            <ownedEnd xmi:id="_patientsEnd" xmi:type="uml:StructuralFeature" containment="true" type="_PatientClass">
                <associationEnd xmi:type="uml:StructuralFeature" 
                                xmi:idref="_PatientClass"/>
            </ownedEnd>
        </packagedElement>

        <!-- DoctorsToDiagnoses Association -->
        <packagedElement xsi:type="umldiagram:Association" name="DoctorsToDiagnoses" xmi:id="_DocsToDiagsAssoc">
            <ownedEnd xmi:id="_diagnosesEnd" type="_IllnessClass"/>
            <ownedEnd xmi:id="_doctorsEnd" type="_DoctorClass"/>
        </packagedElement>
        
        <!-- PatientsToTreatments Association -->
        <packagedElement xsi:type="umldiagram:Association" name="PatientsToTreatments" xmi:id="_PatientsToTreatsAssoc">
            <ownedEnd xmi:type="uml:StructuralFeature"
                      xmi:idref="_PatientClass"/>
            <ownedEnd xmi:type="uml:StructuralFeature"
                      containment="true"
                      xmi:id="_treatmentsEnd" type="_TreatmentClass"/>
        </packagedElement>
    
    </packagedElement>
</umldiagram:Model>
