<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="cruiseModel" nsUri="http://www.example.org/cruise">
    
    <!-- Root Container -->
    <eClass name="CruiseSystem">
      <eStructuralFeatures>
        <eStructuralFeature name="providers" eType="Provider" containment="true"/>
        <eStructuralFeature name="employees" eType="Employee" containment="true"/>
        <eStructuralFeature name="guests" eType="Guest" containment="true"/>
        <eStructuralFeature name="ships" eType="Ship" containment="true"/>
        <eStructuralFeature name="travelAgencies" eType="TravelAgency" containment="true"/>
        <eStructuralFeature name="destinationAreas" eType="DestinationArea" containment="true"/>
        <eStructuralFeature name="cruises" eType="Cruise" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Provider">
      <eStructuralFeatures>
        <eStructuralFeature name="name" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="location" eType="ecore://xmlns/core?EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Employee">
      <eStructuralFeatures>
        <eStructuralFeature name="name" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="socialSecurityNumber" eType="ecore://xmlns/core?EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Guest">
      <eStructuralFeatures>
        <eStructuralFeature name="name" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="isVip" eType="ecore://xmlns/core?EBoolean"/>
        <!-- Association Class Ticket: Guest contains the ticket -->
        <eStructuralFeature name="tickets" eType="Ticket" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Ship">
      <eStructuralFeatures>
        <eStructuralFeature name="name" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="numberOfDecks" eType="ecore://xmlns/core?EInt"/>
        <eStructuralFeature name="length" eType="ecore://xmlns/core?EFloat"/>
        <eStructuralFeature name="numberOfPassengers" eType="ecore://xmlns/core?EInt"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="TravelAgency">
      <eStructuralFeatures>
        <eStructuralFeature name="name" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="address" eType="ecore://xmlns/core?EString"/>
        <!-- Association Class Booking: Agency contains the booking -->
        <eStructuralFeature name="bookings" eType="Booking" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Booking">
      <eStructuralFeatures>
        <eStructuralFeature name="bookingNumber" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="bookingDate" eType="ecore://xmlns/core?EDate"/>
        <eStructuralFeature name="travelAgency" eType="TravelAgency"/>
        <eStructuralFeature name="cruise" eType="Cruise"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="DestinationArea">
      <eStructuralFeatures>
        <eStructuralFeature name="name" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="seaName" eType="ecore://xmlns/core?EString"/>
      </eStructuralFeatures>
    </eClass>

    <eDataType name="DurationType" instanceValue="java.time.Duration"/>

    <eClass name="Show">
      <eStructuralFeatures>
        <eStructuralFeature name="title" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="duration" eType="DurationType"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Ticket">
      <eStructuralFeatures>
        <eStructuralFeature name="guest" eType="Guest"/>
        <eStructuralFeature name="cruise" eType="Cruise"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Cruise">
      <eStructuralFeatures>
        <eStructuralFeature name="number" eType="ecore://xmlns/core?EInt"/>
        <eStructuralFeature name="name" eType="ecore://xmlns/core?EString"/>
        <eStructuralFeature name="startDate" eType="ecore://xmlns/core?EDate"/>
        <eStructuralFeature name="endDate" eType="ecore://xmlns/core?EDate"/>
        <eStructuralFeature name="provider" eType="Provider"/>
        <eStructuralFeature name="ship" eType="Ship"/>
        <eStructuralFeature name="destinationArea" eType="DestinationArea"/>
        <eStructuralFeature name="employees" eType="Employee"/>
        <eStructuralFeature name="shows" eType="Show" containment="true"/>
        <!-- Reference to association classes -->
        <eStructuralFeature name="tickets" eType="Ticket"/>
        <eStructuralFeature name="bookings" eType="Booking"/>
      </eStructuralFeatures>
    </eClass>

  </ePackage>
</xmi:XMI>
