<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI" 
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
                epackageID="com.sober.taxi" 
                name="SoberTaxiPackage" 
                nsURI="http://www.sober.com/taxi/" 
                nsPrefix="sob">
    
    <!-- RootContainer encapsulates all other entities -->
    <eClassifiers xsi:type="ecore:EClass" name="RootContainer" isAbstract="false">
        <eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#_1" containment="true">
                <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore"> 
                    <!-- This class acts as the root container for all other classes -->
                    <!-- It ensures that everything is encapsulated within a single entity -->
                </eAnnotations>
            </eStructuralFeatures>
        </eStructuralFeatures>
    </eClassifiers>
    
    <!-- Car Class Definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Car">
        <eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#_3" name="owners"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" eType="http://www.eclipse.org/emf/2002/Ecore//EString"/>
        </eStructuralFeatures>
    </eClassifiers>
    
    <!-- Owner Class Definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Owner">
        <eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="http://www.eclipse.org/emf/2002/Ecore//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#_5" name="rideHails"/>
            <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#_6" name="rideShares"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Service Base Class Definition -->
    <eClassifiers xsi:type="ecore:EClass" name="Service">
    </eClassifiers>

    <!-- RideHailing Class Definition -->
    <eClassifiers xsi:type="ecore:EClass" name="RideHailing">
        <eSuperTypes>eClassifier="#_7"</eSuperTypes>
        <eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOfPickUp" eType="http://www.eclipse.org/emf/2002/Ecore//ETimestamp"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationOfPickUp" eType="#_8"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOfDropOff" eType="http://www.eclipse.org/emf/2002/Ecore//ETimestamp"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationOfDropOff" eType="#_8"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="rideDuration" eType="#_9"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="#_9"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfPassengers" eType="http://www.eclipse.org/emf/2002/Ecore//EInt"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="fee" eType="#_9"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeOfRequest" eType="http://www.eclipse.org/emf/2002/Ecore//EString"/>
            <eStructuralFeatures xsi:type="ecore:EReference" upperBound="1" eType="#_10" name="leadCustomer"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- RideSharing Class Definition -->
    <eClassifiers xsi:type="ecore:EClass" name="RideSharing">
        <eSuperTypes>eClassifier="#_7"</eSuperTypes>
        <eStructuralFeatures>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOfPickUp" eType="http://www.eclipse.org/emf/2002/Ecore//ETimestamp"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationOfPickUp" eType="#_8"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="timeOfDropOff" eType="http://www.eclipse.org/emf/2002/Ecore//ETimestamp"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationOfDropOff" eType="#_8"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="rideDuration" eType="#_9"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="#_9"/>
            <eStructuralFeatures xsi:type="ecore:EReference" upperBound="-1" eType="#_10" name="customers"/>
            <eStructuralFeatures xsi:type="ecore:EAttribute" name="negotiatedFee" eType="#_9"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- CustomTime Enumeration Definition -->
    <eClassifiers xsi:type="ecore:EEnum" name="CustomDateAndTime">
        <!-- Enumeration for managing time without dates -->
    </eClassifiers>

    <!-- TimeOnly DataType Definition -->
    <eClassifiers xsi:type="ecore:EDataType" name="TimeOnly" baseType="http://www.eclipse.org/emf/2002/Ecore//EString"/>

    <!-- Map Data Type to Manage Ride References -->
    <eStructuralFeatures>
        <eMap xmi:id="_12">
            <eKeys xsi:type="ecore:EAttribute" name="key" eType="http://www.eclipse.org/emf/2002/Ecore//EString"/>
            <eValues>
                <eClassifier>_11</eClassifier>
            </eValues>
        </eMap>

        <!-- Association Definitions -->
        <eReferences>
            <!-- RideHailing Reference to Car Owners -->
            <ec:EReference xmi:id="_12b" eOpposite="#_5a" containment="true" upperBound="-1">
                <references>eClassifier="Car"</references>
            </ec:EReference>

            <!-- Service References by Owner Classes -->
            <ec:EReference xmi:id="_13" containment="false" upperBound="-1">
                <references>eClassifier="#_6"</references> 
            </ec:EReference>

            <!-- Ride Sharing Reference for Customers -->
            <ec:EReference xmi:id="_5a" eOpposite="#_12b" containment="false" upperBound="-1">
                <eType>Owner</eType>
            </ec:EReference>

            <!-- Containment References -->
            <ec:EReference xmi:id="_6" eOpposite="$5b" containment="true" upperBound="-1">
                <references>eClassifier="Service"</references>
            </ec:EReference>

            <ec:EReference xmi:id="_7" containment="false" upperBound="-1">
                <references>eClassifier="#_11"</references> 
            </ec:EReference>
        </eReferences>
    </eStructuralFeatures>
    
</ecore:EPackage>
