<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="airplane"
    nsURI="http://www.example.com/airplane"
    nsPrefix="airplane">

  <eClassifiers xsi:type="ecore:EClass" name="AirplaneModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModelId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplanes" eType="#//Airplane"
        lowerBound="0" upperBound="-1" containment="false" eOpposite="#//Airplane/airplaneModel"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Airplane">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AirPlaneId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplaneModel" eType="#//AirplaneModel"
        lowerBound="1" upperBound="1" eOpposite="#//AirplaneModel/airplanes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acquisition" eType="#//Acquisition"
        lowerBound="0" upperBound="1" eOpposite="#//Acquisition/airplane"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Acquisition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AcquisitionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NegotiatedPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Options" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DeliveryDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplane" eType="#//Airplane"
        lowerBound="0" upperBound="1" eOpposite="#//Airplane/acquisition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contract" eType="#//Contract"
        lowerBound="1" upperBound="1" eOpposite="#//Contract/acquisitions"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Contract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ContractId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="acquisitions" eType="#//Acquisition"
        lowerBound="0" upperBound="-1" eOpposite="#//Acquisition/contract"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airline" eType="#//Airline"
        lowerBound="1" upperBound="1" eOpposite="#//Airline/contracts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" eType="#//Employee"
        lowerBound="1" upperBound="1" eOpposite="#//Employee/contracts"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EmployeeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contracts" eType="#//Contract"
        lowerBound="0" upperBound="-1" eOpposite="#//Contract/employee"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Airline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/EcoreBasicType#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contracts" eType="#//Contract"
        lowerBound="0" upperBound="-1" eOpposite="#//Contract/airline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAirline" eType="#//Airline"
        lowerBound="0" upperBound="1" eOpposite="#//Airline/subsidiaryAirlines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsidiaryAirlines" eType="#//Airline"
        lowerBound="0" upperBound="-1" eOpposite="#//Airline/parentAirline"/>
  </eClassifiers>

</ecore:EPackage>
