<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="airplane"
    nsURI="http://www.example.org/airplane"
    nsPrefix="airplane">

  <!-- AirplaneModel class -->
  <eClassifiers xsi:type="ecore:EClass" name="AirplaneModel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- One AirplaneModel can have zero or more Airplanes -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplanes"
        eType="#//Airplane"
        upperBound="-1"
        eOpposite="#//Airplane/airplaneModel"/>
  </eClassifiers>

  <!-- Airplane class -->
  <eClassifiers xsi:type="ecore:EClass" name="Airplane">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="airPlaneId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Reference back to AirplaneModel (many-to-one side) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplaneModel"
        eType="#//AirplaneModel"
        lowerBound="1"
        eOpposite="#//AirplaneModel/airplanes"/>
    <!-- An Airplane may be part of zero or one Acquisition -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="acquisition"
        eType="#//Acquisition"
        eOpposite="#//Acquisition/airplane"/>
  </eClassifiers>

  <!-- Acquisition class -->
  <eClassifiers xsi:type="ecore:EClass" name="Acquisition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acquisitionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negotiatedPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="options" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Reference back to Airplane (0..1 side) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplane"
        eType="#//Airplane"
        eOpposite="#//Airplane/acquisition"/>
    <!-- Zero or more Acquisitions are part of one Contract -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="contract"
        eType="#//Contract"
        lowerBound="1"
        eOpposite="#//Contract/acquisitions"/>
  </eClassifiers>

  <!-- Contract class -->
  <eClassifiers xsi:type="ecore:EClass" name="Contract">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="contractId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- One Contract has zero or more Acquisitions -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="acquisitions"
        eType="#//Acquisition"
        upperBound="-1"
        eOpposite="#//Acquisition/contract"/>
    <!-- Zero or more Contracts are linked to one Airline -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airline"
        eType="#//Airline"
        lowerBound="1"
        eOpposite="#//Airline/contracts"/>
    <!-- Zero or more Contracts are linked to one Employee -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee"
        eType="#//Employee"
        lowerBound="1"
        eOpposite="#//Employee/contracts"/>
  </eClassifiers>

  <!-- Employee class -->
  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="employeeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- One Employee can be linked to zero or more Contracts -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="contracts"
        eType="#//Contract"
        upperBound="-1"
        eOpposite="#//Contract/employee"/>
  </eClassifiers>

  <!-- Airline class -->
  <eClassifiers xsi:type="ecore:EClass" name="Airline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- One Airline can be linked to zero or more Contracts -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="contracts"
        eType="#//Contract"
        upperBound="-1"
        eOpposite="#//Contract/airline"/>
    <!-- Self-referential: an Airline may have a parent Airline (0..1) and zero or more subsidiary Airlines -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAirline"
        eType="#//Airline"
        eOpposite="#//Airline/subsidiaryAirlines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsidiaryAirlines"
        eType="#//Airline"
        upperBound="-1"
        eOpposite="#//Airline/parentAirline"/>
  </eClassifiers>

</ecore:EPackage>
