<?xml version="1.0" encoding="UTF-8"?>
<ePackage name="filmset" nsURI="http://www.example.org/filmset" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/Ecore/" xmi:version="2.0">
  
  <!-- Root Container acting as a global root -->
  <eClass name="FilmProductionSystem">
    <eStructuralFeatures>
      <eReference name="employees" eClassifier="Employee"/>
      <eReference name="filmSets" eClassifier="FilmSet"/>
      <eReference name="films" eClassifier="Film"/>
      <eReference name="screenwriters" eClassifier="Screenwriter"/>
    </eStructuralFeatures>
  </eClass>

  <!-- Employee Hierarchy -->
  <eClass name="Employee" abstract="true">
    <eStructuralFeatures>
      <eAttribute name="name" eType="ecore:EString"/>
      <eAttribute name="socialSecurityNumber" eType="ecore:EString"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="CreativeEmployee" abstract="true">
    <eSuperTypes>
      <eSuperType eClassifier="Employee"/>
    </eSuperTypes>
    <eStructuralFeatures>
      <eAttribute name="hasOscar" eType="ecore:EBoolean"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Actor">
    <eSuperTypes>
      <eSuperType eClassifier="CreativeEmployee"/>
    </eSuperTypes>
    <eStructuralFeatures>
      <eAttribute name="education" eType="ecore:EString"/>
      <!-- Actors read the screenplay to prepare for roles -->
      <eReference name="readScreenplays" eClassifier="Screenplay"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Director">
    <eSuperTypes>
      <eSuperType eClassifier="CreativeEmployee"/>
    </eSuperTypes>
    <eStructuralFeatures>
      <eAttribute name="assistantName" eType="ecore:EString"/>
      <!-- The director implements the screenplay -->
      <eReference name="implementsScreenplay" eClassifier="Screenplay"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Technician">
    <eSuperTypes>
      <eSuperType eClassifier="Employee"/>
    </eSuperTypes>
    <eStructuralFeatures>
      <eAttribute name="fieldOfActivity" eType="ecore:EString"/>
    </eStructuralFeatures>
  </eClass>

  <!-- Film Set and Films -->
  <eClass name="FilmSet">
    <eStructuralFeatures>
      <eAttribute name="location" eType="ecore:EString"/>
      <eReference name="films" eClassifier="Film"/>
    </eStructuralFeatures>
  </eClass>

  <eEnum name="Genre">
    <eLiterals>
      <eLiteral name="THRILLER"/>
      <eLiteral name="ACTION"/>
      <eLiteral name="HORROR"/>
      <eLiteral name="COMEDY"/>
    </eLiterals>
  </eEnum>

  <eClass name="Film">
    <eStructuralFeatures>
      <eAttribute name="title" eType="ecore:EString"/>
      <eAttribute name="releaseYear" eType="ecore:EInt"/>
      <eAttribute name="genre" eType="Genre"/>
      <eReference name="filmSets" eClassifier="FilmSet"/>
      <eReference name="screenplay" eClassifier="Screenplay"/>
      <eReference name="director" eClassifier="Director"/>
    </eStructuralFeatures>
  </eClass>

  <!-- Screenwriting Process -->
  <eClass name="Screenwriter">
    <eStructuralFeatures>
      <eAttribute name="name" eType="ecore:EString"/>
      <eReference name="mostSuccessfulFilm" eClassifier="Film"/>
      <eReference name="screenplays" eClassifier="Screenplay"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Screenplay">
    <eStructuralFeatures>
      <eAttribute name="title" eType="ecore:EString"/>
      <eAttribute name="version" eType="ecore:EString"/>
      <eAttribute name="date" eType="ecore:EDate"/>
      <eAttribute name="numberOfScenes" eType="ecore:EInt"/>
      <eAttribute name="plot" eType="ecore:EString"/>
      <eReference name="screenwriter" eClassifier="Screenwriter"/>
      <eReference name="film" eClassifier="Film"/>
      <eReference name="sourceMaterial" eClassifier="SourceMaterial"/>
    </eStructuralFeatures>
  </eClass>

  <!-- Source Material Hierarchy -->
  <eClass name="SourceMaterial" abstract="true"/>

  <eClass name="Novel">
    <eSuperTypes>
      <eSuperType eClassifier="SourceMaterial"/>
    </eSuperTypes>
    <eStructuralFeatures>
      <eAttribute name="title" eType="ecore:EString"/>
      <eAttribute name="author" eType="ecore:EString"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Concept">
    <eSuperTypes>
      <eSuperType eClassifier="SourceMaterial"/>
    </eSuperTypes>
  </eClass>

</ePackage>
