<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="medicalPackage"
    nsURI="http://www.example.org/medicalPackage"
    nsPrefix="medicalPackage">

  <eClassifiers xsi:type="ecore:EClass" name="Patient">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Consent"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnoses"
        eType="#//Diagnosis"
        lowerBound="0" upperBound="-1"
        containment="false" eOpposite="#//Diagnosis/patient"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Doctor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnoses"
        eType="#//Diagnosis"
        lowerBound="0" upperBound="-1"
        containment="false" eOpposite="#//Diagnosis/doctor"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Diagnosis">
    <eOperations name="upgradeStage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="downgradeStage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="priorityUpgrade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Stage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient"
        eType="#//Patient"
        lowerBound="1" upperBound="1"
        containment="false" eOpposite="#//Patient/diagnoses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doctor"
        eType="#//Doctor"
        lowerBound="1" upperBound="1"
        containment="false" eOpposite="#//Doctor/diagnoses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="illness"
        eType="#//Illness"
        lowerBound="1" upperBound="1"
        containment="false" eOpposite="#//Illness/diagnoses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedTreatments"
        eType="#//AppliedTreatment"
        lowerBound="0" upperBound="-1"
        containment="false" eOpposite="#//AppliedTreatment/diagnosis"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Illness">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Priority"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnoses"
        eType="#//Diagnosis"
        lowerBound="0" upperBound="-1"
        containment="false" eOpposite="#//Diagnosis/illness"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatments"
        eType="#//Treatment"
        lowerBound="0" upperBound="-1"
        containment="false" eOpposite="#//Treatment/illness"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Treatment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="illness"
        eType="#//Illness"
        lowerBound="1" upperBound="1"
        containment="false" eOpposite="#//Illness/treatments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedTreatments"
        eType="#//AppliedTreatment"
        lowerBound="0" upperBound="-1"
        containment="false" eOpposite="#//AppliedTreatment/treatment"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="AppliedTreatment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnosis"
        eType="#//Diagnosis"
        lowerBound="1" upperBound="1"
        containment="false" eOpposite="#//Diagnosis/appliedTreatments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatment"
        eType="#//Treatment"
        lowerBound="1" upperBound="1"
        containment="false" eOpposite="#//Treatment/appliedTreatments"/>
  </eClassifiers>

</ecore:EPackage>
