<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="donationSystem" nsURI="http://www.example.org/donationSystem"
    nsPrefix="donationSystem">
  <eClassifiers xsi:type="ecore:EClass" name="DonationSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" upperBound="-1"
        eType="#//Vehicle" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ItemCategory">
    <eLiterals name="BabyClothing"/>
    <eLiterals name="Fridge" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="userRoles" upperBound="-1"
        eType="#//UserRole" containment="true" eOpposite="#//UserRole/person"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UserRole" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" eType="#//Person"
        eOpposite="#//Person/userRoles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="#//UserRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neededCategories" upperBound="-1"
        eType="#//ItemCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondHandArticles" upperBound="-1"
        eType="#//SecondHandArticle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Volunteer" eSuperTypes="#//UserRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableDates" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" eOpposite="#//Route/volunteer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resident" eSuperTypes="#//UserRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestedPickedDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pickupRoute" eType="#//Route"
        eOpposite="#//Route/pickedUp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FoodItem" eSuperTypes="#//Item"/>
  <eClassifiers xsi:type="ecore:EClass" name="SecondHandArticle" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeRFID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discarded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//ItemCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dropOffRoute" eType="#//Route"
        eOpposite="#//Route/droppedOff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weightRestriction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes" upperBound="-1"
        eType="#//Route" eOpposite="#//Route/vehicle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" eType="#//Vehicle"
        eOpposite="#//Vehicle/routes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pickedUp" upperBound="-1"
        eType="#//Item" eOpposite="#//Item/pickupRoute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="droppedOff" upperBound="-1"
        eType="#//SecondHandArticle" eOpposite="#//SecondHandArticle/dropOffRoute"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="volunteer" eType="#//Volunteer"
        eOpposite="#//Volunteer/routes"/>
  </eClassifiers>
</ecore:EPackage>
