<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="donation"
    nsURI="http://www.example.org/donation"
    nsPrefix="donation">

  <!-- Enum: ItemCategory -->
  <eClassifiers xsi:type="ecore:EEnum" name="ItemCategory">
    <eLiterals name="BabyClothing" value="0" literal="Baby Clothing"/>
    <eLiterals name="Fridge" value="1" literal="Fridge"/>
  </eClassifiers>

  <!-- Class: Date -->
  <eClassifiers xsi:type="ecore:EClass" name="Date">
  </eClassifiers>

  <!-- Class: Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Association: Person 1 -- 0..* UserRole -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="userRoles"
        eType="#//UserRole"
        upperBound="-1"
        containment="false"
        eOpposite="#//UserRole/person"/>
  </eClassifiers>

  <!-- Abstract Class: UserRole -->
  <eClassifiers xsi:type="ecore:EClass" name="UserRole" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        eType="#//Person"
        lowerBound="1"
        upperBound="1"
        eOpposite="#//Person/userRoles"/>
  </eClassifiers>

  <!-- Class: Client extends UserRole -->
  <eClassifiers xsi:type="ecore:EClass" name="Client" eSuperTypes="#//UserRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="neededCategories"
        eType="#//ItemCategory"
        upperBound="-1"/>
    <!-- Association: Client 0..1 -- 0..* SecondHandArticle -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondHandArticles"
        eType="#//SecondHandArticle"
        upperBound="-1"
        containment="false"
        eOpposite="#//SecondHandArticle/client"/>
  </eClassifiers>

  <!-- Class: Volunteer extends UserRole -->
  <eClassifiers xsi:type="ecore:EClass" name="Volunteer" eSuperTypes="#//UserRole">
    <!-- Composition: Volunteer *-> 0..* Date -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableDates"
        eType="#//Date"
        upperBound="-1"
        containment="true"/>
    <!-- Association: Volunteer 1 -- 0..* Route -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes"
        eType="#//Route"
        upperBound="-1"
        containment="false"
        eOpposite="#//Route/volunteer"/>
  </eClassifiers>

  <!-- Class: Resident extends UserRole -->
  <eClassifiers xsi:type="ecore:EClass" name="Resident" eSuperTypes="#//UserRole">
    <!-- Association: Resident 1 -- 0..* Item -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="items"
        eType="#//Item"
        upperBound="-1"
        containment="false"
        eOpposite="#//Item/resident"/>
  </eClassifiers>

  <!-- Abstract Class: Item -->
  <eClassifiers xsi:type="ecore:EClass" name="Item" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requestedPickedDate"
        eType="#//Date"
        containment="false"/>
    <!-- Opposite of Resident -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="resident"
        eType="#//Resident"
        lowerBound="1"
        upperBound="1"
        eOpposite="#//Resident/items"/>
    <!-- Opposite of Route pickupRoute -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="pickupRoute"
        eType="#//Route"
        upperBound="1"
        eOpposite="#//Route/pickupItems"/>
  </eClassifiers>

  <!-- Class: FoodItem extends Item -->
  <eClassifiers xsi:type="ecore:EClass" name="FoodItem" eSuperTypes="#//Item">
  </eClassifiers>

  <!-- Class: SecondHandArticle extends Item -->
  <eClassifiers xsi:type="ecore:EClass" name="SecondHandArticle" eSuperTypes="#//Item">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="codeRFID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discarded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//ItemCategory"/>
    <!-- Opposite of Client -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="client"
        eType="#//Client"
        upperBound="1"
        eOpposite="#//Client/secondHandArticles"/>
    <!-- Opposite of Route dropOffRoute -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="dropOffRoutes"
        eType="#//Route"
        upperBound="-1"
        eOpposite="#//Route/dropOffArticles"/>
  </eClassifiers>

  <!-- Class: Vehicle -->
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weightRestriction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Opposite of Route -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="routes"
        eType="#//Route"
        upperBound="-1"
        eOpposite="#//Route/vehicle"/>
  </eClassifiers>

  <!-- Class: Route -->
  <eClassifiers xsi:type="ecore:EClass" name="Route">
    <eStructuralFeatures xsi:type="ecore:EReference" name="date"
        eType="#//Date"
        containment="false"/>
    <!-- Association: Volunteer 1 -- 0..* Route -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="volunteer"
        eType="#//Volunteer"
        lowerBound="1"
        upperBound="1"
        eOpposite="#//Volunteer/routes"/>
    <!-- Association: Route 0..* -- 1 Vehicle -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle"
        eType="#//Vehicle"
        lowerBound="1"
        upperBound="1"
        eOpposite="#//Vehicle/routes"/>
    <!-- Association: Route 0..1 -- 0..* Item : pickupRoute -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="pickupItems"
        eType="#//Item"
        upperBound="-1"
        eOpposite="#//Item/pickupRoute"/>
    <!-- Association: Route 0..* -- 0..* SecondHandArticle : dropOffRoute -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="dropOffArticles"
        eType="#//SecondHandArticle"
        upperBound="-1"
        eOpposite="#//SecondHandArticle/dropOffRoutes"/>
  </eClassifiers>

</ecore:EPackage>
