<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://schema.omg.org/spec/XMI/20131001"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="system"
    eClassifiers=
"Location Driver Vehicle Truck Car Van Order Assignment SystemRoot">
  <eClassifiers xsi:type="ecore:EClass" name="SystemRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" type="Location" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drivers" type="Driver" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles" type="Vehicle" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" type="Order" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments" type="Assignment" upperBound="-1" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drivers" type="Driver" upperBound="-1" containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:String"/>
    <eOperations>
      <eOperations name="getFullName">
        <eType xsi:type="ecore:EDataType" href="#//ecore:String"/>
      </eOperations>
    </eOperations>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleNumber" eType="ecore:String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" type="Driver" upperBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Truck" eSuperTypes="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:Int"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Car" eSuperTypes="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSeats" eType="ecore:Int"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Van" eSuperTypes="Vehicle"/>

  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EReference" name="originLocation" type="Location" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationLocation" type="Location" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" type="Driver" lowerBound="1" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionDate" eType="ecore:EDate"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" type="Driver" lowerBound="1" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" type="Vehicle" lowerBound="1" upperBound="1"/>
    <!-- Containment via eContainments element -->
    <eContainments>
      <eReferent type="Driver"/>
    </eContainments>
  </eClassifiers>
</ecore:EPackage>
