<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="gasstation"
    nsURI="http://www.example.org/gasstation"
    nsPrefix="gasstation">

  <!-- Root container class -->
  <eClassifiers xsi:type="ecore:EClass" name="GasStationSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gasStations"
        eType="#//GasStation" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardHolders"
        eType="#//CardHolder" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="CardHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suspended"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoices"
        eType="#//Invoice" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refuelTurns"
        eType="#//RefuelTurn" upperBound="-1" eOpposite="#//RefuelTurn/cardHolder"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="discount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLines"
        eType="#//InvoiceLine" containment="true" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="InvoiceLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="GasStation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pumps"
        eType="#//Pump" containment="true" upperBound="-1" eOpposite="#//Pump/gasStation"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Pump">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inUse"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refillThreshold"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blocked"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gasStation"
        eType="#//GasStation" eOpposite="#//GasStation/pumps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refuelTurns"
        eType="#//RefuelTurn" containment="true" upperBound="-1" eOpposite="#//RefuelTurn/pump"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cashTurns"
        eType="#//CashTurn" containment="true" upperBound="-1" eOpposite="#//CashTurn/pump"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="RefuelTurn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refuelTurnNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pump"
        eType="#//Pump" eOpposite="#//Pump/refuelTurns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardHolder"
        eType="#//CardHolder" eOpposite="#//CardHolder/refuelTurns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLine"
        eType="#//InvoiceLine" upperBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="CashTurn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pump"
        eType="#//Pump" eOpposite="#//Pump/cashTurns"/>
  </eClassifiers>

</ecore:EPackage>
