<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="gasstation"
    nsURI="http://www.example.org/gasstation"
    nsPrefix="gasstation">

  <eClassifiers xsi:type="ecore:EClass" name="CardHolder">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Suspended" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoices" upperBound="-1"
        eType="#//Invoice" containment="true" eOpposite="#//Invoice/cardHolder"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refuelTurns" upperBound="-1"
        eType="#//RefuelTurn" containment="true" eOpposite="#//RefuelTurn/cardHolder"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Invoice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Discount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardHolder" lowerBound="1"
        eType="#//CardHolder" eOpposite="#//CardHolder/invoices"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLines" upperBound="-1"
        eType="#//InvoiceLine" containment="true" eOpposite="#//InvoiceLine/invoice"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="InvoiceLine">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoice" lowerBound="1"
        eType="#//Invoice" eOpposite="#//Invoice/invoiceLines"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refuelTurn" eType="#//RefuelTurn"
        eOpposite="#//RefuelTurn/invoiceLine"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="GasStation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pumps" upperBound="-1"
        eType="#//Pump" containment="true" eOpposite="#//Pump/gasStation"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Pump">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InUse" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RefillThreshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Blocked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gasStation" lowerBound="1"
        eType="#//GasStation" eOpposite="#//GasStation/pumps"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refuelTurns" upperBound="-1"
        eType="#//RefuelTurn" containment="true" eOpposite="#//RefuelTurn/pump"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cashTurns" upperBound="-1"
        eType="#//CashTurn" containment="true" eOpposite="#//CashTurn/pump"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="RefuelTurn">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RefuelTurnNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pump" lowerBound="1"
        eType="#//Pump" eOpposite="#//Pump/refuelTurns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardHolder" lowerBound="1"
        eType="#//CardHolder" eOpposite="#//CardHolder/refuelTurns"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invoiceLine" eType="#//InvoiceLine"
        eOpposite="#//InvoiceLine/refuelTurn"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="CashTurn">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pump" lowerBound="1"
        eType="#//Pump" eOpposite="#//Pump/cashTurns"/>
  </eClassifiers>

</ecore:EPackage>
