<?xml version="1.0" encoding="UTF-8"?>
<XMI xmi:version="2.5.0"
     xmlns:xmi="http://www.omg.org/XMI"
     xmlns:uml="http://schema.omg.org/spec/UML/2.5.1/PDF">

  <uml:Model xmi:id="_1">
  
    <packagedElement xmi:type="uml:Package" name="PizzaDeliveryWithEntertainment">

      <!-- User Base Class -->
      <packagedElement xmi:type="uml:Class" name="User">
        <ownedAttribute xmi:id="_2" name="name" type="_java:string"/>
        <ownedAttribute xmi:id="_3" name="address" type="_Address"/>
        <ownedAttribute xmi:id="_4" displayName="id" name="userId" type="_java:UUID" uniqueness="unique"/>
        <ownedAttribute xmi:id="_5" name="birthday" type="_DateTime"/>
      </packagedElement>
      
      <!-- Address Class -->
      <packagedElement xmi:type="uml:Class" name="Address">
        <ownedAttribute xmi:id="_6" name="street" type="_java:string"/>
        <ownedAttribute xmi:id="_7" name="zipCode" type="_java:string"/>
      </packagedElement>
      
      <!-- BusinessOwner Class -->
      <packagedElement xmi:type="uml:Class" name="BusinessOwner">
        <generalization general="_8">
          <general>_1</general> <!-- Reference to User class ID -->
        </generalization>
        <ownedAttribute xmi:id="_9" name="linkedInAccount" type="_java:string"/>
      </packagedElement>

      <!-- PizzaRestaurant Class -->
      <packagedElement xmi:type="uml:Class" name="PizzaRestaurant">
        <ownedAttribute xmi:id="_10" name="zipCode" type="_java:string"/>
        <ownedAttribute xmi:id="_11" name="address" type="_Address"/>
        <ownedAttribute xmi:id="_12" name="phoneNumber" type="_java:string"/>
        <ownedAttribute xmi:id="_13" name="website" type="_java:string"/>
      </packagedElement>

      <!-- HungryCustomer Class -->
      <packagedElement xmi:type="uml:Class" name="HungryCustomer">
        <generalization general="_8">
          <general>_1</general> <!-- Reference to User class ID -->
        </generalization>
      </packagedElement>

      <!-- Order Class -->
      <packagedElement xmi:type="uml:Class" name="Order">
        <ownedAttribute xmi:id="_15" displayName="id" name="orderId" type="_java:UUID" uniqueness="unique"/>
        <ownedAttribute xmi:id="_16" name="orderDate" type="_DateTime"/>
        <ownedAttribute xmi:id="_17" name="latestDeliveryTime" type="_DateTime"/>
        <ownedAttribute xmi:id="_18" name="numberOfPeople" type="_java:int"/>
      </packagedElement>

      <!-- Pizza Class -->
      <packagedElement xmi:type="uml:Class" name="Pizza">
        <ownedAttribute xmi:id="_23" name="name" type="_java:string"/>
        <ownedAttribute xmi:id="_24" name="crustType" type="CrustType"/>
        <ownedAttribute xmi:id="_25" name="price" type="_java:double"/>
      </packagedElement>

      <!-- Entertainer Class -->
      <packagedElement xmi:type="uml:Class" name="Entertainer">
        <generalization general="_8">
          <general>_1</general> <!-- Reference to User class ID -->
        </generalization>
        
        <ownedAttribute xmi:id="_26" name="stageName" type="_java:string"/>
        <ownedAttribute xmi:id="_27" name="bio" type="_java:stirng"/>
        <ownedAttribute xmi:id="_28" displayName="pricePer30Minutes" name="rate" type="_java:double"/>
      </packagedElement>

    </packagedElement>
    
  </uml:Model>
  
</XMI>
