<xmi:XMI xmlns:xmi="http://www.omg.org/spec/XMI/20131001"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.eclipse.org/emf/2002/Ecore"
         xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore
                              http://git.io/JtYj5Q">
  <EPackage xmi:type="Ecore:EPackage" name="school" nsURI="school" nsPrefix="school">

    <!-- Root container class -->
    <eClassifiers xsi:type="Ecore:EClass" name="SchoolSystem">
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="schools" eType="#//School"
                           upperBound="-1" containment="true"/>
    </eClassifiers>

    <!-- Main classes -->
    <eClassifiers xsi:type="Ecore:EClass" name="Person">
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="firstName" type="EString"/>
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="lastName" type="EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="Teacher" eSuperTypes="#//Person">
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="email" type="EString"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="teachingPositions" eType="#//TeachingPosition"
                           upperBound="-1" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="Student" eSuperTypes="#//Person">
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="classGroup" type="#//ClassGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="School">
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="name" type="EString"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="teachers" eType="#//Teacher"
                           upperBound="-1" containment="true"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="students" eType="#//Student"
                           upperBound="-1" containment="true"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="classGroups" eType="#//ClassGroup"
                           upperBound="-1" containment="true"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="rooms" eType="#//Room"
                           upperBound="-1" containment="true"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="principalPosition" type="#//PrincipalPosition">
        <eOpposite ref="#//PrincipalPosition/school"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="Room">
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="name" type="EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="Classroom" eSuperTypes="#//Room">
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="capacity" type="EInt"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="classGroup" type="#//ClassGroup">
        <eOpposite ref="#//ClassGroup/classroom"/>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="Gym" eSuperTypes="#//Room">
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="sizeSquareMeters" type="EFloat"/>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="ClassGroup">
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="name" type="EString"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="students" eType="#//Student"
                           upperBound="-1" containment="true"/>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="classroom" type="#//Classroom">
        <eOpposite ref="#//Classroom/classGroup"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Association classes -->
    <eClassifiers xsi:type="Ecore:EClass" name="TeachingPosition">
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="teacher" type="#//Teacher">
        <eOpposite ref="#//Teacher/teachingPositions"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="school" type="#//School">
        <!-- Opposite points to the container reference in School -->
        <eOpposite ref="#//School/teachers"/>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="Ecore:EAttribute"
                           name="teachingHours" type="java.time.Duration"/>
    </eClassifiers>
    <eClassifiers xsi:type="Ecore:EClass" name="PrincipalPosition">
      <!-- Opposite for teacher -->
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="teacher" type="#//Teacher">
        <eOpposite ref="/EClass[@name='Teacher']/eStructuralFeatures[3]"/>
      </eStructuralFeatures>
      <!-- Opposite for school -->
      <eStructuralFeatures xsi:type="Ecore:EReference"
                           name="school" type="#//School">
        <eOpposite ref="/EClass[@name='School']/eStructuralFeatures[8]"/>
      </eStructuralFeatures>
    </eClassifiers>

  </EPackage>
</xmi:XMI>
