<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="boeing" nsURI="http://www.boeing.com/model" xmi:id="boeing_package">
    
    <!-- Root Container -->
    <eClass name="BoeingSystem" xmi:id="boeing_system">
      <eStructuralFeatures>
        <eReference xmi:id="bs_employees" name="employees" eType="employee" containment="true"/>
        <eReference xmi:id="bs_airlines" name="airlineCompanies" eType="airlineCompany" containment="true"/>
        <eReference xmi:id="bs_contracts" name="contracts" eType="contract" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Employee" xmi:id="employee">
      <eStructuralFeatures>
        <eAttribute xmi:id="emp_name" name="name" eType="http://www.eclipse.org/emf/2002/Ecore#EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="AirlineCompany" xmi:id="airlineCompany">
      <eStructuralFeatures>
        <eAttribute xmi:id="air_name" name="companyName" eType="http://www.eclipse.org/emf/2002/Ecore#EString"/>
        <eReference xmi:id="air_mother" name="motherCompany" eType="airlineCompany"/>
        <eReference xmi:id="air_daughters" name="daughterCompanies" eType="airlineCompany"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Contract" xmi:id="contract">
      <eStructuralFeatures>
        <eAttribute xmi:id="con_deliveryCond" name="deliveryConditions" eType="http://www.eclipse.org/emf/2002/Ecore#EString"/>
        <eAttribute xmi:id="con_legal" name="legalAspects" eType="http://www.eclipse.org/emf/2002/Ecore#EString"/>
        <eReference xmi:id="con_customer" name="customer" eType="airlineCompany"/>
        <eReference xmi:id="con_salesperson" name="salesperson" eType="employee"/>
        <eReference xmi:id="con_acquisitions" name="acquisitions" eType="acquisition" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Acquisition" xmi:id="acquisition">
      <eStructuralFeatures>
        <eAttribute xmi:id="acq_model" name="airplaneModel" eType="http://www.eclipse.org/emf/2002/Ecore#EString"/>
        <eAttribute xmi:id="acq_price" name="negotiatedPrice" eType="http://www.eclipse.org/emf/2002/Ecore#EDouble"/>
        <eAttribute xmi:id="acq_options" name="optionsCustomizations" eType="http://www.eclipse.org/emf/2002/Ecore#EString"/>
        <eAttribute xmi:id="acq_date" name="deliveryDate" eType="http://www.eclipse.org/emf/2002/Ecore#EDate"/>
      </eStructuralFeatures>
    </eClass>

  </ePackage>
</xmi:XMI>
