<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="ClothingStoreModel" nsURI="clothingstoremodel" nsPrefix="csm">

    <!-- Datatypes -->
    <ecore:EDataType xmi:id="_TimeWithoutDate" name="TimeWithoutDate"/>

    <!-- Classes -->
    <ecore:EClass xmi:id="_RootContainer" name="RootContainer">
      <ecore:EReference xmi:id="_RootContainer_countries" name="countries"
                        eType="#//Country" upperBound="-1" containment="true"/>
      <ecore:EReference xmi:id="_RootContainer_representatives" name="representatives"
                        eType="#//Representative" upperBound="-1" containment="true"/>
      <ecore:EReference xmi:id="_RootContainer_customers" name="customers"
                        eType="#//Customer" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_Country" name="Country">
      <ecore:EAttribute xmi:id="_Country_name" name="name" eType="ecore:EString"/>
      <ecore:EReference xmi:id="_Country_representative" name="representative"
                        eType="#//Representative" upperBound="1"/>
      <ecore:EAttribute xmi:id="_Country_vatRate" name="vatRate" eType="ecore:EDouble"/>
      <ecore:EAttribute xmi:id="_Country_currency" name="currency" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Country_conversionRateToEuro" name="conversionRateToEuro"
                        eType="ecore:EDouble"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_Product" name="Product">
      <ecore:EAttribute xmi:id="_Product_name" name="name" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Product_description" name="description" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Product_netPrice" name="netPrice" eType="ecore:EDouble"/>
      <ecore:EReference xmi:id="_Product_manufacturer" name="manufacturer"
                        eType="#//Manufacturer" upperBound="1"/>
      <ecore:EReference xmi:id="_Product_availableCountries" name="availableCountries"
                        eType="#//Country" upperBound="-1"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_Manufacturer" name="Manufacturer">
      <ecore:EAttribute xmi:id="_Manufacturer_name" name="name" eType="ecore:EString"/>
      <ecore:EReference xmi:id="_Manufacturer_country" name="country"
                        eType="#//Country" upperBound="1"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_Representative" name="Representative">
      <ecore:EAttribute xmi:id="_Representative_firstName" name="firstName" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Representative_lastName" name="lastName" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Representative_socialSecurityNumber" name="socialSecurityNumber"
                        eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Representative_phoneNumber" name="phoneNumber" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Representative_email" name="email" eType="ecore:EString"/>
      <ecore:EReference xmi:id="_Representative_country" name="country"
                        eType="#//Country" upperBound="1"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_Customer" name="Customer">
      <ecore:EAttribute xmi:id="_Customer_name" name="name" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Customer_address" name="address" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Customer_phoneNumber" name="phoneNumber" eType="ecore:EString"/>
      <ecore:EAttribute xmi:id="_Customer_email" name="email" eType="ecore:EString"/>
      <ecore:EReference xmi:id="_Customer_countriesOfResale" name="countriesOfResale"
                        eType="#//Country" upperBound="-1"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_Order" name="Order">
      <ecore:EAttribute xmi:id="_Order_id" name="id" eType="ecore:EString"/>
      <ecore:EReference xmi:id="_Order_product" name="product"
                        eType="#//Product" upperBound="1"/>
      <ecore:EAttribute xmi:id="_Order_quantity" name="quantity" eType="ecore:EInt"/>
      <ecore:EAttribute xmi:id="_Order_orderDate" name="orderDate" eType="ecore:EDate"/>
      <ecore:EAttribute xmi:id="_Order_deliveryDate" name="deliveryDate" eType="ecore:EDate"/>
    </ecore:EClass>

    <!-- Association classes -->
    <ecore:EClass xmi:id="_ProductCountryAvailability" name="ProductCountryAvailability">
      <ecore:EReference xmi:id="_ProductCountryAvailability_product" name="product"
                        eType="#//Product" upperBound="1"/>
      <ecore:EReference xmi:id="_ProductCountryAvailability_country" name="country"
                        eType="#//Country" upperBound="1"/>
    </ecore:EClass>

  </ecore:EPackage>
</xmi:XMI>
