<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.1"
    xmlns:xmi="http://www.omg.org/spec/XMI/2.1"
    xmlns:uml="platform:/plugin/org.eclipse.uml2.common/UML20.ecore#//UML"
    xmi:id="__root__">
    
    <!-- Define the mapping for UML packages -->
    <xmi:XDSMimeAssociation mimeType="ecore"/>
    <xmi:Export version="XMI2.1" specification="UML2.0-XML-METAMODEL/Platform:/plugin/org.eclipse.uml2.common/UML20.ecore">
        <uml:PackageImport xmi:id="_00000000-0000-4000-Y060-000000000041"
            name="UML"
            uri="platform:/plugin/org.eclipse.uml2.common/UML20.ecore#//UML"/>
    </xmi:Export>
    
    <!-- Root container for the E-bike system -->
    <packagedElement xmi:type="uml:Class" name="EBikeSystem">
        
        <!-- Frame Class -->
        <packagedElement xmi:type="uml:Class" name="Frame"/>

        <!-- Motor Class -->
        <packagedElement xmi:type="uml:Class" name="Motor"/>
        
        <!-- Wheel Class -->
        <packagedElement xmi:type="uml:Class" name="Wheel"/>

        <!-- Battery Class -->
        <packagedElement xmi:type="uml:Class" name="Battery">
            <ownedAttribute xmi:id="__energy__" name="storedEnergy"
                type="_20000000-0000-4000-A000-000000000001"/> <!-- Wh stored as String -->
        </packagedElement>

        <!-- DriveSystem Class -->
        <packagedElement xmi:type="uml:Class" name="DriveSystem">
            <ownedAttribute xmi:id="__motorRef_" name="motor"
                type="Motor"/>
        </packagedElement>
        
        <!-- Controller Class with Basic Functionality -->
        <packagedElement xmi:type="uml:Class" name="Controller">
            <ownedOperation xmi:id="__basicFunction__" 
                            name="basicFunctionality()" 
                            visibility="public"/>
        </packagedElement>

        <!-- AdvancedController class which extends Controller -->
        <packagedElement xmi:type="uml:Class" name="AdvancedController"
                         inheritance="{http://www.eclipse.org/uml2/3.0.0/UML}Generalization">
            <owner xmi:type="uml:Namespace" href="#__root__.EBikeSystem"/>
            <supereClass href="#__root__.EBikeSystem.Controller"/>
            <ownedOperation xmi:id="__estimateNextInspectionDateOp__"
                            name="estimateNextInspectionDate()"
                            visibility="public"/>
        </packagedElement>
        
        <!-- EBike Class -->
        <packagedElement xmi:type="uml:Class" name="EBike">
            <ownedAttribute xmi:id="__frameRef_" name="frame"
                type="Frame"/>
            <ownedAttribute xmi:id="__driveSystemRef_" name="driveSystem"
                type="DriveSystem"/>
            <ownedAttribute xmi:id="__controllerRef_" name="controller"
                type="Controller"/>
            <ownedAttribute xmi:id="_batteryAssociation_" 
                            earchType="uml:Association" 
                            href="#BatteryOnEBike"/>
        </packagedElement>

        <!-- Association between Battery and EBike -->
        <packagedElement xmi:type="uml:Association" name="BatteryOnEBike">
            <memberEnd xmi:id="__eBikeAssocEnd__" type="EBike"/>
            <memberEnd xmi:id="__batteryAssocEnd__" type_="Battery">
                <lower>0..1</lower>
                <upper>1</upper>
                <aggregation kind="composite"/>
            </memberEnd>
        </packagedElement>

        <!-- Association of Wheels into Frame -->
        <packagedElement xmi:type="uml:Association" name="WheelsInFrame">
            <memberEnd xmi:id="__frameMemberEnd__" type_="Frame"/>
            <memberEnd xmi:id="__wheelsMemberEnd__" type_="Wheel">
                <lower>2</lower>
                <upper>2</upper>
                <aggregation kind="composite"/>
            </memberEnd>
        </packagedElement>

        <!-- Controller States Enumeration -->
        <packagedElement xmi:type="uml:Enumeration" name="ControllerState"
                         xmi:id="_state_enum__"> 
            <literalLiteral name="OFF"/>
            <literalLiteral name="ON"/>
            <literalLiteral name="CHARGING"/>
        </packagedElement>

    </packagedElement>
    
</uml:Model>
