<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.5" xmlns:xmi="http://www.omg.org/XMI" xmlns:euml="http://helpinghandsstore.example.com/ehandingover">
  <euml:Ecore>
    <!-- Define a unique EPacakge URI -->
    <euml:EPackage uri="http://helpinghandsstore.example.com/EH2SEncoreModeling" nsPrefix="EH2S">
      <euml:Class eId="_Resident">
        <euml:name>Resident</euml:name>
        <euml:attributes>
          <euml:EStructuralFeature eId="_name" name="name" type="String"/>
          <euml:EStructuralFeature eId="_address" name="address" type="String"/>
          <euml:EStructuralFeature eId="_phoneNumber" name="phoneNumber" type="String"/>
          <euml:EStructuralFeature eId="_emailAddress" name="emailAddress" type="String"/>
        </euml:attributes>
      </euml:Class>

      <euml:DataType eId="_LocalTimeType">
        <euml:name>LocalTime</euml:name>
        
        <!-- Use Ecore base package for time representation -->
        <euml:eSuperTypes xmi:type="euml:EClassifier" href="http://www.eclipse.org/emf/2002/Ecore#//EDataType"/>
      </euml:DataType>

      <euml:Class eId="_PickupRequest">
        <euml:name>PickupRequest</euml:name>
        <euml:attributes>
          <euml:EStructuralFeature eId="_description" name="description" type="String"/>
          <euml:EStructuralFeature eId="_scheduledTime" name="scheduledTime" type="_LocalTimeType"/>
        </euml:attributes>
      </euml:Class>

      <euml:Association eId="__residency">
        <euml:name>residency</euml:name>
        <euml:endTypes xmi:type="euml:EClassifier" href="#_Resident" reference="_Vehicle"/>
      </euml:Association>

      <euml:Class eId="_PickupRoute">
        <euml:name>PickupRoute</euml:name>
        <!-- Add attributes or operations as needed -->
      </euml:Class>

      <euml:Class eId="_Vehicle">
        <euml:name>Vehicle</euml:name>
        <!-- Define the relationship with PickupRequest -->
      </euml:Class>

      <euml:Association eId="__pickups">
        <euml:name>_pickups</euml:name>
        <euml:endTypes xmi:type="euml:EClassifier" href="#_PickupRequest"/>
        <euml:eAnnotations>
          <euml:EArc _Vehicle__end="1" containment="true">
            <euml:EStructuralFeatures multiplicity="*" eOpposite="#_Vehicles_has_pickups"/>
          </euml:EArc>
        </euml:eAnnotations>
      </euml:Association>

      <euml:EClass eId="_Vehicle_hasPickupRequest">
        <euml:name>PickupRouteHasVehicle</euml:name>
        <!-- Reference the super types of PickupRoute and Vehicle -->
        <euml:superTypes xmi:type="euml:EClassifier" href="#_Vehicle"/>
      </euml:EClass>

      <euml:Association eId="__vehicleRoute">
        <euml:name>route</euml:name>
        <euml:endTypes xmi:type="euml:EClassifier" href="#_Vehicle_hasPickupRequest"/>
      </euml:Association>

      <!-- Root Container -->
      <euml:Class eId="_H2SContainer">
        <euml:name>H2SContainer</euml:name>
        <euml:attributes/>
        <!-- Associations to include all elements -->
      </euml:Class>
      
    </euml:EPackage>
  </euml:Ecore>
</xmi:XMI>
