<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="filmstudio" nsURI="http://www.example.org/filmstudio" nsPrefix="filmstudio">
  <eClassifiers xsi:type="ecore:EEnum" name="Genre">
    <eLiterals name="Thriller"/>
    <eLiterals name="Action" value="1"/>
    <eLiterals name="Horror" value="2"/>
    <eLiterals name="Comedy" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filmSet" eType="#//FilmSet"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreativeEmployee" abstract="true" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oscar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Technician" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfActivity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Director" eSuperTypes="#//CreativeEmployee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assistentName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedScreenplays"
        upperBound="-1" eType="#//Screenplay" eOpposite="#//Screenplay/implementingDirector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//CreativeEmployee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="education" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readScreenplays" upperBound="-1"
        eType="#//Screenplay" eOpposite="#//Screenplay/readingActors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Screenplay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfScenes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementingDirector" eType="#//Director"
        eOpposite="#//Director/implementedScreenplays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readingActors" upperBound="-1"
        eType="#//Actor" eOpposite="#//Actor/readScreenplays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenplayAuthor" eType="#//ScreenplayAuthor"
        eOpposite="#//ScreenplayAuthor/createdScreenplays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedOnBook" eType="#//Book"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedOnConcept" eType="#//Concept"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilmSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="films" upperBound="-1"
        eType="#//Film" eOpposite="#//Film/filmSets"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Film">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genre" eType="#//Genre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filmSets" upperBound="-1"
        eType="#//FilmSet" eOpposite="#//FilmSet/films"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mostSuccessful" eType="#//ScreenplayAuthor"
        eOpposite="#//ScreenplayAuthor/mostSuccessfulFilm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenplay" lowerBound="1"
        eType="#//Screenplay" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScreenplayAuthor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdScreenplays" upperBound="-1"
        eType="#//Screenplay" eOpposite="#//Screenplay/screenplayAuthor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mostSuccessfulFilm" eType="#//Film"
        eOpposite="#//Film/mostSuccessful"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Book">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Concept"/>
  <eClassifiers xsi:type="ecore:EClass" name="Studio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filmSets" upperBound="-1"
        eType="#//FilmSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="films" upperBound="-1"
        eType="#//Film" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenplayAuthors" upperBound="-1"
        eType="#//ScreenplayAuthor" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
