org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: org.xml.sax.SAXParseException; publicId: file:/Volumes/Sources/goldenuml-emfatic/modelset/School/nl2ecore/phi4:14b/generated.ecore; systemId: file:/Volumes/Sources/goldenuml-emfatic/modelset/School/nl2ecore/phi4:14b/generated.ecore; lineNumber: 1; columnNumber: 39; Element type "ecore:EClass" must be followed by either attribute specifications, ">" or "/>".
