<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="Musicmatic" nsURI="http://musicmatic/model" nsPrefix="musicmatic" xmi:version="2.0">

    <!-- Root Container -->
    <ecore:EClass name="SystemContainer">
      <ecore:EReference name="songs" eType="#//Song" upperBound="-1" containment="true"/>
      <ecore:EReference name="artists" eType="#//Artist" upperBound="-1" containment="true"/>
      <ecore:EReference name="users" eType="#//User" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Artist -->
    <ecore:EClass name="Artist">
      <ecore:EAttribute name="dateOfBirth" eType="ecore:EDate"/>
      <ecore:EAttribute name="name" eType="ecore:EString"/>
      <ecore:EAttribute name="websiteUrl" eType="ecore:EString"/>
    </ecore:EClass>

    <!-- Song -->
    <ecore:EClass name="Song">
      <ecore:EAttribute name="title" eType="ecore:EString"/>
      <ecore:EAttribute name="year" eType="ecore:EInt"/>
      <ecore:EAttribute name="length" eType="#//TimeDuration"/>
      <ecore:EAttribute name="genre" eType="ecore:EString"/>

      <!-- Relationships -->
      <ecore:EReference name="artist" eType="#//Artist" lowerBound="1"/>
    </ecore:EClass>

    <!-- User (Abstract Class) -->
    <ecore:EClass name="User">
      <ecore:EAttribute name="id" eType="ecore:EString"/>
      <ecore:EAttribute name="name" eType="ecore:EString"/>
      <ecore:EAttribute name="address" eType="ecore:EString"/>

      <!-- Relationships -->
    </ecore:EClass>

    <!-- Regular User -->
    <ecore:EClass name="RegularUser">
      <ecore:EGenericSuperType type="#//User"/>
    </ecore:EClass>

    <!-- Business User -->
    <ecore:EClass name="BusinessUser">
      <ecore:EGenericSuperType type="#//User"/>
      <ecore:EAttribute name="vatNumber" eType="ecore:EString"/>
    </ecore:EClass>

    <!-- Single and Hit (Subtypes of Song)-->
    <ecore:EClass name="Single">
      <ecore:EGenericSuperType type="#//Song"/>
    </ecore:EClass>

    <ecore:EClass name="Hit">
      <ecore:EGenericSuperType type="#//Song"/>
      <ecore:EReference name="album" eType="#//Album"/>
      <ecore:EAttribute name="trackNumber" eType="ecore:EInt"/> <!-- Track number in the album -->
    </ecore:EClass>

    <!-- Album -->
    <ecore:EClass name="Album">
      <ecore:EAttribute name="title" eType="ecore:EString"/>

      <!-- Relationships -->
      <ecore:EReference name="hits" eType="#//Hit" upperBound="-1" containment="true"/>
      <ecore:EReference name="suggestedToUsers" eType="#//RegularUser" upperBound="-1"/> <!-- Suggestions to other users -->
    </ecore:EClass>

    <!-- Custom Datatype for Time Duration (using java.time.Duration)-->
    <ecore:EDataType name="TimeDuration">
      <ecore:EAnnotation source="http://www.eclipse.org/emf/2002/Ecore" details="platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EJavaClass"/>
    </ecore:EDataType>

  </ecore:EPackage>
</xmi:XMI>
