<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="labSystem"
    nsURI="http://www.example.org/labSystem"
    nsPrefix="labSystem">

  <!-- Custom datatype for time without date -->
  <eClassifiers xsi:type="ecore:EDataType" name="LocalTime"
      instanceClassName="java.time.LocalTime"/>

  <!-- Enumerations -->
  <eClassifiers xsi:type="ecore:EEnum" name="Interval">
    <eLiterals name="Weekly"/>
    <eLiterals name="Monthly"/>
    <eLiterals name="EveryHalfYear"/>
    <eLiterals name="Yearly"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="AccessType">
    <eLiterals name="Reservable"/>
    <eLiterals name="WalkIn"/>
    <eLiterals name="DropOff"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="DayOfWeek">
    <eLiterals name="Monday"/>
    <eLiterals name="Tuesday"/>
    <eLiterals name="Wednesday"/>
    <eLiterals name="Thursday"/>
    <eLiterals name="Friday"/>
    <eLiterals name="Saturday"/>
    <eLiterals name="Sunday"/>
  </eClassifiers>

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="LabSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons"
        eType="#//Person" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personRoles"
        eType="#//PersonRole" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="labs"
        eType="#//Lab" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testTypes"
        eType="#//TestType" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests"
        eType="#//Test" upperBound="-1" containment="true"/>
  </eClassifiers>

  <!-- Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles"
        eType="#//PersonRole" upperBound="2" eOpposite="#//PersonRole/person"/>
  </eClassifiers>

  <!-- PersonRole (abstract) -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonRole" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        eType="#//Person" eOpposite="#//Person/roles"/>
  </eClassifiers>

  <!-- Patient -->
  <eClassifiers xsi:type="ecore:EClass" name="Patient" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisitions"
        eType="#//Requisition" upperBound="-1"
        containment="true" eOpposite="#//Requisition/patient"/>
  </eClassifiers>

  <!-- Doctor -->
  <eClassifiers xsi:type="ecore:EClass" name="Doctor" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisitions"
        eType="#//Requisition" upperBound="-1" eOpposite="#//Requisition/doctor"/>
  </eClassifiers>

  <!-- Requisition -->
  <eClassifiers xsi:type="ecore:EClass" name="Requisition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectiveDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetitionCount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repetitionInterval"
        eType="#//Interval"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient"
        eType="#//Patient" eOpposite="#//Patient/requisitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doctor"
        eType="#//Doctor" eOpposite="#//Doctor/requisitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lab"
        eType="#//Lab" eOpposite="#//Lab/requisitions"/>
    <!-- Association class: Requisition links to Appointment -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="appointment"
        eType="#//Appointment" eOpposite="#//Appointment/requisition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificTests"
        eType="#//SpecificTest" upperBound="-1"
        containment="true" eOpposite="#//SpecificTest/requisition"/>
  </eClassifiers>

  <!-- Appointment (association class between Lab and Requisition) -->
  <eClassifiers xsi:type="ecore:EClass" name="Appointment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="confirmation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime"
        eType="#//LocalTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime"
        eType="#//LocalTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lab"
        eType="#//Lab" eOpposite="#//Lab/appointments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisition"
        eType="#//Requisition" eOpposite="#//Requisition/appointment"/>
  </eClassifiers>

  <!-- SpecificTest -->
  <eClassifiers xsi:type="ecore:EClass" name="SpecificTest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisition"
        eType="#//Requisition" eOpposite="#//Requisition/specificTests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testResult"
        eType="#//TestResult" upperBound="1"
        containment="true" eOpposite="#//TestResult/specificTest"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="test"
        eType="#//Test" eOpposite="#//Test/specificTests"/>
  </eClassifiers>

  <!-- TestResult -->
  <eClassifiers xsi:type="ecore:EClass" name="TestResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="result"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="report"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificTest"
        eType="#//SpecificTest" eOpposite="#//SpecificTest/testResult"/>
  </eClassifiers>

  <!-- BusinessHour -->
  <eClassifiers xsi:type="ecore:EClass" name="BusinessHour">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dayOfWeek"
        eType="#//DayOfWeek"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime"
        eType="#//LocalTime"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime"
        eType="#//LocalTime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lab"
        eType="#//Lab" eOpposite="#//Lab/businessHours"/>
  </eClassifiers>

  <!-- Lab -->
  <eClassifiers xsi:type="ecore:EClass" name="Lab">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="registrationNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeCancelFee"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisitions"
        eType="#//Requisition" upperBound="-1" eOpposite="#//Requisition/lab"/>
    <!-- Association class end -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="appointments"
        eType="#//Appointment" upperBound="-1"
        containment="true" eOpposite="#//Appointment/lab"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessHours"
        eType="#//BusinessHour" upperBound="7"
        containment="true" eOpposite="#//BusinessHour/lab"/>
  </eClassifiers>

  <!-- Test -->
  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificTests"
        eType="#//SpecificTest" upperBound="-1" eOpposite="#//SpecificTest/test"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="testType"
        eType="#//TestType" eOpposite="#//TestType/tests"/>
  </eClassifiers>

  <!-- TestType -->
  <eClassifiers xsi:type="ecore:EClass" name="TestType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationAdditive"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="access"
        eType="#//AccessType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests"
        eType="#//Test" upperBound="-1" eOpposite="#//Test/testType"/>
  </eClassifiers>

</ecore:EPackage>
