<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="labmodel"
    nsURI="http://www.example.org/labmodel"
    nsPrefix="labmodel">

  <!-- Enumerations -->

  <eClassifiers xsi:type="ecore:EEnum" name="Interval">
    <eLiterals name="Weekly"/>
    <eLiterals name="Monthly"/>
    <eLiterals name="EveryHalfYear"/>
    <eLiterals name="Yearly"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="AccessType">
    <eLiterals name="Reservable"/>
    <eLiterals name="WalkIn"/>
    <eLiterals name="DropOff"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="DayOfWeek">
    <eLiterals name="Monday"/>
    <eLiterals name="Tuesday"/>
    <eLiterals name="Wednesday"/>
    <eLiterals name="Thursday"/>
    <eLiterals name="Friday"/>
    <eLiterals name="Saturday"/>
    <eLiterals name="Sunday"/>
  </eClassifiers>

  <!-- Classes -->

  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PhoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Person "1" - "0..2" PersonRole -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles"
        eType="#//PersonRole"
        upperBound="2"
        eOpposite="#//PersonRole/person"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PersonRole" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="IdNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- PersonRole back-reference to Person -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        eType="#//Person"
        eOpposite="#//Person/roles"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Patient" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DateOfBirth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Patient "1" - "*" Requisition -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisitions"
        eType="#//Requisition"
        upperBound="-1"
        eOpposite="#//Requisition/patient"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Doctor" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Doctor "1" - "*" Requisition -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisitions"
        eType="#//Requisition"
        upperBound="-1"
        eOpposite="#//Requisition/doctor"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Requisition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="EffectiveDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RepetitionCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RepetitionInterval" eType="#//Interval"/>
    <!-- Back-reference to Patient -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient"
        eType="#//Patient"
        eOpposite="#//Patient/requisitions"/>
    <!-- Back-reference to Doctor -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="doctor"
        eType="#//Doctor"
        eOpposite="#//Doctor/requisitions"/>
    <!-- Back-reference to Lab (via association class Appointment) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="labAppointments"
        eType="#//Appointment"
        upperBound="-1"
        eOpposite="#//Appointment/requisition"/>
    <!-- Requisition "1" - "*" SpecificTest -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificTests"
        eType="#//SpecificTest"
        upperBound="-1"
        eOpposite="#//SpecificTest/requisition"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TestResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Result" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Report" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Back-reference to SpecificTest -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificTest"
        eType="#//SpecificTest"
        eOpposite="#//SpecificTest/testResult"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="SpecificTest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- SpecificTest "1" - "0..1" TestResult -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="testResult"
        eType="#//TestResult"
        upperBound="1"
        eOpposite="#//TestResult/specificTest"/>
    <!-- Back-reference to Requisition -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisition"
        eType="#//Requisition"
        eOpposite="#//Requisition/specificTests"/>
    <!-- SpecificTest "*" - "1" Test -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="test"
        eType="#//Test"
        eOpposite="#//Test/specificTests"/>
  </eClassifiers>

  <!-- Association class between Lab and Requisition -->
  <eClassifiers xsi:type="ecore:EClass" name="Appointment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Confirmation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Reference to Lab (replaces Lab end of association) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="lab"
        eType="#//Lab"
        eOpposite="#//Lab/appointments"/>
    <!-- Reference to Requisition (replaces Requisition end of association) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="requisition"
        eType="#//Requisition"
        eOpposite="#//Requisition/labAppointments"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="BusinessHour">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DayOfWeek" eType="#//DayOfWeek"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- BusinessHour "7" - "1" Lab -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="lab"
        eType="#//Lab"
        eOpposite="#//Lab/businessHours"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Lab">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RegistrationNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ChangeCancelFee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <!-- Lab "1" - "7" BusinessHour -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessHours"
        eType="#//BusinessHour"
        upperBound="7"
        lowerBound="7"
        eOpposite="#//BusinessHour/lab"/>
    <!-- Lab end of association with Requisition via Appointment -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="appointments"
        eType="#//Appointment"
        upperBound="-1"
        eOpposite="#//Appointment/lab"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Test">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Test "*" - "1" TestType -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="testType"
        eType="#//TestType"
        eOpposite="#//TestType/tests"/>
    <!-- Back-reference to SpecificTest -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="specificTests"
        eType="#//SpecificTest"
        upperBound="-1"
        eOpposite="#//SpecificTest/test"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TestType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DurationAdditive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Access" eType="#//AccessType"/>
    <!-- Back-reference to Test -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="tests"
        eType="#//Test"
        upperBound="-1"
        eOpposite="#//Test/testType"/>
  </eClassifiers>

</ecore:EPackage>
