<?xml version="1.0" encoding="UTF-8"?>
<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore Ecore.xsd"
       xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore#/"
       xmlns:eAnnotations="http://www.eclipse.org/emf/2002/Ecore#/...">
  <!-- Package definition -->
  <ePackage xsi:type="ecore:EPackage" 
            name="HouseSystem" 
            uri="http://www.example.org/HouseSystem"
            xmi:id="houseSystem">
    <eAnnotations source="genmodel">
      <details key="name" value="HouseSystem"/>
      <details key="identifier" value="houseSystem"/>
      <details key="version" value="1.0.0"/>
    </eAnnotations>

    <!-- Root container class that owns everything else -->
    <eClassifiers xsi:type="ecore:EClass" name="HouseRegistry">
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="houses"
                           upper="-1"
                           eType="#//House"
                           containment="true"/>
    </eClassifiers>

    <!-- Main classes -->
    <eClassifiers xsi:type="ecore:EClass" name="House">
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="address"
                           eType="#//String"/>
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="buildingMaterial"
                           eType="+java.lang.String"/>
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="basement"
                           eType="#//Basement"
                           lower="0" upper="1"/>

      <!-- Jobs performed by companies in this house -->
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="jobs"
                           eType="#//Job"
                           lower="0" upper="-1"
                           containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Basement">
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="size"
                           eType="+java.lang.Double"/>
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="name"
                           eType="#//String"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="EarthBasement"
                  eSuperTypes="#//Basement">
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="humidityLevel"
                           eType="+java.lang.Double"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="ConcreteBasement"
                  eSuperTypes="#//Basement"/>

    <eClassifiers xsi:type="ecore:EClass" name="SemiDetachedHouse"
                  eSuperTypes="#//House">
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="hasGarden"
                           eType="+java.lang.Boolean"/>
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="windowCount"
                           eType="+java.lang.Integer"/>

      <!-- Either two carports or a garage -->
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="carports"
                           eType="#//Carport"
                           lower="0" upper="1"
                           containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="garage"
                           eType="#//Garage"
                           lower="0" upper="1"
                           containment="true"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Carport">
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="isDouble"
                           eType="+java.lang.Boolean"/>
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="hasFlatRoof"
                           eType="+java.lang.Boolean"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Garage">
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="hasAutomaticDoor"
                           eType="+java.lang.Boolean"/>
    </eClassifiers>

    <eClassifiers xsi:type="ecore:EClass" name="Company">
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="name"
                           eType="#//String"/>
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="address"
                           eType="#//String"/>

      <!-- Jobs performed by this company -->
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="jobs"
                           eType="#//Job"
                           lower="0" upper="-1"
                           containment="true"/>
    </eClassifiers>

    <!-- Job log entry connecting a house and a company -->
    <eClassifiers xsi:type="ecore:EClass" name="Job">
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="house"
                           eType="#//House"
                           lower="1" upper="1"/>
      <eStructuralFeatures xsi:type="ecore:EReference"
                           name="company"
                           eType="#//Company"
                           lower="1" upper="1"/>
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="hoursWorked"
                           eType="+java.time.Duration"/>
      <eStructuralFeatures xsi:type="ecore:ENavigationFeature"
                           name="agreedPrice"
                           eType="+java.lang.Double"/>
    </eClassifiers>

    <!-- String alias -->
    <eClassifiers xsi:type="ecore:EDataType" name="String"
                  instanceClassName="java.lang.String"/>

  </ePackage>
</model>
