<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="labtracker" nsURI="http://www.example.org/labtracker">
    
    <!-- Root Container -->
    <eClass name="LabTrackerSystem">
      <eStructuralFeatures>
        <eReference name="doctors" reference="Doctor"/>
        <eReference name="patients" reference="Patient"/>
        <eReference name="requisitions" reference="Requisition"/>
        <eReference name="labs" reference="Lab"/>
        <eReference name="testDefinitions" reference="TestDefinition"/>
        <eReference name="appointments" reference="Appointment"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Doctor">
      <eStructuralFeatures>
        <eAttribute name="practitionerNumber" eType="ecore.EString"/>
        <eAttribute name="signature" eType="ecore.EString"/>
        <eAttribute name="fullName" eType="ecore.EString"/>
        <eAttribute name="address" eType="ecore.EString"/>
        <eAttribute name="phoneNumber" eType="ecore.EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Patient">
      <eStructuralFeatures>
        <eAttribute name="healthNumber" eType="ecore.EString"/>
        <eAttribute name="firstName" eType="ecore.EString"/>
        <eAttribute name="lastName" eType="ecore.EString"/>
        <eAttribute name="dateOfBirth" eType="ecore.EDate"/>
        <eAttribute name="address" eType="ecore.EString"/>
        <eAttribute name="phoneNumber" eType="ecore.EString"/>
      </eStructuralFeatures>
    </eClass>

    <eEnum name="RepetitionInterval">
      <eLiterals name="Weekly"/>
      <eLiterals name="Monthly"/>
      <eLiterals name="HalfYearly"/>
      <eLiterals name="Yearly"/>
    </eEnum>

    <eClass name="Requisition">
      <eStructuralFeatures>
        <eAttribute name="validDate" eType="ecore.EDate"/>
        <eAttribute name="repetitionCount" eType="ecore.EInt"/>
        <eAttribute name="interval" eType="RepetitionInterval"/>
        <eReference name="doctor" reference="Doctor"/>
        <eReference name="patient" reference="Patient"/>
        <!-- Containment reference to the association class -->
        <eReference name="requestedTests" reference="RequestedTest"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Association Class for Requisition and TestDefinition -->
    <eClass name="RequestedTest">
      <eStructuralFeatures>
        <eReference name="requisition" reference="Requisition"/>
        <eReference name="testDefinition" reference="TestDefinition"/>
        <eAttribute name="resultValue" eType="ResultValue"/>
        <eAttribute name="report" eType="ecore.EString"/>
      </eStructuralFeatures>
    </eClass>

    <eEnum name="AppointmentType">
      <eLiterals name="AppointmentRequired"/>
      <eLiterals name="WalkInOnly"/>
      <eLiterals name="SampleDropOff"/>
    </eEnum>

    <eClass name="TestDefinition">
      <eStructuralFeatures>
        <eAttribute name="name" eType="ecore.EString"/>
        <eAttribute name="duration" eType="Duration"/>
        <eAttribute name="testGroup" eType="ecore.EString"/>
        <eAttribute name="appointmentType" eType="AppointmentType"/>
        <!-- Non-containment reference to the association class -->
        <eReference name="requestedTests" reference="RequestedTest"/>
      </eStructuralFeatures>
    </eClass>

    <eEnum name="ResultValue">
      <eLiterals name="Positive"/>
      <eLiterals name="Negative"/>
    </eEnum>

    <eEnum name="DayOfWeek">
      <eLiterals name="Monday"/>
      <eLiterals name="Tuesday"/>
      <eLiterals name="Wednesday"/>
      <eLiterals name="Thursday"/>
      <eLiterals name="Friday"/>
      <eLiterals name="Saturday"/>
      <eLiterals name="Sunday"/>
    </eEnum>

    <eClass name="BusinessHour">
      <eStructuralFeatures>
        <eAttribute name="dayOfWeek" eType="DayOfWeek"/>
        <eAttribute name="startTime" eType="LocalTime"/>
        <eAttribute name="endTime" eType="LocalTime"/>
        <eReference name="lab" reference="Lab"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Lab">
      <eStructuralFeatures>
        <eAttribute name="address" eType="ecore.EString"/>
        <eAttribute name="registrationNumber" eType="ecore.EString"/>
        <eAttribute name="cancellationFee" eType="ecore.EDouble"/>
        <eReference name="businessHours" reference="BusinessHour"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Appointment">
      <eStructuralFeatures>
        <eAttribute name="confirmationNumber" eType="ecore.EString"/>
        <eAttribute name="date" eType="ecore.EDate"/>
        <eAttribute name="startTime" eType="LocalTime"/>
        <eAttribute name="endTime" eType="LocalTime"/>
        <eReference name="patient" reference="Patient"/>
        <eReference name="requisition" reference="Requisition"/>
        <eReference name="lab" reference="Lab"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Custom Datatypes for java.time package -->
    <eDataType name="LocalTime" uri="java.time.LocalTime"/>
    <eDataType name="Duration" uri="java.time.Duration"/>

  </ePackage>
</xmi:XMI>
