<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="repairShopPackage"
    nsURI="http://www.example.com/repairShopPackage"
    nsPrefix="repairShopPackage">

  <!-- Custom datatypes for Date and Time -->
  <eClassifiers xsi:type="ecore:EDataType" name="Date"
      instanceClassName="java.time.LocalDate"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Time"
      instanceClassName="java.time.LocalTime"/>

  <!-- Enum: VehicleType -->
  <eClassifiers xsi:type="ecore:EEnum" name="VehicleType">
    <eLiterals name="RefrigeratedTruck"/>
    <eLiterals name="SmallVan"/>
    <eLiterals name="LoadingPlatform"/>
    <eLiterals name="BoxTruck"/>
  </eClassifiers>

  <!-- Class: RepairShop -->
  <eClassifiers xsi:type="ecore:EClass" name="RepairShop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairs"
        eType="#//Repair"
        upperBound="-1"
        containment="true"
        eOpposite="#//Repair/repairShop"/>
  </eClassifiers>

  <!-- Class: Repair -->
  <eClassifiers xsi:type="ecore:EClass" name="Repair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairShop"
        eType="#//RepairShop"
        eOpposite="#//RepairShop/repairs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle"
        eType="#//Vehicle"
        eOpposite="#//Vehicle/repairs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee"
        eType="#//Employee"
        eOpposite="#//Employee/repairs"/>
  </eClassifiers>

  <!-- Class: Vehicle -->
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licensePlateNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mileage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"
        eType="#//VehicleType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairs"
        eType="#//Repair"
        upperBound="-1"
        eOpposite="#//Repair/vehicle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order"
        upperBound="-1"
        eOpposite="#//Order/vehicle"/>
  </eClassifiers>

  <!-- Class: Order -->
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packetSize"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date"
        eType="#//Date"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime"
        eType="#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime"
        eType="#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pickUpAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle"
        eType="#//Vehicle"
        eOpposite="#//Vehicle/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver"
        eType="#//Driver"
        eOpposite="#//Driver/orders"/>
    <!-- XOR: either administrationEmployee or partnerFirm, not both -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="administrationEmployee"
        eType="#//AdministrationEmployee"
        upperBound="1"
        eOpposite="#//AdministrationEmployee/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partnerFirm"
        eType="#//PartnerFirm"
        upperBound="1"
        eOpposite="#//PartnerFirm/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdBy"
        eType="#//Planner"
        eOpposite="#//Planner/createdOrders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer"
        eType="#//Customer"
        eOpposite="#//Customer/orders"/>
  </eClassifiers>

  <!-- Abstract Class: Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairs"
        eType="#//Repair"
        upperBound="-1"
        eOpposite="#//Repair/employee"/>
  </eClassifiers>

  <!-- Class: Driver (extends Employee) -->
  <eClassifiers xsi:type="ecore:EClass" name="Driver" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order"
        upperBound="-1"
        eOpposite="#//Order/driver"/>
  </eClassifiers>

  <!-- Abstract Class: OtherEmployee (extends Employee) -->
  <eClassifiers xsi:type="ecore:EClass" name="OtherEmployee" abstract="true"
      eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class: Planner (extends OtherEmployee) -->
  <eClassifiers xsi:type="ecore:EClass" name="Planner" eSuperTypes="#//OtherEmployee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdOrders"
        eType="#//Order"
        upperBound="-1"
        eOpposite="#//Order/createdBy"/>
  </eClassifiers>

  <!-- Class: AdministrationEmployee (extends OtherEmployee) -->
  <eClassifiers xsi:type="ecore:EClass" name="AdministrationEmployee"
      eSuperTypes="#//OtherEmployee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfActivity"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order"
        upperBound="-1"
        eOpposite="#//Order/administrationEmployee"/>
  </eClassifiers>

  <!-- Class: PartnerFirm -->
  <eClassifiers xsi:type="ecore:EClass" name="PartnerFirm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order"
        upperBound="-1"
        eOpposite="#//Order/partnerFirm"/>
  </eClassifiers>

  <!-- Class: Customer -->
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order"
        upperBound="-1"
        eOpposite="#//Order/customer"/>
  </eClassifiers>

</ecore:EPackage>
