<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="repairAndDelivery"
    nsURI="http://www.example.org/repairAndDelivery"
    nsPrefix="repairAndDelivery">

  <!-- Enum: VehicleType -->
  <eClassifiers xsi:type="ecore:EEnum" name="VehicleType">
    <eLiterals name="RefrigeratedTruck"/>
    <eLiterals name="SmallVan" value="1"/>
    <eLiterals name="LoadingPlatform" value="2"/>
    <eLiterals name="BoxTruck" value="3"/>
  </eClassifiers>

  <!-- Class: RepairShop -->
  <eClassifiers xsi:type="ecore:EClass" name="RepairShop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairs" lowerBound="1" upperBound="-1"
        eType="#//Repair" containment="true" eOpposite="#//Repair/repairShop"/>
  </eClassifiers>

  <!-- Class: Repair -->
  <eClassifiers xsi:type="ecore:EClass" name="Repair">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairShop" lowerBound="1" upperBound="1"
        eType="#//RepairShop" eOpposite="#//RepairShop/repairs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1" upperBound="1"
        eType="#//Vehicle" eOpposite="#//Vehicle/repairs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employee" lowerBound="1" upperBound="1"
        eType="#//Employee" eOpposite="#//Employee/repairs"/>
  </eClassifiers>

  <!-- Class: Vehicle -->
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="licensePlateNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mileage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//VehicleType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairs" upperBound="-1"
        eType="#//Repair" eOpposite="#//Repair/vehicle"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" lowerBound="1" upperBound="-1"
        eType="#//Order" eOpposite="#//Order/vehicle"/>
  </eClassifiers>

  <!-- Class: Order -->
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packetSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pickUpAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle" lowerBound="1" upperBound="1"
        eType="#//Vehicle" eOpposite="#//Vehicle/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver" lowerBound="1" upperBound="1"
        eType="#//Driver" eOpposite="#//Driver/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdByPlanner" lowerBound="1" upperBound="1"
        eType="#//Planner" eOpposite="#//Planner/createdOrders"/>
    <!-- XOR: either administrationEmployee or partnerFirm, but not both -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="administrationEmployee" lowerBound="0" upperBound="1"
        eType="#//AdministrationEmployee" eOpposite="#//AdministrationEmployee/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partnerFirm" lowerBound="0" upperBound="1"
        eType="#//PartnerFirm" eOpposite="#//PartnerFirm/orders"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" lowerBound="1" upperBound="1"
        eType="#//Customer" eOpposite="#//Customer/orders"/>
  </eClassifiers>

  <!-- Abstract Class: Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repairs" upperBound="-1"
        eType="#//Repair" eOpposite="#//Repair/employee"/>
  </eClassifiers>

  <!-- Class: Driver (extends Employee) -->
  <eClassifiers xsi:type="ecore:EClass" name="Driver" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" lowerBound="1" upperBound="-1"
        eType="#//Order" eOpposite="#//Order/driver"/>
  </eClassifiers>

  <!-- Abstract Class: OtherEmployee (extends Employee) -->
  <eClassifiers xsi:type="ecore:EClass" name="OtherEmployee" abstract="true" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class: Planner (extends OtherEmployee) -->
  <eClassifiers xsi:type="ecore:EClass" name="Planner" eSuperTypes="#//OtherEmployee">
    <eStructuralFeatures xsi:type="ecore:EReference" name="createdOrders" lowerBound="1" upperBound="-1"
        eType="#//Order" eOpposite="#//Order/createdByPlanner"/>
  </eClassifiers>

  <!-- Class: AdministrationEmployee (extends OtherEmployee) -->
  <eClassifiers xsi:type="ecore:EClass" name="AdministrationEmployee" eSuperTypes="#//OtherEmployee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfActivity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" upperBound="-1"
        eType="#//Order" eOpposite="#//Order/administrationEmployee"/>
  </eClassifiers>

  <!-- Class: PartnerFirm -->
  <eClassifiers xsi:type="ecore:EClass" name="PartnerFirm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" upperBound="-1"
        eType="#//Order" eOpposite="#//Order/partnerFirm"/>
  </eClassifiers>

  <!-- Class: Customer -->
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" lowerBound="1" upperBound="-1"
        eType="#//Order" eOpposite="#//Order/customer"/>
  </eClassifiers>

</ecore:EPackage>
