<xml version="1.0" encoding="UTF-8"?>
<EPackage xmlns="http://www.eclipse.org/emf/2003/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <name>BoeingModel</name>
  <eClassifiers>
    <!-- Root container class -->
    <eClass name="BoeingSystem">
      <eStructuralFeatures>
        <eReference name="contracts" type="Contract" upperBound="-1" containment="true"/>
        <eReference name="airlineCompanies" type="AirlineCompany" upperBound="-1" containment="true"/>
        <eReference name="salespeople" type="Employee" upperBound="-1" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Classes -->
    <eClass name="Contract">
      <eStructuralFeatures>
        <eAttribute name="contractId" type="String" unique="true" lowerBound="1"/>
        <eReference name="airlineCompany" type="AirlineCompany" lowerBound="1"/>
        <eReference name="salesperson" type="Employee" lowerBound="1"/>
        <eReference name="acquisitions" type="Acquisition" upperBound="-1" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="AirlineCompany">
      <eStructuralFeatures>
        <eAttribute name="name" type="String" lowerBound="1"/>
        <eReference name="parentCompany" type="AirlineCompany" upperBound="1"/>
        <eReference name="daughterCompanies" type="AirlineCompany" upperBound="-1" containment="true"/>
        <eReference name="contracts" type="Contract" upperBound="-1" opposite="airlineCompany"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Employee">
      <eStructuralFeatures>
        <eAttribute name="employeeId" type="String" unique="true" lowerBound="1"/>
        <eReference name="managedContracts" type="Contract" upperBound="-1" opposite="salesperson"/>
        <eOperation name="assignToContract">
          <eTypeParameters/>
          <eParameters>
            <eParameter name="contract" type="Contract"/>
          </eParameters>
          <eExceptions/>
        </eOperation>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Acquisition">
      <eStructuralFeatures>
        <eAttribute name="acquisitionId" type="String" unique="true" lowerBound="1"/>
        <eReference name="contract" type="Contract" lowerBound="1"/>
        <eAttribute name="airplaneModel" type="String" lowerBound="1"/>
        <eAttribute name="negotiatedPrice" type="Double" lowerBound="1"/>
        <eAttribute name="optionsAndCustomizations" type="String" upperBound="-1"/>
        <eAttribute name="deliveryDate" type="EDate" lowerBound="1"/>
      </eStructuralFeatures>
    </eClass>
  </eClassifiers>
</EPackage>
