<model xmlns="http://www.eclipse.org/emf/2003/XMI"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:xmi="http://schema.omg.org/spec/XMI/20131001"
       xmi:version="2.0">
  
  <eObject xsi:type="ecore:EPackage" name="GasStationModel"
           nillable="true" annotation=" ">
    <eClassifiers>
      
      <!-- Root container class -->
      <eClass name="ModelRoot">
        <eStructuralFeatures>
          <!-- Containment reference to hold GasStation instances -->
          <eReference name="gasStations" eType="#//GasStation"
                      containment="true"/>
        </eStructuralFeatures>
      </eClass>
      
      <!-- GasStation Class -->
      <eClass name="GasStation">
        <eStructuralFeatures>
          <!-- Unique identifier for the gas station -->
          <eAttribute name="id" eType="EString" unique="true"/>
          <!-- Address of the gas station -->
          <eAttribute name="address" eType="EString"/>
          <!-- Reference to FuelPump instances, with a maximum size of 12 and containment -->
          <eReference name="fuelPumps" eType="#//FuelPump" lower="0" upper="12"
                      containment="true"/>
          <!-- Containment reference for DailyPrice records associated with this gas station -->
          <eReference name="dailyPrices" eType="#//DailyPrice" containment="true"/>
          <!-- Containment reference for FuelPurchase transactions conducted at this gas station -->
          <eReference name="fuelPurchases" eType="#//FuelPurchase" containment="true"/>
        </eStructuralFeatures>
      </eClass>

      <!-- FuelPump Class -->
      <eClass name="FuelPump">
        <eStructuralFeatures>
          <!-- Unique number identifying the pump at a gas station -->
          <eAttribute name="number" eType="int"/>
          <!-- Indicates whether the fuel pump is self-service -->
          <eAttribute name="isSelfService" eType="EBoolean"/>
          <!-- Reference to Fuel instances that are available at this pump -->
          <eReference name="availableFuels" eType="#//Fuel" lower="1"/>
        </eStructuralFeatures>
      </eClass>

      <!-- Fuel Class -->
      <eClass name="Fuel">
        <eStructuralFeatures>
          <!-- Name uniquely identifies a fuel type -->
          <eAttribute name="name" eType="EString" unique="true"/>
          <!-- Octane rating of the fuel -->
          <eAttribute name="octaneRating" eType="int"/>
          <!-- Opposite side reference to FuelPump instances where this fuel is available -->
          <eReference name="fuelPumps" eType="#//FuelPump"
                      lower="0" upper="-1" containment="false">
            <eOpposite refProperty="availableFuels"/>
          </eReference>
        </eStructuralFeatures>
      </eClass>

      <!-- DailyPrice Class -->
      <eClass name="DailyPrice">
        <eStructuralFeatures>
          <!-- Date of the price record -->
          <eAttribute name="date" eType="EDate"/>
          <!-- Reference to the Fuel instance this price applies to -->
          <eReference name="fuel" eType="#//Fuel"/>
          <!-- Reference to the GasStation where this price is recorded -->
          <eReference name="gasStation" eType="#//GasStation"/>
          <!-- Price per liter for the fuel on the specified date at the given gas station -->
          <eAttribute name="pricePerLiter" eType="double"/>
        </eStructuralFeatures>
      </eClass>

      <!-- FuelPurchase Class representing a single transaction of fuel dispensing -->
      <eClass name="FuelPurchase">
        <eStructuralFeatures>
          <!-- Unique identifier for the purchase transaction -->
          <eAttribute name="id" eType="EString" unique="true"/>
          <!-- Reference to the FuelPump where the purchase was made -->
          <eReference name="fuelPump" eType="#//FuelPump"/>
          <!-- Association with DailyPrice to indicate which price record applied at transaction time -->
          <eReference name="dailyPrice" eType="#//DailyPrice"/>
          <!-- Number of liters dispensed in this transaction -->
          <eAttribute name="litersDispensed" eType="double"/>
        </eStructuralFeatures>
      </eClass>

    </eClassifiers>
  </eObject>
</model>
