<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="housePackage"
    nsURI="http://www.example.org/housePackage"
    nsPrefix="housePackage">

  <!-- Enum: BMType -->
  <eClassifiers xsi:type="ecore:EEnum" name="BMType">
    <eLiterals name="wood"/>
    <eLiterals name="brick" value="1"/>
    <eLiterals name="concrete" value="2"/>
  </eClassifiers>

  <!-- Abstract class: Basement -->
  <eClassifiers xsi:type="ecore:EClass" name="Basement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class: ConcreteBasement extends Basement -->
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteBasement" eSuperTypes="#//Basement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Quality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- Class: EarthBasement extends Basement -->
  <eClassifiers xsi:type="ecore:EClass" name="EarthBasement" eSuperTypes="#//Basement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Humidity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- Class: House -->
  <eClassifiers xsi:type="ecore:EClass" name="House">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BuildingMaterial" eType="#//BMType"/>
    <!-- Composition: House contains 0..1 Basement -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="basement"
        eType="#//Basement"
        containment="true"
        upperBound="1"/>
    <!-- Association to JobLog (association class for House-Company) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobLogs"
        eType="#//JobLog"
        upperBound="-1"
        eOpposite="#//JobLog/house"/>
  </eClassifiers>

  <!-- Abstract class: SemiDetached extends House -->
  <eClassifiers xsi:type="ecore:EClass" name="SemiDetached" abstract="true" eSuperTypes="#//House">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Garden" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Windows" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- Class: SemiDetachedWithCarport extends SemiDetached -->
  <eClassifiers xsi:type="ecore:EClass" name="SemiDetachedWithCarport" eSuperTypes="#//SemiDetached">
    <!-- Association: SemiDetachedWithCarport 1 - 2 Carport -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="carports"
        eType="#//Carport"
        lowerBound="2"
        upperBound="2"/>
  </eClassifiers>

  <!-- Class: SemiDetachedWithGarage extends SemiDetached -->
  <eClassifiers xsi:type="ecore:EClass" name="SemiDetachedWithGarage" eSuperTypes="#//SemiDetached">
    <!-- Association: SemiDetachedWithGarage 1 - 1 Garage -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="garage"
        eType="#//Garage"
        lowerBound="1"
        upperBound="1"/>
  </eClassifiers>

  <!-- Class: Company -->
  <eClassifiers xsi:type="ecore:EClass" name="Company">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Association to JobLog (association class for House-Company) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="jobLogs"
        eType="#//JobLog"
        upperBound="-1"
        eOpposite="#//JobLog/company"/>
  </eClassifiers>

  <!-- Class: JobLog (association class for House - Company) -->
  <eClassifiers xsi:type="ecore:EClass" name="JobLog">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <!-- Reference back to House -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="house"
        eType="#//House"
        lowerBound="1"
        upperBound="1"
        eOpposite="#//House/jobLogs"/>
    <!-- Reference back to Company -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="company"
        eType="#//Company"
        lowerBound="1"
        upperBound="1"
        eOpposite="#//Company/jobLogs"/>
  </eClassifiers>

  <!-- Class: Carport -->
  <eClassifiers xsi:type="ecore:EClass" name="Carport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DoublePort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flatRoof" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>

  <!-- Class: Garage -->
  <eClassifiers xsi:type="ecore:EClass" name="Garage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Automatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>

</ecore:EPackage>
