<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage xmi:id="clothingSalesSystemPackage" name="ClothingSalesSystem">
    <eClassifiers xmi:type="ecore:EClass" xmi:id="productClass" name="Product">
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="productName" name="name" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="productDescription" name="description" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="productNetPrice" name="netPrice" eType="ecore:EDouble"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="productManufacturerCompany" name="manufacturerCompany" eType="ecore:EString"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="productOriginCountry" name="originCountry" eType="countryClass" containment="false"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="productAvailableCountries" name="availableCountries" eType="countryClass" containment="false"/>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="countryClass" name="Country">
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="countryName" name="name" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="countryVatRate" name="vatRate" eType="ecore:EDouble"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="countryCurrency" name="currency" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="countryConversionRate" name="conversionRateToEuro" eType="ecore:EDouble"/>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="representativeClass" name="Representative">
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="repFirstName" name="firstName" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="repLastName" name="lastName" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="repSsn" name="socialSecurityNumber" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="repPhone" name="phoneNumber" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="repEmail" name="emailAddress" eType="ecore:EString"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="repCountry" name="responsibleCountry" eType="countryClass" containment="false"/>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="customerClass" name="Customer">
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="custName" name="name" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="custAddress" name="address" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="custPhone" name="phoneNumber" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="custEmail" name="emailAddress" eType="ecore:EString"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="custResaleCountries" name="resaleCountries" eType="countryClass" containment="false"/>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="orderClass" name="Order">
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="orderId" name="orderId" eType="ecore:EString"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="orderQuantity" name="quantity" eType="ecore:EInt"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="orderDate" name="orderDate" eType="ecore:EDate"/>
      <eAttributes xmi:type="ecore:EAttribute" xmi:id="deliveryDate" name="desiredDeliveryDate" eType="ecore:EDate"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="orderProduct" name="product" eType="productClass" containment="false"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="orderCustomer" name="customer" eType="customerClass" containment="false"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="orderRepresentative" name="representative" eType="representativeClass" containment="false"/>
    </eClassifiers>

    <eClassifiers xmi:type="ecore:EClass" xmi:id="rootContainerClass" name="ClothingSalesSystemRoot">
      <eReferences xmi:type="ecore:EReference" xmi:id="rootProducts" name="products" eType="productClass" containment="true"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="rootCountries" name="countries" eType="countryClass" containment="true"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="rootRepresentatives" name="representatives" eType="representativeClass" containment="true"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="rootCustomers" name="customers" eType="customerClass" containment="true"/>
      <eReferences xmi:type="ecore:EReference" xmi:id="rootOrders" name="orders" eType="orderClass" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
