<?xml version="1.0" encoding="UTF-8"?>
<ePackage name="tourism" nsURI="http://www.example.org/tourism" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:version="2.0">
  <eClass name="TourismSystem">
    <eStructuralFeatures>
      <eReference name="cities" elementType="City" containment="true"/>
      <eReference name="people" elementType="Person" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="City">
    <eStructuralFeatures>
      <eAttribute name="name" type="EString"/>
      <eAttribute name="inhabitants" type="EInt"/>
      <eReference name="attractions" elementType="Attraction" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Attraction">
    <eStructuralFeatures>
      <eAttribute name="name" type="EString"/>
      <eAttribute name="address" type="EString"/>
      <eReference name="city" elementType="City"/>
      <eReference name="guidedTours" elementType="GuidedTour" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="GuidedTour">
    <eStructuralFeatures>
      <eAttribute name="duration" type="DurationType"/>
      <eAttribute name="number" type="EInt"/>
      <eReference name="guide" elementType="Guide"/>
      <eReference name="attraction" elementType="Attraction"/>
      <!-- Association class Booking: containment end -->
      <eReference name="bookings" elementType="Booking" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Person" abstract="true">
    <eStructuralFeatures>
      <eAttribute name="name" type="EString"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Visitor" extends="Person">
    <eStructuralFeatures>
      <!-- Association class Booking: non-containment end -->
      <eReference name="bookings" elementType="Booking"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Guide" extends="Person"/>

  <eClass name="Booking">
    <eStructuralFeatures>
      <eAttribute name="discountAmount" type="EDouble"/>
      <eReference name="visitor" elementType="Visitor"/>
      <eReference name="guidedTour" elementType="GuidedTour"/>
    </eStructuralFeatures>
  </eClass>

  <eDataType name="DurationType">
    <!-- Custom datatype using java.time.Duration -->
  </eDataType>
</ePackage>
