<model xmlns="urn:tileo:metamodel">
  <!-- Root container class -->
  <TileOModel xsi:type="ecore:EClass" name="TileOModel">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EReference" name="games" type="Game" containment="true"/>
    </eStructuralFeatures>
  </TileOModel>

  <!-- Game class representing a single game instance -->
  <Game xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EReference" name="board" type="Board" containment="true"/>
      <eStructuralFeature xsi:type="ecore:EReference" name="players" type="Player" lowerBound="2" upperBound="4" containment="true"/>
      <eStructuralFeature xsi:type="ecore:EAttribute" name="currentPlayerIndex" type="int"/>
    </eStructuralFeatures>
  </Game>

  <!-- Board class representing the game board -->
  <Board xsi:type="ecore:EClass" name="Board">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EReference" name="tiles" type="Tile" containment="true"/>
    </eStructuralFeatures>
  </Board>

  <!-- Tile class representing a tile on the board -->
  <Tile xsi:type="ecore:EClass" name="Tile">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EReference" name="leftConnection" type="Connection" upperBound="1"/>
      <eStructuralFeature xsi:type="ecore:EReference" name="rightConnection" type="Connection" upperBound="1"/>
      <eStructuralFeature xsi:type="ecore:EReference" name="topConnection" type="Connection" upperBound="1"/>
      <eStructuralFeature xsi:type="ecore:EReference" name="bottomConnection" type="Connection" upperBound="1"/>
      <eStructuralFeature xsi:type="ecore:EAttribute" name="isHidden" type="boolean"/>
      <eStructuralFeature xsi:type="ecore:EAttribute" name="isAction" type="boolean"/>
      <eStructuralFeature xsi:type="ecore:EAttribute" name="visited" type="boolean" defaultValue="false"/>
    </eStructuralFeatures>
  </Tile>

  <!-- Connection class representing a connection between two tiles -->
  <Connection xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EReference" name="tile1" type="Tile" lowerBound="1" upperBound="1"/>
      <eStructuralFeature xsi:type="ecore:EReference" name="tile2" type="Tile" lowerBound="1" upperBound="1"/>
    </eStructuralFeatures>
  </Connection>

  <!-- Player class representing a player in the game -->
  <Player xsi:type="ecore:EClass" name="Player">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EAttribute" name="color" type="String"/>
      <eStructuralFeature xsi:type="ecore:EReference" name="position" type="Tile"/>
    </eStructuralFeatures>
  </Player>

  <!-- ActionCard class representing an action card -->
  <ActionCard xsi:type="ecore:EClass" name="ActionCard">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EReference" name="type" type="ActionType"/>
    </eStructuralFeatures>
  </ActionCard>

  <!-- Enum class for action card types -->
  <ActionType xsi:type="ecore:EEnum" name="ActionType">
    <eLiterals>
      <eLiteral name="EXTRA_TURN"/>
      <eLiteral name="CONNECT_TILES"/>
      <eLiteral name="REMOVE_CONNECTION"/>
      <eLiteral name="MOVE_ARBITRARY"/>
      <eLiteral name="LOSE_NEXT_TURN"/>
    </eLiterals>
  </ActionType>

  <!-- Deck class representing a deck of action cards -->
  <Deck xsi:type="ecore:EClass" name="Deck">
    <eStructuralFeatures>
      <eStructuralFeature xsi:type="ecore:EReference" name="cards" type="ActionCard" containment="true"/>
    </eStructuralFeatures>
  </Deck>

  <!-- Operations for game logic -->
  <operations class="Game">
    <operation name="rollDie">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2003/XMLSchema#int"/>
    </operation>
    <operation name="movePlayer">
      <parameters>
        <parameter name="playerIndex" type="int"/>
        <parameter name="steps" type="int"/>
      </parameters>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2003/XMLSchema#boolean"/>
    </operation>
    <operation name="checkWinCondition">
      <parameters>
        <parameter name="playerIndex" type="int"/>
      </parameters>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2003/XMLSchema#boolean"/>
    </operation>
    <operation name="handleActionTile">
      <parameters>
        <parameter name="playerIndex" type="int"/>
      </parameters>
    </operation>
  </operations>

</model>
