<?xml version="1.0" encoding="UTF-8"?>
<ePackage name="eHome2020" nsURI="http://www.example.org/eHome2020" nsPrefix="ehome" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <eClass name="EHomeSystem">
    <eStructuralFeatures>
      <eReference name="sensorControllers" reference="SensorController" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="SensorController">
    <eStructuralFeatures>
      <eReference name="apartment" reference="Apartment" containment="true"/>
      <eReference name="inhabitants" reference="Inhabitant" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Inhabitant">
    <eStructuralFeatures>
      <eAttribute name="username" type="ecore:EString"/>
      <eAttribute name="password" type="ecore:EString"/>
      <eAttribute name="isAdmin" type="ecore:EBoolean"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Apartment">
    <eStructuralFeatures>
      <eAttribute name="address" type="ecore:EString"/>
      <eAttribute name="emailAddress" type="ecore:EString"/>
      <eReference name="rooms" reference="Room" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Room">
    <eStructuralFeatures>
      <eAttribute name="description" type="ecore:EString"/>
      <eReference name="sensors" reference="Sensor" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Sensor" abstract="true">
    <eStructuralFeatures>
      <eAttribute name="vendorId" type="ecore:EString"/>
      <eAttribute name="description" type="ecore:EString"/>
      <eAttribute name="unit" type="UnitEnum"/>
      <eAttribute name="threshold" type="ecore:EDouble"/>
      <eReference name="measuredValues" reference="MeasuredValue" containment="true"/>
    </eStructuralFeatures>
    <eOperations>
      <eOperation name="getLastValue"/>
    </eOperations>
  </eClass>

  <eClass name="TemperatureSensor">
    <eExtends reference="Sensor"/>
    <eStructuralFeatures>
      <eAttribute name="minRange" type="ecore:EDouble"/>
      <eAttribute name="maxRange" type="ecore:EDouble"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="PowerSensor">
    <eExtends reference="Sensor"/>
    <eStructuralFeatures>
      <eAttribute name="totalConsumption" type="ecore:EDouble"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="MeasuredValue">
    <eStructuralFeatures>
      <eAttribute name="timestamp" type="ecore:EDate"/>
      <eAttribute name="value" type="ecore:EDouble"/>
    </eStructuralFeatures>
  </eClass>

  <eEnum name="UnitEnum">
    <eLiterals>
      <eLiteral name="CELSIUS"/>
      <eLiteral name="WATT"/>
    </eLiterals>
  </eEnum>
</ePackage>
