<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="housemodel" nsURI="http://www.example.org/housemodel">
    <ecore:EClass name="Root">
      <ecore:EStructuralFeatures>
        <ecore:ERefReference name="houses" EReferenceType="House" containment="true"/>
        <ecore:ERefReference name="companies" EReferenceType="Company" containment="true"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EEnum name="BuildingMaterial">
      <ecore:ELiteral name="WOOD"/>
      <ecore:ELiteral name="BRICK"/>
      <ecore:ELiteral name="CONCRETE"/>
    </ecore:EEnum>

    <ecore:EClass name="House">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="address" EAttributeType="String"/>
        <ecore:EAttribute name="buildingMaterial" EAttributeType="BuildingMaterial"/>
        <ecore:ERefReference name="basement" EReferenceType="Basement" containment="true"/>
        - JobLog is an association class. House acts as the container for the log entries
        <ecore:ERefReference name="jobLogs" EReferenceType="JobLog" containment="true"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="SemiDetachedHouse" eSuperClass="House">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="hasGarden" EAttributeType="Boolean"/>
        <ecore:EAttribute name="windowCount" EAttributeType="Integer"/>
        <ecore:ERefReference name="parkingOptions" EReferenceType="ParkingOption" containment="true"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Basement" abstract="true">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="size" EAttributeType="Float"/>
        <ecore:EAttribute name="name" EAttributeType="String"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="EarthBasement" eSuperClass="Basement">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="humidityLevel" EAttributeType="Float"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="ConcreteBasement" eSuperClass="Basement"/>

    <ecore:EClass name="ParkingOption" abstract="true"/>

    <ecore:EClass name="Carport" eSuperClass="ParkingOption">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="isDouble" EAttributeType="Boolean"/>
        <ecore:EAttribute name="hasFlatRoof" EAttributeType="Boolean"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Garage" eSuperClass="ParkingOption">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="hasAutomaticDoor" EAttributeType="Boolean"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Company">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="name" EAttributeType="String"/>
        <ecore:EAttribute name="address" EAttributeType="String"/>
        - JobLog is an association class. Company has a non-containment reference
        <ecore:ERefReference name="jobLogs" EReferenceType="JobLog" containment="false"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="JobLog">
      <ecore:EStructuralFeatures>
        <ecore:EAttribute name="hours" EAttributeType="Float"/>
        <ecore:EAttribute name="price" EAttributeType="Float"/>
        <ecore:ERefReference name="house" EReferenceType="House" containment="false"/>
        <ecore:ERefReference name="company" EReferenceType="Company" containment="false"/>
      </ecore:EStructuralFeatures>
    </ecore:EClass>
  </ecore:EPackage>
</xmi:XMI>
