<model xmlns="http://www.eclipse.org/emf/2003/XMI">
  <eClassifiers>
    <!-- Root Container -->
    <ecore:EClass name="SystemModel"/>

    <!-- User-related Classes -->
    <ecore:EClass name="User" abstract="true">
      <ecore:EAttribute name="username" type="EString"/>
      <ecore:EAttribute name="email" type="EString"/>
      <ecore:EAttribute name="passwordHash" type="EString"/>
    </ecore:EClass>

    <ecore:EClass name="RegisteredUser">
      <ecore:ESuperTypes>
        <ecore:EClass eName="SystemModel"/>
      </ecore:ESuperTypes>
      <ecore:EReference name="ownedBuildings" type="Building" containment="true" upperBound="-1"/>
      <ecore:EOperation name="register">
        <ecore:EParameter name="confirmationLink" type="EString"/>
      </ecore:EOperation>
    </ecore:EClass>

    <ecore:EClass name="Administrator">
      <ecore:ESuperTypes>
        <ecore:EClass eName="RegisteredUser"/>
      </ecore:ESuperTypes>
      <ecore:EAttribute name="idCardNumber" type="EString"/>
    </ecore:EClass>

    <!-- Building-related Classes -->
    <ecore:EClass name="Building">
      <ecore:ESuperTypes>
        <ecore:EClass eName="SystemModel"/>
      </ecore:ESuperTypes>
      <ecore:EAttribute name="id" type="ELong" unique="true"/>
      <ecore:EAttribute name="name" type="EString"/>
      <ecore:EAttribute name="energyClass" type="EnergyClassEnum"/>
      <ecore:EAttribute name="address" type="EString"/>
      <ecore:EAttribute name="yearOfConstruction" type="EInt"/>
      <ecore:EReference name="owner" type="RegisteredUser" lowerBound="1" upperBound="1"/>
      <ecore:EReference name="entries" type="Entry" containment="true" upperBound="-1"/>
      <ecore:EReference name="images" type="Image" containment="true" upperBound="-1"/>
      <ecore:EReference name="profileImage" type="Image" lowerBound="0" upperBound="1"/>
      <ecore:EOperation name="addEntry">
        <ecore:EParameter name="entry" type="Entry"/>
      </ecore:EOperation>
    </ecore:EClass>

    <!-- Entry-related Classes -->
    <ecore:EClass name="Entry" abstract="true">
      <ecore:EAttribute name="name" type="EString"/>
      <ecore:EAttribute name="isPublic" type="EBoolean" eDefault="false"/>
    </ecore:EClass>

    <ecore:EClass name="TextEntry">
      <ecore:ESuperTypes>
        <ecore:EClass eName="Entry"/>
      </ecore:ESuperTypes>
      <ecore:EAttribute name="text" type="EString"/>
    </ecore:EClass>

    <ecore:EClass name="NumericEntry">
      <ecore:ESuperTypes>
        <ecore:EClass eName="Entry"/>
      </ecore:ESuperTypes>
      <ecore:EAttribute name="value" type="EDouble"/>
      <ecore:EAttribute name="unit" type="EString"/>
    </ecore:EClass>

    <!-- Image Class -->
    <ecore:EClass name="Image">
      <ecore:ESuperTypes>
        <ecore:EClass eName="SystemModel"/>
      </ecore:ESuperTypes>
      <ecore:EAttribute name="fileName" type="EString"/>
    </ecore:EClass>

    <!-- WebPortal Class -->
    <ecore:EClass name="WebPortal">
      <ecore:ESuperTypes>
        <ecore:EClass eName="SystemModel"/>
      </ecore:ESuperTypes>
      <ecore:EAttribute name="versionNumber" type="EString"/>
      <ecore:EAttribute name="url" type="EString"/>
      <ecore:EReference name="buildingsCatalog" type="Building" containment="true" upperBound="-1"/>
      <ecore:EOperation name="searchBuildings">
        <ecore:EParameter name="query" type="EString"/>
        <ecore:EException type="SearchErrorException"/>
      </ecore:EOperation>
    </ecore:EClass>

    <!-- Enumeration for Energy Class -->
    <ecore:EEnum name="EnergyClassEnum">
      <ecore:eLiterals>
        <ecore:eLiteral name="A"/>
        <ecore:eLiteral name="B"/>
        <ecore:eLiteral name="C"/>
        <ecore:eLiteral name="D"/>
      </ecore:eLiterals>
    </ecore:EEnum>

    <!-- Exception for Search -->
    <ecore:EClass name="SearchErrorException" abstract="true">
      <!-- Inherits from built-in Exception type (not explicitly modeled here) -->
    </ecore:EClass>

  </eClassifiers>
</model>
