<?xml version="1.0" encoding="UTF-8"?>
<uml:XMI xmi:version="2.5"
         xmlns:xmi="http://www.omg.org/XMI"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:uml="http://www.omg.org/spec/UML/20180901/profiles/uml/structural"
         xsi:schemaLocation="
            http://www.omg.org/spec/UML/2.5.1/uml.xmi 
            https://spec.opengroup.org/resources/open-architectures/emf-gen/umlfacades/src/org/eclipse/uml2/20/uml.xsd">
    <packagedElement xmi:type="uml:Package" name="ScienceConnectMetamodel" xmi:id="_1">
        <!-- Person Class -->
        <packagedElement xmi:type="uml:Class"
                         xmi:id="_2" name="Person">
            <ownedAttribute xmi:id="_3" name="personId" type="_4"/>
            <ownedAttribute xmi:id="_5" name="phoneNumber" type="_6"/>
            <ownedAttribute xmi:id="_7" name="researchKeywords" type="_8"/>
            <ownedAttribute xmi:id="_9"
                            association="_A">
                <references xmi:type="uml:AssociationEnd"
                            href="#institution_code_" />
                <lowerValue xsi:type="uml:LiteralInteger">1</lowerValue>
            </ownedAttribute>
        </packagedElement>
        
        <!-- Institution Class -->
        <packagedElement xmi:type="uml:Class"
                         xmi:id="_B" name="Institution">
            <ownedAttribute xmi:id="_C" name="institutionCode" type="_4"/>
            <ownedAttribute xmi:id="_D"
                            association="_E">
                <references xmi:type="uml:AssociationEnd"
                            href="#_F_" />
            </ownedAttribute>
        </packagedElement>

        <!-- Article Class -->
        <packagedElement xmi:type="uml:Class"
                         xmi:id="_G" name="Article">
            <ownedAttribute xmi:id="_H" name="doi" type="_4"/>
            <ownedAttribute xmi:id="_I" name="title" type="_J"/>
            <!-- Corrected the line with operation by adding '=' after 'return' -->
            <operation xmi:id="_K" name="getAuthorsAsList" return="_L">
                <ownedParameter xmi:type="uml:OperationParameter"
                                direction="return" type="_L"/>
            </operation>
        </packagedElement>

        <!-- PeerReviewedArticle Class -->
        <packagedElement xmi:type="uml:Class"
                         xmi:id="_M" name="PeerReviewedPaper"
                         general="_G">
            <ownedAttribute xmi:id="_N" name="citationCount" type="_O"/>
        </packagedElement>

        <!-- TechnicalReport Class -->
        <packagedElement xmi:type="uml:Class"
                         xmi:id="_P" name="TechnicalReport"
                         general="_G"/>

        <!-- Publisher Class -->
        <packagedElement xmi:type="uml:Class"
                         xmi:id="_Q" name="Publisher">
            <ownedAttribute xmi:id="_R" name="name" type="_J"/>
            <ownedAttribute xmi:id="_S"
                            association="_T">
                <references xmi:type="uml:AssociationEnd"
                            href="#journal_name_" />
            </ownedAttribute>
        </packagedElement>

        <!-- Journal Class -->
        <packagedElement xmi:type="uml:Class"
                         xmi:id="_U" name="Journal">
            <ownedAttribute xmi:id="_V" name="publicationName" type="_J"/>
            <ownedAttribute xmi:id="_W" name="impactFactor" type="_O"/>
        </packagedElement>

        <!-- Relationships and Associations -->
        <uml:Association xmi:id="_A" memberEnd="_X">
            <ownedEnd xmi:id="_X" type="_Y"
                      association="_2"/> 
            <ownedEnd xmi:type="uml:Property" href="#_B_" />
        </uml:Association>

        <uml:Association xmi:id="_E" memberEnd="_F">
            <ownedEnd xmi:id="_F" type="_P" aggregation="composite"
                      association="_B"/>
        </uml:Association>
        
        <uml:Association xmi:id="_T" memberEnd="_U">
            <ownedEnd xmi:id="_U" type="_V" multiplicity="0..*"
                      targetScope="instance"
                      association="_Q"/> 
        </uml:Association>

        <!-- DataType Definitions -->
        <packagedElement xmi:type="uml:PrimitiveType"
                         xmi:id="_4" name="String"/>

        <packagedElement xmi:type="uml:PrimitiveType"
                         xmi:id="_6" name="PhoneNumber"/>

        <packagedElement xmi:type="uml:PrimitiveType"
                         xmi:id="_8" name="ResearchKeywordList"/>

        <packagedElement xmi:type="uml:PrimitiveType"
                         xmi:id="_J" name="String"/>

        <packagedElement xmi:type="uml:PrimitiveType"
                         xmi:id="_O" name="Integer"/>
    </packagedElement>
</uml:XMI>
