<xmi:XMI xmlns:xmi="http://schema.omg.org/spec/XMI/2.0"
         xmlns"xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns.ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage xmi:type="ecore:EPackage" name="university"
                  xmlns="http://www.eclipse.org/emf/2002/Ecore"
                  xmi:id="_0">
    <eClassifiers>
      <!-- Root container class -->
      <eClassifiers xmi:type="ecore:EClass" name="UniversityModel"
                    eSuperTypes="_15" xmi:id="_1">
        <eStructuralFeatures>
          <eStructralFeature xmi:type="ecore:EReference" name="faculties"
                             type="_4" lowerBound="0" upperBound="-1"
                             containment="true" xmi:id="_2"/>
        </eStructralFeatures>
      </eClassifiers>

      <!-- Employee class -->
      <eClassifiers xmi:type="ecore:EClass" name="Employee"
                    eSuperTypes="_15" xmi:id="_3">
        <eStructuralFeatures>
          <eStructralFeature xmi:type="ecore:EAttribute" name="socialSecurityNumber"
                             type="_14" default="''" xmi:id="_6"/>
          <eStructralFeature xmi:type="ecore:EAttribute" name="name"
                            type="_14" default="''" xmi:id="_7"/>
           <eStructralFeature xmi:type="ecore:EAttribute" name="emailAddress"
                             type="_14" default="''" xmi:id="_8"/>
        </eStructuralFeatures>
      </eClassifiers>

      <!-- AbstractEmployee class -->
      <eClassifiers xmi:type="ecore:EClass" name="AbstractEmployee"
                    eSuperTypes="_3" abstract="true" xmi:id="_15"/>

      <!-- ResearchAssistant class -->
      <eClassifiers xmi:type="ecore:EClass" name="ResearchAssistant"
                    eSuperTypes="_15" xmi:id="_4">
        <eStructralFeatures>
          <eStructralFeature xmi:type="ecore:EReference" name="institutes"
                             type="_9" lowerBound="1" upperBound="-1"
                             containment="false" xmi:id="_10"/>
          <eStructralFeature xmi:type="ecore:EAttribute" name="researchField"
                             type="_14" default="''" xmi:id="_11"/>
        </eStructralFeatures>
      </eClassifiers>

      <!-- Lecturer class -->
      <eClassifiers xmi:type="ecore:EClass" name="Lecturer"
                    eSuperTypes="_4" xmi:id="_16"/>

     <!-- Faculty class -->
      <eClassifiers xmi:type="ecore:EClass" name="Faculty"
                    eSuperTypes="_15" xmi:id="_5">
        <eStructralFeatures>
          <eStructralFeature xmi:type="ecore:EAttribute" name="name"
                             type="_14" default="''" xmi:id="_13"/>
          <eStructralFeature xmi:type="ecore:EReference" name="dean"
                             type="_3" lowerBound="0" upperBound="1"
                             containment="false" xmi:id="_17"/>
          <eStructralFeature  xmi:type="ecore:EReference" name="institutes"
                              type="_9" lowerBound="0" upperBound="-1"
                              containment="true" xmi:id="_18"/>
        </eStructralFeatures>
      </eClassifiers>

      <!-- Institute class -->
      <eClassifiers xmi:type="ecore:EClass" name="Institute"
                    eSuperTypes="_15"
                    xmi:id="_9">
        <eStructuralFeatures>
          <eStructralFeature xmi:type="ecore:EAttribute" name="name"
                             type="_14" default="''" xmi:id="_19"/>
           <eStructralFeature xmi:type="ecore:EAttribute" name="address"
                              type="_14" default="''" xmi:id="_20"/>
        </eStructuralFeatures>
      </eClassifiers>

      <!-- Course class -->
     <eClassifiers xmi:type="ecore:EClass" name="Course"
                   eSuperTypes="_15" xmi:id="_12">
        <eStructralFeatures>
           <eStructralFeature  xmi:type="ecore:EAttribute" name="id"
                               type="_14" default="''" xmi:id="_21"/>
          <eStructralFeature xmi:type="ecore:EAttribute" name="name"
                             type="_14" default="''" xmi:id="_22"/>
         <eStructralFeature  xmi:type="ecore:EAttribute" name="weeklyDurationHours"
                              type="_10" default="0.0" xmi:id="_23"/>
        </eStructralFeatures>
      </eClassifiers>

      <!-- ProjectInvolvement association class -->
      <eClassifiers xmi:type="ecore:EClass" name="ProjectInvolvement"
                    eSuperTypes="_15" xmi:id="_24">
        <eStructralFeatures>
         <eStructralFeature  xmi:type="ecore:EReference" name="researchAssistant"
                             type="_4" lowerBound="1" upperBound="1"
                              containment="false" xmi:id="_28"/>
          <eStructralFeature xmi:type="ecore:EReference" name="project"
                             type="_29" lowerBound="1" upperBound="1"
                              containment="false" xmi:id="_30"/>
          <eStructralFeature  xmi:type="ecore:EAttribute" name="hours"
                               type="_10" default="0.0" xmi:id="_31"/>
        </eStructralFeatures>
      </eClassifiers>

      <!-- Project class -->
   <eClassifiers xmi:type="ecore:EClass" name="Project"
                 eSuperTypes="_15"
                  xmi:id="_29">
        <eStructralFeatures>
          <eStructralFeature  xmi:type="ecore:EAttribute" name="name"
                               type="_14" default="''" xmi:id="_32"/>
         <eStructralFeature xmi:type="ecore:EAttribute" name="startDate"
                             type="_13" default="null" xmi:id="_33"/>
          <eStructralFeature  xmi:type="ecore:EAttribute" name="endDate"
                               type="_13" default="null" xmi:id="_34"/>
         <eStructralFeature  xmi:type="ecore:EReference" name="involvements"
                              type="_24" lowerBound="0" upperBound="-1"
                             containment="true" xmi:id="_35"/>
      </eStructralFeatures>
    </eClassifiers>

      <!-- Primitive type classes -->
       <eClassifiers xmi:type="ecore:EClass" name="String"
                     eSuperTypes="_15" instanceClassName="java.lang.String"xmi:id="_14"/>
     <eClassifiers xmi:type="ecore:EClass" name="Integer"
                    eSuperTypes="_15" instanceClassName="java.lang.Integer"
                    xmi:id="_10"/>
   <eClassifiers xmi:type="ecore:EClass" name="Double"
                 eSuperTypes="_15" instanceClassName="java.lang.Double"
                  xmi:id="_11"/>
  <eClassifiers xmi:type="ecore:EClass" name="EDate"
                eSuperTypes="_15" instanceClassName="org.eclipse.emf.ecore.util.EDate"
                xmi:id="_13"/>
    </eClassifiers>
   </ecore:EPackage>
</xmi:XMI>
