<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage 
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore http://www.eclipse.org/emf/2002/Ecore.xsd"
    xmi:version="2.0"
    name="TransportCompany"
    nsURI="http://example.com/transport/company"
    nsPrefix="tco">

  <!-- RootContainer to contain all entities -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_aq" name="RootContainer">
  
    <!-- Employee Base Class -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_B" name="Employee">
      <eStructuralFeatures>
        <eAttribute xmi:id="_C" name="name"/>
        <eAttribute xmi:id="_D" name="socialSecurityNumber" type="#_E"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Abstract EmployeeType Superclass -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_F" isAbstract="true" name="EmployeeType">
      <eSuperTypes href="#_B"/>
    </eClassifiers>
  
    <!-- Derived Classes for Employees -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_G" eSuperTypes="#_F" name="Driver"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_H" eSuperTypes="#_F" name="Planner"/>
    
    <!-- AdministrativeStaff EmployeeType with additional feature -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_I" eSuperTypes="#_F" name="AdministrativeStaff">
      <eStructuralFeatures>
        <eAttribute xmi:id="_J" name="fieldOfActivity"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- User Credentials EDataType -->
    <eClassifiers xsi:type="ecore:EDataType" xmi:id="_K" instanceClassName="UserCredentials">
      <eStructuralFeatures>
        <eAttribute xmi:id="_L" name="username"/>
        <eAttribute xmi:id="_M" name="password"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Vehicle Base Class -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_N" name="Vehicle">
      <eStructuralFeatures>
        <eAttribute xmi:id="_O" name="licensePlateNumber"/>
        <eAttribute xmi:id="_P" name="mileage" type="org.eclipse.emf.ecore.util.FeatureMapEntry"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Abstract VehicleType -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_Q" isAbstract="true" name="VehicleType">
      <eSuperTypes href="#_N"/>
    </eClassifiers>

    <!-- Specific Types of Vehicles -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_R" eSuperTypes="#_Q" name="RefrigeratedTruck"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_S" eSuperTypes="#_Q" name="SmallVan"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_T" eSuperTypes="#_Q" name="LoadingPlatform"/>
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_U" eSuperTypes="#_Q" name="BoxTruck"/>

    <!-- Repair Information Class -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_V" name="Repair">
      <eStructuralFeatures>
        <eReference xmi:id="_W" type="#_Z" name="repairShop"/>
        <eReference xmi:id="_X" reference="#_H" name="employee"/>
        <eAttribute xmi:id="_Y" name="duration" type="http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
        <eAttribute xmi:id="_Z" name="cost"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Customer Class -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_aa" name="Customer">
      <eStructuralFeatures>
        <eAttribute xmi:id="_ab" name="name"/>
        <eAttribute xmi:id="_ac" name="billingAddress"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Order Class -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_ad" name="Order">
      <eStructuralFeatures>
        <eReference xmi:id="_ae" type="#_ag" reference="#_ak" containment="true" name="driver"/>
        <eAttribute xmi:id="_af" name="startTime" type="http://www.eclipse.org/emf/2002/Ecore#//EDateTime"/>
        <eAttribute xmi:id="_ag" name="finishTime" type="http://www.eclipse.org/emf/2002/Ecore#//EDateTime"/>

        <eReference xmi:id="_ah" reference="#_ai" type="#_an" containment="true" name="vehicle"/>
        <eReference xmi:id="_ai" type="#_am" name="planner"/>

        <eAttribute xmi:id="_aj" name="comment"/>
        
        <!-- Order's Customer Association -->
        <eReference xmi:id="_ak" type="#_aa" name="customer"/>
      
        <eAttribute xmi:id="_al" name="pickupAddress"/>
        <eAttribute xmi:id="_am" name="deliveryAddress"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Partner Company Class -->
    <eClassifiers xsi:type="ecore:EClass" xmi:id="_an" name="PartnerCompany">
      <eStructuralFeatures>
        <eAttribute xmi:id="_ao" name="name"/>
        <eAttribute xmi:id="_ap" name="address"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Associations of Root Container -->
    <eReferences xsi:type="ecore:EReference" xmi:id="_ar" type="#_B" containment="true" many="true" name="employees"/>
    <eReferences xsi:type="ecore:EReference" xmi:id="_as" type="#_N" containment="true" many="true" name="vehicles"/>
    <eReferences xsi:type="ecore:EReference" xmi:id="_at" type="#_aa" containment="true" many="true" name="customers"/>
    <eReferences xsi:type="ecore:EReference" xmi:id="_au" type="#_ad" containment="true" many="true" name="orders"/>

  </eClassifiers>

  <!-- Custom DataType for Social Security Number -->
  <eClassifiers xsi:type="ecore:EDataType" xmi:id="_E" instanceClassName="String"/>
  
  <!-- Ecore Basic Types for Date Related Features -->
  <eClassifiers xsi:type="ecore:EDataType" xmi:id="_av" instanceClassName="java.time.Instant"/>

</ecore:EPackage>
