<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="KinepolisModel" nsURI="http://www.kinepolis.com/model" nsPrefix="kinepolis">

    <!-- Root Container -->
    <ecore:EClass name="KinepolisSystem">
      <eStructuralFeatures>
        <ecore:EReference name="cinemas" eType="#//Cinema" upperBound="-1" containment="true"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Cinema -->
    <ecore:EClass name="Cinema">
      <eStructuralFeatures>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
        <ecore:EReference name="location" eType="#//Town" containment="true"/>
        <ecore:EReference name="theatres" eType="#//Theatre" upperBound="-1" containment="true"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Town -->
    <ecore:EClass name="Town">
      <eStructuralFeatures>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Theatre -->
    <ecore:EClass name="Theatre">
      <eStructuralFeatures>
        <ecore:EAttribute name="number" eType="ecore:EInt"/>
        <ecore:EReference name="cinema" eType="#//Cinema"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Movie -->
    <ecore:EClass name="Movie">
      <eStructuralFeatures>
        <ecore:EAttribute name="title" eType="ecore:EString"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- MovieCopy -->
    <ecore:EClass name="MovieCopy">
      <eStructuralFeatures>
        <ecore:EReference name="movie" eType="#//Movie"/>
        <ecore:EAttribute name="copyId" eType="ecore:EString"/>
        <ecore:EReference name="cinema" eType="#//Cinema"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Show -->
    <ecore:EClass name="Show">
      <eStructuralFeatures>
        <ecore:EAttribute name="startTime" eType="#//TimeWithoutDate"/>
        <ecore:EReference name="movieCopy" eType="#//MovieCopy"/>
        <ecore:EReference name="theatre" eType="#//Theatre"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- TimeWithoutDate Datatype -->
    <ecore:EDataType name="TimeWithoutDate">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="instanceClassName" value="java.time.LocalTime"/>
      </eAnnotations>
    </ecore:EDataType>

    <!-- DateTimeWithZone Datatype -->
    <ecore:EDataType name="DateTimeWithZone">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="instanceClassName" value="java.time.ZonedDateTime"/>
      </eAnnotations>
    </ecore:EDataType>

    <!-- Customer -->
    <ecore:EClass name="Customer">
      <eStructuralFeatures>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
        <ecore:EReference name="reservations" eType="#//Reservation" upperBound="-1"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Seat -->
    <ecore:EClass name="Seat">
      <eStructuralFeatures>
        <ecore:EAttribute name="seatNumber" eType="ecore:EInt"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Reservation -->
    <ecore:EClass name="Reservation">
      <eStructuralFeatures>
        <ecore:EReference name="show" eType="#//Show"/>
        <ecore:EAttribute name="reservationTime" eType="#//DateTimeWithZone"/>
        <ecore:EReference name="customer" eType="#//Customer"/>
        <ecore:EReference name="seat" eType="#//Seat" containment="true"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <!-- Ticket -->
    <ecore:EClass name="Ticket">
      <eStructuralFeatures>
        <ecore:EReference name="show" eType="#//Show"/>
        <ecore:EReference name="seat" eType="#//Seat" containment="true"/>
      </eStructuralFeatures>
    </ecore:EClass>

  </ecore:EPackage>
</xmi:XMI>
