<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="HelpingHandsStore">

    <!-- Root container class -->
    <eClassifiers xmi:type="ecore:EClass" name="SystemRoot">
      <eStructuralFeatures xmi:type="ecore:EReference" name="residents" upperBound="-1" eType="#//Resident"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="pickupVehicles" upperBound="-1" eType="#//PickupVehicle"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="volunteerDrivers" upperBound="-1" eType="#//VolunteerDriver"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="pickups" upperBound="-1" eType="#//PickupRequest"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="articles" upperBound="-1" eType="#//Article"/>
    </eClassifiers>

    <!-- Resident class -->
    <eClassifiers xmi:type="ecore:EClass" name="Resident">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="streetAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="emailAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="pickupRequests" upperBound="-1" eType="#//PickupRequest"/>
    </eClassifiers>

    <!-- PickupVehicle class -->
    <eClassifiers xmi:type="ecore:EClass" name="PickupVehicle">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="vehicleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="availableStorageSpace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>

    <!-- VolunteerDriver class -->
    <eClassifiers xmi:type="ecore:EClass" name="VolunteerDriver">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="driverId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="availableDays" upperBound="-1" eType="#//DayOfWeek"/>
    </eClassifiers>

    <!-- Enum for Day of Week -->
    <eClassifiers xmi:type="ecore:EEnum" name="DayOfWeek">
      <eLiterals xmi:type="ecore:EEnumLiteral" name="MONDAY"/>
      <eLiterals xmi:type="ecore:EEnumLiteral" name="TUESDAY"/>
      <eLiterals xmi:type="ecore:EEnumLiteral" name="WEDNESDAY"/>
      <eLiterals xmi:type="ecore:EEnumLiteral" name="THURSDAY"/>
      <eLiterals xmi:type="ecore:EEnumLiteral" name="FRIDAY"/>
    </eClassifiers>

    <!-- PickupRequest class -->
    <eClassifiers xmi:type="ecore:EClass" name="PickupRequest">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="requestId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="resident" eType="#//Resident"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="streetAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="pickupTimeStart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/> <!-- Hour of day (8-14) -->
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="itemDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>

    <!-- Article class -->
    <eClassifiers xmi:type="ecore:EClass" name="Article">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="articleId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="category" eType="#//ArticleCategory"/>
    </eClassifiers>

    <!-- Enum for Article Category -->
    <eClassifiers xmi:type="ecore:EEnum" name="ArticleCategory">
      <eLiterals xmi:type="ecore:EEnumLiteral" name="BABY_CLOTHING"/>
      <eLiterals xmi:type="ecore:EEnumLiteral" name="WOMENS_WINTER_BOOTS"/>
      <eLiterals xmi:type="ecore:EEnumLiteral" name="FRIDGE"/>
      <eLiterals xmi:type="ecore:EEnumLiteral" name="MICROWAVE"/>
      <!-- Add other 130 categories as needed -->
    </eClassifiers>

    <!-- Association class for PickupVehicle and VolunteerDriver -->
    <eClassifiers xmi:type="ecore:EClass" name="DriverAssignment">
      <eStructuralFeatures xmi:type="ecore:EReference" name="vehicle" eType="#//PickupVehicle"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="driver" eType="#//VolunteerDriver"/>
    </eClassifiers>

  </ecore:EPackage>
</xmi:XMI>
