<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="facepage"
    nsURI="http://www.facepage.com/metamodel"
    nsPrefix="facepage">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="Facepage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users"
        eType="#//User" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts"
        eType="#//Account" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- User class -->
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dateOfBirth"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"
        lowerBound="1"/>
    <!-- A user has at most one account (either personal or business) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="account"
        eType="#//Account" upperBound="1"
        eOpposite="#//Account/owner"/>
  </eClassifiers>

  <!-- Abstract Account class -->
  <eClassifiers xsi:type="ecore:EClass" name="Account" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        lowerBound="1" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner"
        eType="#//User" lowerBound="1"
        eOpposite="#//User/account"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages"
        eType="#//Page" containment="true" upperBound="-1"
        eOpposite="#//Page/administrator"/>
  </eClassifiers>

  <!-- BusinessAccount class -->
  <eClassifiers xsi:type="ecore:EClass" name="BusinessAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="companyName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="monthlyFee"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        lowerBound="1"/>
  </eClassifiers>

  <!-- PersonalAccount class -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonalAccount" eSuperTypes="#//Account">
    <!-- Friend requests sent by this account -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentFriendRequests"
        eType="#//FriendRequest" containment="true" upperBound="-1"
        eOpposite="#//FriendRequest/sender"/>
    <!-- Friend requests received by this account (non-containment) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivedFriendRequests"
        eType="#//FriendRequest" upperBound="-1"
        eOpposite="#//FriendRequest/receiver"/>
    <!-- Pages to which this personal account has been granted privileges -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="privilegedPages"
        eType="#//Page" upperBound="-1"
        eOpposite="#//Page/privilegedAccounts"/>
    <!-- Operations for sending and receiving friend requests -->
    <eOperations name="sendFriendRequest">
      <eParameters name="target" eType="#//PersonalAccount"/>
    </eOperations>
    <eOperations name="receiveFriendRequest">
      <eParameters name="request" eType="#//FriendRequest"/>
    </eOperations>
  </eClassifiers>

  <!-- FriendRequest class -->
  <eClassifiers xsi:type="ecore:EClass" name="FriendRequest">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="#//FriendRequestStatus" lowerBound="1"/>
    <!-- Contained by sender -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender"
        eType="#//PersonalAccount" lowerBound="1"
        eOpposite="#//PersonalAccount/sentFriendRequests"/>
    <!-- Non-containment reference to receiver -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver"
        eType="#//PersonalAccount" lowerBound="1"
        eOpposite="#//PersonalAccount/receivedFriendRequests"/>
  </eClassifiers>

  <!-- FriendRequestStatus enumeration -->
  <eClassifiers xsi:type="ecore:EEnum" name="FriendRequestStatus">
    <eLiterals name="PENDING"/>
    <eLiterals name="ACCEPTED"/>
    <eLiterals name="REJECTED"/>
  </eClassifiers>

  <!-- Page class -->
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfVisits"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        lowerBound="1"/>
    <!-- Each page is administrated by exactly one account -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="administrator"
        eType="#//Account" lowerBound="1"
        eOpposite="#//Account/pages"/>
    <!-- Personal accounts granted privileges on this page -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="privilegedAccounts"
        eType="#//PersonalAccount" upperBound="-1"
        eOpposite="#//PersonalAccount/privilegedPages"/>
  </eClassifiers>

  <!-- AdvertisementPage class (special page only for BusinessAccount) -->
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisementPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounceRate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clickThroughRate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionRate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        lowerBound="1"/>
  </eClassifiers>

</ecore:EPackage>
