<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackages>
    <ePackage xmi:id="celo_package" name="CelO" nsURI="http://www.example.org/celo" eNSXMIFileType="ecore">
      <eClass xmi:id="celo_CelOSystem" name="CelOSystem">
        <eStructuralFeatures>
          <eReference xmi:id="sys_organizers" name="organizers" eType="#celo_Organizer" containment="true"/>
          <eReference xmi:id="sys_attendees" name="attendees" eType="#celo_Attendee" containment="true"/>
          <eReference xmi:id="sys_events" name="events" eType="#celo_Event" containment="true"/>
          <eReference xmi:id="sys_eventKinds" name="eventKinds" eType="#celo_EventKind" containment="true"/>
          <eReference xmi:id="sys_locations" name="locations" eType="#celo_Location" containment="true"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_User" name="User" abstract="true">
        <eStructuralFeatures>
          <eAttribute xmi:id="user_email" name="email" eType="eString"/>
          <eAttribute xmi:id="user_password" name="password" eType="eString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_Organizer" name="Organizer">
        <eSuperTypes>
          <eClass xmi:id="sup_org" reference="#celo_User"/>
        </eSuperTypes>
        <eStructuralFeatures>
          <eAttribute xmi:id="org_firstName" name="firstName" eType="eString"/>
          <eAttribute xmi:id="org_lastName" name="lastName" eType="eString"/>
          <eAttribute xmi:id="org_postalAddress" name="postalAddress" eType="eString"/>
          <eAttribute xmi:id="org_phoneNumber" name="phoneNumber" eType="eString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_Attendee" name="Attendee">
        <eSuperTypes>
          <eClass xmi:id="sup_att" reference="#celo_User"/>
        </eSuperTypes>
      </eClass>

      <eClass xmi:id="celo_EventKind" name="EventKind">
        <eStructuralFeatures>
          <eAttribute xmi:id="ek_name" name="name" eType="eString"/>
          <eReference xmi:id="ek_templates" name="taskTemplates" eType="#celo_TaskTemplate" containment="true"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_TaskTemplate" name="TaskTemplate">
        <eStructuralFeatures>
          <eAttribute xmi:id="tt_desc" name="description" eType="eString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_Location" name="Location">
        <eStructuralFeatures>
          <eAttribute xmi:id="loc_name" name="name" eType="eString"/>
          <eAttribute xmi:id="loc_address" name="address" eType="eString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_Event" name="Event">
        <eStructuralFeatures>
          <eAttribute xmi:id="ev_occasion" name="occasion" eType="eString"/>
          <eAttribute xmi:id="ev_start" name="startTime" eType="eDate"/>
          <eAttribute xmi:id="ev_end" name="endTime" eType="eDate"/>
          <eReference xmi:id="ev_loc" name="location" eType="#celo_Location"/>
          <eReference xmi:id="ev_kind" name="eventKind" eType="#celo_EventKind"/>
          <eReference xmi:id="ev_invites" name="invitations" eType="#celo_Invitation" containment="true"/>
          <eReference xmi:id="ev_tasks" name="tasks" eType="#celo_EventTask" containment="true"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_Invitation" name="Invitation">
        - Association Class between Event and Attendee -
        <eStructuralFeatures>
          <eReference xmi:id="inv_att" name="attendee" eType="#celo_Attendee"/>
          <eAttribute xmi:id="inv_status" name="status" eType="#celo_AttendanceStatus"/>
        </eStructuralFeatures>
      </eClass>

      <eClass xmi:id="celo_EventTask" name="EventTask">
        <eStructuralFeatures>
          <eReference xmi:id="et_temp" name="template" eType="#celo_TaskTemplate"/>
          <eAttribute xmi:id="et_status" name="status" eType="#celo_TaskStatus"/>
          <eReference xmi:id="et_perf" name="performingAttendee" eType="#celo_Attendee"/>
        </eStructuralFeatures>
      </eClass>

      <eEnum xmi:id="celo_AttendanceStatus" name="AttendanceStatus">
        <eLiterals>
          <eLiteral name="confirmed"/>
          <eLiteral name="maybe"/>
          <eLiteral name="cannotAttend"/>
          <eLiteral name="notReplied"/>
        </eLiterals>
      </eEnum>

      <eEnum xmi:id="celo_TaskStatus" name="TaskStatus">
        <eLiterals>
          <eLiteral name="needsToBeDone"/>
          <eLiteral name="hasBeenDone"/>
          <eLiteral name="notApplicable"/>
        </eLiterals>
      </eEnum>
    </ePackage>
  </ePackages>
</xmi:XMI>
