<model xmlns="org.eclipse.emf.ecore:1.0"
       xsi:schemaLocation="http://www.eclipse.org/emf/2003/xmi http://www.eclipse.org/emf/2003/XMI.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <!-- Root container class -->
  <EClass name="TransportCompany" abstract="false">

    <!-- Enumeration for vehicle types -->
    <EEnum name="VehicleType">
      <eLiteral name="RefrigeratedTruck"/>
      <eLiteral name="SmallVan"/>
      <eLiteral name="LoadingPlatform"/>
      <eLiteral name="BoxTruck"/>
    </EEnum>

    <!-- Data type for time without date using java.time.LocalTime -->
    <EDatatype name="LocalTime" instanceClassName="java.time.LocalTime"/>

    <!-- Employee class -->
    <EClass name="Employee" abstract="false">
      <EAttribute name="name" eType="string"/>
      <EAttribute name="socialSecurityNumber" eType="string"/>
    </EClass>

    <!-- Planner class (specialization of Employee) -->
    <EClass name="Planner" abstract="false">
      <ESuperType>
        <eStructuralFeatures eType="Employee"/>
      </ESuperType>
      <EAttribute name="username" eType="string"/>
      <EAttribute name="password" eType="string"/>
    </EClass>

    <!-- AdministrativeStaff class (specialization of Employee) -->
    <EClass name="AdministrativeStaff" abstract="false">
      <ESuperType>
        <eStructuralFeatures eType="Employee"/>
      </ESuperType>
      <EAttribute name="fieldOfActivity" eType="string"/>
      <EAttribute name="username" eType="string"/>
      <EAttribute name="password" eType="string"/>
    </EClass>

    <!-- Customer class -->
    <EClass name="Customer" abstract="false">
      <EAttribute name="name" eType="string"/>
      <EAttribute name="billingAddress" eType="string"/>
    </EClass>

    <!-- PartnerCompany class -->
    <EClass name="PartnerCompany" abstract="false">
      <EAttribute name="name" eType="string"/>
      <EAttribute name="address" eType="string"/>
    </EClass>

    <!-- Vehicle class -->
    <EClass name="Vehicle" abstract="false">
      <EAttribute name="licensePlateNumber" eType="string"/>
      <EAttribute name="mileage" eType="int"/>
      <EAttribute name="type" eType="VehicleType"/>
    </EClass>

    <!-- RepairShop class -->
    <EClass name="RepairShop" abstract="false">
      <EAttribute name="name" eType="string"/>
      <EAttribute name="address" eType="string"/>
    </EClass>

    <!-- Order class with operations -->
    <EClass name="Order" abstract="false">
      <EReference name="customer" lowerBound="1" eType="Customer"/>
      <EAttribute name="pickUpAddress" eType="string"/>
      <EAttribute name="deliveryAddress" eType="string"/>
      <EAttribute name="comment" eType="string"/>
      <EReference name="assignedToDriver" upperBound="1" eType="Driver" changeable="false"/>
      <EReference name="assignedVehicle" upperBound="1" eType="Vehicle" changeable="false"/>

      <!-- Operation to start the order -->
      <EOperation name="startOrder">
        <EParameter name="startTime" eType="LocalTime"/>
      </EOperation>

      <!-- Operation to finish the order -->
      <EOperation name="finishOrder">
        <EParameter name="endTime" eType="LocalTime"/>
      </EOperation>
    </EClass>

    <!-- Driver class -->
    <EClass name="Driver" abstract="false">
      <EAttribute name="name" eType="string"/>
      <EAttribute name="socialSecurityNumber" eType="string"/>
      <EReference name="orders" upperBound="-1" eType="Order" opposite="assignedToDriver" changeable="false" containment="true"/>
    </EClass>

    <!-- AssignmentAssociation as association class for the relationship between Planner and Order -->
    <EClass name="AssignmentAssociation" abstract="false">
      <EReference name="planner" lowerBound="1" eType="Planner" opposite="assignments" changeable="false"/>
      <EReference name="order" lowerBound="1" eType="Order" opposite="assignment" changeable="false"/>
    </EClass>

    <!-- Extend Planner and Order to reference AssignmentAssociation -->
    <EReference name="assignments" upperBound="-1" containment="true" opposite="planner" eType="AssignmentAssociation" changeable="false" container="Planner"/>
    <EReference name="assignment" upperBound="1" eType="AssignmentAssociation" opposite="order" changeable="false" container="Order"/>

    <!-- Repair class as association class for the relationship between Vehicle and RepairShop -->
    <EClass name="Repair" abstract="false">
      <EReference name="vehicle" lowerBound="1" eType="Vehicle" opposite="repairs" changeable="false"/>
      <EReference name="repairShop" lowerBound="1" eType="RepairShop" opposite="repairsPerformed" changeable="false"/>
      <EReference name="employeeInCharge" upperBound="1" eType="Employee" opposite="performedRepairs" changeable="false"/>
      <EAttribute name="duration" eType="int"/>
      <EAttribute name="cost" eType="float"/>
    </EClass>

    <!-- Extend Vehicle, RepairShop, and Employee to reference Repair -->
    <EReference name="repairs" upperBound="-1" containment="false" opposite="vehicle" eType="Repair" changeable="false" container="Vehicle"/>
    <EReference name="repairsPerformed" upperBound="-1" containment="false" opposite="repairShop" eType="Repair" changeable="false" container="RepairShop"/>
    <EReference name="performedRepairs" upperBound="-1" containment="false" opposite="employeeInCharge" eType="Repair" changeable="false" container="Employee"/>

    <!-- Root class features to contain all other classes -->
    <EReference name="drivers" upperBound="-1" containment="true" eType="Driver"/>
    <EReference name="planners" upperBound="-1" containment="true" eType="Planner"/>
    <EReference name="administrativeStaff" upperBound="-1" containment="true" eType="AdministrativeStaff"/>
    <EReference name="customers" upperBound="-1" containment="true" eType="Customer"/>
    <EReference name="partnerCompanies" upperBound="-1" containment="true" eType="PartnerCompany"/>
    <EReference name="vehicles" upperBound="-1" containment="true" eType="Vehicle"/>
    <EReference name="repairShops" upperBound="-1" containment="true" eType="RepairShop"/>
    <EReference name="orders" upperBound="-1" containment="true" eType="Order"/>
  </EClass>
</model>
