<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="medicalSystem"
    nsURI="http://www.example.org/medicalSystem"
    nsPrefix="medicalSystem">

  <eClassifiers xsi:type="ecore:EClass" name="ProblemType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatmentPlan"
        lowerBound="0" upperBound="1"
        eType="#//TreatmentPlan"
        eOpposite="#//TreatmentPlan/problemType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnoses"
        lowerBound="0" upperBound="-1"
        eType="#//Diagnosis"
        eOpposite="#//Diagnosis/problemType"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TreatmentPlan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="problemType"
        lowerBound="1" upperBound="1"
        eType="#//ProblemType"
        eOpposite="#//ProblemType/treatmentPlan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advisedExaminationTypes"
        lowerBound="0" upperBound="-1"
        eType="#//AdvisedExaminationType"
        eOpposite="#//AdvisedExaminationType/treatmentPlan"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatments"
        lowerBound="0" upperBound="-1"
        eType="#//Treatment"
        eOpposite="#//Treatment/treatmentPlan"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="AdvisedExaminationType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatmentPlan"
        lowerBound="1" upperBound="1"
        eType="#//TreatmentPlan"
        eOpposite="#//TreatmentPlan/advisedExaminationTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examinationType"
        lowerBound="1" upperBound="1"
        eType="#//ExaminationType"
        eOpposite="#//ExaminationType/advisedExaminationTypes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advisedExaminations"
        lowerBound="0" upperBound="-1"
        eType="#//AdvisedExamination"
        eOpposite="#//AdvisedExamination/advisedExaminationType"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ExaminationType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advisedExaminationTypes"
        lowerBound="0" upperBound="-1"
        eType="#//AdvisedExaminationType"
        eOpposite="#//AdvisedExaminationType/examinationType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions"
        lowerBound="0" upperBound="-1"
        eType="#//Permission"
        eOpposite="#//Permission/examinationType"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Diagnosis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="problemType"
        lowerBound="1" upperBound="1"
        eType="#//ProblemType"
        eOpposite="#//ProblemType/diagnoses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatments"
        lowerBound="0" upperBound="-1"
        eType="#//Treatment"
        eOpposite="#//Treatment/diagnosis"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="consultation"
        lowerBound="1" upperBound="1"
        eType="#//Consultation"
        eOpposite="#//Consultation/diagnoses"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Treatment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatmentPlan"
        lowerBound="1" upperBound="1"
        eType="#//TreatmentPlan"
        eOpposite="#//TreatmentPlan/treatments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnosis"
        lowerBound="1" upperBound="1"
        eType="#//Diagnosis"
        eOpposite="#//Diagnosis/treatments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advisedExaminations"
        lowerBound="0" upperBound="-1"
        eType="#//AdvisedExamination"
        eOpposite="#//AdvisedExamination/treatment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="freeExaminations"
        lowerBound="0" upperBound="-1"
        eType="#//FreeExamination"
        eOpposite="#//FreeExamination/treatment"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="AdvisedExamination">
    <eStructuralFeatures xsi:type="ecore:EReference" name="advisedExaminationType"
        lowerBound="1" upperBound="1"
        eType="#//AdvisedExaminationType"
        eOpposite="#//AdvisedExaminationType/advisedExaminations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatment"
        lowerBound="1" upperBound="1"
        eType="#//Treatment"
        eOpposite="#//Treatment/advisedExaminations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permission"
        lowerBound="1" upperBound="1"
        eType="#//Permission"
        eOpposite="#//Permission/advisedExaminations"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Permission">
    <eStructuralFeatures xsi:type="ecore:EReference" name="advisedExaminations"
        lowerBound="0" upperBound="-1"
        eType="#//AdvisedExamination"
        eOpposite="#//AdvisedExamination/permission"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="freeExaminations"
        lowerBound="0" upperBound="-1"
        eType="#//FreeExamination"
        eOpposite="#//FreeExamination/permission"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="examinationType"
        lowerBound="1" upperBound="1"
        eType="#//ExaminationType"
        eOpposite="#//ExaminationType/permissions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hospital"
        lowerBound="1" upperBound="1"
        eType="#//Hospital"
        eOpposite="#//Hospital/permissions"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Consultation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnoses"
        lowerBound="0" upperBound="-1"
        eType="#//Diagnosis"
        eOpposite="#//Diagnosis/consultation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="affiliation"
        lowerBound="1" upperBound="1"
        eType="#//Affiliation"
        eOpposite="#//Affiliation/consultations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patient"
        lowerBound="1" upperBound="1"
        eType="#//Patient"
        eOpposite="#//Patient/consultations"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="FreeExamination">
    <eStructuralFeatures xsi:type="ecore:EReference" name="treatment"
        lowerBound="1" upperBound="1"
        eType="#//Treatment"
        eOpposite="#//Treatment/freeExaminations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permission"
        lowerBound="1" upperBound="1"
        eType="#//Permission"
        eOpposite="#//Permission/freeExaminations"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Patient">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consultations"
        lowerBound="0" upperBound="-1"
        eType="#//Consultation"
        eOpposite="#//Consultation/patient"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Affiliation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="consultations"
        lowerBound="0" upperBound="-1"
        eType="#//Consultation"
        eOpposite="#//Consultation/affiliation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doctor"
        lowerBound="1" upperBound="1"
        eType="#//Doctor"
        eOpposite="#//Doctor/affiliations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hospital"
        lowerBound="1" upperBound="1"
        eType="#//Hospital"
        eOpposite="#//Hospital/affiliations"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Doctor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affiliations"
        lowerBound="0" upperBound="-1"
        eType="#//Affiliation"
        eOpposite="#//Affiliation/doctor"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Hospital">
    <eStructuralFeatures xsi:type="ecore:EReference" name="affiliations"
        lowerBound="0" upperBound="-1"
        eType="#//Affiliation"
        eOpposite="#//Affiliation/hospital"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="permissions"
        lowerBound="0" upperBound="-1"
        eType="#//Permission"
        eOpposite="#//Permission/hospital"/>
  </eClassifiers>

</ecore:EPackage>
