<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmlns:xmi="http://www.omg.org/XMI"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
                xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore
                                    http://www.eclipse.org/emf/2002/Ecore.xsd"
                ePackageUri="AirTravel.ecore" name="AirTravel">
                
  <eClassifiers xsi:type="ecore:EEnum" name="DayOfWeek"/>
  
  <!-- EntityContainer for Top-Level Entities -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_0" name="EntityContainer"/>

  <!-- Aircraft Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_1" name="Aircraft">
    <eStructuralFeatures>
      <eAttribute xmi:id="_2" eType="#//EString">name</eAttribute>
      <eAttribute xmi:id="_3" eType="#//EString">type</eAttribute>
      <eAttribute xmi:id="_4" eType="ecore:EInt">yearOfManufacture</eAttribute>
      <eAttribute xmi:id="_5" eType="ecore:EDate">nextInspectionDate</eAttribute>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Flight Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_6" name="Flight">
    <eStructuralFeatures>
      <eAttribute xmi:id="_7" eType="#//EString">flightNumber</eAttribute>
      <eAttribute xmi:id="_8" eType="ecore:EDate">flightDate</eAttribute>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Passenger Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_9" name="Passenger">
    <eStructuralFeatures>
      <eAttribute xmi:id="__0" eType="#//EString">name</eAttribute>
      <eAttribute xmi:id="_A" eType="#//EString">passportNumber</eAttribute>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Ticket Association Class -->
  <eClassifiers xsi:type="ecore:EAssociationClass" xmi:id="_B" name="Ticket">
    <eStructuralFeatures>
      <eAttribute xmi:id="_C" eType="#//EString">ticketNumber</eAttribute>
      <eAttribute xmi:id="_D" eType="ecore:EDouble">price</eAttribute>
      <eAttribute xmi:id="_E" eType="ecore:EBoolean">upgradeDesired</eType>
    </eStructuralFeatures>

    <!-- Bidirectional Associations -->
    <eReferences base="_9" eOpposite="_F">
      <eLowerValue>1</eLowerValue>
      <eUpperValue>-1</eUpperValue>
      <rOrdered>true</rOrdered>
    </eReferences>

    <eReferences base="_6" eOpposite="_G">
      <eLowerValue>1</eLowerValue>
      <eUpperValue>1</eUpperValue>
      <rContainment>false</rContainment>
      <rOrdered>true</rOrdered>
    </eReferences>
  </eClassifiers>

  <!-- PassengerAircraft as Subclass of Aircraft -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_H" name="PassengerAircraft">
    <eSuperTypes eType="#//Aircraft"/>
    <eStructuralFeatures>
      <eAttribute xmi:id="_I" eType="ecore:EInt">numberOfSeats</eType>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- SeatCategory Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_J" name="SeatCategory">
    <eStructuralFeatures>
      <eAttribute xmi:id="_K" eType="#//EString">designation</eType>
      <eAttribute xmi:id="_L" eType="ecore:EBoolean">entertainmentProvided</eType>
      <eAttribute xmi:id="_M" eType="ecore:EInt">numberOfSeats</eType>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Airline Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_N" name="Airline">
    <eStructuralFeatures>
      <eAttribute xmi:id="_O" eType="#//EString">name</eType>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- FlightAttendant Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_P" name="FlightAttendant">
    <eStructuralFeatures>
      <eAttribute xmi:id="_Q" eType="#//EString">name</eType>
      <eAttribute xmi:id="_R" eType="ecore:EDate">dateOfEmployment</eType>
      <eAttribute xmi:id="_S" eType="ecore:EBoolean">isChiefSteward</eType>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Pilot Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_T" name="Pilot">
    <eStructuralFeatures>
      <eAttribute xmi:id="_U" eType="#//EString">name</eType>
      <eAttribute xmi:id="_V" eType="ecore:EDate">dateOfEmployment</eType>
      <eAttribute xmi:id="_W" eType="#//EString">license</eType>
    </eStructuralFeatures>
  </eClassifiers>

  <!-- Airport Class -->
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_X" name="Airport">
    <eStructuralFeatures>
      <eAttribute xmi:id="_Y" eType="#//EString">name</eType>
      <eAttribute xmi:id="_Z" eType="#//EString">address</eType>
      <eAttribute xmi:id="__A" eType="ecore:EInt">numberOfRunways</eType>
    </eStructuralFeatures>
  </eClassifiers>

</ecore:EPackage>
