<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="CelebrationsOrganizationSystem" nsURI="celebrationsorganization.system" nsPrefix="cos" eClassifiers="RootContainer EventType Location Organizer Attendee Invitation Task Event InvitationStatus TaskStatus CustomTimeWithoutDate">
    <!-- Root Container -->
    <ecore:EClass name="RootContainer">
      <ecore:EAttribute name="name" eType="ecore:EString"/>
      <ecore:EReference name="eventTypes" eType="#//EventType" upperBound="-1" containment="true"/>
      <ecore:EReference name="locations" eType="#//Location" upperBound="-1" containment="true"/>
      <ecore:EReference name="organizers" eType="#//Organizer" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Event Type -->
    <ecore:EClass name="EventType">
      <ecore:EAttribute name="name" eType="ecore:EString"/>
      <ecore:EReference name="tasks" eType="#//Task" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Location -->
    <ecore:EClass name="Location">
      <ecore:EAttribute name="name" eType="ecore:EString"/>
      <ecore:EAttribute name="address" eType="ecore:EString"/>
    </ecore:EClass>

    <!-- Organizer -->
    <ecore:EClass name="Organizer">
      <ecore:EAttribute name="firstName" eType="ecore:EString"/>
      <ecore:EAttribute name="lastName" eType="ecore:EString"/>
      <ecore:EAttribute name="email" eType="ecore:EString"/>
      <ecore:EAttribute name="address" eType="ecore:EString"/>
      <ecore:EAttribute name="phoneNumber" eType="ecore:EString"/>
      <ecore:EAttribute name="password" eType="ecore:EString"/>

      <!-- Event-related attributes -->
      <ecore:EReference name="events" eType="#//Event" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Attendee -->
    <ecore:EClass name="Attendee">
      <ecore:EAttribute name="firstName" eType="ecore:EString"/>
      <ecore:EAttribute name="lastName" eType="ecore:EString"/>
      <ecore:EAttribute name="email" eType="ecore:EString"/>
      <ecore:EReference name="tasksToAccomplish" eType="#//Task" upperBound="-1"/>
    </ecore:EClass>

    <!-- Invitation -->
    <ecore:EClass name="Invitation">
      <ecore:EAttribute name="status" eType="#//InvitationStatus"/>

      <!-- Associations -->
      <ecore:EReference name="attendee" eType="#//Attendee"/>
      <ecore:EReference name="event" eType="#//Event"/>
    </ecore:EClass>

    <!-- Task -->
    <ecore:EClass name="Task">
      <ecore:EAttribute name="description" eType="ecore:EString"/>
      <ecore:EAttribute name="status" eType="#//TaskStatus"/>

      <!-- Associations -->
      <ecore:EReference name="assignedToAttendee" eType="#//Attendee" upperBound="-1"/>
    </ecore:EClass>

    <!-- Event -->
    <ecore:EClass name="Event">
      <ecore:EAttribute name="type" eType="#//EventType"/>
      <ecore:EAttribute name="startDateTime" eType="#//CustomTimeWithoutDate"/>
      <ecore:EAttribute name="endDateTime" eType="#//CustomTimeWithoutDate"/>
      <ecore:EAttribute name="occasion" eType="ecore:EString"/>
      <ecore:EAttribute name="location" eType="#//Location"/>

      <!-- Associations -->
      <ecore:EReference name="organizers" eType="#//Organizer" upperBound="-1"/>
      <ecore:EReference name="attendees" eType="#//Attendee" upperBound="-1"/>
      <ecore:EReference name="tasks" eType="#//Task" upperBound="-1"/>
    </ecore:EClass>

    <!-- Enumerations -->
    <ecore:EEnum name="InvitationStatus">
      <ecore:ELiteral name="Attending" value="0"/>
      <ecore:ELiteral name="MaybeAttending" value="1"/>
      <ecore:ELiteral name="CannotAttend" value="2"/>
    </ecore:EEnum>

    <ecore:EEnum name="TaskStatus">
      <ecore:ELiteral name="ToDo" value="0"/>
      <ecore:ELiteral name="Done" value="1"/>
      <ecore:ELiteral name="NotApplicable" value="2"/>
    </ecore:EEnum>

    <!-- Custom Data Type for Time Without Date -->
    <ecore:EDataType name="CustomTimeWithoutDate">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="baseType" value="java.time.LocalTime"/>
      </eAnnotations>
    </ecore:EDataType>
  </ecore:EPackage>
</xmi:XMI>
