<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="researchModel"
    nsURI="http://www.example.org/researchModel"
    nsPrefix="researchModel">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="ResearchModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons"
        eType="#//Person" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="researchInstitutions"
        eType="#//ResearchInstitution" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishers"
        eType="#//Publisher" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- Person class -->
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keywords"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- worksFor opposite -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="worksFor"
        eType="#//ResearchInstitution" lowerBound="1"
        eOpposite="#//ResearchInstitution/employees"/>
    <!-- reviews relation -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="reviews"
        eType="#//PeerReviewedPaper" upperBound="-1"
        eOpposite="#//PeerReviewedPaper/reviewers"/>
    <!-- authorship (association class) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorships"
        eType="#//Author" upperBound="-1"
        eOpposite="#//Author/person"/>
  </eClassifiers>

  <!-- ResearchInstitution class -->
  <eClassifiers xsi:type="ecore:EClass" name="ResearchInstitution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="institutionCode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees"
        eType="#//Person" upperBound="-1"
        eOpposite="#//Person/worksFor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribesTo"
        eType="#//Journal" upperBound="-1"
        eOpposite="#//Journal/subscribingInstitutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishesTechnicalReports"
        eType="#//TechnicalReport" upperBound="-1" containment="true"
        eOpposite="#//TechnicalReport/publishingInstitution"/>
  </eClassifiers>

  <!-- Article class (abstract, since it has total disjoint subclasses) -->
  <eClassifiers xsi:type="ecore:EClass" name="Article" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doi"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- association class side: authorships -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="authorships"
        eType="#//Author" upperBound="-1" containment="true"
        eOpposite="#//Author/article"/>
  </eClassifiers>

  <!-- Author association class between Article and Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Author">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="article"
        eType="#//Article" lowerBound="1"
        eOpposite="#//Article/authorships"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        eType="#//Person" lowerBound="1"
        eOpposite="#//Person/authorships"/>
  </eClassifiers>

  <!-- PeerReviewedPaper class -->
  <!-- PeerReviewedPaper is contained by Journal, so not in root -->
  <eClassifiers xsi:type="ecore:EClass" name="PeerReviewedPaper" eSuperTypes="#//Article">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="citationCount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reviewers"
        eType="#//Person" upperBound="-1"
        eOpposite="#//Person/reviews"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishedIn"
        eType="#//Journal" lowerBound="1"
        eOpposite="#//Journal/peerReviewedPapers"/>
  </eClassifiers>

  <!-- TechnicalReport class -->
  <!-- TechnicalReport is contained by ResearchInstitution, so not in root -->
  <eClassifiers xsi:type="ecore:EClass" name="TechnicalReport" eSuperTypes="#//Article">
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishingInstitution"
        eType="#//ResearchInstitution" lowerBound="1"
        eOpposite="#//ResearchInstitution/publishesTechnicalReports"/>
  </eClassifiers>

  <!-- Publisher class -->
  <eClassifiers xsi:type="ecore:EClass" name="Publisher">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Publisher contains Journals -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishes"
        eType="#//Journal" upperBound="-1" containment="true"
        eOpposite="#//Journal/publisher"/>
  </eClassifiers>

  <!-- Journal class -->
  <!-- Journal is contained by Publisher, so not in root -->
  <eClassifiers xsi:type="ecore:EClass" name="Journal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impactFactor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publisher"
        eType="#//Publisher" lowerBound="1"
        eOpposite="#//Publisher/publishes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subscribingInstitutions"
        eType="#//ResearchInstitution" upperBound="-1"
        eOpposite="#//ResearchInstitution/subscribesTo"/>
    <!-- Journal contains PeerReviewedPapers -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="peerReviewedPapers"
        eType="#//PeerReviewedPaper" upperBound="-1" containment="true"
        eOpposite="#//PeerReviewedPaper/publishedIn"/>
  </eClassifiers>

</ecore:EPackage>
