<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="transport"
    nsURI="http://www.example.org/transport"
    nsPrefix="transport">

  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes"
        lowerBound="0" upperBound="-1"
        eType="#//Driver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from"
        lowerBound="1" upperBound="1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to"
        lowerBound="1" upperBound="1"
        eType="#//Location"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle"
        lowerBound="1" upperBound="1"
        eType="#//Vehicle"
        containment="true"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drives"
        lowerBound="0" upperBound="-1"
        eType="#//Vehicle"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver"
        lowerBound="0" upperBound="-1"
        eType="#//Driver"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="status"
        lowerBound="1" upperBound="1"
        eType="#//VehicleStatus"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Truck" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tonnage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PassengerCar" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Transporter" eSuperTypes="#//Vehicle"/>

  <eClassifiers xsi:type="ecore:EEnum" name="VehicleStatus">
    <eLiterals name="READY" value="0"/>
    <eLiterals name="ASSIGNMENT" value="1"/>
    <eLiterals name="MAINTENANCE" value="2"/>
  </eClassifiers>

</ecore:EPackage>
