<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="transportPackage"
    nsURI="http://www.example.org/transportPackage"
    nsPrefix="transportPackage">

  <!-- Root container class -->
  <eClassifiers xsi:type="ecore:EClass" name="TransportSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignments"
        eType="#//Assignment" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations"
        eType="#//Location" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drivers"
        eType="#//Driver" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicles"
        eType="#//Vehicle" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!-- Assignment class -->
  <eClassifiers xsi:type="ecore:EClass" name="Assignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Assignment "0..1" - executes -> "*" Driver -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes"
        eType="#//Driver" upperBound="-1"/>
    <!-- Assignment "*" - from -> "1" Location -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="from"
        eType="#//Location" lowerBound="1"/>
    <!-- Assignment "*" - to -> "1" Location -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="to"
        eType="#//Location" lowerBound="1"/>
  </eClassifiers>

  <!-- Location class -->
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Location "1" *- composites -> "1" Vehicle -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="vehicle"
        eType="#//Vehicle" containment="true" lowerBound="1"/>
  </eClassifiers>

  <!-- Driver class -->
  <eClassifiers xsi:type="ecore:EClass" name="Driver">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Driver "1..*" - driver -> "*" Vehicle -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="driverVehicles"
        eType="#//Vehicle" upperBound="-1"/>
  </eClassifiers>

  <!-- Vehicle class -->
  <eClassifiers xsi:type="ecore:EClass" name="Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vehicleNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Vehicle "0..1" - driver -> "*" Driver -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="driver"
        eType="#//Driver" upperBound="-1"/>
    <!-- Vehicle "1" - status -> "1" VehicleStatus (EEnum used as EAttribute) -->
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="#//VehicleStatus" lowerBound="1"/>
  </eClassifiers>

  <!-- Truck class (extends Vehicle) -->
  <eClassifiers xsi:type="ecore:EClass" name="Truck" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tonnage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- PassengerCar class (extends Vehicle) -->
  <eClassifiers xsi:type="ecore:EClass" name="PassengerCar" eSuperTypes="#//Vehicle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seats"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- Transporter class (extends Vehicle) -->
  <eClassifiers xsi:type="ecore:EClass" name="Transporter" eSuperTypes="#//Vehicle"/>

  <!-- VehicleStatus enum -->
  <eClassifiers xsi:type="ecore:EEnum" name="VehicleStatus">
    <eLiterals name="READY" value="0"/>
    <eLiterals name="ASSIGNMENT" value="1"/>
    <eLiterals name="MAINTENANCE" value="2"/>
  </eClassifiers>

</ecore:EPackage>
