<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="music"
    nsURI="http://www.example.org/music"
    nsPrefix="music">

  <!-- Root container: MusicCatalog -->
  <eClassifiers xsi:type="ecore:EClass" name="MusicCatalog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artists"
        eType="#//Artist" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users"
        eType="#//User" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albums"
        eType="#//Album" containment="true" upperBound="-1"/>
  </eClassifiers>

  <!--
    Song class
    - title, year, length, genre attributes
    - artist: back-reference to Artist (opposite of Artist/songs)
    - publishedBy: reference to BusinessUser (many Songs to one BusinessUser)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="Song">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genre"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artist"
        eType="#//Artist"
        eOpposite="#//Artist/songs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishedBy"
        eType="#//BusinessUser"
        eOpposite="#//BusinessUser/songs"/>
  </eClassifiers>

  <!--
    Artist class
    - birthDate (EDate), name, website attributes
    - songs: contained songs by this artist (opposite of Song/artist)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="Artist">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="website"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="songs"
        eType="#//Song" containment="true" upperBound="-1"
        eOpposite="#//Song/artist"/>
  </eClassifiers>

  <!--
    User class (abstract, with {total} constraint meaning all users
    are either RegularUser or BusinessUser)
    - userID, name, address attributes
  -->
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userID"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!--
    RegularUser class (subclass of User)
    - singles: associated singles (opposite of Single/regularUsers)
    - composedAlbums: albums composed by this user (containment,
        opposite of Album/composer)
    - suggestedAlbums: albums suggested by this user
        (opposite of Album/suggestedBy)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="RegularUser" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="singles"
        eType="#//Single" upperBound="-1"
        eOpposite="#//Single/regularUsers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedAlbums"
        eType="#//Album" upperBound="-1" containment="true"
        eOpposite="#//Album/composer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedAlbums"
        eType="#//Album" upperBound="-1"
        eOpposite="#//Album/suggestedBy"/>
  </eClassifiers>

  <!--
    BusinessUser class (subclass of User, {overlap} so can also be RegularUser)
    - vATnumber attribute
    - songs: songs published by this business user (opposite of Song/publishedBy)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="BusinessUser" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vATnumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="songs"
        eType="#//Song" upperBound="-1"
        eOpposite="#//Song/publishedBy"/>
  </eClassifiers>

  <!--
    Single class (subclass of Song, disjoint from Hit)
    - regularUsers: users who own/follow this single
        (opposite of RegularUser/singles)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="Single" eSuperTypes="#//Song">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regularUsers"
        eType="#//RegularUser" upperBound="-1"
        eOpposite="#//RegularUser/singles"/>
  </eClassifiers>

  <!--
    Hit class (subclass of Song, disjoint from Single)
    - tracks: Track instances linking this Hit to Albums
        (containment, opposite of Track/hit)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="Hit" eSuperTypes="#//Song">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks"
        eType="#//Track" containment="true" upperBound="-1"
        eOpposite="#//Track/hit"/>
  </eClassifiers>

  <!--
    Album class (implied by the diagram)
    - tracks: Track instances linking this Album to Hits
        (opposite of Track/album)
    - composer: the RegularUser who composed this album
        (opposite of RegularUser/composedAlbums)
    - suggestedBy: RegularUsers who suggested this album
        (opposite of RegularUser/suggestedAlbums)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks"
        eType="#//Track" upperBound="-1"
        eOpposite="#//Track/album"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composer"
        eType="#//RegularUser"
        eOpposite="#//RegularUser/composedAlbums"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedBy"
        eType="#//RegularUser" upperBound="-1"
        eOpposite="#//RegularUser/suggestedAlbums"/>
  </eClassifiers>

  <!--
    Track class (association class between Hit and Album)
    - trackNumber attribute
    - hit: the Hit this track belongs to (opposite of Hit/tracks)
    - album: the Album this track belongs to (opposite of Album/tracks)
  -->
  <eClassifiers xsi:type="ecore:EClass" name="Track">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hit"
        eType="#//Hit"
        eOpposite="#//Hit/tracks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="album"
        eType="#//Album"
        eOpposite="#//Album/tracks"/>
  </eClassifiers>

</ecore:EPackage>
