<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="musicModel"
    nsURI="http://www.example.org/musicModel"
    nsPrefix="musicModel">

  <!-- Song class -->
  <eClassifiers xsi:type="ecore:EClass" name="Song">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Genre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Song to Artist: many Songs linked to one Artist -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="artist"
        eType="#//Artist"
        lowerBound="1"
        eOpposite="#//Artist/songs"/>
    <!-- Song to BusinessUser: many Songs linked to one BusinessUser -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessUser"
        eType="#//BusinessUser"
        lowerBound="1"
        eOpposite="#//BusinessUser/songs"/>
  </eClassifiers>

  <!-- Artist class -->
  <eClassifiers xsi:type="ecore:EClass" name="Artist">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BirthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Website" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Artist to Song: one Artist linked to many Songs -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="songs"
        eType="#//Song"
        upperBound="-1"
        eOpposite="#//Song/artist"/>
  </eClassifiers>

  <!-- User class -->
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UserID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- RegularUser class, extends User -->
  <eClassifiers xsi:type="ecore:EClass" name="RegularUser" eSuperTypes="#//User">
    <!-- RegularUser to Single: many-to-many -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="singles"
        eType="#//Single"
        upperBound="-1"
        eOpposite="#//Single/regularUsers"/>
    <!-- RegularUser composes Album: one RegularUser composes many Albums -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedAlbums"
        eType="#//Album"
        upperBound="-1"
        containment="true"
        eOpposite="#//Album/composer"/>
    <!-- RegularUser suggests Album: many-to-many -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedAlbums"
        eType="#//Album"
        upperBound="-1"
        eOpposite="#//Album/suggestedBy"/>
  </eClassifiers>

  <!-- BusinessUser class, extends User -->
  <eClassifiers xsi:type="ecore:EClass" name="BusinessUser" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VATnumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- BusinessUser to Song: one BusinessUser linked to many Songs -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="songs"
        eType="#//Song"
        upperBound="-1"
        eOpposite="#//Song/businessUser"/>
  </eClassifiers>

  <!-- Hit class, extends Song -->
  <eClassifiers xsi:type="ecore:EClass" name="Hit" eSuperTypes="#//Song">
    <!-- Hit to Track (association class connecting Hit and Album) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks"
        eType="#//Track"
        upperBound="-1"
        eOpposite="#//Track/hit"/>
  </eClassifiers>

  <!-- Single class, extends Song -->
  <eClassifiers xsi:type="ecore:EClass" name="Single" eSuperTypes="#//Song">
    <!-- Single to RegularUser: many-to-many -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="regularUsers"
        eType="#//RegularUser"
        upperBound="-1"
        eOpposite="#//RegularUser/singles"/>
  </eClassifiers>

  <!-- Album class -->
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <!-- Album to Track (association class connecting Hit and Album) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks"
        eType="#//Track"
        upperBound="-1"
        eOpposite="#//Track/album"/>
    <!-- Album composed by one RegularUser -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="composer"
        eType="#//RegularUser"
        lowerBound="1"
        eOpposite="#//RegularUser/composedAlbums"/>
    <!-- Album suggested by many RegularUsers -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedBy"
        eType="#//RegularUser"
        upperBound="-1"
        eOpposite="#//RegularUser/suggestedAlbums"/>
  </eClassifiers>

  <!-- Track class: association class between Hit and Album -->
  <eClassifiers xsi:type="ecore:EClass" name="Track">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TrackNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hit"
        eType="#//Hit"
        lowerBound="1"
        eOpposite="#//Hit/tracks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="album"
        eType="#//Album"
        lowerBound="1"
        eOpposite="#//Album/tracks"/>
  </eClassifiers>

</ecore:EPackage>
