<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="music" nsURI="http://www.example.org/music" nsPrefix="music">
  <eClassifiers xsi:type="ecore:EClass" name="MusicCatalog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="artists" upperBound="-1"
        eType="#//Artist" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="albums" upperBound="-1"
        eType="#//Album" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Song">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genre" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="artist" eType="#//Artist"
        eOpposite="#//Artist/songs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="publishedBy" eType="#//BusinessUser"
        eOpposite="#//BusinessUser/songs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Artist">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="website" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="songs" upperBound="-1"
        eType="#//Song" containment="true" eOpposite="#//Song/artist"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegularUser" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="singles" upperBound="-1"
        eType="#//Single" eOpposite="#//Single/regularUsers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedAlbums" upperBound="-1"
        eType="#//Album" eOpposite="#//Album/composer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedAlbums" upperBound="-1"
        eType="#//Album" eOpposite="#//Album/suggestedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessUser" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vatNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="songs" upperBound="-1"
        eType="#//Song" eOpposite="#//Song/publishedBy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Single" eSuperTypes="#//Song">
    <eStructuralFeatures xsi:type="ecore:EReference" name="regularUsers" upperBound="-1"
        eType="#//RegularUser" eOpposite="#//RegularUser/singles"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hit" eSuperTypes="#//Song">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" upperBound="-1"
        eType="#//Track" containment="true" eOpposite="#//Track/hit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Album">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tracks" upperBound="-1"
        eType="#//Track" eOpposite="#//Track/album"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composer" eType="#//RegularUser"
        eOpposite="#//RegularUser/composedAlbums"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="suggestedBy" upperBound="-1"
        eType="#//RegularUser" eOpposite="#//RegularUser/suggestedAlbums"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Track">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trackNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hit" eType="#//Hit" eOpposite="#//Hit/tracks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="album" eType="#//Album"
        eOpposite="#//Album/tracks"/>
  </eClassifiers>
</ecore:EPackage>
