<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="ScienceConnect" nsURI="http://www.scienceconnect.org/model">
    <eClass name="ScienceConnectSystem">
      <eStructuralFeatures>
        <eReference name="persons" eClassifier="Person" containment="true"/>
        <eReference name="institutions" eClassifier="ResearchInstitution" containment="true"/>
        <eReference name="publishers" eClassifier="Publisher" containment="true"/>
        <eReference name="articles" eClassifier="ScientificArticle" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Person">
      <eStructuralFeatures>
        <eAttribute name="personId" eType="eString"/>
        <eAttribute name="phoneNumber" eType="eString"/>
        <eAttribute name="keywords" eType="eString"/>
        <eReference name="institution" eClassifier="ResearchInstitution"/>
        <eReference name="authorships" eClassifier="AuthorShip"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="ResearchInstitution">
      <eStructuralFeatures>
        <eAttribute name="institutionCode" eType="eString"/>
        <eReference name="subscribedJournals" eClassifier="Journal"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="ScientificArticle" abstract="true">
      <eStructuralFeatures>
        <eAttribute name="doi" eType="eString"/>
        <eAttribute name="title" eType="eString"/>
        <eReference name="authorships" eClassifier="AuthorShip" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="PeerReviewedPaper">
      <eSuperTypes>
        <eClassifier eClassifier="ScientificArticle"/>
      </eSuperTypes>
      <eStructuralFeatures>
        <eAttribute name="citationCount" eType="eInt"/>
        <eReference name="reviewers" eClassifier="Person"/>
        <eReference name="journal" eClassifier="Journal"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="TechnicalReport">
      <eSuperTypes>
        <eClassifier eClassifier="ScientificArticle"/>
      </eSuperTypes>
      <eStructuralFeatures>
        <eReference name="publishingInstitution" eClassifier="ResearchInstitution"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="AuthorShip">
      <eStructuralFeatures>
        <eAttribute name="position" eType="eInt"/>
        <eReference name="author" eClassifier="Person"/>
        <eReference name="article" eClassifier="ScientificArticle"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Publisher">
      <eStructuralFeatures>
        <eAttribute name="name" eType="eString"/>
        <eReference name="journals" eClassifier="Journal" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Journal">
      <eStructuralFeatures>
        <eAttribute name="name" eType="eString"/>
        <eAttribute name="impactFactor" eType="eDouble"/>
        <eReference name="publisher" eClassifier="Publisher"/>
      </eStructuralFeatures>
    </eClass>
  </ePackage>
</xmi:XMI>
