<?xml version="1.0" encoding="UTF-8"?>
<ePackage name="btms" nsURI="http://www.example.org/btms" xmlns="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmi:version="2.0">
  <eClass name="BTMS">
    <eStructuralFeatures>
      <eReference name="drivers" elementType="Driver" containment="true"/>
      <eReference name="buses" elementType="Bus" containment="true"/>
      <eReference name="routes" elementType="BusRoute" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Driver">
    <eStructuralFeatures>
      <eAttribute name="name" type="EString"/>
      <eAttribute name="driverId" type="EInt"/>
      <eAttribute name="isOnSickLeave" type="EBoolean"/>
      <!-- Association class for Driver Assignment: Containment end -->
      <eReference name="driverAssignments" elementType="DriverAssignment" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Bus">
    <eStructuralFeatures>
      <eAttribute name="licencePlate" type="EString"/>
      <eAttribute name="isInRepairShop" type="EBoolean"/>
      <!-- Association class for Bus Assignment: Containment end -->
      <eReference name="busAssignments" elementType="BusAssignment" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="BusRoute">
    <eStructuralFeatures>
      <eAttribute name="routeNumber" type="EInt"/>
      <!-- Association class for Bus Assignment: Non-containment end -->
      <eReference name="busAssignments" elementType="BusAssignment"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="BusAssignment">
    <eStructuralFeatures>
      <eAttribute name="date" type="EDate"/>
      <!-- Association ends point to the association class; references back to participants -->
      <eReference name="bus" elementType="Bus"/>
      <eReference name="route" elementType="BusRoute"/>
      <!-- Association class for Driver Assignment: Non-containment end -->
      <eReference name="driverAssignments" elementType="DriverAssignment"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="DriverAssignment">
    <eStructuralFeatures>
      <eAttribute name="shift" type="ShiftType"/>
      <!-- References back to participants -->
      <eReference name="driver" elementType="Driver"/>
      <eReference name="busAssignment" elementType="BusAssignment"/>
    </eStructuralFeatures>
  </eClass>

  <eEnum name="ShiftType">
    <eLiterals name="MORNING"/>
    <eLiterals name="AFTERNOON"/>
    <eLiterals name="NIGHT"/>
  </eEnum>
</ePackage>
