<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="clothing"
    nsURI="http://www.example.com/clothing"
    nsPrefix="clothing">

  <!-- Custom datatype for time without date -->
  <eClassifiers xsi:type="ecore:EDataType" name="LocalTime"
      instanceClassName="java.time.LocalTime"/>

  <!-- Country -->
  <eClassifiers xsi:type="ecore:EClass" name="Country">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vatRate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currency"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionRateToEuro"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- Manufacturer -->
  <eClassifiers xsi:type="ecore:EClass" name="Manufacturer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country"
        eType="#//Country"/>
  </eClassifiers>

  <!-- Product -->
  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eOperations name="getGrossPrice">
      <eParameters name="country" eType="#//Country"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netPrice"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manufacturer"
        eType="#//Manufacturer"/>
    <!-- Association to countries via ProductAvailability -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="availabilities"
        eType="#//ProductAvailability"
        containment="true" upperBound="-1" eOpposite="#//ProductAvailability/product"/>
  </eClassifiers>

  <!-- ProductAvailability: association class between Product and Country -->
  <eClassifiers xsi:type="ecore:EClass" name="ProductAvailability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="product"
        eType="#//Product"
        eOpposite="#//Product/availabilities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country"
        eType="#//Country"/>
  </eClassifiers>

  <!-- Representative -->
  <eClassifiers xsi:type="ecore:EClass" name="Representative">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="socialSecurityNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telephoneNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country"
        eType="#//Country"/>
  </eClassifiers>

  <!-- Address -->
  <eClassifiers xsi:type="ecore:EClass" name="Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postalCode"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country"
        eType="#//Country"/>
  </eClassifiers>

  <!-- Customer -->
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="address"
        eType="#//Address" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="telephoneNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Countries in which the customer resells goods -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="resellingCountries"
        eType="#//Country" upperBound="-1"/>
  </eClassifiers>

  <!-- Order -->
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderQuantity"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desiredDeliveryDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product"
        eType="#//Product"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer"
        eType="#//Customer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representative"
        eType="#//Representative"/>
  </eClassifiers>

  <!-- ClothingStore: root container -->
  <eClassifiers xsi:type="ecore:EClass" name="ClothingStore">
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries"
        eType="#//Country" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manufacturers"
        eType="#//Manufacturer" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products"
        eType="#//Product" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="representatives"
        eType="#//Representative" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers"
        eType="#//Customer" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders"
        eType="#//Order" containment="true" upperBound="-1"/>
  </eClassifiers>

</ecore:EPackage>
