<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmi:version="2.0"
           xmlns:xmi="http://www.omg.org/XMI"
           xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML"
           xmlns:ecore="ecore:ECore">

  <eAnnotations source="Custom" annotation="ecore:Stereotype">
    <details key="name">RootContainer</details>
  </eAnnotations>

  <!-- Custom Datatypes -->
  <DataType id="LocalTimeCustom" name="LocalTime" eType="java.time.LocalTime"/>

  <!-- Root Container -->
  <Classifier id="_1" name="RootContainer" isAbstract="false">
    <packagedElement xmi:idref="_2"/>
    <packagedElement xmi:idref="_3"/>
    <packagedElement xmi:idref="_4"/>
    <packagedElement xmi:idref="_5"/>
  </Classifier>

  <!-- Country Class -->
  <Class id="_2" name="Country">
    <ownedAttribute id="_6" name="name" type="String"/>
    <ownedAttribute id="_7" name="vatRate" type="eDouble"/>
    <ownedAttribute id="_8" name="currency" type="String"/>
    <ownedAttribute id="_9" name="conversionRateToEur" type="eDouble"/>
  </Class>

  <!-- Product Class -->
  <Class id="_3" name="Product">
    <ownedAttribute id="_10" name="name" type="String"/>
    <ownedAttribute id="_11" name="description" type="String"/>
    <ownedAttribute id="_12" name="netPrice" type="eDouble"/>
    <generalization general="_13"/>
  </Class>

  <!-- ClothingProduct Class -->
  <Class id="_4" name="ClothingProduct">
    <generalization general="_3"/>
    <ownedAttribute id="_14" name="manufacturer" type="_15"/>
    <ownedAttribute id="_16" name="producedIn" type="_2" eType="_17"/>
  </Class>

  <!-- ClothingAssociation Class -->
  <Class id="_5" name="SellingInfo">
    <ownedAttribute id="_18" name="country" type="_2" containment="true"/>
    <association xmi:idref="_19"/>
  </Class>

  <!-- Manufacturer Class -->
  <Class id="_15" name="Manufacturer"/>

  <!-- Customer Class -->
  <Class id="_13" name="Customer">
    <ownedAttribute id="_20" name="name" type="String"/>
    <ownedAttribute id="_21" name="address" type="String"/>
    <ownedAttribute id="_22" name="telephoneNumber" type="String"/>
    <ownedAttribute id="_23" name="emailAddress" type="String"/>
  </Class>

  <!-- Order Class -->
  <Class id="_26" name="Order">
    <ownedAttribute id="_27" name="orderId" type="eInt"/>
    <ownedAttribute id="_28" name="productOrdered" type="_3" eType="_29"/>
    <ownedAttribute id="_30" name="orderQuantity" type="eInt"/>
    <ownedAttribute id="_31" name="orderDate" type="EDate"/>
    <ownedAttribute id="_32" name="desiredDeliveryDate" type="EDate"/>
  </Class>

  <!-- Representative Class -->
  <Class id="_35" name="Representative">
    <ownedAttribute id="_36" name="firstName" type="String"/>
    <ownedAttribute id="_37" name="lastName" type="String"/>
    <ownedAttribute id="_38" name="socialSecurityNumber" type="String"/>
    <ownedAttribute id="_39" name="telephoneNumber" type="String"/>
    <ownedAttribute id="_40" name="emailAddress" type="String"/>
    <ownedAttribute id="_41" name="countryResponsibility" type="_15" eType="_42"/>
  </Class>

  <!-- Associations -->

  <!-- Product - Manufacturer -->
  <Association id="_43">
    <end xmi:idref="_44_1" type="_15" oppositon="_14" containment="false"/>
    <end xmi:idref="_45_2" type="_3" oppositon="_12" containment="true"/>
  </Association>

  <!-- Product - Country -->
  <Association id="_17">
    <end xmi:idref="_46_1" type="_2" oppositon="_16" containment="false"/>
    <end xmi:idref="_47_2" type="_3" oppositon="_15" containment="true"/>
  </Association>

  <!-- ClothingProduct - SellingInfo -->
  <Association id="_19">
    <end xmi:idref="_48_1" type="_5" oppositon="_18" containment="false"/>
    <end xmi:idref="_49_2" type="_4" oppositon="_20" containment="true"/>
  </Association>

  <!-- Order - Representative -->
  <Association id="_50">
    <end xmi:idref="_51_1" type="_35" oppositon="_52_2"/>
    <end xmi:idref="_53_2" type="_26" oppositon="_54_1"/>
  </Association>
  
</uml:Model>
