<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="tutoring"
    nsURI="http://www.example.org/tutoring"
    nsPrefix="tutoring">

  <!-- Enumerations -->
  <eClassifiers xsi:type="ecore:EEnum" name="LevelOfTutoring">
    <eLiterals name="PrimarySchool"/>
    <eLiterals name="HighSchool" value="1"/>
    <eLiterals name="University" value="2"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="SessionStatus">
    <eLiterals name="Proposed"/>
    <eLiterals name="Confirmed" value="1"/>
    <eLiterals name="Completed" value="2"/>
    <eLiterals name="Paid" value="3"/>
    <eLiterals name="Cancelled" value="4"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="PaymentKind">
    <eLiterals name="CreditCard"/>
    <eLiterals name="WireTransfer" value="1"/>
  </eClassifiers>

  <!-- Abstract Classes -->
  <eClassifiers xsi:type="ecore:EClass" name="TutoringRole" abstract="true"/>

  <eClassifiers xsi:type="ecore:EClass" name="TutoringElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tutoringLevel"
        eType="#//LevelOfTutoring"/>
  </eClassifiers>

  <!-- User -->
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles"
        eType="#//TutoringRole"
        lowerBound="0" upperBound="2"
        containment="true"/>
  </eClassifiers>

  <!-- BestTutorAward -->
  <eClassifiers xsi:type="ecore:EClass" name="BestTutorAward">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="year" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="month" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- Tutor -->
  <eClassifiers xsi:type="ecore:EClass" name="Tutor" eSuperTypes="#//TutoringRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bankAccount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutoringOffers"
        eType="#//TutoringOffer"
        lowerBound="0" upperBound="-1"
        containment="true" eOpposite="#//TutoringOffer/tutor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availabilities"
        eType="#//TutorAvailability"
        lowerBound="0" upperBound="-1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bestTutorAwards"
        eType="#//BestTutorAward"
        lowerBound="0" upperBound="-1"
        containment="true"/>
  </eClassifiers>

  <!-- Student -->
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//TutoringRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutoringRequests"
        eType="#//TutoringRequest"
        lowerBound="0" upperBound="-1"
        containment="true"/>
  </eClassifiers>

  <!-- TutorAvailability -->
  <eClassifiers xsi:type="ecore:EClass" name="TutorAvailability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Subject -->
  <eClassifiers xsi:type="ecore:EClass" name="Subject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutoringOffers"
        eType="#//TutoringOffer"
        lowerBound="0" upperBound="-1"
        eOpposite="#//TutoringOffer/subject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutoringRequests"
        eType="#//TutoringRequest"
        lowerBound="0" upperBound="-1"
        eOpposite="#//TutoringRequest/subject"/>
  </eClassifiers>

  <!-- TutoringOffer -->
  <eClassifiers xsi:type="ecore:EClass" name="TutoringOffer" eSuperTypes="#//TutoringElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hourlyPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutor"
        eType="#//Tutor"
        lowerBound="1" upperBound="1"
        eOpposite="#//Tutor/tutoringOffers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject"
        eType="#//Subject"
        lowerBound="1" upperBound="1"
        eOpposite="#//Subject/tutoringOffers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutoringRequests"
        eType="#//TutoringRequest"
        lowerBound="0" upperBound="-1"
        eOpposite="#//TutoringRequest/tutoringOffer"/>
  </eClassifiers>

  <!-- TutoringRequest -->
  <eClassifiers xsi:type="ecore:EClass" name="TutoringRequest" eSuperTypes="#//TutoringElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject"
        eType="#//Subject"
        lowerBound="1" upperBound="1"
        eOpposite="#//Subject/tutoringRequests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tutoringOffer"
        eType="#//TutoringOffer"
        lowerBound="0" upperBound="1"
        eOpposite="#//TutoringOffer/tutoringRequests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allSessions"
        eType="#//TutoringSession"
        lowerBound="0" upperBound="-1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstSession"
        eType="#//TutoringSession"
        lowerBound="0" upperBound="1"/>
  </eClassifiers>

  <!-- TutoringSession -->
  <eClassifiers xsi:type="ecore:EClass" name="TutoringSession">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sessionStatus" eType="#//SessionStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="payment"
        eType="#//Payment"
        lowerBound="0" upperBound="1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextSession"
        eType="#//TutoringSession"
        lowerBound="0" upperBound="1"/>
  </eClassifiers>

  <!-- Payment -->
  <eClassifiers xsi:type="ecore:EClass" name="Payment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentForm" eType="#//PaymentKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paymentDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

</ecore:EPackage>
