<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="UniversityMetamodel" nsURI="http://www.example.org/university">
    <eClassifications>
      <!-- Root Container -->
      <eClass name="University">
        <eStructuralFeatures>
          <eReference name="faculties" eType="Faculty" containment="true"/>
          <eReference name="employees" eType="Employee" containment="true"/>
          <eReference name="projects" eType="Project" containment="true"/>
          <eReference name="courses" eType="Course" containment="true"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Faculty">
        <eStructuralFeatures>
          <eAttribute name="name" eType="eString"/>
          <eReference name="dean" eType="Employee" containment="false"/>
          <eReference name="institutes" eType="Institute" containment="true"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Institute">
        <eStructuralFeatures>
          <eAttribute name="name" eType="eString"/>
          <eAttribute name="address" eType="eString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Employee" abstract="true">
        <eStructuralFeatures>
          <eAttribute name="ssn" eType="eString"/>
          <eAttribute name="name" eType="eString"/>
          <eAttribute name="emailAddress" eType="eString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="AdministrativeStaff">
        <eSuperTypes>
          <eClass name="Employee"/>
        </eSuperTypes>
      </eClass>

      <eClass name="ResearchStaff">
        <eSuperTypes>
          <eClass name="Employee"/>
        </eSuperTypes>
      </eClass>

      <eClass name="ResearchAssistant">
        <eSuperTypes>
          <eClass name="ResearchStaff"/>
        </eSuperTypes>
        <eStructuralFeatures>
          <eAttribute name="fieldOfResearch" eType="eString"/>
          <eReference name="institutes" eType="Institute" containment="false"/>
          <!-- Association Class reference (Containment end) -->
          <eReference name="projectAssignments" eType="RAProjectAssignment" containment="true"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Lecturer">
        <eSuperTypes>
          <eClass name="ResearchAssistant"/>
        </eSuperTypes>
        <eStructuralFeatures>
          <eReference name="courses" eType="Course" containment="false"/>
        </eStructuralFeatures>
      </eClass>

      <!-- Association Class for RA <-> Project -->
      <eClass name="RAProjectAssignment">
        <eStructuralFeatures>
          <eAttribute name="hours" eType="eInt"/>
          <!-- Association Class reference (Non-containment end) -->
          <eReference name="project" eType="Project" containment="false"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Project">
        <eStructuralFeatures>
          <eAttribute name="name" eType="eString"/>
          <eAttribute name="startDate" eType="eDate"/>
          <eAttribute name="endDate" eType="eDate"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Course">
        <eStructuralFeatures>
          <eAttribute name="id" eType="eString"/>
          <eAttribute name="name" eType="eString"/>
          <eAttribute name="weeklyDurationHours" eType="eDouble"/>
        </eStructuralFeatures>
      </eClass>
    </eClassifications>
  </ePackage>
</xmi:XMI>
