<?xml version="1.0" encoding="UTF-8"?>
<uml:XMI xmi:version="2.5"
         xmlns:xmi="http://www.omg.org/XMI"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
         xmlns:uml="http://www.eclipse.org/omg/uml2.5.0/Pivot">

  <XMTPEngineVersionInfo>
    <!-- XMI Model -->
  </XMTPEngineVersionInfo>

  <packagedElements>

    <!-- Package Definition -->
    <Package xmi:id="_RootPackage" name="BuildingManagement">
    
      <!-- Root container -->
      <PackagedElement xmi:id="_rootContainer" name="RootContainer" isAbstract="true"/>

      <!-- EEnum for EnergyClass -->
      <EEnum xmi:id="_EnergyClassEnum" name="EnergyClass">
        <Literals>
          <LiteralMember xmi:id="_A_Literal" name="A"/>
          <LiteralMember xmi:id="_B_Literal" name="B"/>
          <LiteralMember xmi:id="_C_Literal" name="C"/>
          <LiteralMember xmi:id="_D_Literal" name="D"/>
        </Literals>
      </EEnum>

      <!-- User class -->
      <Class xmi:id="_User" name="User">
        <ownedAttributes>
          <Attribute xmi:id="_uniqueUserName" name="uniqueUserName" type="String"/>
          <Attribute xmi:id="_emailAddress" name="emailAddress" type="String"/>
          <Attribute xmi:id="_password" name="password" type="String"/>
        </ownedAttributes>
      </Class>

      <!-- Administrator class -->
      <Class xmi:id="_Administrator" name="Administrator">
        <isAbstract>false</isAbstract>
        <generalization xmi:type="Generalization" general="_User"/>
        <ownedAttributes>
          <Attribute xmi:id="_idCardNumber" name="idCardNumber" type="String"/>
        </ownedAttributes>
      </Class>

      <!-- WebPortal class -->
      <Class xmi:id="_WebPortal" name="WebPortal">
        <ownedAttributes>
          <Attribute xmi:id="_versionNumber" name="versionNumber" type="String"/>
          <Attribute xmi:id="_urlAddress" name="urlAddress" type="String"/>
        </ownedAttributes>
      </Class>

      <!-- Building class -->
      <Class xmi:id="_Building" name="Building">
        <ownedAttributes>
          <Attribute xmi:id="_uniqueID" name="uniqueID" type="String"/>
          <Attribute xmi:id="_name" name="name" type="String"/>
          <Attribute xmi:id="_energyClass" name="energyClass" type="_EnergyClassEnum"/>
          <Attribute xmi:id="_address" name="address" type="String"/>
          <Attribute xmi:id="_yearOfConstruction" name="yearOfConstruction" type="int"/>
        </ownedAttributes>
      </Class>

      <!-- Entry class -->
      <Class xmi:id="_Entry" name="Entry">
        <ownedAttributes>
          <Attribute xmi:id="_name" name="name" type="String"/>
          <Attribute xmi:id="_information" name="information" type="String" defaultValueLiteral="null"/>
          <Attribute xmi:id="_value" name="value" type="float" defaultValueLiteral="-1.0"/>
          <Attribute xmi:id="_unit" name="unit" type="String" defaultValueLiteral="null"/>
          <Attribute xmi:id="_isPublic" name="isPublic" type="boolean" defaultValueLiteral="false"/>
        </ownedAttributes>
      </Class>

      <!-- Image class -->
      <Class xmi:id="_Image" name="Image">
        <ownedAttributes>
          <Attribute xmi:id="_fileName" name="fileName" type="String"/>
          <Attribute xmi:id="_isProfilePhoto" name="isProfilePhoto" type="boolean" defaultValueLiteral="false"/>
        </ownedAttributes>
      </Class>

      <!-- Relationships -->

      <!-- Relationship between WebPortal and Building -->
      <Association xmi:id="_WebPortalsContainBuildings" name="containsBuildings">
        <memberEnd xmi:type="uml:Property" base="_Building" owner="_WebPortal" isUnique="false" association="_WebPortalsContainBuildings"/>
      </Association>

      <!-- User ownership relationship to Building -->
      <Association xmi:id="_BuildingsOwnedByUsers" name="ownedBy">
        <memberEnd xmi:type="uml:Property" base="_Building" owner="_User" isUnique="false" association="_BuildingsOwnedByUsers"/>
        <memberEnd xmi:type="uml:Property" base="_User" owner="_Building" isUnique="true" association="_BuildingsOwnedByUsers"/>
      </Association>

    </Package>
  </packagedElements>
</uml:XMI>
