<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:version="2.0">
  <ecore:EPackage name="EBikeModel" nsURI="ebikemodel" nsPrefix="ebikemodel" xmi:id="_1">
    <!-- Classes -->
    <ecore:EClass xmi:id="_2" name="EBikeRootContainer">
      <ecore:EReference name="eBikes" upperBound="-1" eType="#_3"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_3" name="EBike">
      <ecore:EAttribute name="serialNumber" eType="ecore:EString"/>
      <ecore:EReference name="frame" lowerBound="1" eType="#_4"/>
      <ecore:EReference name="wheels" upperBound="-1" eType="#_5"/>
      <ecore:EReference name="driveSystem" lowerBound="1" eType="#_6"/>
      <ecore:EReference name="controller" lowerBound="1" eType="#_7"/>
      <ecore:EReference name="battery" eType="#_9"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_4" name="Frame">
      <ecore:EAttribute name="material" eType="ecore:EString"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_5" name="Wheel"/>

    <ecore:EClass xmi:id="_6" name="DriveSystem">
      <ecore:EReference name="motor" lowerBound="1" eType="#_10"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_7" name="Controller">
      <ecore:EAttribute name="state" eType="#_23"/>
      <ecore:EOperation name="controlBattery"/>
      <ecore:EOperation name="commandDriveSystem"/>
      <ecore:EReference name="battery" lowerBound="0" eType="#_9"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_8" name="AdvancedController">
      <ecore:EGenericSuperTypes eType="#_7"/>
      <ecore:EOperation name="estimateNextInspection" eType="#_14"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_9" name="Battery">
      <ecore:EAttribute name="storedEnergy" eType="#_15"/>
    </ecore:EClass>

    <ecore:EClass xmi:id="_10" name="Motor"/>

    <!-- DataTypes -->
    <ecore:EDataType xmi:id="_14" name="Date" instanceClassName="java.time.LocalDate"/>
    <ecore:EDataType xmi:id="_15" name="WattHours" instanceClassName="double"/>

    <!-- Enumerations -->
    <ecore:EEnum xmi:id="_23" name="ControllerState">
      <ecore:ELiteral name="On" value="0"/>
      <ecore:ELiteral name="Off" value="1"/>
      <ecore:ELiteral name="Charging" value="2"/>
    </ecore:EEnum>
  </ecore:EPackage>
</xmi:XMI>
