<xmi:XMI xmi:version="2.0"
        xmlns:xmi="http://schema.omg.org/spec/XMI/20030701"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:Ecore="http://www.eclipse.org/emf/2002/Ecore">
  <Ecore:EPackage xmi:id="_root" name="ResearchProjectManagement"
                  nsWithPrefixes="rpm=org.example.researchprojectmanagement">

    <!-- Root container class -->
    <Ecore:classes xsi:type="Ecore:EClass" name="Model" id="_model">
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="departments"
                                  eType="#/_department"
                                  lowerUnbounded="true"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="researchers"
                                  eType="#/_researcher"
                                  lowerUnbounded="true"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="workPackages"
                                  eType="#/_workPackage"
                                  lowerUnbounded="true"/>
    </Ecore:classes>

    <!-- Department class -->
    <Ecore:classes xsi:type="Ecore:EClass" name="Department" id="_department">
      <Ecore:eStructuralFeatures xsi:type="Ecore:EAttribute"
                                  name="name"
                                  eType="String"
                                  id="_department_name"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="researchGroups"
                                  eType="#/_researchGroup"
                                  lowerUnbounded="true"
                                  containment="true"/>
    </Ecore:classes>

    <!-- ResearchGroup class -->
    <Ecore:classes xsi:type="Ecore:EClass" name="ResearchGroup" id="_researchGroup">
      <Ecore:eStructuralFeatures xsi:type="Ecore:EAttribute"
                                  name="name"
                                  eType="String"
                                  id="_researchGroup_name"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="department"
                                  eType="#/_department"
                                  id="_researchGroup_department"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="researchers"
                                  eType="#/_researcher"
                                  lowerUnbounded="true"
                                  containment="true"/>
    </Ecore:classes>

    <!-- Researcher class -->
    <Ecore:classes xsi:type="Ecore:EClass" name="Researcher" id="_researcher">
      <Ecore:eStructuralFeatures xsi:type="Ecore:EAttribute"
                                  name="name"
                                  eType="String"
                                  id="_researcher_name"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="researchGroup"
                                  eType="#/_researchGroup"
                                  id="_researcher_researchGroup"/>

      <!-- Association class for researcher-work package assignment -->
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="assignments"
                                  eType="#/_Assignment"
                                  lowerUnbounded="true"
                                  containment="true"
                                  opposite="researcher"/>
    </Ecore:classes>

    <!-- WorkPackage class -->
    <Ecore:classes xsi:type="Ecore:EClass" name="WorkPackage" id="_workPackage">
      <Ecore:eStructuralFeatures xsi:type="Ecore:EAttribute"
                                  name="name"
                                  eType="String"
                                  id="_workPackage_name"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="leader"
                                  eType="#/_researchGroup"
                                  id="_workPackage_leader"/>

      <!-- Association class for researcher-work package assignment -->
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="assignments"
                                  eType="#/_Assignment"
                                  lowerUnbounded="true"
                                  containment="true"
                                  opposite="workPackage"/>
    </Ecore:classes>

    <!-- Association class for researcher-work package assignment -->
    <Ecore:classes xsi:type="Ecore:EClass" name="Assignment" id="_Assignment">
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="researcher"
                                  eType="#/_researcher"
                                  lowerUnbounded="false"
                                  opposite="assignments"/>
      <Ecore:eStructuralFeatures xsi:type="Ecore:EReference"
                                  name="workPackage"
                                  eType="#/_workPackage"
                                  lowerUnbounded="false"
                                  opposite="assignments"/>

      <!-- Operations to handle reassignment logic -->
      <Ecore:eOperations>
        <Ecore:EOperation name="reassignOnResearcherChange" id="_Assignment_reassignOnResearcherChange">
          <Ecore:eParameters>
            <Ecore:EParameter name="newResearchGroup" eType="#/_researchGroup"
                              id="_param_newRG"/>
          </Ecore:eParameters>
        </Ecore:EOperation>
        <Ecore:EOperation name="reassignOnWorkPackageChange" id="_Assignment_reassignOnWPChange">
          <Ecore:eParameters>
            <Ecore:EParameter name="newLeader" eType="#/_researchGroup"
                              id="_param_newLeader"/>
          </Ecore:eParameters>
        </Ecore:EOperation>
      </Ecore:eOperations>
    </Ecore:classes>

  </Ecore:EPackage>
</xmi:XMI>
