<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="socialnetwork" nsURI="http://www.example.org/socialnetwork"
    nsPrefix="socialnetwork">
  <eClassifiers xsi:type="ecore:EClass" name="SocialNetwork">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users" upperBound="-1"
        eType="#//User" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts" upperBound="-1"
        eType="#//Account" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friendRequests" upperBound="-1"
        eType="#//FriendRequest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" lowerBound="1"
        eType="#//Account" eOpposite="#//Account/user"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Account" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//User"
        eOpposite="#//User/account"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="companyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="advertisementPages" upperBound="-1"
        eType="#//AdvertisementPage" eOpposite="#//AdvertisementPage/businessAccount"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EReference" name="administratedPages" upperBound="-1"
        eType="#//PersonalPage" eOpposite="#//PersonalPage/administrator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privileges" upperBound="-1"
        eType="#//Privilege" containment="true" eOpposite="#//Privilege/personalAccount"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentFriendRequests" upperBound="-1"
        eType="#//FriendRequest" eOpposite="#//FriendRequest/sender"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivedFriendRequests"
        upperBound="-1" eType="#//FriendRequest" eOpposite="#//FriendRequest/receiver"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FriendRequest">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" lowerBound="1"
        eType="#//PersonalAccount" eOpposite="#//PersonalAccount/sentFriendRequests"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" lowerBound="1"
        eType="#//PersonalAccount" eOpposite="#//PersonalAccount/receivedFriendRequests"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonalPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="administrator" eType="#//PersonalAccount"
        eOpposite="#//PersonalAccount/administratedPages"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="privileges" upperBound="-1"
        eType="#//Privilege" eOpposite="#//Privilege/personalPage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Privilege">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeOfPrivilege" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalAccount" lowerBound="1"
        eType="#//PersonalAccount" eOpposite="#//PersonalAccount/privileges"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalPage" lowerBound="1"
        eType="#//PersonalPage" eOpposite="#//PersonalPage/privileges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisementPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounceRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clickThroughRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businessAccount" lowerBound="1"
        eType="#//BusinessAccount" eOpposite="#//BusinessAccount/advertisementPages"/>
  </eClassifiers>
</ecore:EPackage>
