<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="socialNetwork"
    nsURI="http://www.example.org/socialNetwork"
    nsPrefix="socialNetwork">

  <!-- User class -->
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- 1 to 1 reference to Account -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" eType="#//Account" containment="true"/>
  </eClassifiers>

  <!-- Abstract Account class -->
  <eClassifiers xsi:type="ecore:EClass" name="Account" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- BusinessAccount class, extends Account -->
  <eClassifiers xsi:type="ecore:EClass" name="BusinessAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="companyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- 1 to many reference to AdvertisementPage -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="advertisementPages" upperBound="-1" eType="#//AdvertisementPage" containment="true"/>
  </eClassifiers>

  <!-- PersonalAccount class, extends Account -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonalAccount" eSuperTypes="#//Account">
    <!-- PersonalAccount as administrator of PersonalPage (1 to many) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="administeredPages" upperBound="-1" eType="#//PersonalPage"/>
    <!-- PersonalAccount many-to-many with PersonalPage -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalPages" upperBound="-1" eType="#//PersonalPage"/>
  </eClassifiers>

  <!-- FriendRequest class -->
  <eClassifiers xsi:type="ecore:EClass" name="FriendRequest">
    <!-- many FriendRequests to 1 PersonalAccount as sender -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" eType="#//PersonalAccount"/>
    <!-- many FriendRequests to 1 PersonalAccount as receiver -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//PersonalAccount"/>
  </eClassifiers>

  <!-- Abstract Page class -->
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- PersonalPage class, extends Page -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonalPage" eSuperTypes="#//Page"/>

  <!-- Privilege class -->
  <!-- Privilege is an association class between PersonalAccount and PersonalPage -->
  <eClassifiers xsi:type="ecore:EClass" name="Privilege">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeOfPrivilege" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalAccount" eType="#//PersonalAccount"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalPage" eType="#//PersonalPage"/>
  </eClassifiers>

  <!-- AdvertisementPage class, extends Page -->
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisementPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bounceRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clickThroughRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

</ecore:EPackage>
