<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="socialnetwork"
    nsURI="http://www.example.org/socialnetwork"
    nsPrefix="socialnetwork">

  <!-- User class -->
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="UserID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BirthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- User "1" - "1" Account -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="account" eType="#//Account" containment="true"/>
  </eClassifiers>

  <!-- Abstract Account class -->
  <eClassifiers xsi:type="ecore:EClass" name="Account" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AccountNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- BusinessAccount extends Account -->
  <eClassifiers xsi:type="ecore:EClass" name="BusinessAccount" eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CompanyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- BusinessAccount "1" - "*" AdvertisementPage -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="advertisementPages" upperBound="-1" eType="#//AdvertisementPage" containment="true"/>
  </eClassifiers>

  <!-- PersonalAccount extends Account -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonalAccount" eSuperTypes="#//Account">
    <!-- PersonalAccount "*" - "*" PersonalPage (via Privilege association class) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="privileges" upperBound="-1" eType="#//Privilege"/>
    <!-- FriendRequest "*" - "1" PersonalAccount : sender -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sentRequests" upperBound="-1" eType="#//FriendRequest" eOpposite="#//FriendRequest/sender"/>
    <!-- FriendRequest "*" - "1" PersonalAccount : receiver -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivedRequests" upperBound="-1" eType="#//FriendRequest" eOpposite="#//FriendRequest/receiver"/>
    <!-- PersonalAccount "1" - "*" PersonalPage : administrator -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="administeredPages" upperBound="-1" eType="#//PersonalPage" eOpposite="#//PersonalPage/administrator"/>
  </eClassifiers>

  <!-- FriendRequest class -->
  <eClassifiers xsi:type="ecore:EClass" name="FriendRequest">
    <!-- sender -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sender" eType="#//PersonalAccount" eOpposite="#//PersonalAccount/sentRequests"/>
    <!-- receiver -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="receiver" eType="#//PersonalAccount" eOpposite="#//PersonalAccount/receivedRequests"/>
  </eClassifiers>

  <!-- Abstract Page class -->
  <eClassifiers xsi:type="ecore:EClass" name="Page" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Visits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- PersonalPage extends Page -->
  <!-- PersonalAccount "*" - "*" PersonalPage is realized via Privilege association class -->
  <!-- PersonalAccount "1" - "*" PersonalPage : administrator -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonalPage" eSuperTypes="#//Page">
    <!-- administrator reference back to PersonalAccount -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="administrator" eType="#//PersonalAccount" eOpposite="#//PersonalAccount/administeredPages"/>
    <!-- PersonalPage side of Privilege association class -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="privileges" upperBound="-1" eType="#//Privilege"/>
  </eClassifiers>

  <!-- Privilege association class (between PersonalAccount and PersonalPage) -->
  <eClassifiers xsi:type="ecore:EClass" name="Privilege">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TypeOfPrivilege" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalAccount" eType="#//PersonalAccount"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="personalPage" eType="#//PersonalPage"/>
  </eClassifiers>

  <!-- AdvertisementPage extends Page -->
  <eClassifiers xsi:type="ecore:EClass" name="AdvertisementPage" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BounceRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClickThroughRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConversionRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

</ecore:EPackage>
