<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmlns:xmi="http://www.omg.org/XMI"
           xmlns:uml="http://www.eclipse.org/uml2/5.0.0/UML"
           xmi:id="_TeamSportsScoutingSystem_Model"
           xmi:version="2.0">
    <!-- Root Container -->
    <packagedElement xsi:type="uml:Class" name="ScoutingSystem"
                     xmi:id="_ScoutingSystem">
        <ownedAttribute isUnique="false" name="headCoach">
            <type xsi:type="uml:Class" href="#_HeadCoach"/>
        </ownedAttribute>
        <ownedAttribute isUnique="false" name="directorOfTheClub">
            <type xsi:type="uml:Class" href="#_DirectorOfTheClub"/>
        </ownedAttribute>
        <ownedAttribute isUnique="false" name="scouts">
            <type xsi:href="#_Scout"/>
        </ownedAttribute>
    </packagedElement>

    <!-- Head Coach Class -->
    <packagedElement xsi:type="uml:Class"
                     xmi:id="_HeadCoach" name="HeadCoach">
        <ownedOperation href="#identifyPlayerProfiles_Operation"/>
        <ownedOperation href="#evaluateShortList_Operation"/>
        <ownedOperation href="#decideFinalPlayers_Operation"/>
    </packagedElement>
    
    <!-- Identity operations for Head Coach -->
    <packagedElement xsi:type="uml:Operation" xmi:id="_identifyPlayerProfiles_Operation"
                     name="identifyPlayerProfiles()"/>

     <packagedElement xsi:type="uml:Operation" xmi:id="_evaluateShortList_Operation"
                     name="evaluateShortList()"/>
    
    <packagedElement xsi:type="uml:Operation" xmi:id="_decideFinalPlayers_Operation"
                     name="decideFinalPlayers()"/>
    
    <!-- Director Of The Club Class -->
    <packagedElement xsi:type="uml:Class"
                     xmi:id="_DirectorOfTheClub" name="DirectorOfTheClub">
        <ownedOperation href="#makeOfficialOffer_Operation"/>
    </packagedElement>
    
    <!-- Identity operations for Director Of The Club -->
    <packagedElement xsi:type="uml:Operation" xmi:id="_makeOfficialOffer_Operation"
                     name="makeOfficialOffer(Player)"/>

    <!-- Scout Class -->
    <packagedElement xsi:type="uml:Class"
                     xmi:id="_Scout" name="Scout">
        <ownedOperation href="#submitScoutingReport_Operation"/>
    </packagedElement>
    
    <!-- Identity operations for Scout -->
    <packagedElement xsi:type="uml:Operation" xmi:id="_submitScoutingReport_Operation"
                     name="submitScoutingReport(Player, ScoutingReport)"/>

    <!-- Other Classes -->

    <packagedElement xsi:type="uml:Class"
                     xmi:id="_ScoutingReport" name="ScoutingReport">
        <ownedAttribute isUnique="false" name="pros">
            <type xsi:type="uml:String"/>
        </ownedAttribute>
        <ownedAttribute isUnique="false" name="cons">
            <type xsi:type="uml:String"/>
        </ownedAttribute>
        <ownedAttribute isUnique="false" name="recommendation">
            <type href="#Recommendation"/>
        </ownedAttribute>
    </packagedElement>

    <packagedElement xsi:type="uml:Class"
                     xmi:id="_PlayerProfile" name="PlayerProfile">
        <ownedAttribute isUnique="false" name="targetPosition">
            <type xsi:type="uml:String"/>
        </ownedAttribute>
        <ownedAttribute isUnique="false" name="attributes">
            <type xsi:type="uml.Map" keyType="String" valueType="String"/>
        </ownedAttribute>
    </packagedElement>

    <!-- Associations -->
    
    <packagedElement xsi:type="uml:Association"
                     xmi:id="_LongListObservation" name="LongListObservation">
        <member end xmi:id="_s1_End" type="#_Scout" association="0..*">
            <lowerValue value="0"/>
            <upperValue value="*"/>
        </member>
        <member end xmi:id="_p2_End" type="#_PlayerProfile" association="1..1">
            <lowerValue value="1"/>
            <upperValue value="1"/>
        </member>
    </packagedElement>

    <packagedElement xsi:type="uml:Association"
                     xmi:id="_ScoutingAssignment" name="ScoutingAssignment">
        <member end xmi:id="_p1_End" type="#_SoccerClub::Scout" association="0..*">
            <lowerValue value="0"/>
            <upperValue value="*"/>
        </member>
        <member end xmi:id="_s2_End"
                 href="#_PlayerProfile" association="1..1">
            <lowerValue value="1"/>
            <upperValue value="1"/>
        </member>
    </packagedElement>

    <packagedElement xsi:type="uml:Class"
                     xmi:id="_Recommendation" name="Recommendation">
        <!-- You can enumerate values for possible recommendations -->
    </packagedElement>
</uml:Model>
