<?xml version="1.0" encoding="UTF-8"?>
<uml:xmi xmlns:uml="http://www.eclipse.org/emf/2002/Ecore"
         xmlns:xmi="http://schema.omg.org/spec/XMI/2.4" 
         xmi.version="2.5.0">
  <xmi:Extension>

    <!-- Root Model -->
    <uml:Model id="_root" name="FilmSetSystem">

      <!-- Package: FilmSet -->
      <uml:Package id="_pkgFilmSet" name="FilmSet">
        
        <!-- Class: FilmSet -->
        <uml:Class id="_FilmSet" name="FilmSet">
          <eAnnotations source="Model">
            <details key="label" value="FilmSet"/>
          </eAnnotations>
          
          <eStructuralFeatures id="_featureLocation" eFeatureID="_loc" eType="_EString" name="location"/>

          <!-- FilmSet has films (composition) -->
          <eStructuralFeatures id="_association_FilmToFirmSet">
            <name>films</name>
            <type href="#_Film"/>
            <eType href="#_Film"/>
            <eMany>true</eMany>
            <eOpposite href="#Film_set"/>
          </eStructuralFeatures>

        </uml:Class>
        
        <!-- Package: Employee -->
        <uml:Package id="_pkgEmployee" name="Employee">
          
          <!-- Class: CreativeEmployee -->
          <uml:Class id="_CreativeEmployee" name="CreativeEmployee">
            <eAnnotations source="Model">
              <details key="label" value="CreativeEmployee"/>
            </eAnnotations>
          </uml:Class>

          <!-- Class: Director -->
          <uml:Class id="_Director" name="Director" isAbstract="false" abstract="false">
            <eSuperTypes href="#_CreativeEmployee"/>
            <eStructuralFeatures id="_directorOscarWinner" eFeatureID="_isOscar" eType="_EBoolean" name="isOscarWinner"/>

            <!-- Association to FilmSets -->
            <eStructuralFeatures id="_association_DirectorToFilmSet">
              <name>filmSet</name>
              <type href="#_FilmSet"/>
              <eType href="#_FilmSet"/>
              <eOpposite href="#director_set"/>
            </eStructuralFeatures>

          </uml:Class>

          <!-- Class: Actor -->
          <uml:Class id="_Actor" name="Actor">
            <eSuperTypes href="#_CreativeEmployee"/>
            <eStructuralFeatures id="_actorEducation" eFeatureID="_education" eType="_EString" name="educationCompleted"/>
            <eStructuralFeatures id="_actorOscarWinner" eFeatureID="_isOscar" eType="_EBoolean" name="isOscarWinner"]

            <!-- Association to FilmSets -->
            <eStructuralFeatures id="_association_ActorToFilmSet">
              <name>filmSet</name>
              <type href="#_FilmSet"/>
              <eType href="#_FilmSet"/>
              <eOpposite href="#actor_set"/>
            </eStructuralFeatures>

          </uml:Class>

          <!-- Class: Technician -->
          <uml:Class id="_Technician" name="Technician">  
            <eStructuralFeatures id="_technicianActivity" eFeatureID="_activityField" eType="_EString" name="activityField"/> 

            <!-- Association to FilmSets -->
            <eStructuralFeatures id="_association_TechnicianToFilmSet">
              <name>filmSet</name>
              <type href="#_FilmSet"/>
              <eType href="#_FilmSet"/>
              <eOpposite href="#technician_set"/>
            </eStructuralFeatures>

          </uml:Class>
        </uml:Package>

      </uml:Package>

      <!-- Package: Film -->
      <uml:Package id="_pkgFilm" name="Film">
      
        <!-- Class: Film -->
        <uml:Class id="_Film" name="Film">
          <eAnnotations source="Model">
            <details key="label" value="Film"/>
          </eAnnotations>
        
          <eStructuralFeatures id="_titleFeature" eFeatureID="_title" eType="_EString" name="title"/>         
          <eStructuralFeatures id="_releaseYearFeature" eFeatureID="_year" eType="_EInt" name="releaseYear"/>

          <!-- Film belongs to a genre -->
          <eStructuralFeatures id="_genreFeature">
            <name>genre</name>
            <type href="#_Genre"/>
            <eType href="#_Genre"/>
          </eStructuralFeatures>

          <!-- Association to FilmSet (composition) -->
          <eStructuralFeatures id="_association_FilmToFilmSet">
            <name>filmSets</name>
            <type href="#_FilmSet"/>
            <eOpposite href="#films"/>
          </eStructuralFeatures>

        </uml:Class>

      </uml:Package>

      <!-- Package: Screenplay -->
      <uml:Package id="_pkgScreenplay" name="Screenplay">
        
        <!-- Class: Screenwriter -->
        <uml:Class id="_Screenwriter" name="Screenwriter">
          <eAnnotations source="Model">
            <details key="label" value="ScreenWriter"/>
          </eAnnotations>
          
          <eStructuralFeatures id="_screenwriterName" eFeatureID="_name" eType="_EString" name="name"/>
          <eStructuralFeatures id="_mostSuccessfulFilmFeature" eFeatureID="_success" eType="_EReference" name="mostSuccessfulFilm"/>

          <!-- Screenwriter writes multiple screenplays (association) -->
          <eStructuralFeatures id="_association_ScreenwritersToScreenplay">
            <name>screenplays</name>
            <type href="#_Screenplay"/>
            <lowerValueLiteral>1</lowerValueLiteral>
            <upperValueLiteral>N</upperValueLiteral>
            <eOpposite href="#writtenBy"/>
          </eStructuralFeatures>

        </uml:Class>

        <!-- Class: Screenplay -->
        <uml:Class id="_Screenplay" name="Screenplay">
          
          <eStructuralFeatures id="_titleFeaturePy" eFeatureID="_pTitle" eType="_EString" name="title"/>
          <eStructuralFeatures id="_versionFeature" eFeatureID="_vsn" eType="_EString" name="version"/>
          <eStructuralFeatures id="_dateFeature" eFeatureID="_dt" eType="_EDate" name="date"/>
          <eStructuralFeatures id="_numberScenesFeature" eFeatureID="_scenes" eType="_EInt" name="numberScenes"/>
          <eStructuralFeatures id="_plotFeature" eFeatureID="_plt" eType="_EString" name="plot"/>

          <!-- Screenplay is based on a Novel or Concept -->
          <eStructuralFeatures id="_association_ScreenplaysToNovelOrConcept">
            <name>basedOn</name>
            <type href="#_NovelOrConcept"/>
            <upperValueLiteral>1</upperValueLiteral>
            <lowerValueLiteral>1</lowerValueLiteral>
          </eStructuralFeatures>

          <!-- Association to Film (composition) -->
          <eStructuralFeatures id="_association_ScreenplayToFilm">
            <name>film</name>
            <type href="#_Film"/>
            <upperValueLiteral>1</upperValueLiteral>
            <lowerValueLiteral>1</lowerValueLiteral>
            <eOpposite href="#screenplay"/>
          </eStructuralFeatures>

        </uml:Class>

      </uml:Package>

      <!-- NovelOrConcept Superclass -->
      <uml:Class id="_NovelOrConcept" name="NovelOrConcept"/>

      <!-- Class: Novel -->
      <uml:Class isAbstract="false" abstract="false" id="_Novel" name="Novel">
        <eSuperTypes href="#_NovelOrConcept"/>
        <eStructuralFeatures id="_titleFeature_novel" eFeatureID="_nTitle" eType="_EString" name="title"/>
        <eStructuralFeatures id="_authorFeature" eFeatureID="_auth" eType="_EString" name="author"/>
      </uml:Class>

    </uml:Model>
  </xmi:Extension>
</uml:xmi>
