<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="celo"
    nsURI="http://www.example.org/celo"
    nsPrefix="celo">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="CelOSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="users"
        eType="#//User" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events"
        eType="#//Event" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventKinds"
        eType="#//EventKind" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations"
        eType="#//Location" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tasks"
        eType="#//Task" upperBound="-1" containment="true"/>
  </eClassifiers>

  <!-- Abstract User base class -->
  <eClassifiers xsi:type="ecore:EClass" name="User" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Organizer -->
  <eClassifiers xsi:type="ecore:EClass" name="Organizer" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postalAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizedEvents"
        eType="#//EventOrganizer" upperBound="-1" eOpposite="#//EventOrganizer/organizer"/>
    <eOperations name="viewInvitationStatus">
      <eParameters name="event" eType="#//Event"/>
    </eOperations>
    <eOperations name="setTaskStatus">
      <eParameters name="task" eType="#//EventTask"/>
      <eParameters name="status" eType="#//TaskStatus"/>
    </eOperations>
    <eOperations name="addTask">
      <eParameters name="task" eType="#//Task"/>
      <eParameters name="event" eType="#//Event"/>
    </eOperations>
    <eOperations name="designateTaskForAttendee">
      <eParameters name="task" eType="#//EventTask"/>
    </eOperations>
    <eOperations name="inviteAttendee">
      <eParameters name="firstName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="lastName"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="email"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
  </eClassifiers>

  <!-- Attendee -->
  <eClassifiers xsi:type="ecore:EClass" name="Attendee" eSuperTypes="#//User">
    <eStructuralFeatures xsi:type="ecore:EReference" name="invitations"
        eType="#//Invitation" upperBound="-1" eOpposite="#//Invitation/attendee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignedTasks"
        eType="#//AttendeeTask" upperBound="-1" eOpposite="#//AttendeeTask/attendee"/>
    <eOperations name="respondToInvitation">
      <eParameters name="invitation" eType="#//Invitation"/>
      <eParameters name="status" eType="#//InvitationStatus"/>
    </eOperations>
    <eOperations name="selectTask">
      <eParameters name="eventTask" eType="#//EventTask"/>
    </eOperations>
  </eClassifiers>

  <!-- OrganizerAttendee: a person who is both an organizer and an attendee -->
  <eClassifiers xsi:type="ecore:EClass" name="OrganizerAttendee"
      eSuperTypes="#//Organizer #//Attendee"/>

  <!-- EventKind (e.g., birthday party, graduation party) -->
  <eClassifiers xsi:type="ecore:EClass" name="EventKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultTasks"
        eType="#//Task" upperBound="-1"/>
  </eClassifiers>

  <!-- Location -->
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Event -->
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occasion"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDateTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endDateTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="kind"
        eType="#//EventKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers"
        eType="#//EventOrganizer" upperBound="-1" containment="true"
        eOpposite="#//EventOrganizer/event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invitations"
        eType="#//Invitation" upperBound="-1" containment="true"
        eOpposite="#//Invitation/event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checklist"
        eType="#//EventTask" upperBound="-1" containment="true"
        eOpposite="#//EventTask/event"/>
  </eClassifiers>

  <!-- Association class: EventOrganizer (links an Organizer to an Event) -->
  <eClassifiers xsi:type="ecore:EClass" name="EventOrganizer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="event"
        eType="#//Event" eOpposite="#//Event/organizers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizer"
        eType="#//Organizer" eOpposite="#//Organizer/organizedEvents"/>
  </eClassifiers>

  <!-- Invitation (association class between Attendee and Event) -->
  <eClassifiers xsi:type="ecore:EClass" name="Invitation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="#//InvitationStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event"
        eType="#//Event" eOpposite="#//Event/invitations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendee"
        eType="#//Attendee" eOpposite="#//Attendee/invitations"/>
  </eClassifiers>

  <!-- Task (reusable task template) -->
  <eClassifiers xsi:type="ecore:EClass" name="Task">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventKind"
        eType="#//EventKind"/>
  </eClassifiers>

  <!-- EventTask: a task instance on the checklist of a specific event -->
  <eClassifiers xsi:type="ecore:EClass" name="EventTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="#//TaskStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assignedToAttendee"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="task"
        eType="#//Task"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event"
        eType="#//Event" eOpposite="#//Event/checklist"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendeeTasks"
        eType="#//AttendeeTask" upperBound="-1" containment="true"
        eOpposite="#//AttendeeTask/eventTask"/>
  </eClassifiers>

  <!-- AttendeeTask: records which attendee has taken on an EventTask -->
  <eClassifiers xsi:type="ecore:EClass" name="AttendeeTask">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTask"
        eType="#//EventTask" eOpposite="#//EventTask/attendeeTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendee"
        eType="#//Attendee" eOpposite="#//Attendee/assignedTasks"/>
  </eClassifiers>

  <!-- Enumerations -->

  <eClassifiers xsi:type="ecore:EEnum" name="InvitationStatus">
    <eLiterals name="ATTENDING" value="0"/>
    <eLiterals name="MAYBE_ATTENDING" value="1"/>
    <eLiterals name="NOT_ATTENDING" value="2"/>
    <eLiterals name="NO_REPLY" value="3"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EEnum" name="TaskStatus">
    <eLiterals name="TODO" value="0"/>
    <eLiterals name="DONE" value="1"/>
    <eLiterals name="NOT_APPLICABLE" value="2"/>
  </eClassifiers>

</ecore:EPackage>
