<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="transport_system" nsURI="http://www.example.com/transport_system">
    
    <!-- Custom DataType for java.time.LocalTime to handle times without dates -->
    <ecore:eDataType name="LocalTime" instance="java.time.LocalTime"/>

    <!-- Root Container: Contains all entities that do not have a specific container -->
    <ecore:eClass name="TransportCompanySystem">
      <ecore:eReference name="employees" eType="Employee"/>
      <ecore:eReference name="customers" eType="Customer"/>
      <ecore:eReference name="vehicles" eType="Vehicle"/>
      <ecore:eReference name="repairShops" eType="RepairShop"/>
      <ecore:eReference name="partnerCompanies" eType="PartnerCompany"/>
      <ecore:eReference name="orders" eType="Order"/>
    </ecore:eClass>

    <!-- Employee Hierarchy -->
    <ecore:eClass name="Employee" abstract="true">
      <ecore:eAttribute name="name" eType="EString"/>
      <ecore:eAttribute name="socialSecurityNumber" eType="EString"/>
    </ecore:eClass>

    <ecore:eClass name="Driver" eSuperClass="Employee"/>

    <ecore:eClass name="Staff" eSuperClass="Employee" abstract="true">
      <ecore:eAttribute name="username" eType="EString"/>
      <ecore:eAttribute name="password" eType="EString"/>
    </ecore:eClass>

    <ecore:eClass name="Planner" eSuperClass="Staff"/>

    <ecore:eClass name="AdministrativeStaff" eSuperClass="Staff">
      <ecore:eAttribute name="fieldOfActivity" eType="EString"/>
    </ecore:eClass>

    <!-- Customer -->
    <ecore:eClass name="Customer">
      <ecore:eAttribute name="name" eType="EString"/>
      <ecore:eAttribute name="billingAddress" eType="EString"/>
    </ecore:eClass>

    <!-- Vehicle Hierarchy -->
    <ecore:eClass name="Vehicle" abstract="true">
      <ecore:eAttribute name="licensePlateNumber" eType="EString"/>
      <ecore:eAttribute name="mileage" eType="EInt"/>
    </ecore:eClass>

    <ecore:eClass name="RefrigeratedTruck" eSuperClass="Vehicle"/>
    <ecore:eClass name="SmallVan" eSuperClass="Vehicle"/>
    <ecore:eClass name="LoadingPlatform" eSuperClass="Vehicle"/>
    <ecore:eClass name="BoxTruck" eSuperClass="Vehicle"/>

    <!-- Repair Shop -->
    <ecore:eClass name="RepairShop">
      <ecore:eAttribute name="name" eType="EString"/>
      <ecore:eAttribute name="address" eType="EString"/>
    </ecore:eClass>

    <!-- Repair event details -->
    <ecore:eClass name="Repair">
      <ecore:eAttribute name="duration" eType="EString"/>
      <ecore:eAttribute name="cost" eType="EDouble"/>
      <ecore:eReference name="vehicle" eType="Vehicle"/>
      <ecore:eReference name="employee" e umaEmployee" eType="Employee"/>
      <ecore:eReference name="repairShop" eType="RepairShop"/>
    </ecore:eClass>

    <!-- Partner Company -->
    <ecore:eClass name="PartnerCompany">
      <ecore:eAttribute name="name" eType="EString"/>
      <ecore:eAttribute name="address" eType="EString"/>
    </ecore:eClass>

    <!-- Order Management -->
    <ecore:eClass name="Order">
      <ecore:eAttribute name="packageSize" eType="EString"/>
      <ecore:eAttribute name="comment" eType="EString"/>
      <ecore:eAttribute name="startTime" eType="LocalTime"/>
      <ecore:eAttribute name="finishTime" eType="LocalTime"/>
      <ecore:eAttribute name="pickUpAddress" eType="EString"/>
      <ecore:eAttribute name="deliveryAddress" eType="EString"/>
      
      <!-- The client who is the customer -->
      <ecore:eReference name="client" eType="Customer"/>
      
      <!-- Planner responsible for assigning the order to a vehicle -->
      <ecore:eReference name="assignedBy" eType="Planner"/>
      
      <!-- Execution details: Driver and Vehicle used -->
      <ecore:eReference name="completedBy" eType="Driver"/>
      <ecore:eReference name="usedVehicle" eType="Vehicle"/>
      
      <!-- Placement source: Administrative employee or Partner company -->
      <ecore:eReference name="placedByAdmin" eType="AdministrativeStaff"/>
      <ecore:eReference name="placedByPartner" eType="PartnerCompany"/>
    </ecore:eClass>

  </ecore:EPackage>
</xmi:XMI>
