<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="ebike" nsURI="http://www.example.org/ebike" xmi:id="ebike_pkg">
    
    <!-- Root Container -->
    <eClass name="EBikeSystem" xmi:id="ebike_system">
      <eStructuralFeatures>
        <eStructuralFeature xmi:id="sys_bikes" name="bikes" eType="ebike_class" />
        <eStructuralFeature xmi:id="sys_batteries" name="batteries" eType="battery_class" />
      </eStructuralFeatures>
    </eClass>

    <eClass name="EBike" xmi:id="ebike_class">
      <eStructuralFeatures>
        <eStructuralFeature xmi:id="bike_frame" name="frame" eType="frame_class" />
        <eStructuralFeature xmi:id="bike_driveSystem" name="driveSystem" eType="drivesystem_class" />
        <eStructuralFeature xmi:id="bike_controller" name="controller" eType="controller_class" />
        <eStructuralFeature xmi:id="bike_battery" name="battery" eType="battery_class" />
      </eStructuralFeatures>
    </eClass>

    <eClass name="Frame" xmi:id="frame_class">
      <eStructuralFeatures>
        <eStructuralFeature xmi:id="frame_material" name="material" eType="eString" />
        <eStructuralFeature xmi:id="frame_wheels" name="wheels" eType="wheel_class" />
      </eStructuralFeatures>
    </eClass>

    <eClass name="Wheel" xmi:id="wheel_class" />

    <eClass name="DriveSystem" xmi:id="drivesystem_class">
      <eStructuralFeatures>
        <eStructuralFeature xmi:id="ds_motor" name="motor" eType="motor_class" />
      </eStructuralFeatures>
    </eClass>

    <eClass name="Motor" xmi:id="motor_class" />

    <eClass name="Battery" xmi:id="battery_class">
      <eStructuralFeatures>
        <eStructuralFeature xmi:id="batt_energy" name="storedEnergyWh" eType="eDouble" />
      </eStructuralFeatures>
    </eClass>

    <eClass name="Controller" abstract="true" xmi:id="controller_class">
      <eStructuralFeatures>
        <eStructuralFeature xmi:id="ctrl_state" name="state" eType="controller_state_enum" />
        <eStructuralFeature xmi:id="ctrl_battery" name="battery" eType="battery_class" />
        <eStructuralFeature xmi:id="ctrl_driveSystem" name="driveSystem" eType="drivesystem_class" />
      </eStructuralFeatures>
    </eClass>

    <eClass name="BasicController" xmi:id="basic_controller_class">
      <eSuperTypes>
        <eSuperType eClass="controller_class" />
      </eSuperTypes>
    </eClass>

    <eClass name="AdvancedController" xmi:id="advanced_controller_class">
      <eSuperTypes>
        <eSuperType eClass="controller_class" />
      </eSuperTypes>
      <eStructuralFeatures>
        <eStructuralFeature xmi:id="adv_inspDate" name="nextInspectionDate" eType="eDate" />
      </eStructuralFeatures>
    </eClass>

    <eEnum name="ControllerState" xmi:id="controller_state_enum">
      <eLiterals>
        <eLiteral name="On" />
        <eLiteral name="Off" />
        <eLiteral name="Charging" />
      </eLiterals>
    </eEnum>

  </ePackage>
</xmi:XMI>
