<?xml version="1.0" encoding="UTF-8"?>
<uml:Model xmlns:xmi="http://www.omg.org/XMI"
           xmlns:uml="http://www.eclipse.org/uml2/4.4.0/UML"
           xmi:id="_model_id_"
           xmi:version="2.1">

    <!-- Define a root container class -->
    <packagedElement xmi:type="uml:Package" xmi:id="_1" name="RootContainer">
        <packagedElement>
            <packagedElement xmi:type="uml:Class" xmi:id="_2" name="BusTransportationManagementSystem">

                <!-- Attributes -->
                <ownedAttribute xmi:id="_3" name="drivers"/>
                <ownedAttribute xmi:id="_4" name="buses"/>

                <!-- Operations -->
                <ownedOperation xmi:id="_5" name="assignDriverToShift(String driverId, String busId, Date date)"/>

            </packagedElement>

            <!-- Define the Driver class -->
            <packagedElement xmi:type="uml:Class" xmi:id="_6" name="Driver">
                <ownedAttribute xmi:type="uml:Attribute" xmi:id="_7" name="name"/>
                <ownedAttribute xmi:type="uml:Attribute" xmi:id="_8" name="driverId"
                                type="_Integer"/>
                <ownedAttribute xmi:type="uml:Boolean" xmi:id="_9" name="isSickLeave"/>

            </packagedElement>

            <!-- Define the LicencePlate class -->
            <packagedElement xmi:type="uml:Class" xmi:id="_10" name="LicencePlate">
                <ownedAttribute xmi:type="uml:Attribute" xmi:id="_11" name="licenceNumber"
                                type="_String"/>
            </packagedElement>

            <!-- Define the Bus class -->
            <packagedElement xmi:type="uml:Class" xmi:id="_12" name="Bus">

                <ownedAttribute xsi:type="uml:AssociationEnd" xmi:id="_13" association="_14">
                    <memberEnd xmi:idref="_6"/>
                    <lower>0</lower>
                    <upper>1</upper>
                </ownedAttribute>

                <ownedAttribute xmi:id="_15" name="licencePlate"
                                type="_10"/>

            </packagedElement>

            <!-- Define the BusRoute class -->
            <packagedElement xmi:type="uml:Class" xmi:id="_16" name="BusRoute">

                <ownedAttribute xsi:type="uml:Attribute" xmi:id="_17" name="routeNumber"
                                type="_Integer"/>

                <ownedOperation xmi:id="_18" name="addBus(Bus bus, Date date)"/>

            </packagedElement>

            <!-- Define the Schedule class with association classes -->
            <packagedElement xmi:type="uml:Class" xmi:id="_19" name="Schedule">

                <ownedAttribute>
                    <associationEnd xmi:idref="_14"/>
                    <ordered>true</ordered>
                    <lower>1</lower>
                    <upper>3</upper>
                </ownedAttribute>

                <ownedOperation xmi:id="_20" 
                                name="addShift(Date date, String shiftType)"/>

            </packagedElement>

            <!-- Define the ScheduleAssignment association class -->
            <packagedElement xmi:type="uml:Class" xmi:id="_21" name="ScheduleAssignment">

                <associationEnd xsi:type="uml:NavigableAssociation" xmi:idref="_22">

                    <memberEnd xmi:idref="_6"/>
                    
                </associationEnd>

                <!-- Define association ends for Bus and Schedule -->
                <ownedAttribute xsi:type="uml:AssociationEnd" xmi:id="_24">
                    <memberEnd xmi:idref="_13"/>
                    <lower>0</lower>
                    <upper>-1</upper>
                    <type href="#_12">Bus</type>
                </ownedAttribute>

                <ownedAttribute xmi:type="uml:AssociationEnd" xmi:id="_25">
                    <memberEnd xmi:idref="_19"/>
                </ownedAttribute>

            </packagedElement>

            <!-- Association between Driver and ScheduleAssignment -->
            <associated xmi:id="_14" name="driverSchedule">

                <eType xmi:href="#_21">ScheduleAssignment</eType>
                
                <end type="1" aggregation="composite" navigable="true"/>
                
                <ownedEnd xmi:type="uml:AssociationEnd" xmi:id="_23">
                    <type href="#_6"/>
                </ownedEnd>

                <ownedEnd xmi:type="uml:AssociationEnd" xmi:idref="_25"/>

            </associated>
        </packagedElement>
    </packagedElement>
</uml:Model>
