<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="HealthcareModel" nsURI="http://www.healthcare.model" eNSXMIType="healthcare.model.HealthcarePackage">
    <eClassifications>
      <eClass name="HealthcareSystem">
        <eStructuralFeatures>
          <eReference name="hospitals" eType="Hospital"/>
          <eReference name="doctors" eType="Doctor"/>
          <eReference name="patients" eType="Patient"/>
          <eReference name="problems" eType="Problem"/>
          <eReference name="examinationTypes" eType="ExaminationType"/>
          <eReference name="treatmentPlans" eType="TreatmentPlan"/>
          <eReference name="diagnoses" eType="Diagnosis"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Hospital">
        <eStructuralFeatures>
          <eAttribute name="name" eType="ecore:EString"/>
          <eReference name="permittedExaminationTypes" eType="ExaminationType"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Doctor">
        <eStructuralFeatures>
          <eAttribute name="name" eType="ecore:EString"/>
          <eReference name="affiliatedHospital" eType="Hospital"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Patient">
        <eStructuralFeatures>
          <eAttribute name="name" eType="ecore:EString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="ExaminationType">
        <eStructuralFeatures>
          <eAttribute name="typeName" eType="ecore:EString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Problem">
        <eStructuralFeatures>
          <eAttribute name="description" eType="ecore:EString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="TreatmentPlan">
        <eStructuralFeatures>
          <eReference name="problem" eType="Problem"/>
          <eReference name="advisedExaminations" eType="ExaminationType"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="Diagnosis">
        <eStructuralFeatures>
          <eReference name="doctor" eType="Doctor"/>
          <eReference name="patient" eType="Patient"/>
          <eReference name="hospitalVisited" eType="Hospital"/>
          <eReference name="identifiedProblem" eType="Problem"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="ActualTreatment">
        <eStructuralFeatures>
          <eReference name="diagnosis" eType="Diagnosis"/>
          <eReference name="basisPlan" eType="TreatmentPlan"/>
          <eReference name="actions" eType="MedicalAction"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="MedicalAction" abstract="true">
        <eStructuralFeatures>
          <eAttribute name="description" eType="ecore:EString"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="ExaminationOrder" eSuperClass="MedicalAction">
        <eStructuralFeatures>
          <eReference name="examinationType" eType="ExaminationType"/>
          <eReference name="performingHospital" eType="Hospital"/>
        </eStructuralFeatures>
      </eClass>

      <eClass name="GeneralMedicalAction" eSuperClass="MedicalAction">
        <eStructuralFeatures>
          <eAttribute name="actionDetail" eType="ecore:EString"/>
        </eStructuralFeatures>
      </eClass>
    </eClassifications>
  </ePackage>
</xmi:XMI>
