<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.5"
         xmlns:xmi="http://www.omg.org/spec/XMI/2.5"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
    <xmi:Diagrams/>
    
    <!-- Root Container -->
    <ecore:EClass xmi:id="_RootContainer" name="RootContainer"/>

    <!-- User Class -->
    <ecore:EClass xmi:id="_User" name="User">
        <eStructuralFeatures>
            <ecore:EAttribute xmi:id="__username" name="username" type="ecore:EJavaObject"/>
            <ecore:EReference xmi:id="__playerReference" 
                              eType="#_Player" containment="true" name="player"/>
            <ecore:EReference xmi:id="__adminReference"
                              eType="#_Admin" multiplicity="0..1" name="admin"/>
        </eStructuralFeatures>
    </ecore:EClass>

    <!-- Player Class -->
    <ecore:EClass xmi:id="_Player" name="Player">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/DONT_DELETE_CONTENT"/>
        <eStructuralFeatures/>
    </ecore:EClass>

    <!-- Admin Class -->
    <ecore:EClass xmi:id="_Admin" name="Admin">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/DONT_DELETE_CONTENT"/>
        <eStructuralFeatures/>
    </ecore:EClass>

    <!-- Game Class -->
    <ecore:EClass xmi:id="_Game" name="Game">
        <eStructuralFeatures>
            <ecore:EAttribute xmi:id="__gameName" name="name" type="ecore:EJavaObject"/>
            <ecore:EReference xmi:id="__hallOfFameReference"
                              eType="#_HallOfFame" containment="true" name="hallOfFame"/>
            <ecore:EReference xmi:id="__blocksSetReference"
                              eType="#__BlocksSet" containment="true" name="blocksSet"/>
        </eStructuralFeatures>
    </ecore:EClass>

    <!-- BlocksSet Class -->
    <ecore:EClass xmi:id="__BlocksSet" name="BlocksSet">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/DONT_DELETE_CONTENT"/>
        <eStructuralFeatures>
            <ecore:EReference xmi:id="__blockReferences"
                              eType="#__Block" many="true" name="blocks"/>
        </eStructuralFeatures>
    </ecore:EClass>

    <!-- Block Class -->
    <ecore:EClass xmi:id="__Block" name="Block">
        <eStructuralFeatures>
            <ecore:EAttribute xmi:id="__color" name="color" type="ecore:EJavaObject"/>
            <ecore:EAttribute xmi:id="__points" name="points" type="_EInt"/>
        </eStructuralFeatures>
    </ecore:EClass>

    <!-- Level Class -->
    <ecore:EClass xmi:id="_Level" name="Level">
        <eStructuralFeatures>
            <ecore:EReference xmi:id="__levelNumber"
                              eType="_EIntegerObject" containment="true" name="number"/>
            <ecore:EReference xmi:id="__startingArrangementReference"
                              eType="#__StartingArrangement" containment="true" name="startingArrangement"/>
        </eStructuralFeatures>
    </ecore:EClass>

    <!-- StartingArrangement Class -->
    <ecore:EClass xmi:id="__StartingArrangement" name="StartingArrangement">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/DONT_DELETE_CONTENT"/>
    </ecore:EClass>

    <!-- HallOfFame Class -->
    <ecore:EClass xmi:id="_HallOfFame" name="HallOfFame">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/DONT_DELETE_CONTENT"/>
        <eStructuralFeatures>
            <ecore:EReference xmi:id="__highScoresReference"
                              eType="#_HighScore" many="true" name="highScores"/>
        </eStructuralFeatures>
    </ecore:EClass>

    <!-- HighScore Class -->
    <ecore:EClass xmi:id="_HighScore" name="HighScore">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/DONT_DELETE_CONTENT"/>
        <eStructuralFeatures>
            <ecore:EReference xmi:id="__playerReference"
                              eType="#_Player" containment="false" name="player"/>
            <ecore:EAttribute xmi:id="__score" name="score" type="ecore:EInt"/>
        </eStructuralFeatures>
    </ecore:EClass>

</xmi:XMI>
