<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fitnessCenter" nsURI="http://www.example.org/fitnessCenter"
    nsPrefix="fitnessCenter">
  <eClassifiers xsi:type="ecore:EClass" name="FitnessCenterModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="centers" upperBound="-1"
        eType="#//Center" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Center">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" lowerBound="1" upperBound="-1"
        eType="#//Room" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roomNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCapacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sessions" upperBound="-1"
        eType="#//Session" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Session" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndividualSession" eSuperTypes="#//Session">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" lowerBound="1"
        eType="#//Member" eOpposite="#//Member/individualSessions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GroupSession" eSuperTypes="#//Session">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" eOpposite="#//Member/groupSessions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trainer" lowerBound="1"
        eType="#//Trainer" eOpposite="#//Trainer/groupSessions"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="birthDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="individualSessions" upperBound="-1"
        eType="#//IndividualSession" eOpposite="#//IndividualSession/member"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupSessions" upperBound="-1"
        eType="#//GroupSession" eOpposite="#//GroupSession/members"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trainer" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diploma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="groupSessions" upperBound="-1"
        eType="#//GroupSession" eOpposite="#//GroupSession/trainer"/>
  </eClassifiers>
</ecore:EPackage>
