<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:version="2.0">
  <ecore:EPackage name="eHome2020" nsURI="http://www.example.org/eHome2020" nsPrefix="eHome2020" xmi:id="package_1">

    <!-- Enumeration for Unit -->
    <ecore:EEnum name="Unit" xmi:id="enum_unit">
      <ecore:ELiteral name="CELSIUS" value="0"/>
      <ecore:ELiteral name="WATT" value="1"/>
    </ecore:EEnum>

    <!-- Root Container Class -->
    <ecore:EClass name="SystemRoot" xmi:id="class_systemroot">
      <ecore:EReference name="apartments" eType="#//Apartment" upperBound="-1" containment="true"/>
      <ecore:EReference name="sensors" eType="#//Sensor" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Apartment Class -->
    <ecore:EClass name="Apartment" xmi:id="class_apartment">
      <ecore:EAttribute name="address" eType="ecore:EString"/>
      <ecore:EReference name="inhabitants" eType="#//Inhabitant" upperBound="-1" containment="true"/>
      <ecore:EReference name="rooms" eType="#//Room" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Inhabitant Class -->
    <ecore:EClass name="Inhabitant" xmi:id="class_inhabitant">
      <ecore:EAttribute name="username" eType="ecore:EString"/>
      <ecore:EAttribute name="password" eType="ecore:EString"/>
      <ecore:EReference name="emailAddress" eType="ecore:EString"/>
    </ecore:EClass>

    <!-- Room Class -->
    <ecore:EClass name="Room" xmi:id="class_room">
      <ecore:EAttribute name="description" eType="ecore:EString"/>
      <ecore:EReference name="sensors" eType="#//Sensor" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Sensor Class -->
    <ecore:EClass name="Sensor" xmi:id="class_sensor">
      <ecore:EAttribute name="vendorId" eType="ecore:EString"/>
      <ecore:EAttribute name="description" eType="ecore:EString"/>
      <ecore:EReference name="room" eType="#//Room"/>
      <ecore:EAttribute name="unit" eType="#//Unit"/>
      <ecore:EReference name="measurementValues" eType="#//SensorValue" upperBound="-1" containment="true"/>
      <ecore:EReference name="lastMeasurementValue" eType="#//SensorValue"/>
    </ecore:EClass>

    <!-- TemperatureSensor Class -->
    <ecore:EClass name="TemperatureSensor" xmi:id="class_temperaturesensor">
      <ecore:EGenericType xmi:id="temperatureSensor_genericType" instanceClassName="java.time.LocalTime"/>
      <ecore:EAttribute name="minValue" eType="ecore:EFloat"/>
      <ecore:EAttribute name="maxValue" eType="ecore:EFloat"/>
    </ecore:EClass>

    <!-- PowerSensor Class -->
    <ecore:EClass name="PowerSensor" xmi:id="class_powersensor">
      <ecore:EReference name="totalPowerConsumption" eType="#//SensorValue"/>
    </ecore:EClass>

    <!-- SensorValue Class -->
    <ecore:EClass name="SensorValue" xmi:id="class_sensorvalue">
      <ecore:EAttribute name="timestamp" eType="#//Time"/>
      <ecore:EReference name="value" eType="ecore:EFloat"/>
    </ecore:EClass>

    <!-- Time Data Type -->
    <ecore:EDataType name="Time" instanceClassName="java.time.LocalTime"/>

  </ecore:EPackage>
</xmi:XMI>
