<?xml version="1.0" encoding="UTF-8"?>
<uml:XMI xmi:version="2.5"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:uml="http://www.eclipse.org/uml2/4.1.0/UML"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    
    xmlns:musicmatic="http://example.com/musicmatic.ecore">
  
  <!-- Package Definitions -->
  
  <package xmi:id="_MusicmaticPackage" name="musicmatic" 
           nsURI="http://example.com/musicmatic.ecore"
           nsPrefix="mm">

    <!-- EDataType Definitions -->

    <eClassifiers xsi:type=ecore:EDataType>
      <eAnnotations source='http://www.eclipse.org/emf/2002/Ecore'>
        <details key='base_Class' value='\java.time.LocalDate'/>
      </eAnnotations>
      <name>EDate</name>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EDataType>
      <eAnnotations source='http://www.eclipse.org/emf/2002/Ecore'>
        <details key='base_Class' value='\java.time.Duration'/>
      </eAnnotations>
      <name>Duration</name>
    </eClassifiers>

    <!-- Class Definitions -->

    <eClassifiers xsi:type=ecore:EClass>
      <name>Artist</name>
      <eStructuralFeatures>
        <EStructuralFeature name="artistName" type="_String"/>
        <EStructuralFeature name="dateOfBirth" eGenericType="#_EDate"/>
        <EStructuralFeature name="websiteURL" type="_String"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>Song</name>
      <eStructuralFeatures>
        <EStructuralFeature name="title" type="_String"/>
        <EStructuralFeature name="releaseYear" type="_Integer"/>
        <EStructuralFeature name="length" type="#_Duration"/>
        <EStructuralFeature name="genre" type="_String"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>User</name>
      <eSuperTypes>
        <esuperType href="#_Root"/>
      </eSuperTypes>
      <eStructuralFeatures>
        <EStructuralFeature name="uniqueID" type="_String"/>
        <EStructuralFeature name="userName" type="_String"/>
        <EStructuralFeature name="userAddress" type="_String"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>RegularUser</name>
      <eSuperTypes>
        <esuperType href="#_User"/>
      </eSuperTypes>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>BusinessUser</name>
      <eSuperTypes>
        <esuperType href="#_User"/>
      </eSuperTypes>
      <eStructuralFeatures>
        <EStructuralFeature name="vatNumber" type="_String"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>Album</name>
      <eSupertype/>
      <eStructuralFeatures>
        <EStructuralFeature name="hitsCollection"
                            eType="#_TrackAssociation" 
                            upper="-1" lower="0" many="true" containment="true"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>Hit</name>
      <eSuperTypes>
        <esuperType href="#_Song"/>
      </eSuperTypes>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>Suggestion</name>
      <eStructuralFeatures>
        <EStructuralFeature name="suggestedAlbum" eType="#_Album"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>TrackAssociation</name>
      <eSuperTypes/>
      <eStructuralFeatures>
        <EStructuralFeature name="hit" eType="#_Hit"/>
        <EStructuralFeature name="numberInAlbum" type="_Integer"/>
      </eStructuralFeatures>
    </eClassifiers>

    <eClassifiers xsi:type=ecore:EClass>
      <name>SongArtistAssociation</name>
      <eSuperTypes/>
      <eStructuralFeatures>
        <EStructuralFeature name="song" eType="#_Song"/>
        <EStructuralFeature name="artist" eType="#_Artist"/>
      </eStructuralFeatures>
    </eClassifiers>

    <!-- Root Class -->

    <eClassifiers xsi:type=ecore:EClass>
      <name>Musicmatic</name>
      <eSuperTypes/>
      <eStructuralFeatures>
        <EStructuralFeature name="songs"
                            eType="#_Song" 
                            upper="-1" lower="0" many="true"
                            containment="true"/>
        <EStructuralFeature name="users"
                            eType="#_User" 
                            upper="-1" lower="0" many="true"
                            containment="true"/>
        <EStructuralFeature name="artists"
                            eType="#_Artist" 
                            upper="-1" lower="0" many="true"
                            containment="true"/>
      </eStructuralFeatures>
    </eClassifiers>

  </package>

</uml:XMI>
