<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="schoolSystem" nsURI="http://www.example.org/schoolSystem" nsPrefix="school">
    <eClass name="Root" xmi:id="root_cls">
      <eReference name="schools" eType="school_cls" containment="true"/>
      <eReference name="people" eType="person_cls" containment="true"/>
    </eClass>

    <eClass name="Person" abstract="true" xmi:id="person_cls">
      <eAttribute name="firstName" eType="eString"/>
      <eAttribute name="lastName" eType="eString"/>
    </eClass>

    <eClass name="Teacher" xmi:id="teacher_cls" eSuperType="person_cls">
      <eAttribute name="email" eType="eString"/>
      <eReference name="teachingRelationships" eType="teaching_rel_cls" containment="false"/>
    </eClass>

    <eClass name="Student" xmi:id="student_cls" eSuperType="person_cls">
      <eReference name="school" eType="school_cls"/>
      <eReference name="classGroup" eType="class_group_cls"/>
    </eClass>

    <eClass name="School" xmi:id="school_cls">
      <eAttribute name="name" eType="eString"/>
      <eReference name="principal" eType="teacher_cls"/>
      <eReference name="rooms" eType="room_cls" containment="true"/>
      <eReference name="teachingRelationships" eType="teaching_rel_cls" containment="true"/>
    </eClass>

    <eClass name="TeachingRelationship" xmi:id="teaching_rel_cls">
      <eAttribute name="hours" eType="eInt"/>
      <eReference name="teacher" eType="teacher_cls"/>
      <eReference name="school" eType="school_cls"/>
    </eClass>

    <eClass name="Room" abstract="true" xmi:id="room_cls">
      <eAttribute name="name" eType="eString"/>
    </eClass>

    <eClass name="Classroom" xmi:id="classroom_cls" eSuperType="room_cls">
      <eAttribute name="capacity" eType="eInt"/>
      <eReference name="classGroup" eType="class_group_cls"/>
    </eClass>

    <eClass name="OtherRoom" xmi:id="other_room_cls" eSuperType="room_cls">
      <eAttribute name="sizeInSquareMeters" eType="eDouble"/>
    </eClass>

    <eClass name="ClassGroup" xmi:id="class_group_cls">
      <eAttribute name="name" eType="eString"/>
      <eReference name="classroom" eType="classroom_cls"/>
      <eReference name="students" eType="student_cls"/>
    </eClass>
  </ePackage>
</xmi:XMI>
