<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

  <ecore:EPackage name="university" nsURI="http://example.org/university" nsPrefix="university">
    <!-- DataTypes -->
    <ecore:EDataType name="TimeWithoutDate"/>

    <!-- Classes -->
    <ecore:EClass name="University" abstract="false">
      <eStructuralFeatures>
        <ecore:EReference name="faculties" eType="#//Faculty" upperBound="-1" containment="true"/>
        <ecore:EAttribute name="totalEmployees" eType="ecore:EInt"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Faculty" abstract="false">
      <eStructuralFeatures>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
        <ecore:EReference name="institutes" eType="#//Institute" upperBound="-1" containment="true"/>
        <ecore:EReference name="dean" eType="#//Dean"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Institute" abstract="false">
      <eStructuralFeatures>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
        <ecore:EAttribute name="address" eType="ecore:EString"/>
        <ecore:EReference name="researchAssistants" eType="#//ResearchAssistant" upperBound="-1"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Employee" abstract="true">
      <eStructuralFeatures>
        <ecore:EAttribute name="socialSecurityNumber" eType="ecore:EString"/>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
        <ecore:EAttribute name="email" eType="ecore:EString"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Dean">
      <eSuperTypes eClass="#//Employee"/>
      <eStructuralFeatures/>
    </ecore:EClass>

    <ecore:EClass name="ResearchAssistant" abstract="false">
      <eSuperTypes eClass="#//Employee"/>
      <eStructuralFeatures>
        <ecore:EReference name="institutes" eType="#//Institute" upperBound="-1"/>
        <ecore:EAttribute name="fieldOfResearch" eType="ecore:EString"/>
        <ecore:EReference name="projects" eType="#//Project" upperBound="-1" containment="true"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Lecturer">
      <eSuperTypes eClass="#//ResearchAssistant"/>
      <eStructuralFeatures>
        <ecore:EReference name="courses" eType="#//Course" upperBound="-1" containment="true"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Project" abstract="false">
      <eStructuralFeatures>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
        <ecore:EAttribute name="startDate" eType="#//TimeWithoutDate"/>
        <ecore:EAttribute name="endDate" eType="#//TimeWithoutDate"/>
      </eStructuralFeatures>
    </ecore:EClass>

    <ecore:EClass name="Course" abstract="false">
      <eStructuralFeatures>
        <ecore:EAttribute name="id" eType="ecore:EInt"/>
        <ecore:EAttribute name="name" eType="ecore:EString"/>
        <ecore:EAttribute name="durationHoursPerWeek" eType="ecore:EInt"/>
      </eStructuralFeatures>
    </ecore:EClass>

  </ecore:EPackage>
</xmi:XMI>
