<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="Musicmatic" nsURI="http://www.musicmatic.com/metamodel">
    
    <!-- Root container to hold all top-level elements -->
    <eClass name="MusicmaticSystem">
      <eStructuralFeatures>
        <eReference name="artists" EReferenceType="containment" EReference="Artist"/>
        <eReference name="users" EReferenceType="containment" EReference="User"/>
        <eReference name="songs" EReferenceType="containment" EReference="Song"/>
        <eReference name="albums" EReferenceType="containment" EReference="Album"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Artist">
      <eStructuralFeatures>
        <eAttribute name="name" EAttributeType="EString"/>
        <eAttribute name="dateOfBirth" EAttributeType="EDate"/>
        <eAttribute name="websiteUrl" EAttributeType="EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="User">
      <eStructuralFeatures>
        <eAttribute name="id" EAttributeType="EString"/>
        <eAttribute name="name" EAttributeType="EString"/>
        <eAttribute name="address" EAttributeType="EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="RegularUser">
      <eSuperTypes>
        <eClass name="User"/>
      </eSuperTypes>
      <eStructuralFeatures>
        <!-- Regular users can buy singles -->
        <eReference name="purchasedSingles" EReference="Single"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="BusinessUser">
      <eSuperTypes>
        <eClass name="User"/>
      </eSuperTypes>
      <eStructuralFeatures>
        <eAttribute name="vatNumber" EAttributeType="EString"/>
        <!-- Business users upload songs -->
        <eReference name="uploadedSongs" EReference="Song"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Song">
      <eStructuralFeatures>
        <eAttribute name="title" EAttributeType="EString"/>
        <eAttribute name="year" EAttributeType="EInt"/>
        <eAttribute name="length" EAttributeType="Duration"/>
        <eAttribute name="genre" EAttributeType="EString"/>
        <eReference name="artist" EReference="Artist"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Single">
      <eSuperTypes>
        <eClass name="Song"/>
      </eSuperTypes>
    </eClass>

    <eClass name="Hit">
      <eSuperTypes>
        <eClass name="Song"/>
      </eSuperTypes>
      <!-- Reference to the association class for Album -->
      <eStructuralFeatures>
        <eReference name="albumEntries" EReference="AlbumEntry"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Album">
      <eStructuralFeatures>
        <eReference name="creator" EReference="User"/>
        <!-- Suggestion to other regular users -->
        <eReference name="suggestedTo" EReference="RegularUser"/>
        <!-- Containment reference to the association class AlbumEntry -->
        <eReference name="entries" EReferenceType="containment" EReference="AlbumEntry"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Association Class for Album and Hit -->
    <eClass name="AlbumEntry">
      <eStructuralFeatures>
        <eAttribute name="trackNumber" EAttributeType="EInt"/>
        <eReference name="album" EReference="Album"/>
        <eReference name="hit" EReference="Hit"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Custom datatype for song length using java.time.Duration -->
    <eDataType name="Duration" instance="java.time.Duration"/>

  </ePackage>
</xmi:XMI>
