<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="gasstation" nsURI="http://www.example.org/gasstation" nsPrefix="gasstation">

    <!-- Root container -->
    <eClassifiers xsi:type="ecore:EClass" name="GasStationSystem">
      <eStructuralFeatures xmi:type="ecore:EReference" name="gasStations" eType="#//GasStation" upperBound="-1"/>
    </eClassifiers>

    <!-- Gas Station -->
    <eClassifiers xsi:type="ecore:EClass" name="GasStation">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="id" eType="ecore:EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="address" eType="ecore:EString"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="fuelPumps" eType="#//FuelPump" upperBound="-1"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="dailyPrices" eType="#//DailyPrice" upperBound="-1"/>
    </eClassifiers>

    <!-- Fuel Pump -->
    <eClassifiers xsi:type="ecore:EClass" name="FuelPump">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="pumpNumber" eType="ecore:EInt"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="isSelfService" eType="ecore:EBoolean"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="fuelsOffered" eType="#//Fuel" upperBound="-1"/>
    </eClassifiers>

    <!-- Fuel -->
    <eClassifiers xsi:type="ecore:EClass" name="Fuel">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="name" eType="ecore:EString"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="octaneRating" eType="ecore:EFloat"/>
    </eClassifiers>

    <!-- Daily Price -->
    <eClassifiers xsi:type="ecore:EClass" name="DailyPrice">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="date" eType="ecore:EDate"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="fuel" eType="#//Fuel"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="gasStation" eType="#//GasStation"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="pricePerLiter" eType="ecore:EFloat"/>
    </eClassifiers>

    <!-- Fuel Purchase -->
    <eClassifiers xsi:type="ecore:EClass" name="FuelPurchase">
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="id" eType="ecore:EString"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="fuelPump" eType="#//FuelPump"/>
      <eStructuralFeatures xmi:type="ecore:EReference" name="dailyPrice" eType="#//DailyPrice"/>
      <eStructuralFeatures xmi:type="ecore:EAttribute" name="litersDispensed" eType="ecore:EFloat"/>
    </eClassifiers>

  </ecore:EPackage>
</xmi:XMI>
