<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" epackageID="FitnessSystem">
    
    <!-- Root Container -->
    <eClassifiers xsi:type="ecore:EClass" name="FitnessSystemRoot"/>

    <!-- Center Class -->
    <eClassifiers xsi:type="ecore:EClass" name="Center">
        <eStructuralFeatures xsi:type="ecore:EReference" lowerValue="1" upperValue="-1"
                             eOpposite="#centerRooms" containment="true">
            <eType href="#Room"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"/>
    </eClassifiers>

    <!-- Room Class -->
    <eClassifiers xsi:type="ecore:EClass" name="Room">
        <eStructuralFeatures xsi:type="ecore:EReference" eOpposite="#centerRooms"
                             containment="false">
            <eType href="#Center"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="number"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="maximumCapacity"/>
    </eClassifiers>

    <!-- Person Class -->
    <eClassifiers xsi:type="ecore:EClass" name="Person">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="familyName"/>
        <eStructuralFeatures xsi:type="ecore:EDate.EDataType"
                             eOpposite="#birthDate">
            <eType href="http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <name>birthDate</name>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Trainer Class -->
    <eClassifiers xsi:type="ecore:EClass" name="Trainer">
        <eSuperTypes>#{Person}</eSuperTypes>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="diploma"/>
    </eClassifiers>

    <!-- Session class -->
    <eClassifiers xsi:type="ecore:EClass" name="Session">
        <eStructuralFeatures xsi:type="ecore:EDate.EDataType"
                             eOpposite="#sessionDate">
            <eType href="http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
            <name>sessionDate</name>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="startingHour"/>
    </eClassifiers>

    <!-- GroupSession Class -->
    <eClassifiers xsi:type="ecore:EClass" name="GroupSession">
        <eSuperTypes>#{Session}</eSuperTypes>
        <eStructuralFeatures xsi:type="ecore:EReference" eOpposite="#groupTrainer"
                             containment="true">
            <eType href="#GroupSessionTrainer"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"/>
    </eClassifiers>

    <!-- IndividualSession Class -->
    <eClassifiers xsi:type="ecore:EClass" name="IndividualSession">
        <eSuperTypes>#{Session}</eSuperTypes>
    </eClassifiers>

    <!-- SessionRoom Association Class -->
    <eClassifiers xsi:type="ecore:EClass" name="SessionRoom">
        <eStructuralFeatures xsi:type="ecore:EReference" eOpposite="#sessionRooms"
                             containment="true">
            <eType href="#Center"/>
            <lowerValue>1</lowerValue>
            <upperValue>1</upperValue>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" many="true" eOpposite="#sessionsInThisRoom"
                             containment="true">
            <eType href="#Session"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- GroupSessionTrainer Association Class -->
    <eClassifiers xsi:type="ecore:EClass" name="GroupSessionTrainer">
        <eStructuralFeatures xsi:type="ecore:EReference" eOpposite="#trainsInGroupSession"
                             containment="true">
            <eType href="#Trainer"/>
        </eStructuralFeatures>
        <eStructuralFeatures xsi:type="ecore:EReference" eOpposite="#groupTrainer"
                             containment="false">
            <eType href="#GroupSession"/>
        </eStructuralFeatures>
    </eClassifiers>

</ecore:EPackage>
