<?xml version="1.0" encoding="UTF-8"?>
<ePackage name="Facepage" nsURI="http://www.facepage.com/model" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmi:version="2.0">
  <eClass name="FacepageRoot">
    <eStructuralFeatures>
      <eReference name="users" eType="User" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="User">
    <eStructuralFeatures>
      <eAttribute name="id" eType="ecore:EString"/>
      <eAttribute name="name" eType="ecore:EString"/>
      <eAttribute name="email" eType="ecore:EString"/>
      <eAttribute name="dateOfBirth" eType="ecore:EDate"/>
      <eReference name="account" eType="Account" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Account" abstract="true">
    <eStructuralFeatures>
      <eAttribute name="accountNumber" eType="ecore:EInt"/>
      <eReference name="user" eType="User"/>
      <eReference name="pages" eType="Page" containment="true"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="PersonalAccount">
    <eExtendSuperClass eClass="Account"/>
    <eStructuralFeatures>
      <eReference name="friends" eType="PersonalAccount"/>
      <eReference name="privilegedPages" eType="Page"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="BusinessAccount">
    <eExtendSuperClass eClass="Account"/>
    <eStructuralFeatures>
      <eAttribute name="companyName" eType="ecore:EString"/>
      <eAttribute name="monthlyFee" eType="ecore:EDouble"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="Page">
    <eStructuralFeatures>
      <eAttribute name="pageName" eType="ecore:EString"/>
      <eAttribute name="visitCount" eType="ecore:EInt"/>
      <eReference name="adminAccount" eType="Account"/>
    </eStructuralFeatures>
  </eClass>

  <eClass name="AdvertisementPage">
    <eExtendSuperClass eClass="Page"/>
    <eStructuralFeatures>
      <eAttribute name="bounceRate" eType="ecore:EDouble"/>
      <eAttribute name="clickThroughRate" eType="ecore:EDouble"/>
      <eAttribute name="conversionRate" eType="ecore:EDouble"/>
    </eStructuralFeatures>
  </eClass>
</ePackage>
