<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="cardgame" nsUri="http://www.example.org/cardgame" nsPrefix="cardgame">
    <eClass name="CardGameSystem">
      <eStructuralFeatures>
        <eReference name="games" elementType="Game" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Game">
      <eStructuralFeatures>
        <eAttribute name="id" type="ecore:EString"/>
        <eReference name="players" elementType="Player" containment="true"/>
        <eReference name="deck" elementType="Deck" containment="true"/>
        <eReference name="scoringTable" elementType="ScoringTable" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Player">
      <eStructuralFeatures>
        <eAttribute name="id" type="ecore:EString"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Deck">
      <eStructuralFeatures>
        <eAttribute name="id" type="ecore:EString"/>
        <eReference name="cards" elementType="Card" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Card">
      <eStructuralFeatures>
        <eAttribute name="id" type="ecore:EString"/>
        <eReference name="suit" elementType="Suit"/>
      </eStructuralFeatures>
      <eOperations>
        <eOperation name="compareHeight">
          <eParameters>
            <eParameter name="other" elementType="Card"/>
          </eParameters>
          <eReturnType elementType="HeightComparison"/>
        </eOperation>
      </eOperations>
    </eClass>

    <eEnum name="Suit">
      <eLiterals name="DIAMONDS"/>
      <eLiterals name="HEARTS"/>
      <eLiterals name="SPADES"/>
      <eLiterals name="CLUBS"/>
    </eEnum>

    <eEnum name="HeightComparison">
      <eLiterals name="LOWER"/>
      <eLiterals name="EQUAL"/>
      <eLiterals name="HIGHER"/>
    </eEnum>

    <eClass name="ScoringTable">
      <eStructuralFeatures>
        <eAttribute name="id" type="ecore:EString"/>
        <eReference name="rounds" elementType="Round" containment="true"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Round">
      <eStructuralFeatures>
        <eAttribute name="id" type="ecore:EString"/>
        <eAttribute name="pointValue" type="ecore:EInt"/>
        <eReference name="winningPlayers" elementType="Player"/>
        <eAttribute name="isJackRound" type="ecore:EBoolean"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="SoloRound">
      <eExtends elementType="Round"/>
      <eStructuralFeatures>
        <eReference name="soloType" elementType="SoloType"/>
        <eReference name="soloPlayer" elementType="Player"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="MandatorySoloRound">
      <eExtends elementType="SoloRound"/>
    </eClass>

    <eEnum name="SoloType">
      <eLiterals name="TRUMP"/>
      <eLiterals name="JACK"/>
      <eLiterals name="QUEEN"/>
    </eEnum>
  </ePackage>
</xmi:XMI>
