<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

    <ecore:EPackage name="bank" nsURI="http://example.com/bank" nsPrefix="bank">
        <!-- Root container class -->
        <ecore:EClass name="BankSystem">
            <ecore:EAttribute name="name" type="ecore:EString"/>
            <ecore:EReference name="customers" eType="#//Customer" containment="true"
                upperBound="-1"/>
            <ecore:EReference name="branches" eType="#//Branch" containment="true"
                upperBound="-1"/>
        </ecore:EClass>

        <!-- Customer class -->
        <ecore:EClass name="Customer">
            <ecore:EAttribute name="firstName" type="ecore:EString"/>
            <ecore:EAttribute name="lastName" type="ecore:EString"/>
            <ecore:EReference name="accounts" eType="#//Account"
                containment="true" upperBound="-1"/>
        </ecore:EClass>

        <!-- Branch class -->
        <ecore:EClass name="Branch">
            <ecore:EAttribute name="name" type="ecore:EString"/>
        </ecore:EClass>

        <!-- Account abstract class -->
        <ecore:EClass name="Account" abstract="true">
            <ecore:EAttribute name="accountNumber" type="ecore:EInt"/>
            <ecore:EAttribute name="currentBalance" type="ecore:EDouble"/>
            <ecore:EReference name="owner" eType="#//Customer"
                containment="false"/>
        </ecore:EClass>

        <!-- CurrentAccount class -->
        <ecore:EClass name="CurrentAccount">
            <ecore:EGeneralization eSuperType="#//Account"/>
            <ecore:EAttribute name="overdraftLimit" type="ecore:EDouble"/>
        </ecore:EClass>

        <!-- SavingsAccount class -->
        <ecore:EClass name="SavingsAccount">
            <ecore:EGeneralization eSuperType="#//Account"/>
        </ecore:EClass>
    </ecore:EPackage>
</xmi:XMI>
