<?xml version="1.0" encoding="UTF-8"?>
<ePackage name="TruckLogistics" nsUri="http://www.example.org/trucklogistics" xmlns="http://www.eclipse.org/emf/2002/Ecore" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <eClass name="SystemRoot">
    <eReferences>
      <eReference name="locations" elementType="Location" containment="true"/>
      <eReference name="orders" elementType="Order" containment="true"/>
    </eReferences>
  </eClass>

  <eClass name="Location">
    <eAttributes>
      <eAttribute name="address" type="EString"/>
    </eAttributes>
    <eReferences>
      <eReference name="drivers" elementType="Driver" containment="true"/>
      <eReference name="vehicles" elementType="Vehicle" containment="true"/>
    </eReferences>
  </eClass>

  <eClass name="Driver">
    <eAttributes>
      <eAttribute name="firstName" type="EString"/>
      <eAttribute name="lastName" type="EString"/>
    </eAttributes>
    <eReferences>
      <eReference name="currentOrder" elementType="Order"/>
    </eReferences>
  </eClass>

  <eClass name="Order">
    <eAttributes>
      <eAttribute name="dateOfExecution" type="EDate"/>
    </eAttributes>
    <eReferences>
      <eReference name="origin" elementType="Location"/>
      <eReference name="destination" elementType="Location"/>
      <eReference name="drivers" elementType="Driver"/>
    </eReferences>
  </eClass>

  <eClass name="Vehicle" abstract="true">
    <eAttributes>
      <eAttribute name="vehicleNumber" type="EString"/>
    </eAttributes>
    <eReferences>
      <eReference name="driver" elementType="Driver"/>
    </eReferences>
  </eClass>

  <eClass name="Truck">
    <eSuperClass elementType="Vehicle"/>
    <eAttributes>
      <eAttribute name="weight" type="EDouble"/>
    </eAttributes>
  </eClass>

  <eClass name="Car">
    <eSuperClass elementType="Vehicle"/>
    <eAttributes>
      <eAttribute name="seats" type="EInt"/>
    </eAttributes>
  </eClass>

  <eClass name="Van">
    <eSuperClass elementType="Vehicle"/>
  </eClass>
</ePackage>
