<model xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="org.eclipse.emf.ecore/model/Ecore.xsd"
       xmlns:e="org/eclipse/emf/emf.do_domain.ecore/1.3.2">
  <metaModel name="PizzaDeliveryWithEntertainment" e:package="emf.do_domain.ecore">
    <!-- Root container class -->
    <e:EClass name="Application" abstract="false">
      <e:EAnnotation source="documentation">Root container for the entire model.</e:EAnnotation>
      <e:EStructuralFeature name="users" eType="#//User" upperBound="-1"
                            ordered="true" containment="true"/>
      <e:EStructuralFeature name="restaurants" eType="#//Restaurant" upperBound="-1"
                            ordered="true" containment="true"/>
      <e:EStructuralFeature name="orders" eType="#//Order" upperBound="-1"
                            ordered="true" containment="true"/>
      <e:EStructuralFeature name="entertainers" eType="#//Entertainer" upperBound="-1"
                            ordered="true" containment="true"/>
    </e:EClass>

    <!-- User class -->
    <e:EClass name="User" abstract="false">
      <e:EAnnotation source="documentation">Represents a user of the app.</e:EAnnotation>
      <e:EStructuralFeature name="id" eType="e:EString" derived="true"
                            ordered="true"/>
      <e:EStructralFeature name="name" eType="e:EString" upperBound="1"
                           ordered="true"/>
      <e:EStructralFeature name="birthday" eType="e:EDate" upperBound="1"
                           ordered="true"/>
      <e:EStructralFeature name="address" eType="e:EString" upperBound="1"
                           ordered="true"/>
    </e:EClass>

    <!-- BusinessOwner class -->
    <e:EClass name="BusinessOwner" abstract="false">
      <e:EAnnotation source="documentation">A user who owns pizza restaurants.</e:EAnnotation>
      <e:eSuperTypes e:refEClass="#//User"/>
      <e:EStructralFeature name="linkedInProfile" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EReference name="restaurants" eType="#//Restaurant" upperBound="-1"
                     ordered="true" containment="false"/>
    </e:EClass>

    <!-- Restaurant class -->
    <e:EClass name="Restaurant" abstract="false">
      <e:EAnnotation source="documentation">A pizza restaurant owned by a business owner.</e:EAnnotation>
      <e:EStructralFeature name="zipCode" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="address" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="phoneNumber" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="website" eType="e:EURL"
                           upperBound="1" ordered="true"/>
      <e:EReference name="openingHours" eType="#//OpeningHours" upperBound="1"
                     ordered="true" containment="true"/>
      <e:EReference name="owner" eType="#//BusinessOwner" upperBound="1"
                     ordered="true" containment="false"/>
    </e:EClass>

    <!-- Pizza class -->
    <e:EClass name="Pizza" abstract="false">
      <e:EAnnotation source="documentation">A pizza offered by a restaurant.</e:EAnnotation>
      <e:EStructralFeature name="name" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="crustStructure" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="price" eType="e:EDouble"
                           upperBound="1" ordered="true"/>
      <e:EReference name="restaurant" eType="#//Restaurant"
                     upperBound="1" ordered="true" containment="false"/>
    </e:EClass>

    <!-- HungryCustomer class -->
    <e:EClass name="HungryCustomer" abstract="false">
      <e:EAnnotation source="documentation">A user who orders pizzas.</e:EAnnotation>
      <e:eSuperTypes e:refEClass="#//User"/>
      <e:EStructralFeature name="deliveryAddress" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EReference name="orders" eType="#//Order" upperBound="-1"
                     ordered="true" containment="false"/>
    </e:EClass>

    <!-- Order class -->
    <e:EClass name="Order" abstract="false">
      <e:EAnnotation source="documentation">An order placed by a hungry customer.</e:EAnnotation>
      <e:EStructralFeature name="id" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="placedAt" eType="e:ETimestamp"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="latestDeliveryTime" eType="#//LocalTime"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="numberOfPeople" eType="e:EInt"
                           upperBound="1" ordered="true"/>
      <e:EReference name="customer" eType="#//HungryCustomer"
                     upperBound="1" ordered="true" containment="false"/>
      <e:EReference name="pizzas" eType="#//PizzaOrderItem" upperBound="-1"
                     ordered="true" containment="true"/>
    </e:EClass>

    <!-- PizzaOrderItem association class -->
    <e:EClass name="PizzaOrderItem" abstract="false">
      <e:EAnnotation source="documentation">Links an order to a pizza with quantity.</e:EAnnotation>
      <e:EStructralFeature name="quantity" eType="e:EInt"
                           upperBound="1" ordered="true"/>
      <e:EReference name="order" eType="#//Order"
                     upperBound="1" ordered="true" containment="false"/>
      <e:EReference name="pizza" eType="#//Pizza"
                     upperBound="1" ordered="true" containment="false"/>
    </e:EClass>

    <!-- EntertainmentOrder class -->
    <e:EClass name="EntertainmentOrder" abstract="false">
      <e:EAnnotation source="documentation">An order that includes entertainment.</e:EAnnotation>
      <e:eSuperTypes e:refEClass="#//Order"/>
      <e:EStructralFeature name="entertainmentType" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="durationInMinutes" eType="e:EInt"
                           upperBound="1" ordered="true"/>
    </e:EClass>

    <!-- Entertainer class -->
    <e:EClass name="Entertainer" abstract="false">
      <e:EAnnotation source="documentation">A person who provides entertainment.</e:EAnnotation>
      <e:EStructralFeature name="stageName" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="bio" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="pricePer30Minutes" eType="e:EDouble"
                           upperBound="1" ordered="true"/>
      <e:EReference name="fulfilledOrders" eType="#//EntertainmentOrder"
                     upperBound="-1" ordered="true" containment="false"/>
      <e:EReference name="workRestaurantAssociations"
                     eType="#//WorkRestaurantAssociation" upperBound="-1"
                     ordered="true" containment="true"/>
    </e:EClass>

    <!-- WorkRestaurantAssociation association class -->
    <e:EClass name="WorkRestaurantAssociation">
      <e:EAnnotation source="documentation">Links an entertainer to a restaurant with availability.</e:EAnnotation>
      <e:EStructralFeature name="availabilityByDay" eType="#//AvailabilityByDay"
                           upperBound="-1" ordered="true" containment="true"/>
      <e:EReference name="entertainer" eType="#//Entertainer"
                     upperBound="1" ordered="true" containment="false"/>
      <e:EReference name="restaurant" eType="#//Restaurant"
                     upperBound="1" ordered="true" containment="false"/>
    </e:EClass>

    <!-- AvailabilityByDay class -->
    <e:EClass name="AvailabilityByDay">
      <e:EAnnotation source="documentation">Specifies availability of an entertainer
        for a restaurant by day.</e:EAnnotation>
      <e:EStructralFeature name="dayOfWeek" eType="e:EString"
                           upperBound="1" ordered="true"/>
      <e:EReference name="association" eType="#//WorkRestaurantAssociation"
                     upperBound="1" ordered="true" containment="false"/>
    </e:EClass>

    <!-- OpeningHours class -->
    <e:EClass name="OpeningHours">
      <e:EAnnotation source="documentation">Represents opening hours of a restaurant.</e:EAnnotation>
      <e:EReference name="monday" eType="#//TimeRange"
                     upperBound="1" ordered="true" containment="true"/>
      <e:EReference name="tuesday" eType="#//TimeRange"
                     upperBound="1" ordered="true" containment="true"/>
      <e:EReference name="wednesday" eType="#//TimeRange"
                     upperBound="1" ordered="true" containment="true"/>
      <e:EReference name="thursday" eType="#//TimeRange"
                     upperBound="1" ordered="true" containment="true"/>
      <e:EReference name="friday" eType="#//TimeRange"
                     upperBound="1" ordered="true" containment="true"/>
      <e:EReference name="saturday" eType="#//TimeRange"
                     upperBound="1" ordered="true" containment="true"/>
      <e:EReference name="sunday" eType="#//TimeRange"
                     upperBound="1" ordered="true" containment="true"/>
    </e:EClass>

    <!-- TimeRange class -->
    <e:EClass name="TimeRange">
      <e:EAnnotation source="documentation">Represents a time range
        (start and end).</e:EAnnotation>
      <e:EStructralFeature name="startTime" eType="#//LocalTime"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="endTime" eType="#//LocalTime"
                           upperBound="1" ordered="true"/>
    </e:EClass>

    <!-- Custom datatype for LocalTime -->
    <e:EClass name="LocalTime">
      <e:EAnnotation source="documentation">Custom datatype representing a time
        without date (java.time.LocalTime).</e:EAnnotation>
      <e:EStructralFeature name="hour" eType="e:EInt"
                           upperBound="1" ordered="true"/>
      <e:EStructralFeature name="minute" eType="e:EInt"
                           upperBound="1" ordered="true"/>
    </e:EClass>

  </metaModel>
</model>
