<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="_DlQf0H4AEfGSOav8d3CALw" name="AircraftManagement" nsURI="http://www.example.org/AircraftManagement" nsPrefix="am">
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQf0X4AEfGSOav8d3CALw" name="Aircraft">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf0n4AEfGSOav8d3CALw" name="name" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf1H4AEfGSOav8d3CALw" name="type" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf1n4AEfGSOav8d3CALw" name="yearOfManufacture" lowerBound="1" eType="_DlQgMX4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf2H4AEfGSOav8d3CALw" name="dateOfNextInspection" eType="_DlQgMn4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf2n4AEfGSOav8d3CALw" name="flights" upperBound="-1" eType="_DlQf4H4AEfGSOav8d3CALw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf3H4AEfGSOav8d3CALw" name="tickets" upperBound="-1" eType="_DlQf-H4AEfGSOav8d3CALw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf3n4AEfGSOav8d3CALw" name="airline" eType="_DlQgEn4AEfGSOav8d3CALw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQf4H4AEfGSOav8d3CALw" name="Flight">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf4X4AEfGSOav8d3CALw" name="flightNumber" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf434AEfGSOav8d3CALw" name="date" lowerBound="1" eType="_DlQgMn4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf5X4AEfGSOav8d3CALw" name="passengers" upperBound="-1" eType="_DlQf734AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf534AEfGSOav8d3CALw" name="tickets" upperBound="-1" eType="_DlQf-H4AEfGSOav8d3CALw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf6X4AEfGSOav8d3CALw" name="aircraft" lowerBound="1" eType="_DlQf0X4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf634AEfGSOav8d3CALw" name="departureAirport" lowerBound="1" eType="_DlQgG34AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf7X4AEfGSOav8d3CALw" name="destinationAirport" lowerBound="1" eType="_DlQgG34AEfGSOav8d3CALw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQf734AEfGSOav8d3CALw" name="Passenger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf8H4AEfGSOav8d3CALw" name="name" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf8n4AEfGSOav8d3CALw" name="passportNumber" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf9H4AEfGSOav8d3CALw" name="flights" upperBound="-1" eType="_DlQf4H4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf9n4AEfGSOav8d3CALw" name="tickets" upperBound="-1" eType="_DlQf-H4AEfGSOav8d3CALw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQf-H4AEfGSOav8d3CALw" name="Ticket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf-X4AEfGSOav8d3CALw" name="ticketNumber" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf-34AEfGSOav8d3CALw" name="price" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQf_X4AEfGSOav8d3CALw" name="upgradeDesired">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQf_34AEfGSOav8d3CALw" name="passenger" lowerBound="1" eType="_DlQf734AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQgAX4AEfGSOav8d3CALw" name="flight" lowerBound="1" eType="_DlQf4H4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQgA34AEfGSOav8d3CALw" name="seatCategory" eType="_DlQgC34AEfGSOav8d3CALw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQgBX4AEfGSOav8d3CALw" name="PassengerAircraft" eSuperTypes="_DlQf0X4AEfGSOav8d3CALw">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgBn4AEfGSOav8d3CALw" name="numberOfSeats" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQgCH4AEfGSOav8d3CALw" name="seatCategories" upperBound="-1" eType="_DlQgC34AEfGSOav8d3CALw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQgC34AEfGSOav8d3CALw" name="SeatCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgDH4AEfGSOav8d3CALw" name="designation" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgDn4AEfGSOav8d3CALw" name="hasEntertainment">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgEH4AEfGSOav8d3CALw" name="numberOfSeats" lowerBound="1" eType="_DlQgMX4AEfGSOav8d3CALw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQgEn4AEfGSOav8d3CALw" name="Airline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgE34AEfGSOav8d3CALw" name="name" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQgFX4AEfGSOav8d3CALw" name="aircrafts" upperBound="-1" eType="_DlQf0X4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQgF34AEfGSOav8d3CALw" name="flightAttendants" upperBound="-1" eType="_DlQgIn4AEfGSOav8d3CALw" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" xmi:id="_DlQgGX4AEfGSOav8d3CALw" name="pilots" upperBound="-1" eType="_DlQgKX4AEfGSOav8d3CALw" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQgG34AEfGSOav8d3CALw" name="Airport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgHH4AEfGSOav8d3CALw" name="name" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgHn4AEfGSOav8d3CALw" name="address" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgIH4AEfGSOav8d3CALw" name="numberOfRunways" lowerBound="1" eType="_DlQgMX4AEfGSOav8d3CALw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQgIn4AEfGSOav8d3CALw" name="FlightAttendant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgI34AEfGSOav8d3CALw" name="name" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgJX4AEfGSOav8d3CALw" name="dateOfEmployment" lowerBound="1" eType="_DlQgMn4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgJ34AEfGSOav8d3CALw" name="isChiefSteward">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" xmi:id="_DlQgKX4AEfGSOav8d3CALw" name="Pilot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgKn4AEfGSOav8d3CALw" name="name" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgLH4AEfGSOav8d3CALw" name="dateOfEmployment" lowerBound="1" eType="_DlQgMn4AEfGSOav8d3CALw"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" xmi:id="_DlQgLn4AEfGSOav8d3CALw" name="license" lowerBound="1" eType="_DlQgMH4AEfGSOav8d3CALw"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" xmi:id="_DlQgMH4AEfGSOav8d3CALw" name="String" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" xmi:id="_DlQgMX4AEfGSOav8d3CALw" name="Integer" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EDataType" xmi:id="_DlQgMn4AEfGSOav8d3CALw" name="Date" instanceClassName="java.util.Date"/>
</ecore:EPackage>
