<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="kinepolis" nsUri="http://www.kinepolis.com/model" xmi:id="kinepolis_package">

    <!-- Custom datatype for time without dates -->
    <eDataType name="LocalTime" instanceMethod="java.time.LocalTime" xmi:id="localTime_type"/>

    <!-- Root container class -->
    <eClass name="KinepolisSystem" xmi:id="kinepolisSystem_class">
      <eStructuralFeatures>
        <eReference xmi:id="ks_cinemas" name="cinemas" eType="cinema_class"/>
        <eReference xmi:id="ks_movies" name="movies" eType="movie_class"/>
      </eStructuralFeatures>
      <eOperations>
        <eOperation name="publishWeeklyProgram" xmi:id="ks_op_publish"/>
      </eOperations>
    </eClass>

    <eClass name="Cinema" xmi:id="cinema_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="cin_name" name="name" eType="ecore://xmlns/EString"/>
        <eAttribute xmi:id="cin_town" name="town" eType="ecore://xmlns/EString"/>
        <eReference xmi:id="cin_theatres" name="theatres" eType="theatre_class"/>
        <eReference xmi:id="cin_copies" name="movieCopies" eType="movieCopy_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Theatre" xmi:id="theatre_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="th_name" name="name" eType="ecore://xmlns/EString"/>
        <eAttribute xmi:id="th_cap" name="capacity" eType="ecore://xmlns/EInt"/>
        <eReference xmi:id="th_seats" name="seats" eType="seat_class"/>
        <eReference xmi:id="th_cinema" name="cinema" eType="cinema_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Seat" xmi:id="seat_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="sea_num" name="seatNumber" eType="ecore://xmlns/EString"/>
        <eReference xmi:id="sea_theatre" name="theatre" eType="theatre_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Movie" xmi:id="movie_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="mov_title" name="title" eType="ecore://xmlns/EString"/>
        <eAttribute xmi:id="mov_dur" name="durationMinutes" eType="ecore://xmlns/EInt"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="MovieCopy" xmi:id="movieCopy_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="mc_id" name="copyId" eType="ecore://xmlns/EString"/>
        <eReference xmi:id="mc_movie" name="movie" eType="movie_class"/>
        <eReference xmi:id="mc_cinema" name="currentCinema" eType="cinema_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Show" xmi:id="show_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="sh_start" name="startTime" eType="ecore://xmlns/EDate"/>
        <eAttribute xmi:id="sh_pub" name="isPublished" eType="ecore://xmlns/EBoolean"/>
        <eReference xmi:id="sh_theatre" name="theatre" eType="theatre_class"/>
        <eReference xmi:id="sh_copy" name="movieCopy" eType="movieCopy_class"/>
      </eStructuralFeatures>
      <eOperations>
        <eOperation name="calculateAvailableSeats" xmi:id="sh_op_seats"/>
        <eOperation name="cancelShow" xmi:id="sh_op_cancel"/>
      </eOperations>
    </eClass>

    <eClass name="Reservation" xmi:id="reservation_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="res_time" name="reservationTime" eType="ecore://xmlns/EDate"/>
        <eAttribute xmi:id="res_card" name="creditCardNumber" eType="ecore://xmlns/EString"/>
        <eAttribute xmi:id="res_stat" name="status" eType="ecore://xmlns/EString"/>
        <eReference xmi:id="res_show" name="show" eType="show_class"/>
        <eReference xmi:id="res_seat" name="seat" eType="seat_class"/>
      </eStructuralFeatures>
      <eOperations>
        <eOperation name="cancelReservation" xmi:id="res_op_cancel"/>
      </eOperations>
    </eClass>

    <eClass name="Ticket" xmi:id="ticket_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="tic_id" name="ticketId" eType="ecore://xmlns/EString"/>
        <eAttribute xmi:id="tic_time" name="issueTime" eType="ecore://xmlns/EDate"/>
        <eReference xmi:id="tic_show" name="show" eType="show_class"/>
        <eReference xmi:id="tic_seat" name="seat" eType="seat_class"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="AlternativeOffer" xmi:id="offer_class">
      <eStructuralFeatures>
        <eAttribute xmi:id="off_exp" name="offerExpiryDate" eType="ecore://xmlns/EDate"/>
        <eAttribute xmi:id="off_stat" name="status" eType="ecore://xmlns/EString"/>
        <eReference xmi:id="off_res" name="originalReservation" eType="reservation_class"/>
        <eReference xmi:id="off_show" name="targetShow" eType="show_class"/>
      </eStructuralFeatures>
      <eOperations>
        <eOperation name="acceptOffer" xmi:id="off_op_acc"/>
        <eOperation name="declineOffer" xmi:id="off_op_dec"/>
      </eOperations>
    </eClass>

  </ePackage>
</xmi:XMI>
