<uml:UML xmi:version="2.1" 
         xmlns:xmi="http://www.omg.org/spec/XMI/20130706"
         xmlns:uml="http://www.eclipse.org/uml2/3.0.0/UML"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <!-- Define the top-level package -->
  <packagedElement xmi:type="uml:Package" name="GasStationManagement">
    <eAnnotations>
      <details key="packageUris" value="gasstationmanagement"/>
    </eAnnotations>

    <!-- Embedded Class for Root Container -->
    <ownedElement xmi:type="uml:Class" name="GasStationSystem">
      <eAnnotations>
        <details key="xmi.id" value="_1"/>
      </eAnnotations>
      <ownedAttribute name="gasStations">
        <type xsi:type="uml:SimpleType">ocl:any</type>
        <lowerValue xmi:idref="#_2" xmi:type="uml:LiteralInteger" value="0"/>
        <upperValue xmi:idref="#_3" xmi:type="uml:LiteralUnlimitedNatural" value="-1"/>
      </ownedAttribute>
    </ownedElement>

    <!-- Define sub-packages and classes -->
    
    <!-- Sub-package for Core Models -->
    <packagedElement xmi:type="uml:Package" name="Model">
      <eAnnotations>
        <details key="packageUris" value="gasstationmanagement.model"/>
      </eAnnotations>

      <ownedElement xmi:type="uml:Class" name="GasStation">
        <eAnnotations>
          <details key="xmi.id" value="_4"/>
        </eAnnotations>
        
        <ownedAttribute name="id">
          <type xsi:type="uml:SimpleType">ocl:string</type>
          <upperValue xmi:idref="#_5" xmi:type="uml:LiteralUnlimitedNatural" value="-1"/>
        </ownedAttribute>

        <ownedAttribute name="address">
          <type xsi:type="uml:SimpleType">ocl:string</type>
          <upperValue xmi:idref="#_6" xmi:type="uml:LiteralUnlimitedNatural" value="-1"/>
        </ownedAttribute>

        <ownedAttribute name="fuelPumps">
          <type xsi:type="uml:SimpleType">ocl:any</type>
          <lowerValue xmi:idref="#_7" xmi:type="uml:LiteralInteger" value="0"/>
          <upperValue xmi:idref="#_8" xmi:type="uml:LiteralUnlimitedNatural" value="12"/>
        </ownedAttribute>

      </ownedElement>

    </packagedElement>
    
    <!-- Sub-package for Associations -->
    <packagedElement xmi:type="uml:Package" name="Associations">
      <eAnnotations>
        <details key="packageUris" value="gasstationmanagement.associations"/>
      </eAnnotations>

      <ownedElement xmi:type="uml:Class" name="FuelPump">
        <eAnnotations>
          <details key="xmi.id" value="_9"/>
        </eAnnotations>

        <ownedAttribute name="number" type="ocl:integer"/>

        <ownedAttribute name="isSelfService" type="ocl:boolean"/>

      </ownedElement>

      <!-- Additional Association Classes Here -->

    </packagedElement>
    
  </packagedElement>
</uml:UML>
