<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ePackage name="helpinghands" nsUri="http://www.helpinghands.org/model" xmi:id="package_root">

    <!-- Root Container -->
    <eClass name="H2SStore" xmi:id="class_H2SStore">
      <eStructuralFeatures>
        <eReference name="cities" eType="class_City" xmi:id="ref_H2SStore_cities"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="City" xmi:id="class_City">
      <eStructuralFeatures>
        <eAttribute name="cityName" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_City_name"/>
        <eReference name="residents" eType="class_Resident" xmi:id="ref_City_residents"/>
        <eReference name="clients" eType="class_Client" xmi:id="ref_City_clients"/>
        <eReference name="employees" eType="class_Employee" xmi:id="ref_City_employees"/>
        <eReference name="vehicles" eType="class_Vehicle" xmi:id="ref_City_vehicles"/>
        <eReference name="volunteerDrivers" eType="class_VolunteerDriver" xmi:id="ref_City_drivers"/>
        <eReference name="routes" eType="class_Route" xmi:id="ref_City_routes"/>
        <eReference name="categories" eType="class_Category" xmi:id="ref_City_categories"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Resident" xmi:id="class_Resident">
      <eStructuralFeatures>
        <eAttribute name="name" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Res_name"/>
        <eAttribute name="streetAddress" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Res_addr"/>
        <eAttribute name="phoneNumber" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Res_phone"/>
        <eAttribute name="emailAddress" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Res_email"/>
        <eReference name="pickupRequests" eType="class_PickupRequest" xmi:id="ref_Res_requests"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="PickupRequest" xmi:id="class_PickupRequest">
      <eStructuralFeatures>
        <eAttribute name="requestedDate" eType="http://www.eclipse.org/emf/2002/Ecore#//EDate" xmi:id="attr_PR_date"/>
        <eAttribute name="itemsDescription" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_PR_desc"/>
        <eAttribute name="scheduledTime" eType="type_LocalTime" xmi:id="attr_PR_time"/>
        <eReference name="resident" eType="class_Resident" xmi:id="ref_PR_res"/>
        <eReference name="items" eType="class_Item" xmi:id="ref_PR_items"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Item" abstract="true" xmi:id="class_Item">
      <eStructuralFeatures>
        <eAttribute name="description" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Item_desc"/>
        <eAttribute name="weight" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" xmi:id="attr_Item_weight"/>
        <eAttribute name="dimensions" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Item_dim"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="SecondHandArticle" xmi:id="class_SecondHandArticle">
      <eExtends xmi:id="ext_SHA_Item" eClass="class_Item"/>
      <eStructuralFeatures>
        <eAttribute name="rfidTag" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_SHA_rfid"/>
        <eReference name="category" eType="class_Category" xmi:id="ref_SHA_cat"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="NonPerishableFood" xmi:id="class_NonPerishableFood">
      <eExtends xmi:id="ext_NPF_Item" eClass="class_Item"/>
    </eClass>

    <eClass name="Category" xmi:id="class_Category">
      <eStructuralFeatures>
        <eAttribute name="categoryName" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Cat_name"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Vehicle" xmi:id="class_Vehicle">
      <eStructuralFeatures>
        <eAttribute name="storageCapacity" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" xmi:id="attr_Veh_cap"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="VolunteerDriver" xmi:id="class_VolunteerDriver">
      <eStructuralFeatures>
        <eAttribute name="name" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Driver_name"/>
        <eReference name="availabilities" eType="class_DriverAvailability" xmi:id="ref_Driver_avail"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="DriverAvailability" xmi:id="class_DriverAvailability">
      <eStructuralFeatures>
        <eAttribute name="availableDate" eType="http://www.eclipse.org/emf/2002/Ecore#//EDate" xmi:id="attr_DA_date"/>
        <eReference name="driver" eType="class_VolunteerDriver" xmi:id="ref_DA_driver"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Route" xmi:id="class_Route">
      <eStructuralFeatures>
        <eAttribute name="routeDate" eType="http://www.eclipse.org/emf/2002/Ecore#//EDate" xmi:id="attr_Route_date"/>
        <eReference name="vehicle" eType="class_Vehicle" xmi:id="ref_Route_veh"/>
        <eReference name="driver" eType="class_VolunteerDriver" xmi:id="ref_Route_driver"/>
        <eReference name="stops" eType="class_Stop" xmi:id="ref_Route_stops"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Stop" xmi:id="class_Stop">
      <eStructuralFeatures>
        <eAttribute name="scheduledTime" eType="type_LocalTime" xmi:id="attr_Stop_time"/>
        <eAttribute name="address" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Stop_addr"/>
        <eReference name="pickupRequest" eType="class_PickupRequest" xmi:id="ref_Stop_PR"/>
        <eReference name="deliveryTask" eType="class_DeliveryTask" xmi:id="ref_Stop_DT"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Employee" xmi:id="class_Employee">
      <eStructuralFeatures>
        <eAttribute name="name" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Emp_name"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="Client" xmi:id="class_Client">
      <eStructuralFeatures>
        <eAttribute name="name" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Cli_name"/>
        <eAttribute name="streetAddress" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Cli_addr"/>
        <eAttribute name="phoneNumber" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Cli_phone"/>
        <eAttribute name="emailAddress" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_Cli_email"/>
        <eReference name="categoryPreferences" eType="class_CategoryPreference" xmi:id="ref_Cli_pref"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Association Class for Client and Category -->
    <eClass name="CategoryPreference" xmi:id="class_CategoryPreference">
      <eStructuralFeatures>
        <eReference name="client" eType="class_Client" xmi:id="ref_CP_cli"/>
        <eReference name="category" eType="class_Category" xmi:id="ref_CP_cat"/>
      </eStructuralFeatures>
    </eClass>

    <eClass name="DeliveryTask" xmi:id="class_DeliveryTask">
      <eStructuralFeatures>
        <eReference name="article" eType="class_SecondHandArticle" xmi:id="ref_DT_art"/>
        <eReference name="recipientClient" eType="class_Client" xmi:id="ref_DT_cli"/>
        <eAttribute name="deliveryDate" eType="http://www.eclipse.org/emf/2002/Ecore#//EDate" xmi:id="attr_DT_date"/>
      </eStructuralFeatures>
    </eClass>

    <eDataType name="LocalTime" xmi:id="type_LocalTime">
      <eStructuralFeatures>
        <eAttribute name="javaType" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" xmi:id="attr_LT_java" value="java.time.LocalTime"/>
      </eStructuralFeatures>
    </eDataType>

  </ePackage>
</xmi:XMI>
