<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="game"
    nsURI="http://www.example.com/game"
    nsPrefix="game">

  <eClassifiers xsi:type="ecore:EClass" name="GameArea">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="characters"
        lowerBound="1" upperBound="2"
        eType="#//GameCharacter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements"
        lowerBound="1" upperBound="-1"
        eType="#//GameElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="finalBoss"
        lowerBound="1" upperBound="1"
        eType="#//Enemy"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="GameCharacter"/>

  <eClassifiers xsi:type="ecore:EClass" name="GameElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="#//GameElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isConnectedWith"
        upperBound="-1"
        eType="#//Shape"
        eOpposite="#//Shape/isConnectedWith"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//GameElement"/>

  <eClassifiers xsi:type="ecore:EClass" name="Enemy" eSuperTypes="#//GameElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfLives" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eOperations name="toKill"/>
  </eClassifiers>

</ecore:EPackage>
