<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="airline"
    nsURI="http://www.example.org/airline"
    nsPrefix="airline">

  <eClassifiers xsi:type="ecore:EClass" name="Airline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1"
        eType="#//Employee" eOpposite="#//Employee/airline"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplanes" upperBound="-1"
        eType="#//Airplane" containment="false" eOpposite="#//Airplane/airline"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airline" lowerBound="0"
        upperBound="1" eType="#//Airline" eOpposite="#//Airline/employees"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Airport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runwayCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedAirplanes" upperBound="-1"
        eType="#//Airplane" eOpposite="#//Airplane/baseAirport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFlights" upperBound="-1"
        eType="#//Flight" eOpposite="#//Flight/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationFlights" upperBound="-1"
        eType="#//Flight" eOpposite="#//Flight/destination"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="FlightAttendant" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purser" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecutions" upperBound="-1"
        eType="#//FlightExecution" eOpposite="#//FlightExecution/flightAttendants"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Airplane">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constructionYear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextInspection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airline" lowerBound="0"
        upperBound="1" eType="#//Airline" eOpposite="#//Airline/airplanes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="baseAirport" lowerBound="0"
        upperBound="1" eType="#//Airport" eOpposite="#//Airport/basedAirplanes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecutions" upperBound="-1"
        eType="#//FlightExecution" eOpposite="#//FlightExecution/airplane"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Flight">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flightNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="0"
        upperBound="1" eType="#//Airport" eOpposite="#//Airport/sourceFlights"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destination" lowerBound="0"
        upperBound="1" eType="#//Airport" eOpposite="#//Airport/destinationFlights"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecutions" upperBound="-1"
        eType="#//FlightExecution" eOpposite="#//FlightExecution/flight"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Pilot" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="captainExecutions" upperBound="-1"
        eType="#//FlightExecution" eOpposite="#//FlightExecution/captain"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copilotExecutions" upperBound="-1"
        eType="#//FlightExecution" eOpposite="#//FlightExecution/copilots"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="PassengerPlane" eSuperTypes="#//Airplane">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seatCategories" upperBound="-1"
        eType="#//SeatCategory" containment="true" eOpposite="#//SeatCategory/passengerPlane"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="FlightExecution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplane" lowerBound="0"
        upperBound="1" eType="#//Airplane" eOpposite="#//Airplane/flightExecutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flight" lowerBound="0"
        upperBound="1" eType="#//Flight" eOpposite="#//Flight/flightExecutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightAttendants" upperBound="-1"
        eType="#//FlightAttendant" eOpposite="#//FlightAttendant/flightExecutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="captain" lowerBound="0"
        upperBound="1" eType="#//Pilot" eOpposite="#//Pilot/captainExecutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="copilots" upperBound="2"
        eType="#//Pilot" eOpposite="#//Pilot/copilotExecutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengers" upperBound="-1"
        eType="#//Passenger" eOpposite="#//Passenger/flightExecutions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets" upperBound="-1"
        eType="#//Ticket" eOpposite="#//Ticket/flightExecution"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="SeatCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entertainment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengerPlane" lowerBound="0"
        upperBound="1" eType="#//PassengerPlane" eOpposite="#//PassengerPlane/seatCategories"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets" upperBound="-1"
        eType="#//Ticket" eOpposite="#//Ticket/seatCategory"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Passenger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passportNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecutions" upperBound="-1"
        eType="#//FlightExecution" eOpposite="#//FlightExecution/passengers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets" upperBound="-1"
        eType="#//Ticket" eOpposite="#//Ticket/passenger"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Ticket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ticketId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upgrade" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seatCategory" lowerBound="0"
        upperBound="1" eType="#//SeatCategory" eOpposite="#//SeatCategory/tickets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passenger" lowerBound="0"
        upperBound="1" eType="#//Passenger" eOpposite="#//Passenger/tickets"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecution" lowerBound="0"
        upperBound="1" eType="#//FlightExecution" eOpposite="#//FlightExecution/tickets"/>
  </eClassifiers>

</ecore:EPackage>
