<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="airline"
    nsURI="http://www.example.org/airline"
    nsPrefix="airline">

  <!-- Root container -->
  <eClassifiers xsi:type="ecore:EClass" name="AirlineSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="airlines"
        eType="#//Airline" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airports"
        eType="#//Airport" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flights"
        eType="#//Flight" upperBound="-1" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengers"
        eType="#//Passenger" upperBound="-1" containment="true"/>
    <!-- Airplanes are contained at root level -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplanes"
        eType="#//Airplane" upperBound="-1" containment="true"/>
  </eClassifiers>

  <!-- Airline class -->
  <eClassifiers xsi:type="ecore:EClass" name="Airline">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Airline 0..1 to 0..* Employee -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees"
        eType="#//Employee" upperBound="-1" containment="true"
        eOpposite="#//Employee/airline"/>
    <!-- Airline 0..1 aggregation to 0..* Airplane (non-containment, contained at root) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplanes"
        eType="#//Airplane" upperBound="-1"
        eOpposite="#//Airplane/airline"/>
  </eClassifiers>

  <!-- Employee abstract class -->
  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDate"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="airline"
        eType="#//Airline" eOpposite="#//Airline/employees"/>
  </eClassifiers>

  <!-- FlightAttendant extends Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="FlightAttendant" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="purser"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <!-- FlightExecution 0..* to 0..* FlightAttendant -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecutions"
        eType="#//FlightExecution" upperBound="-1"
        eOpposite="#//FlightExecution/flightAttendants"/>
  </eClassifiers>

  <!-- Pilot extends Employee -->
  <eClassifiers xsi:type="ecore:EClass" name="Pilot" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="license"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- FlightExecution 0..* to 0..1 Pilot as Captain -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="captainExecutions"
        eType="#//FlightExecution" upperBound="-1"
        eOpposite="#//FlightExecution/captain"/>
    <!-- FlightExecution 0..* to 0..2 Pilot as Co-pilot -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="coPilotExecutions"
        eType="#//FlightExecution" upperBound="-1"
        eOpposite="#//FlightExecution/coPilots"/>
  </eClassifiers>

  <!-- Airport class -->
  <eClassifiers xsi:type="ecore:EClass" name="Airport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runwayCount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Airport 0..1 to 0..* Flight as Source -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFlights"
        eType="#//Flight" upperBound="-1"
        eOpposite="#//Flight/sourceAirport"/>
    <!-- Airport 0..1 to 0..* Flight as Destination -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationFlights"
        eType="#//Flight" upperBound="-1"
        eOpposite="#//Flight/destinationAirport"/>
    <!-- Airplane 0..* to 0..1 Airport -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplanes"
        eType="#//Airplane" upperBound="-1"
        eOpposite="#//Airplane/homeAirport"/>
  </eClassifiers>

  <!-- Airplane class -->
  <eClassifiers xsi:type="ecore:EClass" name="Airplane">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constructionYear"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextInspection"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Non-containment reference back to Airline -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airline"
        eType="#//Airline" eOpposite="#//Airline/airplanes"/>
    <!-- Airplane 0..* to 0..1 Airport -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="homeAirport"
        eType="#//Airport" eOpposite="#//Airport/airplanes"/>
    <!-- Airplane 0..1 to 0..* FlightExecution (containment) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecutions"
        eType="#//FlightExecution" upperBound="-1" containment="true"
        eOpposite="#//FlightExecution/airplane"/>
  </eClassifiers>

  <!-- PassengerPlane extends Airplane -->
  <eClassifiers xsi:type="ecore:EClass" name="PassengerPlane" eSuperTypes="#//Airplane">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seats"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- PassengerPlane 0..1 composition to 0..* SeatCategory -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="seatCategories"
        eType="#//SeatCategory" upperBound="-1" containment="true"
        eOpposite="#//SeatCategory/passengerPlane"/>
  </eClassifiers>

  <!-- SeatCategory class -->
  <eClassifiers xsi:type="ecore:EClass" name="SeatCategory">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entertainment"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatCount"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengerPlane"
        eType="#//PassengerPlane" eOpposite="#//PassengerPlane/seatCategories"/>
    <!-- SeatCategory 0..1 to 0..* Ticket -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets"
        eType="#//Ticket" upperBound="-1"
        eOpposite="#//Ticket/seatCategory"/>
  </eClassifiers>

  <!-- Flight class -->
  <eClassifiers xsi:type="ecore:EClass" name="Flight">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flightNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Airport 0..1 to 0..* Flight as Source -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceAirport"
        eType="#//Airport" eOpposite="#//Airport/sourceFlights"/>
    <!-- Airport 0..1 to 0..* Flight as Destination -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationAirport"
        eType="#//Airport" eOpposite="#//Airport/destinationFlights"/>
    <!-- Flight 0..1 to 0..* FlightExecution -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecutions"
        eType="#//FlightExecution" upperBound="-1"
        eOpposite="#//FlightExecution/flight"/>
  </eClassifiers>

  <!-- FlightExecution class -->
  <eClassifiers xsi:type="ecore:EClass" name="FlightExecution">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Airplane 0..1 to 0..* FlightExecution -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="airplane"
        eType="#//Airplane" eOpposite="#//Airplane/flightExecutions"/>
    <!-- Flight 0..1 to 0..* FlightExecution -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="flight"
        eType="#//Flight" eOpposite="#//Flight/flightExecutions"/>
    <!-- FlightExecution 0..* to 0..* FlightAttendant -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightAttendants"
        eType="#//FlightAttendant" upperBound="-1"
        eOpposite="#//FlightAttendant/flightExecutions"/>
    <!-- FlightExecution 0..* to 0..1 Pilot as Captain -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="captain"
        eType="#//Pilot" eOpposite="#//Pilot/captainExecutions"/>
    <!-- FlightExecution 0..* to 0..2 Pilot as Co-pilot -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="coPilots"
        eType="#//Pilot" upperBound="2"
        eOpposite="#//Pilot/coPilotExecutions"/>
    <!-- Association class: FlightExecution contains Ticket -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets"
        eType="#//Ticket" upperBound="-1" containment="true"
        eOpposite="#//Ticket/flightExecution"/>
  </eClassifiers>

  <!-- Passenger class -->
  <eClassifiers xsi:type="ecore:EClass" name="Passenger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passportNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Passenger non-containment reference to Ticket -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="tickets"
        eType="#//Ticket" upperBound="-1"
        eOpposite="#//Ticket/passenger"/>
  </eClassifiers>

  <!-- Ticket association class for FlightExecution and Passenger -->
  <eClassifiers xsi:type="ecore:EClass" name="Ticket">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ticketId"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="price"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upgrade"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <!-- Contained by FlightExecution -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="flightExecution"
        eType="#//FlightExecution" eOpposite="#//FlightExecution/tickets"/>
    <!-- Non-containment reference to Passenger -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="passenger"
        eType="#//Passenger" eOpposite="#//Passenger/tickets"/>
    <!-- SeatCategory 0..1 to 0..* Ticket -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="seatCategory"
        eType="#//SeatCategory" eOpposite="#//SeatCategory/tickets"/>
  </eClassifiers>

</ecore:EPackage>
