<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="banking"
    nsURI="http://www.example.org/banking"
    nsPrefix="banking">

  <!-- Bank acts as the root container -->
  <eClassifiers xsi:type="ecore:EClass" name="Bank">
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches"
        eType="#//Branch"
        upperBound="-1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers"
        eType="#//Customer"
        upperBound="-1"
        eOpposite="#//Customer/banks"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Branch">
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accounts"
        eType="#//Account"
        lowerBound="1"
        upperBound="5"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="banks"
        eType="#//Bank"
        upperBound="-1"
        eOpposite="#//Bank/customers"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Account" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accountNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="balance"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="SavingsAccount"
      eSuperTypes="#//Account"/>

  <eClassifiers xsi:type="ecore:EClass" name="CheckingAccount"
      eSuperTypes="#//Account">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="overdraftLimit"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

</ecore:EPackage>
