<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.5" xmlns:xmi="http://www.omg.org/spec/XMI/20131029" xmlns:uml="http://www.eclipse.org/emf/2002/UML">
  <xmi:Diagrams>
    <!-- Root Container -->
    <umldiagram:ModelElementContainer xmi:id="_root_Container_" name="UniversitySystemDiagrams" visualStyle="_UML"/>
    
    <!-- University Package -->
    <uml:Package xmi:id="_University_Package_">
      <name>University</name>

      <!-- Class University -->
      <packagedElement:Class xmi:type="uml:Class" xmi:id="_University_" name="University">
        <ownedAttribute>
          <umlattribute:Property xmi:id="_deanReference_" type="_Employee_" aggregated=false association="_University_has_Faculty_Association_"/>
          <umlattribute:Property xmi:id="_totalEmployeesCount_" type="_Integer_" name="total number of employees"/>
        </ownedAttribute>

        <packagedElement:Association xmi:type="uml:Realization" xmi:id="_University_consists_Of_Faculties_association">
          <client>_University_</client>
          <supplier>_Faculty_</supplier>
        </packagedElement:Association>

      </packagedElement:Class>

    </uml:Package>
    
    <!-- Faculty Package -->
    <uml:Package xmi:id="_Faculty_Package_">
      <name>Faculty</name>

      <!-- Class Faculty with a reference to University -->
      <packagedElement:Class xmi:type="uml:Class" xmi:id="_Faculty_" name="Faculty">
        <ownedAttribute>
          <umlattribute:Property xmi:id="_name_Reference_" type="_String_"/>
        </ownedAttribute>

        <packagedElement:Association xmi:type="uml:Realization" xmi:id="_Faculty_consists_Of_Institutes_association">
          <client>_Faculty_</client>
          <supplier>_Institute_</supplier>
        </packagedElement:Association>
      </packagedElement:Class>

    </uml:Package>

    <!-- Institute Package -->
    <uml:Package xmi:id="_Institute_Package_">
      <name>Institutes</name>

      <!-- Class Institute -->
      <packagedElement:Class xmi:type="uml:Class" xmi:id="_Institute_" name="Institute">
        <ownedAttribute>
          <umlattribute:Property xmi:id="_name_Property_" type="_String_"/>
          <umlattribute:Property xmi:id="_address_WithProperty_" type="_String_"/>
        </ownedAttribute>
      </packagedElement:Class>

    </uml:Package>

    <!-- Employee Package -->
    <uml:Package xmi:id="_Employee_Package_">
      <name>Employees</name>

      <!-- Class Employee and its subclasses ResearchAssistant and Lecturer -->
      <packagedElement:Class xmi:type="uml:Class" xmi:id="_Employee_" name="Employee">
        <ownedAttribute>
          <umlattribute:Property xmi:id="_ssn_WithProperty_" type="_String_"/>
          <umlattribute:Property xmi:id="_name_Property2_" type="_String_"/>
          <umlattribute:Property xmi:id="_email_Address_Property" type="_String_"/>
        </ownedAttribute>

      </packagedElement:Class>

      <!-- Subclass for ResearchAssistant -->
      <packagedElement:Class xmi:type="uml:Class" xmi:id="_ResearchAssistant_" name="ResearchAssistant" isAbstract="false">
        <generalization>
          <packagedElement:Generalization xmi:id="_extends_Employee_realtion">
            <supertype>_Employee_</supertype>

            <subtype>_ResearchAssistant_</subtype>
          </packagedElement:Generalization>
        </generalization>

        <ownedAttribute>
          <umlattribute:Property xmi:id="_fieldOfResearch_" type="_String_"/>
        </ownedAttribute>
        
      </packagedElement:Class>

      <!-- Subclass for Lecturer -->
      <packagedElement:Class xmi:type="uml:Class" xmi:id="_Lecturer_" name="Lecturer" isAbstract="false">
        <generalization>
          <packagedElement:Generalization xmi:id="_extends_ResearchAssistant_realation">
            <supertype>_ResearchAssistant_</supertype>

            <subtype>_Lecturer_</subtype>
          </packagedElement:Generalization>
        </generalization>

      </packagedElement:Class>

    </uml:Package>

    <!-- Additional packages for Course, Project, and WorkingHoursInProject can be similarly defined -->

  </xmi:Diagrams>
  
  <!-- Defining DataTypes -->
  <DataType xmi:type="uml:PrimitiveType" name="TDateDuration" xmi:id="_TDateDuration_">
    <ownedRule/>
  </DataType>

</xmi:XMI>
