<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="school"
    nsURI="http://www.example.org/school"
    nsPrefix="school">

  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Teacher" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schools" eType="#//School"
        lowerBound="0" upperBound="3" eOpposite="#//School/teachers"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="principalOf" eType="#//School"
        lowerBound="0" upperBound="1" eOpposite="#//School/principal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacherAssignments" eType="#//TeacherAssignment"
        lowerBound="0" upperBound="-1" containment="true" eOpposite="#//TeacherAssignment/teacher"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classGroup" eType="#//ClassGroup"
        lowerBound="1" upperBound="1" eOpposite="#//ClassGroup/students"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="TeacherAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacher" eType="#//Teacher"
        lowerBound="1" upperBound="1" eOpposite="#//Teacher/teacherAssignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        lowerBound="1" upperBound="1" eOpposite="#//School/teacherAssignments"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teachers" eType="#//Teacher"
        lowerBound="0" upperBound="-1" eOpposite="#//Teacher/schools"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="principal" eType="#//Teacher"
        lowerBound="0" upperBound="1" eOpposite="#//Teacher/principalOf"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms" eType="#//Room"
        lowerBound="1" upperBound="-1" containment="true" eOpposite="#//Room/school"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacherAssignments" eType="#//TeacherAssignment"
        lowerBound="0" upperBound="-1" eOpposite="#//TeacherAssignment/school"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Room" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school" eType="#//School"
        lowerBound="1" upperBound="1" eOpposite="#//School/rooms"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ClassRoom" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classGroup" eType="#//ClassGroup"
        lowerBound="0" upperBound="1" eOpposite="#//ClassGroup/classRoom"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="OtherRoom" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ClassGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students" eType="#//Student"
        lowerBound="10" upperBound="31" eOpposite="#//Student/classGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classRoom" eType="#//ClassRoom"
        lowerBound="1" upperBound="1" eOpposite="#//ClassRoom/classGroup"/>
  </eClassifiers>

</ecore:EPackage>
