<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="schoolMetamodel"
    nsURI="http://www.example.org/schoolMetamodel"
    nsPrefix="schoolMetamodel">

  <!-- Abstract class Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class Teacher, extends Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Teacher" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Teacher "*"-"0..3" School via TeacherAssignment association class -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacherAssignments"
        eType="#//TeacherAssignment"
        containment="true"
        upperBound="-1"/>
    <!-- Teacher "1"-"0..1" School : Principal -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="principalOf"
        eType="#//School"
        upperBound="1"
        eOpposite="#//School/principal"/>
  </eClassifiers>

  <!-- Class Student, extends Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person">
    <!-- Student "10..31"-o"1" ClassGroup -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="classGroup"
        eType="#//ClassGroup"
        upperBound="1"
        eOpposite="#//ClassGroup/students"/>
  </eClassifiers>

  <!-- Association class TeacherAssignment -->
  <eClassifiers xsi:type="ecore:EClass" name="TeacherAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Reference to School -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="school"
        eType="#//School"
        lowerBound="1"
        upperBound="1"
        eOpposite="#//School/teacherAssignments"/>
  </eClassifiers>

  <!-- Class School -->
  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- School "1"*-"*" Room: composition -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms"
        eType="#//Room"
        containment="true"
        upperBound="-1"
        lowerBound="1"/>
    <!-- Opposite of Teacher principalOf -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="principal"
        eType="#//Teacher"
        upperBound="1"
        eOpposite="#//Teacher/principalOf"/>
    <!-- Opposite of TeacherAssignment school -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacherAssignments"
        eType="#//TeacherAssignment"
        upperBound="-1"
        eOpposite="#//TeacherAssignment/school"/>
  </eClassifiers>

  <!-- Abstract class Room -->
  <eClassifiers xsi:type="ecore:EClass" name="Room" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class ClassRoom, extends Room -->
  <eClassifiers xsi:type="ecore:EClass" name="ClassRoom" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>

  <!-- Class OtherRoom, extends Room -->
  <eClassifiers xsi:type="ecore:EClass" name="OtherRoom" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- Class ClassGroup -->
  <eClassifiers xsi:type="ecore:EClass" name="ClassGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- ClassGroup "1"-"1" ClassRoom -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="classRoom"
        eType="#//ClassRoom"
        lowerBound="1"
        upperBound="1"/>
    <!-- Opposite of Student classGroup -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="students"
        eType="#//Student"
        upperBound="31"
        lowerBound="10"
        eOpposite="#//Student/classGroup"/>
  </eClassifiers>

  <!-- Root container class -->
  <eClassifiers xsi:type="ecore:EClass" name="SchoolSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schools"
        eType="#//School"
        containment="true"
        upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teachers"
        eType="#//Teacher"
        containment="true"
        upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="students"
        eType="#//Student"
        containment="true"
        upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classGroups"
        eType="#//ClassGroup"
        containment="true"
        upperBound="-1"/>
  </eClassifiers>

</ecore:EPackage>
