<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="school"
    nsURI="http://www.example.org/school"
    nsPrefix="school">

  <!-- Abstract class Person with FirstName and LastName -->
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FirstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- Class Teacher extends Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Teacher" eSuperTypes="#//Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Teacher to TeacherAssignment: 0..* (Teacher works at 0..3 Schools via TeacherAssignment) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacherAssignments"
        upperBound="-1"
        eType="#//TeacherAssignment"
        containment="false"
        eOpposite="#//TeacherAssignment/teacher"/>
    <!-- Teacher as Principal of 0..1 School -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="principalOf"
        lowerBound="0" upperBound="1"
        eType="#//School"
        eOpposite="#//School/principal"/>
  </eClassifiers>

  <!-- Class Student extends Person -->
  <eClassifiers xsi:type="ecore:EClass" name="Student" eSuperTypes="#//Person">
    <!-- Student belongs to 1 ClassGroup; multiplicity 10..31 on student side -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="classGroup"
        lowerBound="1" upperBound="1"
        eType="#//ClassGroup"
        eOpposite="#//ClassGroup/students"/>
  </eClassifiers>

  <!-- Association class TeacherAssignment between Teacher and School -->
  <eClassifiers xsi:type="ecore:EClass" name="TeacherAssignment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Hours" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacher"
        lowerBound="1" upperBound="1"
        eType="#//Teacher"
        eOpposite="#//Teacher/teacherAssignments"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school"
        lowerBound="1" upperBound="1"
        eType="#//School"
        eOpposite="#//School/teacherAssignments"/>
  </eClassifiers>

  <!-- Class School -->
  <eClassifiers xsi:type="ecore:EClass" name="School">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- School to TeacherAssignment -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="teacherAssignments"
        upperBound="-1"
        eType="#//TeacherAssignment"
        containment="false"
        eOpposite="#//TeacherAssignment/school"/>
    <!-- School has principal Teacher (0..1) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="principal"
        lowerBound="0" upperBound="1"
        eType="#//Teacher"
        eOpposite="#//Teacher/principalOf"/>
    <!-- School contains 1..* Rooms (composition) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="rooms"
        lowerBound="1" upperBound="-1"
        eType="#//Room"
        containment="true"
        eOpposite="#//Room/school"/>
  </eClassifiers>

  <!-- Abstract class Room -->
  <eClassifiers xsi:type="ecore:EClass" name="Room" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="school"
        lowerBound="1" upperBound="1"
        eType="#//School"
        eOpposite="#//School/rooms"/>
  </eClassifiers>

  <!-- Class ClassRoom extends Room -->
  <eClassifiers xsi:type="ecore:EClass" name="ClassRoom" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- ClassRoom is assigned to 0..1 ClassGroup -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="classGroup"
        lowerBound="0" upperBound="1"
        eType="#//ClassGroup"
        eOpposite="#//ClassGroup/classRoom"/>
  </eClassifiers>

  <!-- Class OtherRoom extends Room -->
  <eClassifiers xsi:type="ecore:EClass" name="OtherRoom" eSuperTypes="#//Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>

  <!-- Class ClassGroup -->
  <eClassifiers xsi:type="ecore:EClass" name="ClassGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- ClassGroup has 10..31 Students (aggregation) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="students"
        lowerBound="10" upperBound="31"
        eType="#//Student"
        eOpposite="#//Student/classGroup"/>
    <!-- ClassGroup is assigned to exactly 1 ClassRoom -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="classRoom"
        lowerBound="1" upperBound="1"
        eType="#//ClassRoom"
        eOpposite="#//ClassRoom/classGroup"/>
  </eClassifiers>

</ecore:EPackage>
