<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmlns:xmi="http://www.omg.org/XMI"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
         xmi:version="2.0">

  <ecore:EPackage name="destroyBlock" nsURI="http://destroyblock/model" nsPrefix="destroyBlock" xmi:id="EPackage_1">
    <!-- Root container class -->
    <ecore:EClass name="DestroyBlockModel" xmi:id="EClass_1">
      <ecore:EReference name="users" eType="#//User" upperBound="-1" containment="true"/>
      <ecore:EReference name="games" eType="#//Game" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- User class -->
    <ecore:EClass name="User" xmi:id="EClass_2">
      <ecore:EAttribute name="username" eType="ecore:EString"/>
      <ecore:EReference name="playerProfile" eType="#//Player" containment="true"/>
      <ecore:EReference name="adminProfile" eType="#//Admin" containment="true"/>
    </ecore:EClass>

    <!-- Player class -->
    <ecore:EClass name="Player" xmi:id="EClass_3">
      <ecore:EAttribute name="password" eType="ecore:EString"/>
      <ecore:EReference name="gamesPlayed" eType="#//Game" upperBound="-1"/>
    </ecore:EClass>

    <!-- Admin class -->
    <ecore:EClass name="Admin" xmi:id="EClass_4">
      <ecore:EAttribute name="password" eType="ecore:EString"/>
      <ecore:EReference name="gamesCreated" eType="#//Game" upperBound="-1" containment="true"/>
    </ecore:EClass>

    <!-- Game class -->
    <ecore:EClass name="Game" xmi:id="EClass_5">
      <ecore:EAttribute name="name" eType="ecore:EString"/>
      <ecore:EReference name="blocks" eType="#//Block" upperBound="-1" containment="true"/>
      <ecore:EReference name="levels" eType="#//Level" upperBound="-1" containment="true"/>
      <ecore:EAttribute name="minSpeed" eType="ecore:EInt"/>
      <ecore:EAttribute name="speedIncreaseFactor" eType="ecore:EDouble"/>
      <ecore:EAttribute name="maxPaddleLength" eType="ecore:EInt"/>
      <ecore:EAttribute name="minPaddleLength" eType="ecore:EInt"/>
    </ecore:EClass>

    <!-- Block class -->
    <ecore:EClass name="Block" xmi:id="EClass_6">
      <ecore:EAttribute name="color" eType="ecore:EString"/>
      <ecore:EAttribute name="points" eType="ecore:EInt"/>
    </ecore:EClass>

    <!-- Level class -->
    <ecore:EClass name="Level" xmi:id="EClass_7">
      <ecore:EAttribute name="number" eType="ecore:EInt"/>
      <ecore:EReference name="blocksArrangement" eType="#//BlocksArrangement" upperBound="-1" containment="true"/>
      <ecore:EAttribute name="isRandom" eType="ecore:EBoolean"/>
    </ecore:EClass>

    <!-- Blocks Arrangement class -->
    <ecore:EClass name="BlocksArrangement" xmi:id="EClass_8">
      <ecore:EReference name="block" eType="#//Block" containment="true"/>
      <ecore:EAttribute name="gridPosition" eType="ecore:EString"/>
    </ecore:EClass>
  </ecore:EPackage>

</xmi:XMI>
