<xmi:XMI xmlns:xmi="http://schema.omg.org/spec/XMI/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage xmi:id="_package" name="btms" nsiVersion="5.6.0" eClass="EPackage"
                  xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">

    <!-- Root container class -->
    <ecore:EClass xmi:id="_BTMS" name="BTMS" eStructuralFeatures>
      <eFeature xmi:type="ecore:EAttribute" name="name" eType="{ecore}EString"/>
      <eFeature xmi:type="ecore:EReference" name="drivers"
                lower="0" upper="-1" containment="true"
                eType="{btms}Driver"/>
      <eFeature xmi:type="ecore:EReference" name="buses"
                lower="0" upper="-1" containment="true"
                eType="{btms}Bus"/>
      <eFeature xmi:type="ecore:EReference" name="routes"
                lower="0" upper="-1" containment="true"
                eType="{btms}Route"/>
      <eFeature xmi:type="ecore:EReference" name="assignments"
                lower="0" upper="-1" containment="true"
                eType="{btms}Assignment"/>
      <eFeature xmi:type="ecore:EReference" name="shifts"
                lower="0" upper="-1" containment="true"
                eType="{btms}ShiftAssignment"/>
    </ecore:EClass>

    <!-- Driver class -->
    <ecore:EClass xmi:id="_Driver" name="Driver" eStructuralFeatures>
      <eFeature xmi:type="ecore:EAttribute" name="id" eType="{ecore}EInt"/>
      <eFeature xmi:type="ecore:EAttribute" name="name" eType="{ecore}EString"/>
      <eFeature xmi:type="ecore:EAttribute" name="isSick"
                default="false" eType="{ecore}EBoolean"/>
    </ecore:EClass>

    <!-- Bus class -->
    <ecore:EClass xmi:id="_Bus" name="Bus" eStructuralFeatures>
      <eFeature xmi:type="ecore:EAttribute" name="licensePlate"
                upper="10" eType="{ecore}EString"/>
      <eFeature xmi:type="ecore:EAttribute" name="isInRepair"
                default="false" eType="{ecore}EBoolean"/>
    </ecore:EClass>

    <!-- Route class -->
    <ecore:EClass xmi:id="_Route" name="Route" eStructuralFeatures>
      <eFeature xmi:type="ecore:EAttribute" name="number"
                upper="9999" eType="{ecore}EIntegerObject"/>
    </ecore:EClass>

    <!-- Shift enumeration -->
    <ecore:EEnum xmi:id="_Shift" name="Shift">
      <eLiterals>
        <eLiteral name="MORNING" value="0"/>
        <eLiteral name="AFTERNOON" value="1"/>
        <eLiteral name="NIGHT" value="2"/>
      </eLiterals>
    </ecore:EEnum>

    <!-- Assignment class (association between Bus and Route with a date) -->
    <ecore:EClass xmi:id="_Assignment" name="Assignment" eStructuralFeatures>
      <eFeature xmi:type="ecore:EReference" name="bus"
                lower="1" upper="1" eType="{btms}Bus"/>
      <eFeature xmi:type="ecore:EReference" name="route"
                lower="1" upper="1" eType="{btms}Route"/>
      <eFeature xmi:type="ecore:EAttribute" name="date"
                eType="{ecore}EDate"/>
    </ecore:EClass>

    <!-- ShiftAssignment class (association between Driver, Bus, Route, and Shift with a date) -->
    <ecore:EClass xmi:id="_ShiftAssignment" name="ShiftAssignment" eStructuralFeatures>
      <eFeature xmi:type="ecore:EReference" name="driver"
                lower="1" upper="1" eType="{btms}Driver"/>
      <eFeature xmi:type="ecore:EReference" name="bus"
                lower="1" upper="1" eType="{btms}Bus"/>
      <eFeature xmi:type="ecore:EReference" name="route"
                lower="1" upper="1" eType="{btms}Route"/>
      <eFeature xmi:type="ecore:EAttribute" name="shift"
                required="true" eType="{btms}Shift"/>
      <eFeature xmi:type="ecore:EAttribute" name="date"
                eType="{ecore}EDate"/>
    </ecore:EClass>

    <!-- Populate the package with its EClasses, EEnum, etc. -->
    <ecore:eClassifiers>
      <eElements xsi:type="ecore:EClassifier" refEClassifier="{btms}BTMS"/>
      <eElements xsi:type="ecore:EClassifier" refEClassifier="{btms}Driver"/>
      <eElements xsi:type="ecore:EClassifier" refEClassifier="{btms}Bus"/>
      <eElements xsi:type="ecore:EClassifier" refEClassifier="{btms}Route"/>
      <eElements xsi:type="ecore:EClassifier" refEClassifier="{btms}Assignment"/>
      <eElements xsi:type="ecore:EClassifier" refEClassifier="{btms}ShiftAssignment"/>
      <eElements xsi:type="ecore:EClassifier" refEClassifier="{btms}Shift"/>
    </ecore:eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
