<xmi:XMI xmlns:xmi="http://schema.omg.org/spec/XMI/2.0">
    <eClass:EPackage xmi:id="_0" name="sober">
        <!-- Root container class -->
        <eClass:EBusinessObject xmi:id="_1" name="SoberSystem">
            <eClass:EAttribute xmi:type="eClass:EInt" name="id" upperBound="1"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="cars"
                               type="_6" upperBound="-1" containment="true"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="rides"
                               type="_12" upperBound="-1" containment="true"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="accidents"
                               type="_16" upperBound="-1" containment="true"/>
        </eClass:EBusinessObject>

        <!-- Car class -->
        <eClass:EBusinessObject xmi:id="_6" name="Car">
            <eClass:EAttribute xmi:type="eClass:EInt" name="id" upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EString" name="ownerName"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EBoolean" name="isCompanyOwned"
                               upperBound="1"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="rides"
                               type="_12" upperBound="-1" containment="false"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="accidents"
                               type="_16" upperBound="-1" containment="false"/>
        </eClass:EBusinessObject>

        <!-- Customer class -->
        <eClass:EBusinessObject xmi:id="_9" name="Customer">
            <eClass:EAttribute xmi:type="eClass:EInt" name="id" upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EString" name="name"
                               upperBound="1"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="rideShares"
                               type="_13" upperBound="-1" containment="false"/>
        </eClass:EBusinessObject>

        <!-- Ride class (abstract) -->
        <eClass:EBusinessObject xmi:id="_12" name="Ride" derived="true">
            <eClass:EAttribute xmi:type="eClass:EInt" name="id" upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EDateTime" name="pickupTime"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EString" name="pickupLocation"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EDateTime" name="dropoffTime"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EString" name="dropoffLocation"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EDuration" name="duration"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EFloat" name="distance"
                               upperBound="1"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="car"
                               type="_6" upperBound="1" containment="false"/>
        </eClass:EBusinessObject>

        <!-- RideHail class -->
        <eClass:EBusinessObject xmi:id="_11" name="RideHail">
            <eClass:ESuperTypes value="_12"/>
            <eClass:EAttribute xmi:type="eClass:EInt" name="passengerCount"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EFloat" name="fee"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EString" name="requestType"
                               upperBound="1"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="leadCustomer"
                               type="_9" upperBound="1" containment="false"/>
        </eClass:EBusinessObject>

        <!-- RideShare class -->
        <eClass:EBusinessObject xmi:id="_13" name="RideShare">
            <eClass:ESuperTypes value="_12"/>
            <eClass:EAttribute xmi:type="eClass:EFloat" name="negotiatedFee"
                               upperBound="1"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="customers"
                               type="_9" upperBound="-1" containment="false"/>
        </eClass:EBusinessObject>

        <!-- Accident class -->
        <eClass:EBusinessObject xmi:id="_16" name="Accident">
            <eClass:EAttribute xmi:type="eClass:EDate" name="date"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EString" name="location"
                               upperBound="1"/>
            <eClass:EAttribute xmi:type="eClass:EFloat" name="damageAmount"
                               upperBound="1"/>
            <eClass:EReference xmi:type="eClass:EClearFeature" name="car"
                               type="_6" upperBound="1" containment="false"/>
        </eClass:EBusinessObject>
    </eClass:EPackage>
</xmi:XMI>
