<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="rideHailingPackage"
    nsURI="http://www.example.org/rideHailingPackage"
    nsPrefix="rideHailingPackage">

  <!-- Ride class -->
  <eClassifiers xsi:type="ecore:EClass" name="Ride" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RideNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PickupDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DropoffDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PickupLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DropoffLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Fee" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Reference to Car via OperatedBy -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="operatedBy" eType="#//Car"
        lowerBound="1" eOpposite="#//Car/rides"/>
  </eClassifiers>

  <!-- RideHailing class (subclass of Ride) -->
  <eClassifiers xsi:type="ecore:EClass" name="RideHailing" eSuperTypes="#//Ride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Passengers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="WaitTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="RequestType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Reference to Customer as LeadCustomer -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="leadCustomer" eType="#//Customer"
        lowerBound="1" eOpposite="#//Customer/hailingRides"/>
  </eClassifiers>

  <!-- RideSharing class (subclass of Ride) -->
  <eClassifiers xsi:type="ecore:EClass" name="RideSharing" eSuperTypes="#//Ride">
    <!-- Reference to Customer via Book -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="book" eType="#//Customer"
        lowerBound="1" eOpposite="#//Customer/sharingRides"/>
  </eClassifiers>

  <!-- Customer class -->
  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CustNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CustName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Opposite of RideHailing.leadCustomer -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="hailingRides" upperBound="-1"
        eType="#//RideHailing" eOpposite="#//RideHailing/leadCustomer"/>
    <!-- Opposite of RideSharing.book -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharingRides" upperBound="-1"
        eType="#//RideSharing" eOpposite="#//RideSharing/book"/>
    <!-- Opposite of OtherCar.owner -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCars" upperBound="-1"
        eType="#//OtherCar" eOpposite="#//OtherCar/owner"/>
  </eClassifiers>

  <!-- Car class (abstract due to total disjoint) -->
  <eClassifiers xsi:type="ecore:EClass" name="Car" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CarNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CarType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Opposite of Ride.operatedBy -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="rides" upperBound="-1"
        eType="#//Ride" eOpposite="#//Ride/operatedBy"/>
    <!-- Reference to Involved (association class for Car-Accident) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="involved" upperBound="-1"
        eType="#//Involved" eOpposite="#//Involved/car"/>
  </eClassifiers>

  <!-- SoberCar class (subclass of Car) -->
  <eClassifiers xsi:type="ecore:EClass" name="SoberCar" eSuperTypes="#//Car"/>

  <!-- OtherCar class (subclass of Car) -->
  <eClassifiers xsi:type="ecore:EClass" name="OtherCar" eSuperTypes="#//Car">
    <!-- Reference to Customer via Owns -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="#//Customer"
        lowerBound="1" eOpposite="#//Customer/ownedCars"/>
  </eClassifiers>

  <!-- Involved association class -->
  <eClassifiers xsi:type="ecore:EClass" name="Involved">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DamageAmount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <!-- Reference back to Car -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="car" eType="#//Car"
        lowerBound="1" eOpposite="#//Car/involved"/>
    <!-- Reference back to Accident -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="accident" eType="#//Accident"
        lowerBound="1" eOpposite="#//Accident/involved"/>
  </eClassifiers>

  <!-- Accident class -->
  <eClassifiers xsi:type="ecore:EClass" name="Accident">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AccNr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AccLocation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AccDateTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <!-- Reference to Involved (association class for Car-Accident) -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="involved" upperBound="-1"
        eType="#//Involved" eOpposite="#//Involved/accident"/>
  </eClassifiers>

</ecore:EPackage>
