<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="filmset"
    nsURI="http://www.example.org/filmset"
    nsPrefix="filmset">

  <!-- Enumerations -->

  <eClassifiers xsi:type="ecore:EEnum" name="Genre">
    <eLiterals name="THRILLER"/>
    <eLiterals name="ACTION"/>
    <eLiterals name="HORROR"/>
    <eLiterals name="COMEDY"/>
  </eClassifiers>

  <!-- Custom Datatypes -->

  <eClassifiers xsi:type="ecore:EDataType" name="LocalDate"
      instanceClassName="java.time.LocalDate"/>

  <!-- Employee hierarchy -->

  <eClassifiers xsi:type="ecore:EClass" name="Employee" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="socialSecurityNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="CreativeEmployee" abstract="true" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasOscar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Director" eSuperTypes="#//CreativeEmployee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="assistantName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements_" eType="#//Film" eOpposite="#//Film/director"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//CreativeEmployee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="education" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenplaysToRead" upperBound="-1" eType="#//Screenplay" eOpposite="#//Screenplay/actors"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Technician" eSuperTypes="#//Employee">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldOfActivity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <!-- FilmSet -->

  <eClassifiers xsi:type="ecore:EClass" name="FilmSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="employees" upperBound="-1" eType="#//Employee" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="films" upperBound="-1" eType="#//Film" eOpposite="#//Film/filmSets"/>
  </eClassifiers>

  <!-- Film -->

  <eClassifiers xsi:type="ecore:EClass" name="Film">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yearOfRelease" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genre" eType="#//Genre"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filmSets" upperBound="-1" eType="#//FilmSet" eOpposite="#//FilmSet/films"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenplay" eType="#//Screenplay" eOpposite="#//Screenplay/film"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="director" eType="#//Director" eOpposite="#//Director/implements_"/>
  </eClassifiers>

  <!-- Screenwriter -->

  <eClassifiers xsi:type="ecore:EClass" name="Screenwriter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mostSuccessfulFilm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenplays" upperBound="-1" eType="#//Screenplay" containment="true" eOpposite="#//Screenplay/screenwriter"/>
  </eClassifiers>

  <!-- Screenplay and its bases -->

  <eClassifiers xsi:type="ecore:EClass" name="Screenplay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="#//LocalDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfScenes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="plot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenwriter" eType="#//Screenwriter" eOpposite="#//Screenwriter/screenplays"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basis" eType="#//ScreenplayBasis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="film" eType="#//Film" eOpposite="#//Film/screenplay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actors" upperBound="-1" eType="#//Actor" eOpposite="#//Actor/screenplaysToRead"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ScreenplayBasis" abstract="true">
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Novel" eSuperTypes="#//ScreenplayBasis">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Concept" eSuperTypes="#//ScreenplayBasis">
  </eClassifiers>

  <!-- Root container -->

  <eClassifiers xsi:type="ecore:EClass" name="FilmStudio">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filmSets" upperBound="-1" eType="#//FilmSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="films" upperBound="-1" eType="#//Film" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="screenwriters" upperBound="-1" eType="#//Screenwriter" containment="true"/>
  </eClassifiers>

</ecore:EPackage>
