<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eventmanagement" nsURI="http://www.example.org/eventmanagement"
    nsPrefix="eventmanagement">
  <eClassifiers xsi:type="ecore:EEnum" name="AttendeeStatus">
    <eLiterals name="Yes"/>
    <eLiterals name="Maybe" value="1"/>
    <eLiterals name="No" value="2"/>
    <eLiterals name="NoResponse" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompletionStatus">
    <eLiterals name="ToBeDone"/>
    <eLiterals name="Done" value="1"/>
    <eLiterals name="NotApplicable" value="2"/>
    <eLiterals name="Attendee" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventManagementSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="persons" upperBound="-1"
        eType="#//Person" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="locations" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventTypes" upperBound="-1"
        eType="#//EventType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkListTasks" upperBound="-1"
        eType="#//CheckListTask" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrations" upperBound="-1"
        eType="#//Registration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskStatuses" upperBound="-1"
        eType="#//TaskStatus" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="2" eType="#//PersonRole"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PersonRole" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Organizer" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" eOpposite="#//Event/organizers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attendee" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskStatuses" upperBound="-1"
        eType="#//TaskStatus" eOpposite="#//TaskStatus/attendee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrations" upperBound="-1"
        eType="#//Registration" eOpposite="#//Registration/attendee"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Registration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//AttendeeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendee" lowerBound="1"
        eType="#//Attendee" eOpposite="#//Attendee/registrations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//Event"
        eOpposite="#//Event/registrations"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TaskStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//CompletionStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendee" eType="#//Attendee"
        eOpposite="#//Attendee/taskStatuses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" lowerBound="1" eType="#//Event"
        eOpposite="#//Event/taskStatuses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkListTask" lowerBound="1"
        eType="#//CheckListTask" eOpposite="#//CheckListTask/taskStatuses"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckListTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskStatuses" upperBound="-1"
        eType="#//TaskStatus" eOpposite="#//TaskStatus/checkListTask"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventType" eType="#//EventType"
        eOpposite="#//EventType/checkListTasks"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" eOpposite="#//Event/location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occasion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers" lowerBound="1"
        upperBound="-1" eType="#//Organizer" eOpposite="#//Organizer/events"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrations" upperBound="-1"
        eType="#//Registration" eOpposite="#//Registration/event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskStatuses" upperBound="-1"
        eType="#//TaskStatus" eOpposite="#//TaskStatus/event"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" eOpposite="#//Location/events"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventType" lowerBound="1"
        eType="#//EventType" eOpposite="#//EventType/events"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EventType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events" upperBound="-1"
        eType="#//Event" eOpposite="#//Event/eventType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkListTasks" upperBound="-1"
        eType="#//CheckListTask" eOpposite="#//CheckListTask/eventType"/>
  </eClassifiers>
</ecore:EPackage>
