<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="eventmanagement"
    nsURI="http://www.example.org/eventmanagement"
    nsPrefix="eventmanagement">

  <!-- Enum: AttendeeStatus -->
  <eClassifiers xsi:type="ecore:EEnum" name="AttendeeStatus">
    <eLiterals name="Yes"/>
    <eLiterals name="Maybe" value="1"/>
    <eLiterals name="No" value="2"/>
    <eLiterals name="NoResponse" value="3"/>
  </eClassifiers>

  <!-- Enum: CompletionStatus -->
  <eClassifiers xsi:type="ecore:EEnum" name="CompletionStatus">
    <eLiterals name="ToBeDone"/>
    <eLiterals name="Done" value="1"/>
    <eLiterals name="NotApplicable" value="2"/>
    <eLiterals name="Attendee" value="3"/>
  </eClassifiers>

  <!-- Class: Person -->
  <!-- Person "1" - "0..2" PersonRole -->
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="emailAddress"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles"
        eType="#//PersonRole"
        upperBound="2"
        containment="true"
        eOpposite="#//PersonRole/person"/>
  </eClassifiers>

  <!-- Abstract Class: PersonRole -->
  <eClassifiers xsi:type="ecore:EClass" name="PersonRole" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="person"
        eType="#//Person"
        lowerBound="1"
        eOpposite="#//Person/roles"/>
  </eClassifiers>

  <!-- Class: Organizer (extends PersonRole) -->
  <!-- Organizer "1..*" - "*" Event -->
  <eClassifiers xsi:type="ecore:EClass" name="Organizer" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events"
        eType="#//Event"
        upperBound="-1"
        eOpposite="#//Event/organizers"/>
  </eClassifiers>

  <!-- Class: Attendee (extends PersonRole) -->
  <!-- Attendee "0..1" - "*" TaskStatus -->
  <!-- Attendee "*" - "*" Event (via Registration) -->
  <eClassifiers xsi:type="ecore:EClass" name="Attendee" eSuperTypes="#//PersonRole">
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskStatuses"
        eType="#//TaskStatus"
        upperBound="-1"
        eOpposite="#//TaskStatus/attendee"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrations"
        eType="#//Registration"
        upperBound="-1"
        eOpposite="#//Registration/attendee"/>
  </eClassifiers>

  <!-- Class: TaskStatus -->
  <!-- Association class of Event - CheckListTask, also linked to Attendee -->
  <eClassifiers xsi:type="ecore:EClass" name="TaskStatus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="#//CompletionStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendee"
        eType="#//Attendee"
        eOpposite="#//Attendee/taskStatuses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event"
        eType="#//Event"
        lowerBound="1"
        eOpposite="#//Event/taskStatuses"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkListTask"
        eType="#//CheckListTask"
        lowerBound="1"
        eOpposite="#//CheckListTask/taskStatuses"/>
  </eClassifiers>

  <!-- Class: Registration (association class of Attendee - Event) -->
  <eClassifiers xsi:type="ecore:EClass" name="Registration">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status"
        eType="#//AttendeeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attendee"
        eType="#//Attendee"
        lowerBound="1"
        eOpposite="#//Attendee/registrations"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event"
        eType="#//Event"
        lowerBound="1"
        eOpposite="#//Event/registrations"/>
  </eClassifiers>

  <!-- Class: CheckListTask -->
  <!-- EventType "1" - "*" CheckListTask -->
  <!-- Event "*" - "*" CheckListTask (via TaskStatus) -->
  <eClassifiers xsi:type="ecore:EClass" name="CheckListTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventType"
        eType="#//EventType"
        lowerBound="1"
        eOpposite="#//EventType/checkListTasks"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskStatuses"
        eType="#//TaskStatus"
        upperBound="-1"
        eOpposite="#//TaskStatus/checkListTask"/>
  </eClassifiers>

  <!-- Class: Location -->
  <!-- Location "1" - "*" Event -->
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events"
        eType="#//Event"
        upperBound="-1"
        eOpposite="#//Event/location"/>
  </eClassifiers>

  <!-- Class: EventType -->
  <!-- EventType "1" - "*" Event -->
  <!-- EventType "1" - "*" CheckListTask -->
  <eClassifiers xsi:type="ecore:EClass" name="EventType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="events"
        eType="#//Event"
        upperBound="-1"
        eOpposite="#//Event/eventType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="checkListTasks"
        eType="#//CheckListTask"
        upperBound="-1"
        eOpposite="#//CheckListTask/eventType"/>
  </eClassifiers>

  <!-- Class: Event -->
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occasion"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <!-- Organizer "1..*" - "*" Event -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizers"
        eType="#//Organizer"
        lowerBound="1"
        upperBound="-1"
        eOpposite="#//Organizer/events"/>
    <!-- Registration association class for Attendee-Event -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="registrations"
        eType="#//Registration"
        upperBound="-1"
        eOpposite="#//Registration/event"/>
    <!-- TaskStatus association class for Event-CheckListTask -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="taskStatuses"
        eType="#//TaskStatus"
        upperBound="-1"
        eOpposite="#//TaskStatus/event"/>
    <!-- Location "1" - "*" Event -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="location"
        eType="#//Location"
        lowerBound="1"
        eOpposite="#//Location/events"/>
    <!-- EventType "1" - "*" Event -->
    <eStructuralFeatures xsi:type="ecore:EReference" name="eventType"
        eType="#//EventType"
        lowerBound="1"
        eOpposite="#//EventType/events"/>
  </eClassifiers>

</ecore:EPackage>
