<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.1.0" xmlns:xmi="http://www.omg.org/XMI"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
    
    <!-- Class: RootContainer -->
    <eClassifiers xsi:type="ecore:EClass" name="RootContainer">
        <eStructuralFeatures/>
    </eClassifiers>
    
    <!-- Enumeration for Sensor Types -->
    <eClassifiers xsi:type="ecore:EEnum" name="SensorType">
        <EEnumLiteral>TEMPERATURE</EEnumLiteral>
        <EEnumLiteral>POWER</EEnumLiteral>
    </eClassifiers>

    <!-- Class: Sensor -->
    <eClassifiers xsi:type="ecore:EClass" name="Sensor">
        <eStructuralFeatures>
            <eStructuralFeature name="vendorId" type="ecore:EString"/>
            <eStructuralFeature name="description" type="ecore:EString"/>
            <eStructuralFeature name="unit" lowerBound="1"
                upperBound="-1" eType="#_SensorUnitEnum" reference-type="containment"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Enumeration for Sensor Unit -->
    <eAnnotations source="ecore:Unique">
        <details value="true"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="_SensorUnitEnum">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore#customTypeMapping">
            <details value="enum(java.time.Unit)"/>
        </eAnnotations>
        <eClassifiers xsi:type="ecore:EEnumLiteral" name="CELSIUS"/>
        <eClassifiers xsi:type="ecore:EEnumLiteral" name="WATT"/>
    </eClassifiers>

    <!-- Class: TemperatureSensor -->
    <eClassifiers xsi:type="ecore:EClass" name="TemperatureSensor">
        <eSuperTypes>
            <eclassifier href="#Sensor"/>
        </eSuperTypes>
        <eStructuralFeatures>
            <eSimpleFeature name="minValue" type="ecore:EDouble"/>
            <eSimpleFeature name="maxValue" type="ecore:EDouble"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Class: PowerSensor -->
    <eClassifiers xsi:type="ecore:EClass" name="PowerSensor">
        <eSuperTypes>
            <eclassifier href="#Sensor"/>
        </eSuperTypes>
        <eStructuralFeatures>
            <eSimpleFeature name="powerConsumption" type="ecore:EDouble"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Class: SensorController -->
    <eClassifiers xsi:type="ecore:EClass" name="SensorController">
        <eStructuralFeatures>
            <eAssociation name="sensors" upperBound="-1" derived="true"
                eType="#//Sensor"/>
            <eReferences name="apartments" upperBound="-1" containment="true"
                eType="#Apartment"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Class: SensorValue -->
    <eClassifiers xsi:type="ecore:EClass" name="SensorValue">
        <eStructuralFeatures>
            <eSimpleFeature name="timestamp" type="_Datetime"/>
            <eSimpleFeature name="value" type="ecore:EDouble"/>
            <eReferences name="sensor" eType="#//Sensor"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Custom Datatype for timestamp without date -->
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore#customTypeMapping">
        <details value="java.time.Instant"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EDataType" xmi:id="_Datetime"/>

    <!-- Class: Room -->
    <eClassifiers xsi:type="ecore:EClass" name="Room">
        <eStructuralFeatures>
            <eStructuralFeature name="description" type="ecore:EString"/>
            <eReferences name="containsSensor"
                upperBound="-1" eType="#//Sensor" derived="true"/>
        </eStructuralFeatures>
    </eClassifiers>

    <!-- Class: Apartment -->
    <eClassifiers xsi:type="ecore:EClass" name="Apartment">
        <eSuperTypes>
            <eclassifier href="#RootContainer"/>
        </eSuperTypes>
        <eStructuralFeatures>
            <eSimpleFeature name="address" type="ecore:EString"/>
            <eReferences name="rooms" upperBound="-1"
                eType="#//Room" containment="true"/>
        </eStructuralFeatures>
    </eClassifiers>

</ecore:EPackage>
