<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="FilmSetModel" nsURI="http://www.example.org/FilmSetModel" nsPrefix="filmsetmodel" eClassifiers="RootContainer Employee CreativeEmployee Actor Director Technician FilmSet Film Genre Screenwriter Screenplay Novel AssociationScreenplayFilm TimeWithoutDate EDate">

    <!-- Custom datatype for times without dates -->
    <ecore:EDataType name="TimeWithoutDate" instanceClassName="java.time.LocalTime"/>

    <!-- Define the custom EDate type if not already present -->
    <ecore:EDataType name="EDate" instanceClassName="org.eclipse.emf.ecore.util.EcoreUtil$EDate"/>

    <!-- Root container class -->
    <ecore:EClass name="RootContainer">
      <eStructuralFeatures name="employees" lowerBound="0" eType="#//Employee"/>
      <eStructuralFeatures name="films" lowerBound="0" eType="#//Film"/>
      <eStructuralFeatures name="screenwriters" lowerBound="0" eType="#//Screenwriter"/>
    </ecore:EClass>

    <!-- Employee class -->
    <ecore:EClass name="Employee">
      <eAttributes name="name" eType="ecore:EDataType #//ecore.EString"/>
      <eAttributes name="socialSecurityNumber" eType="ecore:EDataType #//ecore.EInt"/>
    </ecore:EClass>

    <!-- CreativeEmployee class -->
    <ecore:EClass name="CreativeEmployee">
      <eStructuralFeatures name="employee" lowerBound="1" eType="#//Employee" containment="true"/>
      <eAttributes name="hasOscar" eType="ecore:EDataType #//ecore.EBoolean"/>
    </ecore:EClass>

    <!-- Actor class inheriting from CreativeEmployee -->
    <ecore:EClass name="Actor">
      <eStructuralFeatures name="creativeEmployee" lowerBound="1" eType="#//CreativeEmployee"/>
      <eAttributes name="educationCompleted" eType="ecore:EDataType #//ecore.EString"/>
    </ecore:EClass>

    <!-- Director class inheriting from CreativeEmployee -->
    <ecore:EClass name="Director">
      <eStructuralFeatures name="creativeEmployee" lowerBound="1" eType="#//CreativeEmployee"/>
      <eAttributes name="assistantName" eType="ecore:EDataType #//ecore.EString"/>
    </ecore:EClass>

    <!-- Technician class -->
    <ecore:EClass name="Technician">
      <eStructuralFeatures name="employee" lowerBound="1" eType="#//Employee" containment="true"/>
      <eAttributes name="fieldOfActivity" eType="ecore:EDataType #//ecore.EString"/>
    </ecore:EClass>

    <!-- FilmSet class -->
    <ecore:EClass name="FilmSet">
      <eAttributes name="location" eType="ecore:EDataType #//ecore.EString"/>
      <eStructuralFeatures name="films" lowerBound="0" eType="#//Film" containment="true"/>
    </ecore:EClass>

    <!-- Film class -->
    <ecore:EClass name="Film">
      <eAttributes name="title" eType="ecore:EDataType #//ecore.EString"/>
      <eAttributes name="yearOfRelease" eType="ecore:EDataType #//ecore.EInt"/>
      <eStructuralFeatures name="genre" lowerBound="1" eType="#//Genre"/>
    </ecore:EClass>

    <!-- Genre class -->
    <ecore:EEnum name="Genre">
      <eLiterals name="Thriller"/>
      <eLiterals name="Action"/>
      <eLiterals name="Horror"/>
      <eLiterals name="Comedy"/>
    </ecore:EEnum>

    <!-- Screenwriter class -->
    <ecore:EClass name="Screenwriter">
      <eAttributes name="name" eType="ecore:EDataType #//ecore.EString"/>
      <eAttributes name="mostSuccessfulFilm" eType="ecore:EDataType #//ecore.EString"/>
      <eStructuralFeatures name="screenplays" lowerBound="0" eType="#//Screenplay"/>
    </ecore:EClass>

    <!-- Screenplay class -->
    <ecore:EClass name="Screenplay">
      <eAttributes name="title" eType="ecore:EDataType #//ecore.EString"/>
      <eAttributes name="version" eType="ecore:EDataType #//ecore.EInt"/>
      <eAttributes name="date" eType="#//EDate"/>
      <eAttributes name="numberOfScenes" eType="ecore:EDataType #//ecore.EInt"/>
      <eAttributes name="plot" eType="ecore:EDataType #//ecore.EString"/>
    </ecore:EClass>

    <!-- Novel class -->
    <ecore:EClass name="Novel">
      <eAttributes name="title" eType="ecore:EDataType #//ecore.EString"/>
      <eAttributes name="author" eType="ecore:EDataType #//ecore.EString"/>
    </ecore:EClass>

    <!-- Association class for Screenplay and Film -->
    <ecore:EClass name="AssociationScreenplayFilm">
      <eStructuralFeatures name="screenplay" lowerBound="1" eType="#//Screenplay"/>
      <eStructuralFeatures name="film" lowerBound="1" eType="#//Film"/>
    </ecore:EClass>
  </ecore:EPackage>
</xmi:XMI>
