<?xml version="1.0" encoding="UTF-8"?>
<ecore:Ecore xmlns:xmi="http://www.omg.org/XMI" 
             xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  
  <eClassifiers>
    <!-- Root Container Class -->
    <eClass xsi:type="ecore:EClass" name="RootContainer" isAbstract="false"/>

    <!-- City -->
    <eClass xsi:type="ecore:EClass" name="City">
      <eStructuralFeatures>
        <eAttribute xsi:type="ecore:EAttribute" name="name"/>
        <eAttribute xsi:type="ecore:EAttribute" name="inhabitants" eType="_0"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Attraction -->
    <eClass xsi:type="ecore:EClass" name="Attraction">
      <eStructuralFeatures>
        <eAttribute xsi:type="ecore:EAttribute" name="name"/>
        <eAttribute xsi:type="ecore:EAttribute" name="address"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Person -->
    <eClass xsi:type="ecore:EClass" name="Person">
      <eStructuralFeatures>
        <eAttribute xsi:type="ecore:EAttribute" name="name"/>
      </eStructuralFeatures>
    </eClass>

    <!-- Visitor extends Person -->
    <eClass xsi:type="ecore:EClass" name="Visitor" eSuperTypes="#//Person"/>

    <!-- Guide extends Person -->
    <eClass xsi:type="ecore:EClass" name="Guide" eSuperTypes="#//Person"/>

    <!-- GuidedTour -->
    <eClass xsi:type="ecore:EClass" name="GuidedTour">
      <eStructuralFeatures>
        <eAttribute xsi:type="ecore:EAttribute" name="duration" eType="_1"/>
        <eReference xsi:type="ecore:EReference" name="participants">
          <eType xsi:type="ecore:EAssociationClass" href="#//GuidedTourParticipant"/>
        </eReference>
      </eStructuralFeatures>
    </eClass>

    <!-- Association Class for GuidedTour and Visitor -->
    <eClass xsi:type="ecore:EClass" name="GuidedTourParticipant">
      <eStructuralFeatures>
        <eAttribute xsi:type="ecore:EAttribute" name="discount"/>
        <eReference eContainment="true" xsi:type="ecore:EReference" name="tour" upperBound="-1">
          <eType href="#//GuidedTour"/>
        </eReference>
        <eReference xsi:type="ecore:EReference" name="visitor" upperBound="-1">
          <eType href="#//Visitor"/>
        </eReference>
      </eStructuralFeatures>
    </eClass>

    <!-- Relating City to Attractions -->
    <eClassifiers xsi:type="ecore:EDataType" name="Int" serializable="true">
      <eStructuralFeatures/>
    </eClassifiers>

    <!-- Duration Type (custom datatype based on Java Time) -->
    <eClassifiers xsi:type="ecore:EDatatype" xmi:id="_1" upperBound="-1"/>
    <ePackage.eNsURI>...namespace here...</ePackage.eNsURI>
    
  </eClassifiers>
  
</ecore:Ecore>
