<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="orderManagement"
    nsURI="http://www.example.com/orderManagement"
    nsPrefix="orderManagement">

  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderQuantity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" eType="#//Product" lowerBound="1" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="placedBy" eType="#//Representative" lowerBound="1" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customer" eType="#//Customer" lowerBound="1" upperBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Category">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" eType="#//Product" upperBound="-1" eOpposite="#//Product/category"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Product">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="netPrice" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="category" eType="#//Category" lowerBound="1" upperBound="1" eOpposite="#//Category/products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" eType="#//Order" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" eType="#//Country" upperBound="-1" eOpposite="#//Country/products"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manufacturerCountries" eType="#//ManufacturerCountry" upperBound="-1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Representative">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ssn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" eType="#//Order" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responsibleFor" eType="#//Country" lowerBound="1" upperBound="1"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Manufacturer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" eType="#//Country" upperBound="-1" eOpposite="#//Country/manufacturers"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Country">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conversionRate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="manufacturers" eType="#//Manufacturer" upperBound="-1" eOpposite="#//Manufacturer/countries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" eType="#//Product" upperBound="-1" eOpposite="#//Product/countries"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="customers" eType="#//Customer" upperBound="-1" eOpposite="#//Customer/countries"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Customer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phoneNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="orders" eType="#//Order" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="countries" eType="#//Country" upperBound="-1" eOpposite="#//Country/customers"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="ManufacturerCountry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="manufacturer" eType="#//Manufacturer" lowerBound="1" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="country" eType="#//Country" lowerBound="1" upperBound="1"/>
  </eClassifiers>

</ecore:EPackage>
