<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.1"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="MyGame">

  <eClassifiers xsi:type="ecore:EClass" name="GameArea">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name"/>
    <eReferences name="gameElements" upper="-1" eType="#//GameElement"/>
    <eReferences name="gamePieces" lower="2" upper="-1" eType="#//GamePiece"/>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="GameElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xValue"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yValue"/>
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="Shape" eSuperTypes="#//GameElement">
    <eReferences name="connectedShapes" upper="-1" eType="#//Shape" containment="true">
      <EReference.eOpposite>connectedBy</EReference.eOpposite>
    </eReferences>
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" name="Object" eSuperTypes="#//GameElement"/>
  
  <eClassifiers xsi:type="ecore:EClass" name="Opponent" eSuperTypes="#//GameElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lives"/>
  </eClassifiers>
  
  <eClassifiers xsi:type="ecore:EClass" name="Boss" eSuperTypes="#//Opponent"/>

  <eClassifiers xsi:type="ecore:EClass" name="GamePiece">
    <!-- GamePiece might hold references to actual game elements used as pieces -->
  </eClassifiers>

  <eClassifiers xsi:type="ecore:EClass" abstract="true" name="RootContainer"/>
  
</ecore:EPackage>
